### ISSUE TITLE
test_mem_* fails on 9.2.x

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#1]
As per subject.

**Comment by wrwilliams** [comment]
Appears that we're marking loadsnstores uninstrumentable. So there are two problems:

1) Test should include non-relocatable copies of loadsnstores in its search; the memory instrumentation part of the test depends on whether we can instrument, not how we reach instrumentation
2) We should investigate whether loadsnstores is being misparsed

Also recommend splitting out all of our tests that assume various functions are instrumentable into a big set of parsing tests--it's not a parseAPI test suite yet, but it'll give more informative failures

**Comment by wrwilliams** [comment]
Loadsnstores is being misparsed, and it appears to be because of a VEX decoding bug. John, can you verify that your VEX fixes also result in the memory tests running cleanly?

**Comment by jdetter** [comment]
How do I run the test?

**Comment by wrwilliams** [comment]
Check out the testsuite repo (sibling of this one). Configure it against your installed copy of dyninst, build, and install it; this will give you a testsuite/ directory in your dyninst/bin install location. In the test suite, run 'test_driver -test test_mem_1'. You'll need your library search path to include your dyninst library directory and DYNINSTAPI_RT_LIB pointing to the libdyninstAPI_RT.so in that directory in your environment.

Let me know/drop by if any of this is less straightforward than I make it sound.

**Comment by jdetter** [comment]
I found the source of the issue, I should have it figured out by tomorrow morning.

**Comment by jdetter** [comment]
We are passing all of the memory tests, however we are failing 11 of the other tests on intel.

Gist: https://gist.github.com/jdetter/d1516531aac51731a91626f4a113ef11

**Comment by wrwilliams** [comment]
Okay. For test_pt_ls you should confirm that parseThat is not in your path, fix that, and rerun. The test5 series in rewriter mode is a new set of failures compared to master AFAIK. Run the individual ones with -verbose -log and see what turns up.

Overall this looks promising, though.

**Comment by jdetter** [comment]
To confirm, `parseThat` should not be in my path right? Even when I removed it from my path, it still didn't pass unfortunately. I am working on the series 5 tests now.

**Comment by jdetter** [comment]
All of the series 5 tests have similar output to this:

```
'./binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none @s": symbol lookup error: @s": undefined symbol: logstatus
```

They all complain about logstatus not being a defined symbol.

Full test5_1 failed log:

```
[Tests with dyninst_cxx_group_test.dyn_g++_64_none_none]
-rwxr-xr-x. 1 root root 142312 May 10 17:17 dyninst_cxx_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 (0x00007ffe4f7ae000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f386bf4e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f386bc4b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f386ba34000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f386b673000)
        /lib64/ld-linux-x86-64.so.2 (0x0000560062e4d000)

Snippet cost=0
Snippet cost=0
test_lib_mutateeStart.C[77]:  unlinking ./binaries/test_pt_ls_stdout1
test_lib_mutateeStart.C[77]:  unlinking ./binaries/test_pt_ls_stderr1
test_lib_mutateeStart.C[77]:  unlinking ./binaries/test_pt_ls_stdout2
test_lib_mutateeStart.C[77]:  unlinking ./binaries/test_pt_ls_stderr2
test_lib_mutateeStart.C[268]:  starting rewritten process './binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none @s": symbol lookup error: @s": undefined symbol: logstatus
test_lib_mutateeStart.C[283]:  after waitForCompletion: no crash, result = 127
test_lib_mutateeStart.C[77]:  unlinking ./binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none
test5_1                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
```

**Comment by wrwilliams** [comment]
parseThat *should* be in your path; historically failures have been because it's not.

Re: test5_*: set DYNINST_REWRITER_NO_UNLINK=1 in your environment. That will preserve the rewritten binaries in a binaries/ directory. We can go from there (probably interactive becomes most efficient at that point).

**Comment by jdetter** [comment]
The rewriter portion of the test is passing now for test_pt_ls, however series 5 tests are failing. I have now potentially run into a slicing issue, which I will make as a separate issue.

**Comment by jdetter** [comment]
I am running into a really nasty issue with a LOCK prefixed instruction that won't disassemble, I will hopefully have it figured out by today or tomorrow.

**Comment by jdetter** [comment]
test `test_pt_ls` passing for the rewriter portion, still failing for the create portion. All other tests are unchanged (failing 9 now). However, `runTests --all` finishes with this:

```
*** Process exceeded time limit.  Reaping children.
```

**Comment by jdetter** [comment]
Since the mem tests are now passing, I think we should move this into separate issues.
