### ISSUE TITLE
Dyninst WrapFunction does not work for C++ and golang

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#1006]
**Intention**
Use Dyninst WrapFunction to wrap a library function

**Describe the bug**
As per the implementation of WrapFunction on page no 24 of url https://dyninst.org/sites/default/files/manuals/dyninst/dyninstAPI.pdf, I implemented fastMalloc in a library and origMalloc in a c program.
When origMalloc is the part of c program then wrapfunction works fine but when origMalloc is part of a library which is used by c program then wrpfunction does not work. The same issue exists for golang.

**To Reproduce**
To reproduce the isue, get attached c file. Create library libwmalloc.so for libwmalloc.c, libomalloc.so for libomalloc.c, create c program from cprogram.c which uses libomalloc.so. Use codecoverage to wrap origMalloc by fastMalloc.
[examples.tar.gz](https://github.com/dyninst/dyninst/files/6008007/examples.tar.gz)

**Expected behavior**
wrpfunction should work when origMalloc is part of a library .

**System (please complete the following information):**
 16.04.1-Ubuntu x86_64 GNU/Linux
master branch 10.2.1

**Additional context**
wrpfunction does not work. Same problem comes for go golang binary.

**Comment by hainest** [comment]
Could you update your tarball to include a Makefile or CMakelist.txt to show how you are building your libraries?

**Comment by ManojKumarChauhan** [comment]
> Could you update your tarball to include a Makefile or CMakelist.txt to show how you are building your libraries?

I have uploaded examples.tar.gz which contains Makefile.

For golang, wrapfunction does not work because dyninst does not find any entry for golang binary/library (symtabapi/object-elf.C file), here loaded_elf does not parse it correctly

**Comment by ManojKumarChauhan** [comment]
Hi @hainest ,

WrapFunction does not work for golang because dyninst is not able to find any symbol. Should I create a new bug or it will be fixed in this bug.

**Comment by hainest** [comment]
@ManojKumarChauhan golang is not officially supported. Any changes to behavior for handling those binaries would be incidental.

**Comment by ManojKumarChauhan** [comment]
Hi @hainest 
Should I close this issue?
