### ISSUE TITLE
Dyninst: How to access function variables

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#1022]
I created a c++ application and one function in it.
void testfunction(int *a, char b);

BPatch_function class provides getParams method to access the variables.Example

BPatch_Vector<BPatch_localVar *> *vars =  curFunc->getParams();

I want to access the actual variable address (of a and b) but did not find any  API in BPatch_localVar class to get it.
To know variable type (like int * and char), I used following
BPatch_type *type=(*vars)[i]->getType();
but type->getName() does not print anything (it should print int* and char).

Can someone suggest how to do that.

**Comment by hainest** [comment]
Could you provide a minimal working example of source code that we can debug?

**Comment by ManojKumarChauhan** [comment]
Attached is codecoverage.C which searches a function testfunction and print its argument. For a C language program, It can find the argument name and type name but I did not find any API to access arguments arg1 and arg2.
void testfunction(int *arg1, char arg2)
[testcode.zip](https://github.com/dyninst/dyninst/files/6410111/testcode.zip)

Similarly I created a go program and write below test function.  codecoverage.C can find the argument name and but not the type name. Also I did not find any API to access arguments arg1 and arg2.
func testfunction(arg1 int,arg2 string) 

I have attached testcprogram and testgoprogram both with their code. You can run those using following commands
./codecoverage testcprogram

**Comment by ManojKumarChauhan** [comment]
Hi @hainest 
Any update? If golang is not supported then it's ok but please suggest how to get the address of function arguments. In below example to access a & b, I did not find any function to get their address.
void testfunction(int *a, char b);

**Comment by hainest** [comment]
Whether or not a formal function parameter has an address is defined by the ABI in use. For example, on x86_64, neither parameter would have an address because they are passed in registers. If you want to know the address of the variables which were passed at the callsite, we don't support that yet (though it is under active development).

**Comment by ManojKumarChauhan** [comment]
I want get the function parameters (a and b) and pass them in another function (instrumented function). Is it possible now?

**Comment by ManojKumarChauhan** [comment]
Hi @hainest ,

Is this fixed? 
If not then can I get it in the next version of dyninst?

**Comment by hainest** [comment]
@ManojKumarChauhan Dyninst has a rudimentary understanding of ABI information for formal parameters- even on x86. We are working with a group at LLNL to implement this, but it will be months (at the very least) before it is ready. This definitely won't be in the next version of Dyninst.

**Comment by hainest** [comment]
Answered- closing.
