### ISSUE TITLE
Dyninst 10.1.0 cannot parse newer go binaries

### ISSUE THREAD

**Issue by renxian2** [dyninst/dyninst#1023]
When parsing newer go binaries, Dyninst fails with
"dyninst-10.1.0/src/dyninstAPI/src/addressSpace.C:819: virtual void* AddressSpace::getPtrToInstruction(Dyninst::Address) const: Assertion `0' failed"

Upon examining the source code, it seems that Dyninst did not get the starting offset and size of the code section right.

This happens on Linux 64bit.

[https://www.dropbox.com/s/hkfm5pgv6qt36gr/example?dl=0](url) 
The above link contains one of the binaries that can reproduce this issue.

to reproduce this problem run this code:

```
#include <stdio.h>
#include <vector>
#include "BPatch.h"
#include "BPatch_addressSpace.h"
#include "BPatch_process.h"
#include "BPatch_binaryEdit.h"
#include "BPatch_point.h"
#include "BPatch_function.h"
#include "BPatch_flowGraph.h"
#include "Instruction.h"
#include "InstructionDecoder.h"
#include "slicing.h"
#include "CodeObject.h"
#include "CFG.h"

int main() {
  char *progName = "example";
  char *funcName = "main.main";
  BPatch_image *appImage = getImage(progName);
  vector<BPatch_basicBlock *> bbs;
  BPatch_function *f = getFunction(appImage, funcName);
  if (f != NULL) {
    BPatch_flowGraph *fg = f->getCFG();
    set<BPatch_basicBlock *> blocks;
    fg->getAllBasicBlocks(blocks);
    for (auto blockIter = blocks.begin();
         blockIter != blocks.end();
         ++blockIter) {
      BPatch_basicBlock *block = *blockIter;
      vector <Instruction> insns;
      block ->getInstructions(insns);
  }
}
```

**Comment by hainest** [comment]
Dyninst does not support Go binaries. There is experimental support created by @mxz297.

**Comment by mxz297** [comment]
@renxian2 I believe this issue is resolved offline? If so, can you close this issue?
