### ISSUE TITLE
Dyninst-11.0 prints huge output to stdout

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#1028]
@bbiiggppiigg 

The line caused the printing:

https://github.com/dyninst/dyninst/blob/v11.0.0/dataflowAPI/src/AbslocInterface.C#L501

**Comment by mxz297** [comment]
@bbiiggppiigg There is at least one instance of printing (https://github.com/dyninst/dyninst/blob/master/common/src/dyn_regs.C#L201).

Can you carefully double check your code to remove all printing?

**Comment by bbiiggppiigg** [comment]
@mxz297 Is it fine if I change some of the error indicating information to to std::cerr ?

**Comment by mxz297** [comment]
@mxz297 No, unconditionally printing to either stdout or stderr is not good. We typically have environment variables that enables printing to stderr, which by default are disabled. If you want to retain the printing, you need to do something similar:

https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/debug.h

**Comment by bbiiggppiigg** [comment]
I've pushed new commits to fix this problem.
