### ISSUE TITLE
Cross platform mutatee support

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#103]
Dyninst doesn't have support for mutating binaries that will not run on the current host. For example, a 32 bit x86 host can't rewrite an x86_64 binary. However, we do have support for rewriting x86 binaries on an x86_64 host.

To my knowledge, we also don't support cross platform mutatees between Intel and ARM platforms, which could be a nice feature.

**Comment by wrwilliams** [comment]
This may happen if there's sufficient demand for it, but our first priority is ensuring that cross-platform analysis works for all cases/environments.
