### ISSUE TITLE
Dyninst master fail to compile with gcc-6

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#1031]
I encountered the following error:

```
/home/xm13/dyninst-master/dyninst/dataflowAPI/src/RoseInsnFactory.C:458:22: error: expected unqualified-id before '[' token
                 auto [oper0,oper1] = expandSgprPair(operands[0]);
``` 

when compiling dyninst master branch with gcc-6.4.0 on a power system. 

Structured binding is since C++17 (https://en.cppreference.com/w/cpp/language/structured_binding). Is this an unintended use of a C++17 feature or Dyninst has moved onto C++17?

@hainest @bbiiggppiigg

**Comment by hainest** [comment]
We haven't moved to C++17 yet (although I wouldn't complain if we did), I just missed this during code review. We should change this to use [`std::tie`](https://en.cppreference.com/w/cpp/utility/tuple/tie).

**Comment by hainest** [comment]
Thinking about this more, we explicitly set the `-std=c++11` flag. This means that the Dyninst compiler flags aren't getting passed to the Rose subproject. That needs to be fixed (separately from this, though).
