### ISSUE TITLE
The Function disassembly example from the ParseAPI Programmer's guide doesn't compile

### ISSUE THREAD

**Issue by wcohen** [dyninst/dyninst#1052]
**Intention**
I was trying to better understand the operation of the function disassembly example by having a copy of it working in the dyninst examples git tree.

**Describe the bug**
I was able to transcribe the code from the ParseAPI programmer's guide into a file to compile like the other examples.  I was able to get the CFG example in the same manual to compile as an example.  However, when attempting to compile the function disassembly example get errors on the decoder.decode() method calls:

```
[ 90%] Building CXX object disassemble/CMakeFiles/disassemble.dir/disassemble.cpp.o
/home/wcohen/research/profiling/dyninst/examples/disassemble/disassemble.cpp: In function ‘int main(int, char**)’:
/home/wcohen/research/profiling/dyninst/examples/disassemble/disassemble.cpp:61:96: error: no match for ‘operator=’ (operand types are ‘Dyninst::InstructionAPI::Instruction::Ptr’ {aka ‘boost::shared_ptr<Dyninst::InstructionAPI::Instruction>’} and ‘Dyninst::InstructionAPI::Instruction’)
   61 |                 instr = decoder.decode((unsigned char *)f->isrc()->getPtrToInstruction(crtAddr));
      |  

```

```
/home/wcohen/research/profiling/dyninst/examples/disassemble/disassemble.cpp:72:104: error: no match for ‘operator=’ (operand types are ‘Dyninst::InstructionAPI::Instruction::Ptr’ {aka ‘boost::shared_ptr<Dyninst::InstructionAPI::Instruction>’} and ‘Dyninst::InstructionAPI::Instruction’)
   72 |                         instr = decoder.decode((unsigned char *)f->isrc()->getPtrToInstruction(crtAddr));
      |  

```

**To Reproduce**

On Fedora 34 was doing the following steps with either dyninst-10.2.1-6.fc34 installed or a similarly local rpm build of dyninst-11.0.0 from rawhide:

git clone https://github.com/wcohen/examples
git checkout wcohen/disassemble
cmake . -DDyninst_DIR=/usr/lib64/cmake/Dyninst
make

**Expected behavior**
Expect the all the examples including the function disassembly example to compile.

**System (please complete the following information):**
 - X86_64 running Fedora 34
 - Observed with Fedora Dyninst-10.2.1 and dyninst-11.0.0 rpms
 - glibc-2.33-14.fc34.x86_64

**Additional context**
Took a look to see if there were any testsuite tests that use InstructionDecoder.  There are some aarch64_cft.C, aarch66_decode_ldst.C, test_instruction_profile.C, etc.   Those seem to compile and run successfully from the Fedora RPM.  Looks like something needs to be tweaked in the function disassembly example.

**Comment by wcohen** [comment]
Found that the decode method was returning a different class Instruction (not Instruction::Ptr). Updated the code in commit 82af451e7109745ff30d67e3ffd4bbbaabaa2cf1 and it compiles now.

**Comment by hainest** [comment]
Could you post the diff from 82af451e7?

**Comment by wcohen** [comment]
Current working version of disassemble.cpp is at:
https://github.com/wcohen/examples/blob/wcohen/disassemble/disassemble/disassemble.cpp

There is an additional correction in  there to ensure that the last instruction of each basic block is outputted.  I found that the existing code was existing the loop one instruction early.

**Comment by wcohen** [comment]
all the diffs are listed on the history of the file.

**Comment by hainest** [comment]
Closed by https://github.com/dyninst/examples/pull/19
