### ISSUE TITLE
cray compiler (cce) doesn't understand some gcc warning flags

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1091]
warning: unknown warning option '-Wcomma-subscript'; did you mean '-Wchar-subscripts'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wduplicated-branches' [-Wunknown-warning-option]
    warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
    warning: unknown warning option '-Wenum-conversions'; did you mean '-Wenum-conversion'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wformat-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wformat-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]warning
    warning: unknown warning option '-Wformat-signedness' [-Wunknown-warning-option]
    warning: unknown warning option '-Wjump-misses-init' [-Wunknown-warning-option]
    warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wnoexcept' [-Wunknown-warning-option]
    warning: unknown warning option '-Wrestrict' [-Wunknown-warning-option]
    warning: unknown warning option '-Wstrict-null-sentinel' [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
    warning: unknown warning option '-Wsuggest-attribute=malloc' [-Wunknown-warning-option]
    warning: unknown warning option '-Wvolatile' [-Wunknown-warning-option]

Ping @kupsch 

At least on theta@ALCF, cce is really the Cray build of clang, so these are effectively not supported by clang.

**Comment by kupsch** [comment]
Caused by clang emitting a different diagnostic message than gcc when an unknown warning flag is present.  This caused the check for supported warning messages to always pass.  Pull request available soon.
