### ISSUE TITLE
external build of libiberty fails

### ISSUE THREAD

**Issue by kupsch** [dyninst/dyninst#1098]
**Intention**
On a host without libiberty installed, build it as an external.

**Describe the bug**
If libiberty is not found on the host, then LibIberty.cmake tries to build libiberty and fails with errors.  The first error is

```
CMake Error at cmake/LibIberty.cmake:86 (add_library):
  add_library cannot create imported target "LibIberty" because another
  target with the same name already exists.
```

This is because `ExternalProject_add` defines LIbIberty and the add_library does also.  If the `add_library` is moved into the if clause, so only one is executed, then there is another error:

```
CMake Error at common/CMakeLists.txt:130 (target_link_libraries):
  Target "LibIberty" of type UTILITY may not be linked into another target.
  One may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.
```

**To Reproduce**
cmake <SRC_PATH>

**Expected behavior**
cmake should run without failing

**System (please complete the following information):**
 - x86_64
 - no libiberty installed
 - What commit? master (cd8ac9618)

**Comment by hainest** [comment]
I broke this a year ago and no one noticed. Combined with the maintenance hazards of dealing with doing a live download/install of dependencies (which we should most definitely not be doing), I'm just going to kill this for LibIberty. binutils is too much of a tricky beast to get right, anyway.

**Comment by hainest** [comment]
Oh, and we (correctly) made LibIberty a required package (i.e., passed REQUIRED to `find_package`) when we updated the name demangling, so the `ExternalProject_Add` should have been axed at that time.
