### ISSUE TITLE
ParseAPI equivalent to SymtabAPI getContainingFunction

### ISSUE THREAD

**Issue by wcohen** [dyninst/dyninst#1102]
Would like to find the function containing an address.  ParseAPI has the following function described in the manual:

bool getContainingFunction(Offset offset,
Function *&ret)

This method returns the function, if any, that contains the provided offset. Returns true on
success and false on failure. The error value is set to No_Such_Function. Note that this method
does not parse, and therefore relies on the symbol table for information. As a result it may return
incorrect information if the symbol table is wrong or if functions are either non-contiguous or
overlapping. For more precision, use the ParseAPI library.

However would like to take the advice of the SymtabAPI manual and using ParseAPI instead of SymtabAPI to get this information.  Looking through the ParseAPI manual the following function looks to be the closest in functionality:

int findFuncs(CodeRegion * cr,
Address addr,
std::set<Function*> & funcs)

Finds all functions spanning addr in the code region, adding each to funcs. The number of results
of this stabbing query are returned.

The question is how to get an appropriate CodeRegion for ParseAPI findfuncs?  Or is there a better alternative to map address back to the containing function than findfuncs? When I attempted to compile code using findFuncs passing in an CodeRegions that is unitialized gcc flagged that as an error:

  CXX      stap-analysis.o
analysis.cxx: In function ‘int liveness(const char*, Dwarf_Addr, location_context)’:
analysis.cxx:63:51: error: ‘cr’ may be used uninitialized [-Werror=maybe-uninitialized]
   63 |         bool found = func_to_analyze.co->findFuncs(cr, addr, f);
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

**Comment by wcohen** [comment]
I should add that passing the returned Function *  to run the dataflowAPI liveness analysis.

**Comment by hainest** [comment]
@wcohen There are a couple of ways that I can think of (I've not tried compiling these):

Using `CodeObject::funcs` to parse each code region of the known functions:

    std::set<ParseAPI::Function*> funcs;
    Address addr = 0xDEADBEEF;

    ParseAPI::CodeObject *co = ...;
    for(auto *f : co->funcs()) {
      std::set<ParseAPI::Function*> tmp;
      if(co->findFuncs(f->region(), addr, tmp) > 0) {
        funcs.insert(tmp.begin(), tmp.end());
      }
    }

Using `CodeObject::cs` to parse the raw set of regions for the CodeSource:

    for(auto *r : co->cs()->regions()) {
      std::set<ParseAPI::Function*> tmp;
      if(co->findFuncs(r, addr, tmp) > 0) {
        funcs.insert(tmp.begin(), tmp.end());
      }
    }

I would be saddened if these didn't produce the same answer.

@mxz297 Do you know a better way?

**Comment by wcohen** [comment]
I was hoping to there was a direct analog to the SymtabAPI's findFuncs in ParseAPI and avoid having to iterate through all the possible functions in the CodeObject to find the one that contains the address of interest.  

The second example going through the regions of the CodeObject might be fewer iterations and more attractive.

Interestly, I tried the following test code and it seems that findFuncs() doesn't really care about what is in the region:

```
	for(auto *r : func_to_analyze.co->cs()->regions()) {
		cout << "regions " << *r << endl;
		std::set<ParseAPI::Function*> tmp;
		if(func_to_analyze.co->findFuncs(r, addr, tmp) > 0) {
			for(auto ff : tmp) {
				cout << ff->name() << "[" << addr << "]" << endl;
			}
		}
	}
```

Seems to find the function regardless of the region:

```
regions [1c04e0, 1c29a0)
_int_memalign[8b470]
regions [1c2b80, 1c2ff8)
_int_memalign[8b470]
regions [1be0d8, 1be4e2)
_int_memalign[8b470]
regions [173000, 197a28)
_int_memalign[8b470]
regions [1c04c0, 1c04d0)
_int_memalign[8b470]
regions [1c3000, 1c4620)
_int_memalign[8b470]
regions [26000, 26350)
_int_memalign[8b470]
regions [1c4700, 1c5468)
_int_memalign[8b470]
regions [1719e0, 1728fc)
_int_memalign[8b470]
regions [197a30, 197a4c)
_int_memalign[8b470]
regions [26350, 26690)
_int_memalign[8b470]
regions [197a28, 197a29)
_int_memalign[8b470]
regions [1c5468, 1c5470)
_int_memalign[8b470]
regions [1c4620, 1c46f8)
_int_memalign[8b470]
regions [197a4c, 19dd78)
_int_memalign[8b470]
regions [19dd78, 1be0d8)
_int_memalign[8b470]
regions [26690, 1719dd)
_int_memalign[8b470]

```

**Comment by hainest** [comment]
> I was hoping to there was a direct analog to the SymtabAPI's findFuncs in ParseAPI and avoid having to iterate through all the possible functions in the CodeObject to find the one that contains the address of interest.

Agreed. That kind of helper function seems to be a missing bit of functionality. If you can get to a `ParseAPI::image` object, you can use its [`findFuncs`](https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/image.h#L311) which does effectively what the second version looping over the `cs()->regions()` does. I just wasn't able to figure out how to get to an image object from Symtab, though.

 
> Interestly, I tried the following test code and it seems that findFuncs() doesn't really care about what is in the region:
...
> Seems to find the function regardless of the region:

Uhh... That seems wrong.

**Comment by wcohen** [comment]
Yes, I was surprised also that the code returned the function associated with the address regardless of the region used.  However, it looks like the code doesn't bother to use the CodeRegion:

https://github.com/dyninst/dyninst/blob/master/parseAPI/src/ParseData.C#L112

**Comment by hainest** [comment]
@mxz297 We should chat about this. It seems completely wrong to ignore the CodeRegion when searching for a function via an address. This leads to the spurious results that Will found.

**Comment by mxz297** [comment]
@hainest @wcohen I am sorry for overlooking this issue. My overall feeling is that there is no actual issues here, but there is some misunderstanding. 

To begin with, the ParseData class has two derived classes. One is the StandardParseData class, which represents binary where there is no overlapping addresses; executables and shared libraries fall into this category. The other one is the OverlappingParseData class, which represents binary where there are overlapping addresses; .a files fall into this category.

For binaries backed up by StandardParseData classes, an address can uniquely identify a code region and that's why the code region parameter for CodeObject::findFuncs is ignored as it is not necessary. The code region parameter is necessary for binaries backed up by OverlappingParseData classes as there could be multiple regions containing the same address.

Now, you can definitely argue that the interface is misleading or there is no proper documentation... 

@wcohen In my opinion, if you do not work with .a or .o files, then you can simply ignore the code region parameter by passing a nullptr.

**Comment by wcohen** [comment]
All the files the code is working with are executable binaries or shared libraries.  It would be good if the documentation mentioned this situation where code regions are not needed.  I spent some time trying to figure out how to pass some code region into the findFuncs method:

https://sourceware.org/git/?p=systemtap.git;a=blob;f=analysis.cxx;h=2c0da978a920360438868315af2fa8ea35a5d8f2;hb=refs/heads/wcohen/analysis#l225

In this application can eliminate the search for a CodeRegion and simplify things a little.

**Comment by wcohen** [comment]
Breaking ABI in option 2 seems less attractive.  Wouldn't there be cases where dyninst is used to analyze .o/.a files that the code region will need be be used when using the OverlappingParseData class methods?  Removing the parameter would mean that methods with same name from the different subcasses would now have different signatures.  Seems like approach 1 explaining when CodeRegion is required would make things less different analyzing .o/.a files and completely linked binaries.

**Comment by hainest** [comment]
@wcohen You're right. I didn't notice that these are overriding methods. This is an example where inheritance should not have been used to represent polymorphism. I guess all we can do is document it.
