### ISSUE TITLE
Build failure after removal of boost_system library

### ISSUE THREAD

**Issue by kupsch** [dyninst/dyninst#1114]
**Intention**
Build without failure on systems where dyninst downloads and builds Boost

**Describe the bug**
PR #1112 that removes the boost_system library to fix issue #1111 creates a regression if boost is downloaded and built as part of building dyninst. This is due to the build using version 1.67.0 that requires linking with the boost_system library.

Changing the boost version in cmake/Boost.cmake to 1.69.0 from `set(_boost_min_version 1.67.0)` to `set(_boost_min_version 1.69.0)` allows the build to successfully complete.

**Comment by hainest** [comment]
We *really* need to get rid of those from-sources build. Are you making a PR for this? If not, I will.
