### ISSUE TITLE
Segfault during traversal of slice generated in StackMod

### ISSUE THREAD

**Issue by morehouse** [dyninst/dyninst#113]
On some binaries in SPEC CPU2006 (e.g., Xalan), the backwards slicing check for skipRegs gets a slice of size 1 and segfaults.  We need to determine whether the backwards slicing check even makes sense in the first place.  If it does, we need to handle the case where we get a slice of size 1.  Otherwise, we should replace the check with something more appropriate.

**Comment by wrwilliams** [comment]
Is this fixed by f520de3f49adb2cb3787e0004b11755305a90b96?

**Comment by morehouse** [comment]
No, it's not.  I was getting this issue on the master branch before applying any of my most recent commits, and I had seen it on my local working repository as discussed in the last meeting.

**Comment by jdetter** [comment]
@morehouse  this isn't a VEX issue right?

**Comment by morehouse** [comment]
@jdetter Nope, right now this looks like either a StackMod issue or a slicing issue.

The backwards slice is being used to check for registers with dependence graphs that are linear chains (i.e. no matter what path is followed through the CFG, the contents of the register will always be the same value relative to the registers it depends upon).  My current understanding is that such registers are marked as "skipRegs" since we only need to update the stack height of the first register in the chain in order to safely move the stack object being referenced by the registers in the chain (assuming other safety checks pass, of course).

After a little more investigation, I should have a fix for this issue.

**Comment by morehouse** [comment]
Actually, it seems that my initial evaluation of skipRegs was incorrect.  Whether they were originally intended to work as I described or not, the implementation of adhocMovementTransformer actually seems to cause _extra_ displacement modifications to instructions accessing the stack through skipRegs.

In every case I've examined so far, the skipReg displacement modifications are either the same as normal displacement modifications or are wrong.  This seems to suggest that the backwards slicing check for skipRegs should be removed altogether.

I'm currently testing the effect of such a change on the SPEC CPU2006 suite.

**Comment by morehouse** [comment]
Removing all checks for skipRegs had an excellent effect on the SPEC suite when instrumenting with stack canaries.  Previously, 6 binaries in the suite were giving erroneous output due to improper stack modifications.  Now all binaries give correct output.

I'm going to retest the SPEC suite with stack diversification in case skipRegs have a different effect in that situation.  If that test goes well, I'll push up a patch.
