### ISSUE TITLE
datflowAPI: switch fall throughs

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1138]
There are some switch statements that fall through in https://github.com/dyninst/dyninst/blob/master/dataflowAPI/src/ExpressionConversionVisitor.C#L60. I'm not sure why the compiler warnings are picking these up. Maybe the flags are getting trampled when building the dataflowAPI toolkit?

@kupsch These don't need to be fixed before 12.0. This is just here for a reminder.

**Comment by kupsch** [comment]
After a bit of investigation, I found the cause of the problem.  40 of the files in parseAPI are in a group called ROSE_SRC and this group adds `-w` to the C++ compilation flags.  `-w` means disable all diagnostic output. It is also hard to spot on the command line.  The comment for this says: _FIXME: Rose needs a bunch of warning cleanup_.

There are an additional 1323 diagnostic messages to clean up (in ~400 unique locations in the code. If `-w` is removed.

**Comment by hainest** [comment]
Whoa. I'm curious if we need to upgrade to a newer version of the ROSE source. In either case, let's not work on that right now...

**Comment by kupsch** [comment]
I was thinking the same thing on both points.
