### ISSUE TITLE
glibc rendezvous structure uninitialized in glibc 2.34+

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1155]
@stanfordcox Reports

>seeing this with the "rawhide", latest but not released yet kernel and glibc: mutated:
/home/scox/dyninst-11.0.1/src/dyninstAPI_RT/src/RTlinux.c:412: r_debugCheck: Assertion `_r_debug.r_map' failed.
make: *** [Makefile:22: test] Aborted (core dumped)

>So the symptom is a static mutated executable fails as above.   I see what is going on: something changed in the recent runtime environment and now _r_debug, the dynamic linker rendevous struct, cannot be accessed.  I'll ping the glibc folks and figure out a resolution.

>possibly related to glibc commit a93d9e03a  Extend struct r_debug to support multiple namespaces [BZ #15971]

---

Bugzilla [15971](https://sourceware.org/bugzilla/show_bug.cgi?id=15971) says the extended namespace changes won't go in until 2.35 (scheduled for ~Feb 2022). Yet, this is showing up in 2.34 (2.33 is confirmed unaffected). The full commit is (https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=a93d9e03a31ec14405cb3a09aa95413b67067380;hp=885762aa31d75de8b9fea4c0e2e372b582d4c548).

**Comment by stanfordcox** [comment]
glibc has this comment in reference to _r_debug:
_/* This structure communicates dl state to the debugger.  The debugger
   normally finds it via the DT_DEBUG entry in the dynamic section, but in
   a statically-linked program there is no dynamic section for the debugger
   to examine and it looks for this particular symbol name.  */_
If I understand things correctly, dyninst always uses _r_debug to access struct link_map *r_map
It is also possible, as mentioned above, to use DT_DEBUG.  I coded up a standalone example (attached)
The change came with the glibc namespace change but I am wondering about:
1. If binary is static, no change, use _r_debug
2. If binary is dynamic, go through .dynamic section, find DT_DEBUG, and use that to get the link map (as shown in test)
I'll take a stab at a patch that does that.   Wondering where the code to get DT_DEBUG should go, maybe
[tstdyn.txt](https://github.com/dyninst/dyninst/files/7598803/tstdyn.txt)
 unix.C

**Comment by stanfordcox** [comment]
Looking into a solution that does not rely on _r_debug:  go through program header table, find PT_DYNAMIC (dynamic segment), find DT_DEBUG in dynamic segment which is equivalent to _r_debug.  Cannot rely on _DYNAMIC (as I understand it) dyninst moves the link map, PT_DYNAMIC in the program header is reset,  but _DYNAMIC retains its original value.

**Comment by stanfordcox** [comment]
Need more testing but I have dyninst where it will keep the _DYNAMIC symbol up to date (dyninst adds and changes segments, updates the phdr but did not bother with _DYNAMIC) so changing the runtime to use _DYNAMIC to go through the DT_ array to find DT_DEBUG instead of relying on _r_debug

**Comment by stanfordcox** [comment]
Okay we have a simple fix from the glibc folks, remove:
 DLLEXPORT struct r_debug _r_debug __attribute__ ((weak));
in RTlinux.c.  Explanation:
Previously there was a dynamic relocation against _r_debug in the loader which picked up the interposed definition.
Now we use a direct internal hidden symbol reference, so we don't update the interposed object anymore.  So we don't update the interposed object anymore.
