### ISSUE TITLE
Outdated SymtabAPI Document

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/dyninst#1187]
**Intention**
Call hasLineInformation for SymtabAPI::Module as indicated in the symtabAPI document for dynisnt 12.0

**Describe the bug**
hasLineInformation is not longer a member function of Module

**Comment by bbiiggppiigg** [comment]
Module::getAllVariables is also removed.

**Comment by hainest** [comment]
`hasLineInformation` was removed by 0dee1c8f86d in 2016. `getAllVariables` was removed by b3ad134512 seven months ago. The commit message notes that the function's declaration was added in 2009, but never defined. Going over the docs has been on my general TODO list for a long time.

**Comment by vsoch** [comment]
@hainest any reason the docs can't render into an interface instead of needing to dig up pdf?

**Comment by hainest** [comment]
@vsoch I've been debating if we should just chuck them into github.io or take the time to convert them into Sphynx for readthedocs.io. I like the versioning feature in readthedocs, but I couldn't figure out if github.io has that. It would be great to do a compare-and-contrast (including some other service I don't know about) to get a better idea. It's yet another Dyninst thing that I've wanted to do for a long time.

Additionally, our documentation has a lot of code snippets that have never been updated. It would be amazing if we could include compiling them as part of our doc changes/releases.

**Comment by vsoch** [comment]
> Additionally, our documentation has a lot of code snippets that have never been updated. It would be amazing if we could include compiling them as part of our doc changes/releases.

If you need compiling and versions (I would suggest for a C++ project) you probably want readthedocs. 

How are they currently generated?

**Comment by hainest** [comment]
>If you need compiling and versions (I would suggest for a C++ project) you probably want readthedocs.

I was leaning toward readthedocs. I just dread converting the LaTeX to Sphinx. Pandoc can convert LaTeX to reStructuredText that can then be consumed by Sphinx. But all of the code examples and figures will have to be imported by hand (at least as far as I could tell).

>How are they currently generated?

I manually update the LaTeX files and run pdflatex to make PDFs. Those are then stored in the dyninst/dyninst repo. There are two Word documents that get similar treatment. It's all very manual and error-prone right now.
