### ISSUE TITLE
Power ABI v2 abstractions

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#119]
From Bill:

The PowerPC ABI version 2 has separate local and global entry points for functions. We need to determine whether it is best to treat this as shared code, as a stub tail-calling another function via fallthrough, as a multiple-entry-point function, or as an elided stub much like PLT stubs. We further need to determine whether and how to create, adjust, or annotate the symbols that are present in the binary to reflect useful information to the user.

**Comment by wrwilliams** [comment]
The PowerPC ABI version 2 has separate local and global entry points for functions. We need to determine whether it is best to treat this as shared code, as a stub tail-calling another function via fallthrough, as a multiple-entry-point function, or as an elided stub much like PLT stubs. We further need to determine whether and how to create, adjust, or annotate the symbols that are present in the binary to reflect useful information to the user.

**Comment by mxz297** [comment]
Obsoleted
