### ISSUE TITLE
Rewrite exception handlers to adjust for relocated code

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#121]
From Bill:

C++ exception handlers determine the appropriate catch blocks to handle a piece of code based on the PC where the exception was thrown. When an exception occurs in relocated code, that PC is not covered by any exception handler unless that exception handler had a range of "whole address space". This results in incorrect behavior and unexpected termination of instrumented C++ that relies on successful catch block execution.

We need to rewrite the .eh_frame section and augment or overwrite it with entries mapping relocated code ranges to the appropriate catch code. Alternately, we could hijack the input PC to the throw routine and adjust it back to an original PC. The first approach probably produces faster execution, but perturbs the original binary more. It does allow us to add exception handling for any exceptions thrown by instrumentation, if and when that proves desirable. The second approach is much simpler to implement in the dynamic case, but requires that the mutator's relocated->original translation map be encoded into the mutatee in the rewriter case; it is likely to be modestly more expensive during execution as well. It does not allow us to add new exception handling entries, and will implicitly force exceptions occuring during instrumentation to the same handlers that cover the address of the instpoint where that instrumentation was inserted.

**Comment by wrwilliams** [comment]
C++ exception handlers determine the appropriate catch blocks to handle a piece of code based on the PC where the exception was thrown. When an exception occurs in relocated code, that PC is not covered by any exception handler unless that exception handler had a range of "whole address space". This results in incorrect behavior and unexpected termination of instrumented C++ that relies on successful catch block execution.

We need to rewrite the .eh_frame section and augment or overwrite it with entries mapping relocated code ranges to the appropriate catch code. Alternately, we could hijack the input PC to the throw routine and adjust it back to an original PC. The first approach probably produces faster execution, but perturbs the original binary more. It does allow us to add exception handling for any exceptions thrown by instrumentation, if and when that proves desirable. The second approach is much simpler to implement in the dynamic case, but requires that the mutator's relocated->original translation map be encoded into the mutatee in the rewriter case; it is likely to be modestly more expensive during execution as well. It does not allow us to add new exception handling entries, and will implicitly force exceptions occuring during instrumentation to the same handlers that cover the address of the instpoint where that instrumentation was inserted.

**Comment by fche** [comment]
If the full solution proves too difficult to do soon, would you consider a weaker one?  Namely, instead of supporting instrumenting such programs fully, dyninst could at least _detect_ that an as-yet-unsupported exception throwing process is in progress.  If it detects it, it could signal a warning (before the inevitable SEGV).  It could maybe even undo its own earlier modifications to the target program image, so that the program can be resumed safely.  It could maybe even do this temporarily, and restore the instrumentation after the exception handling process is complete.

Anyway, I don't know which of the above is practical, or much less effort than the full solution.  I am just putting these ideas out there so that y'all consider an intermediate solution for people who are impacted by this now.

**Comment by jdetter** [comment]
@wrwilliams Can I start working on this one? I think I would have a good idea on how to implement this.

**Comment by wrwilliams** [comment]
Sure; let's find some time early next week to talk about your plan/early results.

**Comment by wrwilliams** [comment]
I realized this morning that if we can guarantee cxa_throw is never inlined, there's a simple and proportional approach. @jdetter and I talked about solving this with call emulation; the additional insight is that at maximum we need to emulate calls in functions meeting the following:

1) function is relocated, AND
2) function has catch blocks OR
3) function has non default unwinding recipe

Much simpler than modifying eh_frame and still cheap.

**Comment by jdetter** [comment]
Call emulation seems like a solid approach to me, but won't that be detectable by malware like you were saying?

**Comment by wrwilliams** [comment]
Whether it is or not, that certainly shouldn't stop us from implementing something that works with normal exception handling.

**Comment by jdetter** [comment]
Branch `release9.2/fixes/eh_frame_rewriting` pushed. The fixes we discussed seem to work on my test binaries. However, I had to add a change that includes the boundary byte in the exception block:

```
 SYMTAB_EXPORT bool ExceptionBlock::contains(Offset a) const
  { 
 -   return (a >= tryStart_ && a < tryStart_ + trySize_); 
 +   return (a >= tryStart_ && a <= tryStart_ + trySize_); 
  }
```
*Note: only change is the `<` was changed to `<=`.*

The reason I had to change this is because the offset we are given to check if it is exception sensitive was `0xd73`. Looking at the code, this address should actually be exception sensitive:

**ASM**
```
 d6a:   55                      push   %rbp
 d6b:   48 89 e5                mov    %rsp,%rbp
 d6e:   53                      push   %rbx
 d6f:   48 83 ec 18             sub    $0x18,%rsp
 d73:   e8 b8 ff ff ff          callq  d30 <_Z9function2v>
 d78:   eb 5f                   jmp    dd9 <_Z9function1v+0x6f>
 d7a:   48 83 fa 01             cmp    $0x1,%rdx
 d7e:   74 08                   je     d88 <_Z9function1v+0x1e>
 d80:   48 89 c7                mov    %rax,%rdi
 d83:   e8 58 fe ff ff          callq  be0 <_Unwind_Resume@plt>
 d88:   48 89 c7                mov    %rax,%rdi
 d8b:   e8 40 fe ff ff          callq  bd0 <__cxa_begin_catch@plt>
```

**C**

```
void function1(void)
{
    try
    {
        function2();
    } catch(std::exception& e)
    {
        std::cout << "Caught exception!" << std::endl;
    }
}
```

However, Dyninst defines the block starting at address `0xd73` and ends at address `0xd78`, which does not include `0xd78`. Before the change, the test failed, and after the change the test passed. @wrwilliams Does this seem like it's a valid change or is something else wrong here?

**Test output (with change)**
```
Checking exception block: 0xd73 0xd78
Offset: 0xd78  Address: 0xd78
>>>>>> Sensitive
```

**Comment by wrwilliams** [comment]
Ah, I think I see the problem here. We need to relocate *all* calls in a function that has *any* catch blocks, not just calls in try blocks or catch blocks. EB::contains is correct (it's getting everything in the try, nothing in the catch, which is as expected) but the logic should be at the function level and not consider the location in the function at all.
