### ISSUE TITLE
Use libabigail action in CI

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1218]
https://github.com/buildsi/libabigail-action

**Comment by vsoch** [comment]
I can help here! Do you want to test with the latest release, main branch, or both? Since we use a container for testing we will need to modify the action for that.

**Comment by hainest** [comment]
That's a good question. There is definitely value in checking this on every PR submission so long as the liabigail checks aren't too expensive. In your experience, do you have a rough idea of how long they take?

I'm assuming that by checking every PR that would necessarily ensure that every release is non-breaking (unless we explicitly want it to be)?

**Comment by vsoch** [comment]
Unless you provide binaries with releases it usually means building both side by side so it will take the same time as testing! And the basic info I need to get started are 1. Where are the libs to compare (in the view I think?) and 2. Which ones do you want to check?
