### ISSUE TITLE
Compiler warnings when using CMAKE_BUILD_TYPE=MINSIZEREL

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#1229]
src/elf/src/Elf_X.C: In member function ‘Dyninst::Architecture Dyninst::Elf_X::getArch() const’:
    src/elf/src/Elf_X.C:1841:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
     1841 |                     default:
          |                     ^~~~~~~
    src/elf/src/Elf_X.C:1849:9: note: here
     1849 |         default:
          |         ^~~~~~~
    src/common/src/dyn_regs.C: In member function ‘unsigned int Dyninst::MachRegister::size() const’:
    src/common/src/dyn_regs.C:343:35: error: this statement may fall through [-Werror=implicit-fallthrough=]
      343 |                                   }
          |                                   ^
    src/common/src/dyn_regs.C:345:9: note: here
      345 |         case Arch_amdgpu_cdna2:{
          |         ^~~~
    src/common/src/dyn_regs.C:386:36: error: this statement may fall through [-Werror=implicit-fallthrough=]
      386 |                                    }
          |                                    ^
    src/common/src/dyn_regs.C:389:9: note: here
      389 |         case Arch_aarch64:{
          |         ^~~~
    src/common/src/dyn_regs.C: In member function ‘void Dyninst::MachRegister::getROSERegister(int&, int&, int&)’:
    src/common/src/dyn_regs.C:1261:90: error: ‘firstRegId’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     1261 |                                                           n = armv8_simdfpr_v0 + (baseID - firstRegId);
          |                                                                                  ~~~~~~~~^~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors
    make[2]: *** [elf/CMakeFiles/dynElf.dir/build.make:63: elf/CMakeFiles/dynElf.dir/src/Elf_X.C.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:756: elf/CMakeFiles/dynElf.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    cc1plus: all warnings being treated as errors
    make[2]: *** [common/CMakeFiles/common.dir/build.make:258: common/CMakeFiles/common.dir/src/dyn_regs.C.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:702: common/CMakeFiles/common.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

I freely admit I am stumped as to why this wasn't detected with the other build types.

**Comment by kupsch** [comment]
This is due to cmake (reasonably) defining NDEBUG in the default compiler flags for RELEASE build types (RELEASE, RELWITHDEBINFO, and MINSIZEREL). This has the affect of turning assert into nothing, but dyninst uses asserts as a fatal error handling mechanism by using a parameter that always evaluates to false. Because of this it is not valid to remove these asserts by defining NDEBUG as this turns the function that will not return into one that does resulting in unexpected paths through the code.

The code was previously tested with build types of DEBUG, RELEASE, and RELWITHDBGINFO.

**Comment by hainest** [comment]
Ah, yes, of course. I'd imagine no one was using that build type as it would effectively break Dyninst.
