### ISSUE TITLE
 Each download failed!

### ISSUE THREAD

**Issue by kimiwanano** [dyninst/dyninst#1278]
I found the following error when installing Dyninst:
![QX@0OQTSIKQOUO)T 53($S](https://user-images.githubusercontent.com/76025773/173522830-3bdf4259-44b6-4bae-add2-61ae069fe6b6.png)

I tried to access the address directly, but it was no longer accessible. Then I tried to change the address to https://src.fedoraproject.org/repo/pkgs/libdwarf/libdwarf-20130126.tar.gz 
but it does not work, so how do I solve this problem

**Comment by hainest** [comment]
It looks like you are trying to use an unsupported version of Dyninst. Please update to the latest version.
