### ISSUE TITLE
Logic behind Slicer::kills prevents slicing function arguments

### ISSUE THREAD

**Issue by sonicyang** [dyninst/dyninst#1280]
Hi

I am currently slicing backwards, between functions.
I have a call graph at hand and want to vind the value of a register, let's say `rdi`, in function A.
Function A is called by function B.
According to SystemV ABI, `rdi` is the first parameter.
So I am essential trying to do constant propagation from B to A, via the first function parameter.

However, when I do a backward slicing, returning B in `Predicate::followCallBackward` when slicing from A.
The candidate `rdi` is removed inside `Slicer::kills` during `Slicer::updateAndLink`.
I understand to motivation of removing any candidate that is the output of the current assignment.
But I don't get the reason why the function argument registers and `r11`register are removed in a call/syscall instruction. (I assume r11 is related to system call ABI.) 
This seemed to prevent slicing the function parameters to me.
https://github.com/dyninst/dyninst/blob/0665983154cda40a9dcde1ef58aeced47ee03e4a/dataflowAPI/src/slicing.C#L1535-1542

This behavior puzzled me.
Can anyone kindly explain the reason to me?
Am I missing anything or getting anything wrong?

**Comment by hainest** [comment]
@kupsch I believe you were looking at this before you founded the stripped parsing issue. Do you have any immediate/incomplete notes here?
