### ISSUE TITLE
local_var.h

### ISSUE THREAD

**Issue by lee218llnl** [dyninst/dyninst#1300]
I am the main developer of STAT and STAT is a consumer of local_var.h. I noticed that this header was removed in DynInst 12. Would it be possible to make the inclusion of this header optional in DynInst itself? Alternatively, could you make it a variant in the Spack package? This isn't critical, as I can always manually copy the header or have STAT's build system download the local_var.h file from github. @mplegendre let me know if you have any ideas too.

**Comment by hainest** [comment]
Oh, I see what happened. That file was removed as part of a cleanup effort in d42b659106. But there were two public header files that went from being explicitly named in a Makefile to being implicitly included via a CMake glob- one of which was local_var.h. I'll restore them so they are present in our next release and add STAT to our list of applications to test before doing a release. Mea culpa!
