### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by rain6851** [dyninst/dyninst#1306]
/usr/bin/ld: CMakeFiles/symtabAPI.dir/src/Object.C.o: in function `tbb::cache_aligned_allocator<tbb::interface5::internal::hash_map_base::bucket>::deallocate(tbb::interface5::internal::hash_map_base::bucket*, unsigned long)':
/usr/include/tbb/cache_aligned_allocator.h:88: undefined reference to `tbb::internal::NFS_Free(void*)'
/usr/bin/ld: /usr/include/tbb/cache_aligned_allocator.h:88: undefined reference to `tbb::internal::NFS_Free(void*)'
/usr/bin/ld: /usr/include/tbb/cache_aligned_allocator.h:88: undefined reference to `tbb::internal::NFS_Free(void*)'
/usr/bin/ld: CMakeFiles/symtabAPI.dir/src/Object.C.o: in function `tbb::spin_rw_mutex_v3::scoped_lock::acquire(tbb::spin_rw_mutex_v3&, bool)':
/usr/include/tbb/spin_rw_mutex.h:118: undefined reference to `tbb::spin_rw_mutex_v3::internal_acquire_reader()'
/usr/bin/ld: CMakeFiles/symtabAPI.dir/src/Object.C.o: in function `tbb::spin_rw_mutex_v3::scoped_lock::upgrade_to_writer()':
/usr/include/tbb/spin_rw_mutex.h:127: undefined reference to `tbb::spin_rw_mutex_v3::internal_upgrade()'
/usr/bin/ld: CMakeFiles/symtabAPI.dir/src/Object.C.o: in function `tbb::spin_rw_mutex_v3::scoped_lock::try_acquire(tbb::spin_rw_mutex_v3&, bool)':
/usr/include/tbb/spin_rw_mutex.h:162: undefined reference to `tbb::spin_rw_mutex_v3::internal_try_acquire_writer()'

**Comment by hainest** [comment]
Dyninst doesn't build with the latest versions of TBB. This is a known issue that I'm working on. If possible, try to use an older version. I know that 2019.2 works.
