### ISSUE TITLE
InstructionAPI Result type outputs wrong format string on certain types

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/dyninst#1310]
**Intention**
Disassemble a binary and check that the output assembly is correct

**Describe the bug**

https://github.com/dyninst/dyninst/blob/eea540a94564371d3170d01ab16c62ccbc8f9b9d/instructionAPI/h/Result.h#L441-L522

Result::format  is supposed to return its value in hex type, but for u48 / s48 / u64 / s64, the format function returns a formatted string in dec instead of hex.

And as ArchSpecificFormatters always prepend "0x" to the format string of Immediate, value 48 will be incorrectly outputted as 0x48 when it is of type s64.
https://github.com/dyninst/dyninst/blob/eea540a94564371d3170d01ab16c62ccbc8f9b9d/instructionAPI/src/ArchSpecificFormatters.C#L98-L99

https://github.com/dyninst/dyninst/blob/eea540a94564371d3170d01ab16c62ccbc8f9b9d/instructionAPI/src/ArchSpecificFormatters.C#L158-L159

https://github.com/dyninst/dyninst/blob/eea540a94564371d3170d01ab16c62ccbc8f9b9d/instructionAPI/src/ArchSpecificFormatters.C#L214-L216

**To Reproduce**
Create a Result object with type mentioned above and call format on it.

**Comment by hainest** [comment]
Is this preventing you from doing work right now? This is something that will eventually get fixed when we move to Capstone.

**Comment by bbiiggppiigg** [comment]
It will just be annoying cause I will be looking at wrong offset values when working with assemblies.
I guess I can live with it.
Just note that this is not specific to AMDGPU, but for x86 and aarch64 as well, if they ever make use of these types.
