### ISSUE TITLE
InstructionAPI Instruction assignment operator won't update the formatter member

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/dyninst#1312]
**Intention**
Decode Instructions and output their format using the formatter corresponding to the architecture it decodes from.
Check [disassemble example](https://github.com/dyninst/examples/blob/master/disassemble/disassemble.cpp#L29)

**Describe the bug**
Since the formatter is of reference type, it can't be updated a default Instruction is constructed.
Which means the update in

https://github.com/dyninst/dyninst/blob/eea540a94564371d3170d01ab16c62ccbc8f9b9d/instructionAPI/src/Instruction.C#L215

will take no effect. 
(This line will be skipped when single stepping through Instruction::operator=() in gdb)

**To Reproduce**
Run the disassemble example on non-x86-64 platforms and check what formatter is actually used when calling instr.format()

**Expected behavior**
The formatter that corresponds to the architecture of which the Instruction is decoded from should be used.

**Additional context**
1. While it is possible to change the disassemble example and move the Instruction instr declaration into the loop and combined it with the assignment, I'm not sure if we should make a restriction that Instruction object should always be initialized with the correct architecture.
2. What would be the right fix for this? Changing the member to a pointer or an object?

**Comment by bbiiggppiigg** [comment]
@hainest @kupsch Any recommendation on how to fix this?

**Comment by hainest** [comment]
>Since the formatter is of reference type, it can't be updated a default Instruction is constructed.

I could be missing something obvious, but I don't see where there is a reference to a formatter object. The assignment in `Instruction::operator=` is legal because `arch_decoded_from` is a value type.

**Comment by bbiiggppiigg** [comment]
> > Since the formatter is of reference type, it can't be updated a default Instruction is constructed.
> 
> I could be missing something obvious, but I don't see where there is a reference to a formatter object. The assignment in `Instruction::operator=` is legal because `arch_decoded_from` is a value type.

Sorry I quoted the wrong line, description updated.

**Comment by bbiiggppiigg** [comment]
![image](https://user-images.githubusercontent.com/6196951/198098373-9c453aa6-8af8-47fa-9ed0-8363db3d9bb4.png)
