### ISSUE TITLE
callq instruction in instrumentation

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#1347]
While doing instrumentation, dynist replaces some callq instructions by pushq, movl and retq.  I believe this is required to avoid callq in instrumented code..
This decision is taken based on the instruction type. Dynist decides each type of instruction while opening the process (callq/indirect/conditional).
I noticed that some callq instructions are also considered as indirect. 
My question is:
How  and where dynist decides the type of instruction? Is it possible  to change the instruction type for some instructions? If I do so will it make any -ve impact?

The following  instruction is considered as indirect by dynist. I want to avoid callq here and if possible replace it by  pushq, movl and retq.
callq  *%rdx

Can someone suggest?

**Comment by hainest** [comment]
I'm not sure there is a way to change the semantics of a call instruction (indirect/conditional). Everyone else is on vacation right now, so it will be a few days before we can get you a more useful answer.

**Comment by ManojKumarChauhan** [comment]
Instruction like "callq *%rdx" is not considered because it's a dynamic call and doesn't get resolved. 
Parser::ProcessCFInsn resolves only those which are not dynamic. (resolvable_edge = resolvable_edge && !dynamic_call;)
Can someone suggest a solution?
If it's not possible to resolve this instruction and keep it same in the instrumented code then is there any other solution?

**Comment by ManojKumarChauhan** [comment]
> I'm not sure there is a way to change the semantics of a call instruction (indirect/conditional). Everyone else is on vacation right now, so it will be a few days before we can get you a more useful answer.
Expecting a response.

**Comment by ManojKumarChauhan** [comment]
> I'm not sure there is a way to change the semantics of a call instruction (indirect/conditional). Everyone else is on vacation right now, so it will be a few days before we can get you a more useful answer.

Expecting a response.
Note-> In the instrumented code, callq *%rdx"  is having the correct address and it's calling the same function.

**Comment by ManojKumarChauhan** [comment]
Hi,
I didn't get any reply.
There is one different case where the semantics of callq instruction is not required to change. Here the instrumented code is not working.

Example
if there is nop instruction after callq
a0708e:       e8 2d c6 00 00          callq  a136c0  testfunction1
  a07093:       90                      nop


Here dynist considers the instruction nop as a one block.

The instrumented code crash after executing testfunction1.
Can someone suggest a solution?

**Comment by hainest** [comment]
It's difficult to see what is happening from the code snippets here. Could you add an attachment here or create a gist that contains a _minimum complete_ working example that demonstrates the issue? Please include both a source file that creates a binary to be modified (the mutatee) as well as a source file containing the usage of Dyninst that modifies the binary (the mutator).

**Comment by ManojKumarChauhan** [comment]
I will share all the required items to reproduce it

**Comment by ManojKumarChauhan** [comment]
Hi @hainest 
After analyzing the issue i noticed that it's coming after some interval.
Like if I instrument/wrap a function and hit the instrumented function then it works but If I hit it after some interval (5-10 minutes) then it got crash for following cases:
1. Show the fault address where NOP instruction is there
2. or crash when sleep function  is used in the main source

Any suggestion for that?
Now i have golang example ready with code but i'm trying to prepare c example

**Comment by ManojKumarChauhan** [comment]
@hainest
 Can I share the example of golang

**Comment by ManojKumarChauhan** [comment]
Hi @hainest 
I understand that golang is not yet supported so instead of sharing the producer I want to clear some doubt to solve it. Could you please help me to clear my doubts. 
I have tried with the master branch. I am facing the issue only for one wrap function while other wrap functions are working fine.
For that I need to explain with example

suppose there is a main function in binary
0000000000b11020 <mainfunc1>:
  b11020:       4c 8d 64 24 f8          lea    -0x8(%rsp),%r12
  b11025:       4d 3b 66 10             cmp    0x10(%r14),%r12
  b11029:       0f 86 26 02 00 00       jbe    b11255 <mainfunc1+0x235>
  b1102f:       48 81 ec 88 00 00 00    sub    $0x88,%rsp
  b11036:       48 89 ac 24 80 00 00    mov    %rbp,0x80(%rsp)
  b1103d:       00
  b1103e:       48 8d ac 24 80 00 00    lea    0x80(%rsp),%rbp
  b11045:       00
  b11046:       48 89 84 24 90 00 00    mov    %rax,0x90(%rsp)
  b1104d:       00
  b1104e:       e8 2d c6 00 00          callq  b1d680 <func2>
  b11053:       90                      nop
  b11054:       48 8b 0d 1d 20 5c 00    mov    0x5c201d(%rip),%rcx        # 10d3078 
  b1105b:       48 89 4c 24 30          mov    %rcx,0x30(%rsp)
.....

When I wrap this function using dynist, its definition will be change like
 0xb11020 <mainfunc1>:	jmpq   0x40b875a0
   0xb11025 <mainfunc1+5>:	cmp    0x10(%r14),%r12

0x40b875a0:	pushq  $0xfffffffff9150b60
   0x40b875a5:	movl   $0x7f0f,0x4(%rsp)
   0x40b875ad:	retq   
   0x40b875ae:	lea    -0x8(%rsp),%r12
   0x40b875b3:	cmp    0x10(%r14),%r12
   0x40b875b7:	jbe    0x40b877e3
   0x40b875bd:	sub    $0x88,%rsp
   0x40b875c4:	mov    %rbp,0x80(%rsp)
   0x40b875cc:	lea    0x80(%rsp),%rbp
   0x40b875d4:	mov    %rax,0x90(%rsp)
   0x40b875dc:	callq  0xb1d680 <func2>
   0x40b875e1:	nop
   0x40b875e2:	mov    -0x3fab4571(%rip),%rcx        # 0x10d3078 
   0x40b875e9:	mov    %rcx,0x30(%rsp)
...
Here the wrapper function definition exists at 0x7f0f9150b60

Crash is coming after calling func2.. The crash comes after some interval and show the pc address 0x40b875e1.  This address contains nop.

My questions:
1. Original function exists at b11020 so runtime will have pcs like b11020,b11053
after wrapping the function is shifted at 0x40b875a0. Since these addresses are not in runtime pc list so how does dynist convert these addresses into b11020 range? When wrapping code executes the pc should in range starting from 0x40b875a0 but how dynist convert it into the range b11020?
2. it's crashing for the address 0x40b875e1 which is not in runtime pc list. Why runtime is expecting this address (in range starting from 0x40b875a0) while for other wrapping functions I didn't find any instrumented/wrapped address. Is there any place where I can print the current pc when the function executes to know what pc is used? Can we control runtime behavior to ignore these addresses? 
3. Crash is coming only when the main function calls some other function and there is nop instruction after calling function.

**Comment by ManojKumarChauhan** [comment]
Hi @hainest 
expecting a reply from you

**Comment by hainest** [comment]
>When I wrap this function using dynist, its definition will be change like

When you say you wrap the function, what do you mean by that? What does the mutator do? Are you doing static or dynamic instrumentation? Is it a DSO or executable? We can't look at a sequence of assembly and exactly know what you wanted Dyninst to do because it uses heuristics to accomplish its tasks. This is why we always ask for a mutator and mutatee when diagnosing crashes.

>Since these addresses are not in runtime pc list so how does dynist convert these addresses into b11020 range?

What do you mean by _runtime pc list_?  If you are doing rewriting, Dyninst will adjust all of the target addresses for jumps/calls/loads/stores that refer to the original code block.

>it's crashing for the address 0x40b875e1 which is not in runtime pc list. 

How is it crashing? SEGFAULT? SIGILL? ...

**Comment by ManojKumarChauhan** [comment]
I am using BPatch_addressSpace::wrapFunction for a running process. The mutator wrap a function of running binary.
The wrapped function executes its own code. All the wrap functions are working fine besides the one.

The crash is coming in the binary for unexpected runtime pc. 
What is runtime pc:
When I compile a binary it makes a list of all the pcs from all the functions of binary. When I run the binary then each current pc is searched in the list of stored pc. If the pc doesn't match then there will be a crash due to unknown pc.
When binary is run without using dynist then each current pc will always match in the list.  

what is each current pc-> Suppose binary calls function1 from function 2
function2 definition
0x1000
....
0x1010  callq function1
 0x101f NOP
when function2 calls function1 the current pc is  0x101f. This will always match in the stored list.

Why crash is coming:
Suppose I wrap function2. Dynist will move the definition of function2 at a new address say 0x4000. This new address will never be in the list of stored pc for binary. When user hit a command to execute function2, the wrapped function will actually execute and the current  pc will never be in the address range 0x4000. It's working fine but if the user executes the same function after some interval (3-5 minutes) then current pc comes in the range of 0x4000. This is happening only for the case when NOP instruction exists after function1. If there is no NOP after callq then current pc will never be in the range of 0x4000.

Thats why I asked about how dynist converts the address range 0x4000 to 0x1000 and use 0x1000 range for current pc.

As you sad 
<<Dyninst will adjust all of the target addresses for jumps/calls/loads/stores that refer to the original code block.
Could you please give some more details. In which part of code I can check.

**Comment by hainest** [comment]
>When I compile a binary it makes a list of all the pcs from all the functions of binary. When I run the binary then each current pc is searched in the list of stored pc. If the pc doesn't match then there will be a crash due to unknown pc.
When binary is run without using dynist then each current pc will always match in the list.

For dynamic instrumentation, Dyninst will insert instrumentation code into any free space it can find that is of the correct size using inferior malloc. The chosen location may or may not be in your calculated list of PC values. For example, it might find some unused space at the end of a block where the compiler inserted padding bytes. As far as I know, there is no way to alter this behavior in Dyninst.

>When user hit a command to execute function2, the wrapped function will actually execute and the current pc will never be in the address range 0x4000. It's working fine but if the user executes the same function after some interval (3-5 minutes) then current pc comes in the range of 0x4000. This is happening only for the case when NOP instruction exists after function1. If there is no NOP after callq then current pc will never be in the range of 0x4000.

If Dyninst inserted code into an address range, then that code will always be executed when the relevant springboard is encountered (i.e., the location in the original code that jumps to Dyninst's instrumentation). Whether or not your program _detects_ this is an entirely different question. Based on the description, I would say functions that have a NOP after callq may have an extra delay that is perturbing the sampling frequency of your program. It is impossible for me to say anything further without a mutator and mutatee reproducer.

>> Dyninst will adjust all of the target addresses for jumps/calls/loads/stores that refer to the original code block.
> Could you please give some more details. In which part of code I can check.

That statement is, as far as I know, only true for static instrumentation. Because Dyninst can't rewrite a running binary to which it is attached, it just uses trampolines to insert instrumentation code.

@kupsch @bolo Any additional corrections/clarifications/thoughts?

**Comment by ManojKumarChauhan** [comment]
I am using master branch. I have mutator codeCoverage.C and a go binary.
Can I attach that?

**Comment by ManojKumarChauhan** [comment]
> If Dyninst inserted code into an address range, then that code will always be executed when the relevant springboard is encountered (i.e., the location in the original code that jumps to Dyninst's instrumentation). Whether or not your program _detects_ this is an entirely different question. Based on the description, I would say functions that have a NOP after callq may have an extra delay that is perturbing the sampling frequency of your program. It is impossible for me to say anything further without a mutator and mutatee reproducer.

I think this is not a different question. original code that jumps to a new location contains new pcs which are not in my binary's pc list. For me there are 2 options:
1. Add the new pcs into binary pcs list   
this seems not possible
2. convert new pcs into original pcs
For that I used https://github.com/mxz297/dyninst branch where it converts using unwinding library but it's not working.

Can you suggest me any solution?

**Comment by hainest** [comment]
>convert new pcs into original pcs

I'm not sure this is even possible. I don't think Dyninst can guarantee that the rewritten function has a one-to-one mapping between the old and new addresses. For example, it might insert additional code to save function parameters or adjust the stack based on calling conventions. I think it's just a hard problem.
