### ISSUE TITLE
ABI changes from v9.2.0 to v9.2_patches

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#136]
Just looking at public headers, there are two obvious groups of changes, both from `common/`.  In `dyn_regs.h`, many register variables have been added.  In `entryIDs.h`, a handful of new enum values are added, but since these are added in the middle, they will change all of the values that follow.
[diff-headers-dyninst-v9.2.diff.gz](https://github.com/dyninst/dyninst/files/394528/diff-headers-dyninst-v9.2.diff.gz)

Using [libabigail](http://www.sourceware.org/libabigail/)'s `abipkgdiff`, we can confirm that these are the only real changes, as well as see the function paths where these are exposed.
[abipkgdiff-dyninst-v9.2.log.gz](https://github.com/dyninst/dyninst/files/394527/abipkgdiff-dyninst-v9.2.log.gz)

The plain additions are generally fine for backward compatibility, but not forward.  That is, something which links against the new library may not be able to run with the older library, if it used new symbols.

The existing enum entries which changed their values are a bigger problem, both forward and back.

**Comment by jdetter** [comment]
Are the `entryIDs` a big deal? Just instruction names will be off but that should affect their decoding besides the fact that `format()` will return the wrong name. I could move them to the end of the enum if it's something we should be worried about.

**Comment by jdetter** [comment]
We could also move the x86 register declarations, those were added because a user was able to generate 32 bit code that used YMM registers. We don't necessarily need the 32 bit version of `k0` through `k7` and `ZMM0` through `ZMM31`, I just put them in there to be safe. I don't think AVX512 instructions are valid in 32 bit mode and there will never be a 32 bit intel chip that implements AVX512. The YMM register declarations should be the only ones we for sure need there.

**Comment by cuviper** [comment]
It depends how they are used.  If a library user is ever producing these `entryID` values, then they certainly need to numerically agree with the library itself.  If they're only ever consumed by the user, and especially if only indirectly as something like formatted strings, then it probably doesn't matter.

On the registers, I don't really have any objection to specific additions, just that ABI needs to be considered when *anything* is added.

**Comment by jdetter** [comment]
16fce865a6729b90f4a2443e0c2a6d7977010bca and b47e64d880de6a39375d56f37d8506039d24e86d would need to be reverted to fix the `entryIDs` ABI issue.

**Comment by cuviper** [comment]
If you all are OK with losing this new functionality in 9.2.1, then reverting is certainly the easiest fix.  Are there any serious drawbacks if we don't have these things?

**Comment by jdetter** [comment]
Yeah I think it would be fine to revert those commits. Those instructions are pretty rare/old and there are newer versions of those instructions available (in KNL for example). If the implementation has to wait for 9.3.0 that's totally fine with me.

I have the patch ready, I just want to run it through the testsuite really quickly and then I'll make another PR.

**Comment by cuviper** [comment]
How about the registers?  Can their addition also be deferred?

**Comment by cuviper** [comment]
I guess you said YMM is really needed -- what's the impact there?  Got a bug reference?

**Comment by jdetter** [comment]
Adding the YMM registers fixed #114.

**Comment by cuviper** [comment]
Then to take the question a different direction -- how likely is it that a library user would be referencing these symbols themselves?  IOW, are these truly public symbols, or more like "private" stuff that libcommon is exporting for other dyninst libraries?

If someone compiling against 9.2.1 is not likely to gain new references to these symbols, then it's not really much of an ABI break.

**Comment by jdetter** [comment]
It's probably not very likely but it's possible. The symbols are public and user's have access to their values. Based on DEF_REGISTER, it looks like there shouldn't be any value changes though:

```
#define DEF_REGISTER(name, value, Arch) \
  const signed int i##name = (value); \
  COMMON_EXPORT MachRegister name(i##name, Arch "::" #name)
```

I'm not sure if this would actually cause a user an issue. I would say if we want to be sure were not breaking the ABI, we shouldl just move it to 9.3.0.

**Comment by jdetter** [comment]
I just realized that this breaks the ABI here:

```
   namespace x86
   {
      const signed int L_REG = 0x00000100; //8-bit, first byte
      const signed int H_REG = 0x00000200; //8-bit, second byte
      const signed int W_REG = 0x00000300; //16-bit, first word
      const signed int FULL  = 0x00000000; //32 bits
      const signed int QUAD  = 0x00004000; //64 bits
      const signed int OCT   = 0x00002000; //128 bits
      const signed int FPDBL = 0x00001000; // 80 bits
      const signed int BIT   = 0x00008000; // 1 bit
      const signed int GPR   = 0x00010000;
      const signed int SEG   = 0x00020000;
      const signed int FLAG  = 0x00030000;
      const signed int MISC  = 0x00040000;
      const signed int KMASK = 0x00050000;
      const signed int XMM   = 0x00060000;
      const signed int YMM   = 0x00070000;
      const signed int ZMM   = 0x00080000;
      const signed int MMX   = 0x00090000;
      ...
```

For example, if someone used MMX in the old ABI, it would be interpreted as YMM in the new ABI.

**Comment by jdetter** [comment]
Actually, it looks like the dyn_regs changes made it into v9.3.0, if I'm looking at this correctly:

https://github.com/dyninst/dyninst/blob/3a6ad66df7294417cf61618acdcfcc0fecccb045/common/h/dyn_regs.h

**Comment by cuviper** [comment]
The actual `YMM`/etc. values came in f7e997ea78677, before 9.2.0.
These register definitions didn't come until after release, in 9bb05c69e9a6e.

**Comment by jdetter** [comment]
Yup, you're right. I can take just the register definitions out then.

**Comment by cuviper** [comment]
I just finished another abipkgdiff.  The only differences now are these register definitions.  This is purely a forward-compatibility issue, and fails in an obvious way since the loader just wouldn't find symbols on an older library.  So I could go either way, depending on how important that fix is to you.

**Comment by jdetter** [comment]
I opened #140. If you want to merge it to revert back to v9.2.0 that's fine with me or if you think that it won't cause any issues we can just leave the definitions in. Reverting the register definitions will cause the bug we talked about to reappear.

**Comment by cuviper** [comment]
Thanks, we're ABI-compatible again!
