### ISSUE TITLE
Potential Infinite Loop in emitElf.C

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/dyninst#1445]
**Describe the bug**
At 
https://github.com/dyninst/dyninst/blob/9696c64a3a1d6f41241d27c3c51820616490efa6/symtabAPI/src/emitElf.C#L2402
variable i is used as the loop index variable to iterate through new_dynamic_entries

But in its inner loop, at 
https://github.com/dyninst/dyninst/blob/9696c64a3a1d6f41241d27c3c51820616490efa6/symtabAPI/src/emitElf.C#L2432
variable i is used as the loop index variable to iterate through header 

**To Reproduce**
A binary with no .rel.dyn and .rela.dyn sections, but its target platform uses rel type relocation records.
https://github.com/dyninst/dyninst/blob/9696c64a3a1d6f41241d27c3c51820616490efa6/symtabAPI/src/emitElf.C#L2526-L2527
This kind of binary will create two additional new_dynamic_entries.
So when header->num_entries < new_dynamic_entries.size(), the loop variable will keep getting resetted. 

**Expected behavior**
The two loops uses two different index variable.

**Additional context**
This potential bug is discovered when attempting to instrument AMDGPU binaries and  is related to #1444 . 
Because an AMDGPU binary was previously incorrectly specified as using a rel relocation record, the loop index variable of the outer loop will keep getting resetted.

**Comment by hainest** [comment]
Let's update the code while we're fixing things here.

```
for (unsigned i = 0; i < new_dynamic_entries.size(); i++) {
    long name = new_dynamic_entries[i].first;
    long value = new_dynamic_entries[i].second;
```

could be written

```
for (auto const& entry :  new_dynamic_entries) {
    long name = entry.first;
    long value = entry.second;
```

Using a structured binding here would be ideal. We should _really_ consider moving to C++17...

---

The second loop will have to stay a C-style loop because it's iterating over a flexible array; although that thing isn't even legal C++...
