### ISSUE TITLE
Unable to read all instructions of elf format

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#1482]
Steps to reproduce:
1. Use dynist to attach to a running process.
2. Wrap a function.
3. Dynist will move the function to a new location and copy all its instructions.
4. The new location doesn't contain 7-8 instructions. Seems dynist missed those.

Issue-> Dynist is unable to copy all the instructions.
Process is of golang which has elf format. 
Dynist is unable to read instructions from 1d77979
[testfunc.zip](https://github.com/dyninst/dyninst/files/12366609/testfunc.zip)

**Comment by hainest** [comment]
Those instructions are all supported by Dyninst, so it's not a parser issue. Without a complete reproducer, it will be impossible to say what has happened.

**Comment by ManojKumarChauhan** [comment]
[instrcode.tar.gz](https://github.com/dyninst/dyninst/files/12375431/instrcode.tar.gz)
To reproduce the issue please follow below steps:
1. run a program(attached) in terminal 1
2. run dyninst application dynistinstructions on another terminal. dynistinstructions will call bpatch.processAttach to attach to the program running on terminal 1.
Source code for dynistinstructions is attached. It's compiled as
g++ -o dynistinstructions dynistinstructions.cpp -I pathofdyninstgeaders -Lpathofdynistlibraries -ldyninstAPI

I added a log in parseAPI/src/Parser.cpp
Parser::relink(ParseAPI::Edge * e, Block *src, Block *dst)
{
...
fprintf(stderr, "addresses %lx,%lx\n", src->start(),src->end());
...
}

Take objdump of the program running in terminal 1. 
Above code will not print the instructions after the address 1d77979

**Comment by ManojKumarChauhan** [comment]
Please get prog.tar.gz from https://uploadnow.io/f/pd7vD7V

**Comment by ManojKumarChauhan** [comment]
@hainest did you check the reproducer which I sent?

**Comment by hainest** [comment]
I haven't had a chance to look into this. The link to `prog.tar.gz` is expired. Could you repost it?

**Comment by ManojKumarChauhan** [comment]
https://uploadnow.io/s/cd3d892c-5ae8-4c60-a36f-92c37dfbe65d

Please get this

**Comment by hainest** [comment]
Thanks. I will try to look at this in the next day or so.

**Comment by hainest** [comment]
I'm not sure what Dyninst is doing here. I'll talk with the other devs and see if we can figure it out.

**Comment by ManojKumarChauhan** [comment]
OK. So what I understand here , dynist is not copying all the instructions of a function.
It's missing following instructions
1d77979:       48 8b 44 24 08          mov    0x8(%rsp),%rax
 1d7797e:       48 8b 5c 24 10          mov    0x10(%rsp),%rbx
 1d77983:       8b 4c 24 18             mov    0x18(%rsp),%ecx
 1d77987:       48 8b 7c 24 20          mov    0x20(%rsp),%rdi
 1d7798c:       48 8b 74 24 28          mov    0x28(%rsp),%rsi
 1d77991:       44 0f b6 44 24 30       movzbl 0x30(%rsp),%r8d
 1d77997:       e9 e4 fa ff ff          jmpq   1d77480 <r...>

I tried to debug it and found that the block with above instructions is not found by dynist. I don't know how dynist reads all the blocks and didn't find any document.
But i'm confirmed that it's missing some instructions.

**Comment by hainest** [comment]
There is some kind of parsing error. None of the blocks contains the address 0x1d77979.

```c++
#include "Symtab.h"
#include "CodeSource.h"
#include "CodeObject.h"
#include "CFG.h"
#include <iostream>
#include <algorithm>

namespace st = Dyninst::SymtabAPI;
namespace pa = Dyninst::ParseAPI;

int main(int argc, char *argv[]){
  if(argc != 2) {
    std::cerr << "Usage: " << argv[0] << " file\n";
    return -1;
  }
  
  auto *symtab_source = new pa::SymtabCodeSource(argv[1]);
  auto *co = new pa::CodeObject(symtab_source);
 
  auto const& funcs = co->funcs();
  auto *first = *funcs.begin();
  auto *last = *funcs.rbegin();
  
  std::cout << "Found " << funcs.size() << " functions in range ["
            << std::hex << first->addr() << ","
            << std::hex << last->addr() << ")\n";
  
  constexpr auto addr = 0x1d77979;
  bool found = false;
  for (auto *f : funcs) {
    for(auto b : f->blocks()) {
      if(b->containsAddr(addr)) {
        std::cout << f->name()
                  << "   [" << std::hex << b->start() << ", "
                  << std::hex << b->end() << ")\n";
        found = true;
        break;
      }
    }
  }
  
  if(!found) {
    std::cout << "Found no block for address " << std::hex << addr << '\n';
  }
}
```

  $ ./find_ranges ../influxd 
    Found 115657 functions in range [3f4aa3c,1d1a450)
    Found no block for address 1d77979

**Comment by hainest** [comment]
><24>   DW_AT_producer    : Go cmd/compile go1.17.13; regabi

This is a Golang binary. We have little experience with them, so these parsing issues are not surprising. Looking at the symbol table, there are some crazy names in there. Golang isn't a priority for us, so it will take some time to resolve this.

**Comment by ManojKumarChauhan** [comment]
@hainest I understand & completely agree that golang is not supported and you may take time to support it.
But elf format is standard which is applicable for golang and c/c++ binaries. I'm not sure but I believe the same problem may come in c/c++ binary.
If possible & if you have any document for parsing mechanism then please share OR please guide me so that I can try to solve it myself. I have gone through parseAPi/src/parser.cpp but didn't get where & how it's fetching each block.
