### ISSUE TITLE
Incorrect function boundaries for functions sharing code

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#149]
When parsing a binary provided by Victor van der Veen, parseAPI generated incorrect function boundaries for two functions that "share" code and the two functions do not have consistent block lists. The two functions do not share code actually and I will create another issue for this problem.

When parseAPI is parsing function f, if parseAPI reaches the entry block of function g, parseAPI will stop parsing f and later re-generate the block list of f. However, when parseAPI re-generate the block list of f, g may not have been fully parsed yet. So, later when g is fully parsed, f and g will have inconsistent block lists.

**Comment by wrwilliams** [comment]
Does #139 close this?
