### ISSUE TITLE
Non-returning functions from libstdc++ are not included in the non-returning function list

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#150]
When parsing a binary provided by Victor van der Veen, the non-returning function "_ZSt20__throw_system_error@plt" from libstdc++ is not identified as non-returning. If we apply our non-returning function analysis to commonly linked system libraries such as libc and libstdc++, we should be able to generate a more comprehensive list of non-returning functions.

**Comment by wrwilliams** [comment]
Has this list been generated and added?

**Comment by n738cu** [comment]
@mwkrentel , @mxz297 , @sashanicolas , @hainest : What's the status of this issue?

**Comment by mxz297** [comment]
@n738cu Mark's PR #748 addresses this issue.

**Comment by n738cu** [comment]
Please update the PR to cross reference this issue so that we know to close it.
