### ISSUE TITLE
Assertion failed with a bad DYNINSTAPI_RT_LIB

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#153]
It's certainly a user problem if they set the wrong `DYNINSTAPI_RT_LIB`, but dyninst could be a little more graceful about failing.  Here's a case I just saw:

```
$ export DYNINSTAPI_RT_LIB=[...]/libdyninstAPI.so    # not _RT!
$ ./runTests -test init_fini_callback
init_fini_callback         g++    none 64  create   NA      dynamic nonPIC  FAILED (Group Setup)
test_driver: [...]/dyninstAPI/src/ast.C:2069: virtual bool AstCallNode::initRegisters(codeGen&): Assertion `callee' failed.
*** Child terminated abnormally via signal 6.
init_fini_callback         g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)
```

**Comment by jdetter** [comment]
I have this issue all of the time, one time I didn't notice I didn't have `DYNINSTAPI_RT_LIB` set properly and the core dumps filled up my disk =P

**Comment by wrwilliams** [comment]
I'll note that the call node is not the place for graceful failure; we should have error checking when we create the call snippet re: whether we can actually find the callee. Asserting in the AstCallNode is entirely sensible to do.

**Comment by cuviper** [comment]
Perhaps we could use symtabAPI to sanity-check the symbols in `DYNINSTAPI_RT_LIB` before trying to use it anywhere?

It would also help a lot if Dyninst just determined this path itself, at least if it's not set.  I actually did this in our systemtap client, which you can see [here](https://sourceware.org/git/gitweb.cgi?p=systemtap.git;a=blob;f=stapdyn/dynutil.cxx;h=cd2ae11b7980400b4d247dcc6ebd0639977fbe13;hb=HEAD#l31) using `dl_iterate_phdr`.  Of course, that is OS-specific.

**Comment by wrwilliams** [comment]
I think that auto-detection is a saner approach. We'd want to move the code responsible for swizzling static/dynamic and 32/64 detection in there, obviously, but that should be trivial.

**Comment by wrwilliams** [comment]
@cuviper What's going to make 9.3.0 is a Unix-ish only autodetect of the RTlib based on the same library path resolution we use in binary rewriting. It will need a ton of refactoring to be more general/work on Windows, and won't yet handle the symbol checks, but it should address the main issue here (namely that one can shoot one's self in the foot by specifying something that exists but is not a RTlib at all).

I'll post a PR later today with this.
