### ISSUE TITLE
Fails to build with cmake when specifying custom elfutils dir

### ISSUE THREAD

**Issue by bbiiggppiigg** [dyninst/dyninst#1537]
**Intention**
Build Dyninst from source using cmake and specifies the elfutils install location

**Describe the bug**

**To Reproduce**

1. The handle -DLibElf_ROOT_DIR ( specified here: https://github.com/dyninst/dyninst/wiki/Building-Dyninst ) is not used by the project. 
2. Replacing it with ElfUtils_ROOT_DIR  (specified here: https://github.com/dyninst/dyninst/wiki/third-party-deps ) causes cmake to reports the following error
CMake Error at /home/opt/cmake-3.20.6/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibELF (missing: LibELF_LIBRARIES LibELF_INCLUDE_DIRS)
  (Required is at least version "0.186")
Call Stack (most recent call first):
  /home/opt/cmake-3.20.6/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibELF.cmake:102 (find_package_handle_standard_args)
  cmake/Modules/FindElfutils.cmake:67 (find_package)
  cmake/tpls/DyninstElfUtils.cmake:39 (find_package)
  CMakeLists.txt:40 (include)

**System (please complete the following information):**
x86_64 / master branch

Reported by an AMD employee who is trying to build Dyninst.

**Comment by kupsch** [comment]
If the variable `EU_DIR` points to the elf utils install and you are using the cmake flag `--DElfUtils_ROOT_DIR=$EU_DIR` do the files `$EU_DIR/lib/libelf.so` and `$EU_DIR/include/elf.h` exist? If `EU_DIR` points to an install of elfutils this works for me.

**Comment by hainest** [comment]
Just had a teams meeting with Hsuan-Heng and the AMD person. The problem is that binutils isn't installing from source correctly. Nothing to do on our end.
