### ISSUE TITLE
Missing htobe32 function under Visual Studio

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#16]
Broken by https://github.com/dyninst/dyninst/commit/080b3fac7422dc84c6e0d8a163fec12d8a3f002f#diff-79cd8ea5743e12f03821c4269fae3431R276
Visual Studio does not define a htobe32 function as far as I can tell.

**Comment by wrwilliams** [comment]
I can't find a clean endian swap outside of the network code either; boost has one but it's new in 1.58 (which is too new for us to depend on IMO). htonl will IIRC drag in a WinSock link dependency, which is absurd for an endian swap. Probably best addressed with the byte shuffling code that was there before, as Windows (in versions we support, at least) is guaranteed little-endian for the foreseeable future.

**Comment by pefoley2** [comment]
It looks like the "before" was simply not calling that function.
Maybe just ifdef it out if os==windows?

**Comment by pefoley2** [comment]
A cherry-pick of https://github.com/dyninst/dyninst/pull/19/commits/154b0307ac4d1c1a21f8cb4d02634b1ed5d35270 should resolve this issue.

**Comment by wrwilliams** [comment]
Fixed on master, as we've reverted to byte-swapping.

**Comment by pefoley2** [comment]
Still seems to be an issue at https://github.com/dyninst/dyninst/blob/master/dataflowAPI/src/RoseInsnFactory.C#L276

**Comment by wrwilliams** [comment]
Fixed by #77.
