### ISSUE TITLE
make install not working on latest master

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#160]
On the latest master, `make install` won't complete on Fedora 23:

```
[detter@localhost dyninst]$ make install
[  0%] Building DyninstRT
[ 25%] Built target dyninstAPI_RT
[ 51%] Built target dyninstAPI_RT_m32
[ 75%] Built target dyninstAPI_RT_m32_static
[100%] Built target dyninstAPI_RT_static
[  0%] Built target DyninstRT
[  9%] Built target common
[ 10%] Built target dynElf
[ 13%] Built target dynDwarf
[ 14%] Built target symLite
[ 18%] Built target instructionAPI
[ 27%] Built target symtabAPI
[ 47%] Built target parseAPI
[ 56%] Built target pcontrol
[ 62%] Built target stackwalk
[ 68%] Built target patchAPI
[ 95%] Built target dyninstAPI
[ 97%] Built target parseThat
[100%] Built target dynC_API
Install the project...
-- Install configuration: "Debug"
CMake Error at dyninstAPI_RT/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/detter/Workspace/dyninst/dyninstAPI_RT/CMakeFiles/CMakeRelink.dir/libdyninstAPI_RT.so.9.2.0".
Call Stack (most recent call first):
  cmake_install.cmake:36 (include)



Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by jdetter** [comment]
Is anyone else able to reproduce this or is this a local issue for me?

**Comment by wrwilliams** [comment]
Does this persist with a clean cache/clean build?

**Comment by jdetter** [comment]
I'm having issues with this on Fedora 23 and Ubuntu 16.04, however it seems to be a non issue on RHEL 6.

**Comment by wrwilliams** [comment]
What are we generating in that relink directory? Anything that looks remotely sane?

**Comment by jdetter** [comment]
That relink directory doesn't exist when the install script is ran.

**Comment by jdetter** [comment]
Sorry wait yes it does, but it's empty.

**Comment by jdetter** [comment]
@wrwilliams Do you have some extra bandwidth to look at this today? This is kind of blocking my development. If you need an Ubuntu environment, you should be able to log into pepperjack. All of the libraries you should need for dyninst are installed by default except libdwarf.

**Comment by jdetter** [comment]
All of the libraries are being generated in their respective `CMakeFiles/CMakeRelink.dir/` except dyninstAPI_RT. That's the only one that has an empty relink directory.

**Comment by wrwilliams** [comment]
make VERBOSE=1 and see what shows up; there's got to be something going weird with the RTlib build.

**Comment by jdetter** [comment]
I had to change the generated install script to copy from the right location. I'm not sure why it's trying to grab the libraries out of the relink directory. Here is what I changed:

```
file(INSTALL DESTINATION "/usr/lib" TYPE SHARED_LIBRARY FILES
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/CMakeFiles/CMakeRelink.dir/libdyninstAPI_RT.so.9.2.0"
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/CMakeFiles/CMakeRelink.dir/libdyninstAPI_RT.so.9.2"
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/CMakeFiles/CMakeRelink.dir/libdyninstAPI_RT.so"
    )
```

to:

```
file(INSTALL DESTINATION "/usr/lib" TYPE SHARED_LIBRARY FILES
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/libdyninstAPI_RT.so.9.2.0"
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/libdyninstAPI_RT.so.9.2"
    "/home/detter/Workspace/dyninst/dyninstAPI_RT/libdyninstAPI_RT.so"
    )
```

and now it will install without any issues.

**Comment by jdetter** [comment]
@pefoley2 It looks like 09b01aa09079339b47b6bbaae8c9dedb682a56f6 introduced this issue with newer versions of cmake, would you know how to fix it?

**Comment by pefoley2** [comment]
Odd. Maybe try reverting the file(remove_recurse) change?

**Comment by jdetter** [comment]
That seems to have fixed the problem, I will open a PR soon with the fix.
