### ISSUE TITLE
Issues with Static Instruction Insertion using Dyninst

### ISSUE THREAD

**Issue by Ouhznehc** [dyninst/dyninst#1699]
Hello,

I am attempting to use Dyninst for static instruction insertion at given legal addresses in a binary file. Specifically, my goal is to read an input file containing addresses followed by the assembly instructions that should be inserted at those addresses. The input file format looks like this:
```
0x3013 0 8b 83 a8 01 00 00
0x368b 0 8b 82 a4 01 00 00
0x66ad 0 8b 86 9c 01 00 00
0x66d5 0 8b 96 90 01 00 00
0x73ef 0 8b 83 b0 01 00 00
0x9902 0 8b 86 9c 01 00 00
```
The first number in each line represents the address in the original file, and the subsequent numbers represent the assembly instructions to be inserted. (Ignore the `0` in the middle)

Following examples provided by developers, I wrote the following code:
```c++
#include "BPatch.h"
#include "BPatch_function.h"
#include "BPatch_object.h"
#include "BPatch_image.h"
#include "BPatch_point.h"
#include "BPatch_snippet.h"

#include "PatchMgr.h"
#include "PatchModifier.h"
#include "Point.h"
#include "Snippet.h"

#include "Instruction.h"
#include "InstructionDecoder.h"
#include "Register.h"
#include "Expression.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <cstdint>

using namespace Dyninst;
using namespace Dyninst::PatchAPI;
using namespace InstructionAPI;

#define TOSTRING(x) #x

// BPatch is the top level object in Dyninst
BPatch bpatch;

struct instruction_t {
    unsigned long address;
    std::vector<unsigned char> bytes;
};

std::vector<instruction_t> tracked_instructions;

class AsmSnippet : public Dyninst::PatchAPI::Snippet {
    public:
        AsmSnippet(std::vector<unsigned char> bytes) {instruction_bytes = bytes;}
        bool generate(Dyninst::PatchAPI::Point* pt, Dyninst::Buffer& buf) override {
            std::cerr << "INSERT: 0x" << std::hex << pt->addr() << " format = " << pt->insn().format() << std::endl;
            buf.copy(instruction_bytes.data(), instruction_bytes.size());
            return true;
        }

    private:
        std::vector<unsigned char> instruction_bytes;
};

void parse_file(std::string file_path) {
    std::ifstream file(file_path);
    if (!file.is_open()) {
        std::cerr << "Could not open " << file_path << std::endl;
        exit(1);
    }

    std::string line;
    while (std::getline(file, line)) {
        std::istringstream iss(line);
        std::string address_str, byte_str;
        iss >> address_str;

        instruction_t instruction;
        instruction.address = std::stoul(address_str, nullptr, 16);

        while (iss >> std::hex >> byte_str) {
            if (byte_str.length() == 2) {
                unsigned int byte = std::stoul(byte_str, nullptr, 16);
                instruction.bytes.push_back(static_cast<unsigned char>(byte));
            }
        }

        tracked_instructions.push_back(instruction);
    }

    file.close();
}

BPatch_point* FindPoint(BPatch_image* image, Dyninst::Address address) {
    std::vector<BPatch_point*> points;
    image->findPoints(address, points);

    if (points.empty()) {
        std::cerr << "No point found at address 0x" << std::hex << address << std::endl;
        return nullptr;
    }

    if (points.size() > 1) {
        std::cerr << "Warning: Multiple points found at address 0x" << std::hex << address << std::endl;
    }

    return points.front();
}

int main(int argc, char** argv) {
    if (argc != 4) {
        std::cerr << "Usage: " << argv[0] << " <input_binary> <output_binary> <list>" << std::endl;
        return -1;
    }

#ifdef __ARCH_32__
    setenv("DYNINSTAPI_RT_LIB", DYNINSTAPI_RT_LIB, 1);
#endif

#ifdef __ARCH_64__
    setenv("DYNINSTAPI_RT_LIB", DYNINSTAPI_RT_LIB, 1);
#endif

    parse_file(argv[3]);

    BPatch_binaryEdit* app = bpatch.openBinary(argv[1]);
    if (!app) {
        std::cerr << "Failed to open binary" << std::endl;
        return -1;
    }

    BPatch_image* image = app->getImage();

    for (auto& instruction : tracked_instructions) {

        std::vector<BPatch_point*> points;
        
        auto point = FindPoint(image, instruction.address);

        Snippet::Ptr codeBufferSnippet = AsmSnippet::create(new AsmSnippet(instruction.bytes));
        if(!codeBufferSnippet) std::cerr << "AsmSnippet::create failed" << std::endl;

        Point* patch_point = Dyninst::PatchAPI::convert(point, BPatch_callAfter);
        if(!patch_point) std::cerr << "Dyninst::PatchAPI::convert failed" << std::endl;

        if (!patch_point->pushBack(codeBufferSnippet))
            std::cerr << "Failed to push back snippet at address: 0x" << std::hex << instruction.address << std::endl;
    }

    if (!app->writeFile(argv[2])) {
        std::cerr << "Failed to write the instrumented binary to " << argv[2] << std::endl;
        return -1;
    }

    return 0;
}
```
However, this implementation does not correctly insert the instructions for some files as intended. Could there be an issue with my implementation, or is there a better, more convenient way to achieve this?

Here's a brief summary of the code's functionality:
- Parse the input file to read addresses and corresponding instruction bytes.
- Use Dyninst APIs to locate the insertion points in the binary.
- Create a custom AsmSnippet class to handle the instruction bytes' insertion.
- For each address, find the insertion point, create a snippet, and attempt to insert it.
- Finally, write the instrumented binary to an output file.

I've encountered difficulties with some files where the instructions aren't inserted as expected. I'm seeking advice on whether there are issues with my approach or if there are any suggestions for improvements.

Thank you for your help!

**Comment by bbiiggppiigg** [comment]
Can you elaborate on what you mean by "not correctly insert the instructions" and "for what files", maybe provide the files you want to instrument if possible?

**Comment by Ouhznehc** [comment]
Thank you for your response. I've uploaded an example that illustrates the issues I'm encountering to [Archive.zip](https://github.com/dyninst/dyninst/files/14512366/Archive.zip)。 The archive contains three files: `rewrite.log`, `rewrite_error.log` and `pbzip2-0.9.4_gcc-m32.bin`.
- `rewrite.log` lists the instructions I aim to instrument into the binary.
- `rewrite_error.log` provides the debug messages generated during the process.
- `pbzip2-0.9.4_gcc-m32.bin` is the file to be instrumented.

One specific issue I observed is with the instructions at some address like `0x4014f4`, which were not instrumented correctly. Additionally, there is a warning in the logs, but I'm unsure of its implications or how it might be affecting the instrumentation process.

Could you help me understand the warning's significance and suggest any steps to resolve the incorrect instrumentation issue?

**Comment by bbiiggppiigg** [comment]
@Ouhznehc 

So the problem here is Dynisnt concluded that the function main has unresolvable control flow and marked the function as non-instrumentable. (ie. jmp eax at 0x4015f4)

As a result, none of the addresses that you have provided that sits in main got instrumented.
I'll discuss with other maintainers to see if we can add some warning/error to make this easier to spot. (It is pretty hard to spot even for someone who is familiar with the code base).

**Comment by Ouhznehc** [comment]
@bbiiggppiigg 

Thanks! 
I have already found this problem by running my program with `DYNINST_DEBUG_RELOC=1`, and got the following output:
  ```
  ADDRSPACE::Relocate called; modified functions reports 1 objects to relocate.
  Function main is non-instrumentable, skipping
  ```
I'll close this issue, thank you for your help!
