### ISSUE TITLE
Bundling cvconst.h

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#17]
On Windows, dyninst currently requires the DIA sdk for cvconst.h
Microsoft has recently released this header under the MIT licence at https://github.com/Microsoft/microsoft-pdb/blob/master/include/cvconst.h.
Might it make sense to bundle this header with dyninst to avoid the dependency on the DIA sdk being installed?

**Comment by wrwilliams** [comment]
Quite likely sensible, and IIRC dbghelp.dll is part of a regular Windows install. I think give it its own directory with MS copyright and license files, and clean out the configuration option.

**Comment by pefoley2** [comment]
Resolved by #18

**Comment by jdetter** [comment]
Can this be closed?

**Comment by pefoley2** [comment]
Not till the change has actually been merged into master, it's still just a pull request currently.

**Comment by pefoley2** [comment]
Rather than blocking on the whole pr, you could just cherry-pick https://github.com/dyninst/dyninst/pull/18/commits/682e01e12fbc2370350d5d10f7b33a52c01dce00

**Comment by pefoley2** [comment]
Fixed by #102
