### ISSUE TITLE
GitHub Release for 13.0.0

### ISSUE THREAD

**Issue by blue42u** [dyninst/dyninst#1713]
Please create a release on GitHub for version 13.0.0. I keep getting confused what the latest version is when I arrive at [the front page on GitHub](https://github.com/dyninst/dyninst), it looks like the latest is 12.3.0 even though I know that is no longer true:

![Release widget screenshot](https://github.com/dyninst/dyninst/assets/17242663/7071d095-9573-4c3c-ad28-a6d66807e45a)

**Comment by hainest** [comment]
Sorry about that. This release had about 6x the normal number of commits, so it's taken a while to get the official release items together.

@kupsch Did you make a draft release? I don't see one. If not, I can make a stub release we can fill in once you've had an opportunity to go through the commits.

**Comment by kupsch** [comment]
I'll have the release notes complete in a day or so and will make the official release then.

**Comment by kupsch** [comment]
release added to github releases
