### ISSUE TITLE
release cmake configury: unable to install under /usr/lib64/...

### ISSUE THREAD

**Issue by fche** [dyninst/dyninst#1720]
I'm trying to package dyninst 13 for Fedora, wherein dyninst libraries should sit under /usr/lib64/dyninst (or even /usr/lib64).  However, the cmake files appear to override all my efforts to set DYNINST_INSTALL_LIBDIR or any other library-like path cmake variable, and end up with cmake --install plopping them under /usr/lib/.  This used to work back in the dyninst 12 days.

**Comment by hainest** [comment]
Looking at the old code, it's not clear to me that ``DYNINST_INSTALL_LIBDIR`` would have had any influence on the install paths. Previously, they were hard-coded in ``INSTALL_{LIB,INCLUDE}_DIR`` and then extended to be absolute paths relative to ``CMAKE_INSTALL_PREFIX``. This has never been the correct method of setting installation paths in CMake, so it was removed.

The current ``DYNINST_INSTALL_{LIB,BIN,INCLUDE,CMAKE}DIR`` are internal variables that cannot be set by users. At one point, I had thought it might be useful to let users set the installation structure, but ultimately decided against it as it would make the resulting CMake package non-portable. The downside is that all libraries are installed in 'lib' and not 'lib64', but both are generally in linker/loader default search paths. We've been testing on Fedora 37-39 with both the default /usr/lib and a custom ``CMAKE_INSTALL_PREFIX``/lib without any trouble.

If there is a need to have them in ``*/lib64``, I could add a config variable for that.

**Comment by fche** [comment]
Hi, Tim, thanks for the response.  Yeah I don't doubt that what you have there works (installing 64-bit binaries into /usr/lib).  The problem is that as a distro packager, that's outside the guidelines used for cohesion of the whole system.  I suppose the packaging scripts could move these files into /usr/lib64 after all your cmake stuff is finished.  But it would be better if the package could be made to fit directly into distro filesystem standards.

**Comment by fche** [comment]
Similarly, installing dyninst headers right under /usr/include kinda works, but /usr/include/dyninst would let it cohabit with the many other system libraries better.

**Comment by kupsch** [comment]
@hainest, what do you think about `include(GNUInstallDirs)` and then use the variables: `CMAKE_INSTALL_BINDIR`, `CMAKE_INSTALL_INCLUDEDIR` and `CMAKE_INSTALL_LIBDIR` as defaults for the dyninst variables. These are _advanced_ cached options and are supposed use pick lib or lib64 depending on the platform and would allow user definitions.

**Comment by hainest** [comment]
@kupsch That works for me. Did you want to take this one?

**Comment by kupsch** [comment]
I'll take care of it.

Thanks.

**Comment by kupsch** [comment]
@fche let us know if the fix for this works for your use case.
