### ISSUE TITLE
Windows 64-bit support doesn't exist (yet)

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#174]
Dyninst fails at a number of elements of Windows 64-bit support:
- Building 64-bit mutators
- Analyzing 64-bit mutatees
- Controlling 64-bit processes
- Relocating 64-bit code
- Generating 64-bit instrumentation

This issue should be superseded by more detailed issues for each of the above as development proceeds.

**Comment by rvlsridhar** [comment]
Is this sipport in plan for next release?

**Comment by hainest** [comment]
@rvlsridhar Windows is not officially supported in Dyninst. There is some machinery to try to build it on that platform, but it is unverified. It is unlikely a 64-bit port will be completed anytime soon- certainly not for the upcoming 10.1 release.
