### ISSUE TITLE
Call emulation causing testsuite failures

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#187]
I am getting multiple testsuite failures with this error message:

```
test_lib_mutateeStart.C[268]:  starting rewritten process './binaries/rewritten_test1_14.stat_gcc_64_pic_none Mutatee ./binaries/rewritten_test1_14.stat_gcc_64_pic_none [C]:""
**Failed test #14 (replace/remove function call)
    call to test1_14_func2() was not replaced
    call to test1_14_func3() was not removed
    call to test1_14_func4() was not inter-module replaced: 3 instead of 2
test_lib_mutateeStart.C[283]:  after waitForCompletion: no crash, result = 255
test_lib_mutateeStart.C[77]:  unlinking ./binaries/rewritten_test1_14.stat_gcc_64_pic_none
test1_14                   gcc    none 64  rewriter NA      static  PIC     FAILED (Group Teardown)
```

@wrwilliams can you give me any context on this so I can get a better idea of what's going wrong?

**Comment by wrwilliams** [comment]
Call site manipulation is what we're testing here; there's probably some bad interaction between the call emulation and the manipulation we want to perform. I expect DYNINST_DEBUG_RELOC will at least help shed some light.

**Comment by wrwilliams** [comment]
@jdetter Is this now clean on the exception handling PR? If so, please close.

**Comment by jdetter** [comment]
I think what I pushed to the PR will be the final fix for this issue but this is almost wrapped up.
