### ISSUE TITLE
findMain failing on master under Jenkins

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#188]
http://jenkins.dyninst.org/jenkins/job/dyninst-test/13/console

We're getting bad shared pointer derefs and empty block lists on basically all mutatees. The environment should be visible/recorded in the upstream dyninst-build run's output, but it's an Ubuntu-based system.

@jdetter let me know if you need help with this one but it's a pretty high priority.

**Comment by jdetter** [comment]
Ok I can start working on this right away.

**Comment by jdetter** [comment]
You might have to enable all of the ptrace features, I'm not sure if that's a contributing factor or not but you're getting a warning:

```
Warning: your Linux system provides limited ptrace functionality as a security
measure. This measure prevents ProcControl and Dyninst from attaching to binaries.
To temporarily disable this measure (until a reboot), execute the following command:
	echo 0 > /proc/sys/kernel/yama/ptrace_scope
To permanently disable this measure, edit the file "/etc/sysctl.d/10-ptrace.conf"
and follow the directions in that file.
```

This is running on AWS right? What version of Ubuntu is this? 16.04? 14.04?

**Comment by jdetter** [comment]
I'm actually able to reproduce your issue so I am working on it now.

**Comment by jdetter** [comment]
I've eliminated a significant amount of the testsuite failures, I'll let it finish before I open a PR.

**Comment by jdetter** [comment]
Can I make one last change before this goes in? I commented out the old code and it's still there, should I delete it? Or is it fine to just have that huge block commented out?

**Comment by wrwilliams** [comment]
Go ahead and delete dead code.

**Comment by jdetter** [comment]
Ok I'll do that now.
