### ISSUE TITLE
Incorrect operand suffix for register size for string instruction

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#197]
@jdetter I think this is a part of the transfer to AT&T syntax. We seem to have the incorrect suffix on multiple instructions (scas and sbb):

On scas, we use the 'w' prefix for %eax when we should have 'l'.
Bytes: af
Dyninst Output: scasw %es:(%rdi),%eax

**Comment by jdetter** [comment]
This should have been fixed in #271.
