### ISSUE TITLE
Two options for opcode should print one, not both.

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#199]
@jdetter I don't know if this is necessarily something needed to put us in line with ATT syntax, but it isn't assembly output that can be assembled.

The following are opcodes that we print two versions of with a '/' instead of printing just the correct one:

We print: shl/sal
Should print: shl

We print: movhps/movlhps
Should print: movhps

We print: movlps/movhlps
Should print: movlps

**Comment by jdetter** [comment]
I'm really not sure why this is a thing. We should be able to differentiate between instructions. I have seen this before in the past but I wasn't sure if I should fix it. We can talk about it during the meeting but I agree this should be fixed.
