### ISSUE TITLE
Instructions produce FIXME opcodes, but otherwise appear correct

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#202]
The following bytes produce FIXME opcodes in dyninst with the rest of the instruction output correct. The bytes and correct output are given with one example for each opcode that this affects.

Bytes: db e2
Correct output: fnclex

Bytes: db e3
Correct output: fninit

Bytes: 0f 0f 81 02 37 78 e4
Correct output: pfmin -0x1b87c8fe(%rcx), %mm0

Bytes: 0f 0f c8 1c
Correct output: pf2iw %mm0, %mm1

Bytes: 0f 0f 41 82
Correct output: pmulhrw -0x7e(%rcx), %mm0

Bytes: 0f 0f 01 8a
Correct output: pfnacc (%rcx), %mm0

Bytes: 0f 0f 85 82 37 78 e5
Correct output: pfmul -0x1a87c87e(%rbp), %mm0

Bytes: 0f 0f 85 82 37 78 e5
Correct output: pfrcp -0x1a87c87e(%rbp), %mm0

Bytes: 0f 0f 81 82 37 78 65
Correct output: pfcmpge 0x65783782(%rcx), %mm0

Bytes: 0f 0f 81 82 37 78 e5
Correct output: pfmax -0x1a87c87e(%rcx), %mm0

Bytes: 0f 0f 81 82 37 78 e5
Correct output: pfadd -0x1a87c87e(%rcx), %mm0

Bytes: 0f 0f 81 82 37 78 e5
Correct output: pfrsqrt -0x1a87c87e(%rcx), %mm0

Bytes: 0f 0f 2c c5 76 fd 2f c8
Correct output: pavgusb -0x37d0028a(, %rax, 8)

**Comment by jdetter** [comment]
We discussed this at the meting and I believe these are 3DNow! instructions that we aren't going to bother with. Correct me if I'm wrong.
