### ISSUE TITLE
Operands labelled "[empty]" with operand type mismatch (all with 0x67 prefix)

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#203]
At times, we decode part of an operand as "[empty]" creating invalid output with an operand type mismatch. Below are three examples with their input bytes, current output and correct output.

Bytes: 67 20 36
Dyninst: and %dh, $0x[empty]
Correct output: and %dh, (%esi)

Bytes: 67 ff 1e
Dyninst: call $0x[empty]
Correct output: lcall *(%esi)

Bytes: 67 c5 09 16 06
Dyninst: vmovhpd %xmm14,$0x[empty],%xmm8
Correct output: vmovhpd (%esi), %xmm14, %xmm8

**Comment by jdetter** [comment]
Still working on this one, this is a syntax generation issue.

**Comment by jdetter** [comment]
These ended up being uncommon usages of the ModRM byte where MOD=00 and RM isn't 4 or 5 which is the common case. We basically had undefined behavior which returned an empty result. This should be fixed on `att_syntax`.

**Comment by jdetter** [comment]
@nathanhjay I have verified the fix locally with `dyndump`.
