### ISSUE TITLE
[ARM Syntax] Repeated register number as constant

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#216]
We seem to be adding an additional field to an instruction, possibly a repeat of the register number as a numeric operand. Here's an example:

Bytes: f3 f6 0b 3c
Dyninst Output: str b19, [x23, 23], 0xbf
Expected Output: str b19, [x23], #191

Here's the assembler's best guess at what we're doing wrong:
ERROR:  cannot combine pre- and post-indexing at operand 2

**Comment by nathanhjay** [comment]
The operand base doesn't matter at all (0xbf vs. #191).

**Comment by nathanhjay** [comment]
It appears that this issue occurs with hex values as well, for example:

Bytes: 9f eb 55 5c
Dyninst Output: ldr d31, [0xabd70, xabd70]
Expected Output: ldr d31, 0xabd70

**Comment by ssunny7** [comment]
Fixed by commit d60c21bc943e800f95cc4d54fe4c21c1ee6a4902

**Comment by jdetter** [comment]
@nathanhjay Can we close any of these issues?
