### ISSUE TITLE
[ARM Syntax] Immediate out of range for LDRSB

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#217]
We seem to be producing an LDRSB instruction with an immediate that is out of range. It looks like the immediate was just shifted and should not have been.

Bytes: f2 a1 ec 39
Dyninst Output: ldrsb w18, [x15, 0xb280]
Expected Output: ldrsb w18, [x15, 0xb28]

**Comment by ssunny7** [comment]
Fixed by commit 9251bc6ba19d7f0cb78ad8884980e9d5c983ac4f.
