### ISSUE TITLE
[ARM Syntax] Shifted immediate for CCMP and CCMN

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#218]
The immediate value provided for CCMP and CCMN appears to be shifted 28 bits. An example follows.

Bytes: 8d fb 4b fa
Dyninst Output: ccmp x28, 0xb, 0xd0000000, nv, pstate
Expected Output: ccmp x28, 0xb, 0xd, nv

The mention of "pstate" should be removed, but I think that's been reported already.

**Comment by ssunny7** [comment]
Fixed by commit de78ce551ff270c0e2a5ed5ffe11d270865ce974.
