### ISSUE TITLE
[ARM Decoding] Invalid CCMP and CCMN decoded as valid

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#219]
Both CCMP and CCMN are invalid if bit 4 of the instruction is a '1'. These instructions are decoded as valid by Dyninst. Here's an example:

Bytes: 9d fb 4b fa
Dyninst Output: ccmp x28, 0xb, 0xd0000000, nv, pstate

**Comment by ssunny7** [comment]
Fixed by commit de78ce551ff270c0e2a5ed5ffe11d270865ce974.
