### ISSUE TITLE
[ARM Syntax] Zero register should have sizing, either XZR or WZR

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#220]
When the zero register is used, its size should be specified. Here's an example where it's not:

Bytes: 9f eb 55 f9
Dyninst Output: ldr zr, [x28, 0x2bd0]
Expected Output: ldr xzr, [x28, 0x2bd0]

**Comment by ssunny7** [comment]
Fixed by commit dd48e72c1520f9d7bac94005f130f701d2c14b6e.
