### ISSUE TITLE
[ARM Decoding] Decoding of ADDHN ignore reserved size bits

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#221]
When the size bits of an ADDHN instruction are '11', the instruction should be invalid. Dyninst currently decodes these instructions as valid.

Bytes: 84 41 fd 4e
Dyninst Output: addhn hq4, q12, q29

**Comment by ssunny7** [comment]
Fixed by commit 5afd17c707ba0dca4fc32f48d5625e19d1700b97.

Please test all other instructions in the SIMD 3 Different category.
