### ISSUE TITLE
[ARM Decoding] Decoding of MOVK instruction ignores restriction on combination of size and hw bits

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#222]
The manual specifies that the size field cannot be 0 if bit 1 of the hw field is 1, but Dyninst decodes the instruction as valid even when this specification is not followed.

Bytes: 9d fb cb 72
Dyninst Output: movk w29, 0x5fdc, lsl 0x20

**Comment by ssunny7** [comment]
Fixed by commit 5afd17c707ba0dca4fc32f48d5625e19d1700b97.

Please test other instructions in the move-wide immediate category viz. MOVN, MOVZ, MOV (wide immediate) and MOV (inverted wide immediate).

**Comment by nathanhjay** [comment]
I tested the cases you requested and they are fixed as well.
