### ISSUE TITLE
LibraryTracker unclear in StackWalkerAPI

### ISSUE THREAD

**Issue by hzhang86** [dyninst/dyninst#224]
It took me a while to figure out how to get the absolute address of a symbol in a symbol table, mainly because the manual lacks the instruction of how to get the loaded base address of binaries. There is no info about class LibraryTracker in the manual. With the help of Bill, I know that it should follow the walker->getProcessState()->getLibraryTracker()->getLibraries() ... chain.

Therefore I think adding info about class LibraryTracker and an example for how to use it would be of great help to the users.

**Comment by cuviper** [comment]
Yeah, there are a few "tracking" libraries that need docs -- see also #151.
