### ISSUE TITLE
BPatch_function.C.o build failure on PPC64le

### ISSUE THREAD

**Issue by mcfadden8** [dyninst/dyninst#23]
Note (builds okay on x86_64).

I am seeing the following build failure:

[ 65%] Building CXX object dyninstAPI/CMakeFiles/dyninstAPI.dir/src/BPatch_function.C.o
In file included from /g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/parse-cfg.h:49:0,
                 from /g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/function.h:43,
                 from /g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/BPatch_function.C:37:
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h:78:5: error: 'vector' does not name a type
     vector<int> _func_allocs;
     ^
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h:79:5: error: 'vector' does not name a type
     vector<int> _edge_allocs;
     ^
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h: In member function 'void DynCFGFactory::_record_func_alloc(Dyninst::ParseAPI::FuncSource)':
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h:87:11: error: '_func_allocs' was not declared in this scope
         ++_func_allocs[fs];
           ^
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h: In member function 'void DynCFGFactory::_record_edge_alloc(Dyninst::ParseAPI::EdgeTypeEnum, bool)':
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/Parsing.h:92:11: error: '_edge_allocs' was not declared in this scope
         ++_edge_allocs[et];
           ^
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/BPatch_function.C: At global scope:
/g/g0/martymcf/dyninst/dyninst/dyninstAPI/src/BPatch_function.C:1115:6: warning: unused parameter 'mods' [-Wunused-parameter]
 bool BPatch_function::addMods(std::set<StackMod*> mods)
      ^
make[2]: *** [dyninstAPI/CMakeFiles/dyninstAPI.dir/src/BPatch_function.C.o] Error 1
make[1]: *** [dyninstAPI/CMakeFiles/dyninstAPI.dir/all] Error 2
make: *** [all] Error 2

**Comment by wrwilliams** [comment]
Missing a "using std::vector" there. @pefoley2, mind working with Marty on cleaning this up?

**Comment by pefoley2** [comment]
Sure, should be fairly straightforward.

**Comment by pefoley2** [comment]
Above PR should fix this.

**Comment by mcfadden8** [comment]
Yes, I applied the fix locally and confirmed that it now builds successfully.
