### ISSUE TITLE
att_syntax not building after merge

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#230]
I merged `att_syntax` with master and now we're having an issue building due to some register names not being recognised. @ssunny7 can you pull the latest `att_syntax` and take a look?

```
Scanning dependencies of target common
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'common/CMakeFiles/common.dir/depend.make' has modification time 3 s in the future
[  2%] Building CXX object common/CMakeFiles/common.dir/src/Ident.C.o
[  2%] Building CXX object common/CMakeFiles/common.dir/src/Timer.C.o
[  3%] Building CXX object common/CMakeFiles/common.dir/src/Types.C.o
[  3%] Building CXX object common/CMakeFiles/common.dir/src/string-regex.C.o
[  3%] Building CXX object common/CMakeFiles/common.dir/src/debugOstream.C.o
[  3%] Building CXX object common/CMakeFiles/common.dir/src/lprintf.C.o
[  3%] Building CXX object common/CMakeFiles/common.dir/src/pathName.C.o
[  4%] Building CXX object common/CMakeFiles/common.dir/src/Time.C.o
[  4%] Building CXX object common/CMakeFiles/common.dir/src/fraction.C.o
[  4%] Building CXX object common/CMakeFiles/common.dir/src/timing.C.o
[  4%] Building CXX object common/CMakeFiles/common.dir/src/stats.C.o
[  4%] Building CXX object common/CMakeFiles/common.dir/src/Annotatable.C.o
[  5%] Building CXX object common/CMakeFiles/common.dir/src/MappedFile.C.o
[  5%] Building CXX object common/CMakeFiles/common.dir/src/sha1.C.o
[  5%] Building CXX object common/CMakeFiles/common.dir/src/serialize-bin.C.o
[  5%] Building CXX object common/CMakeFiles/common.dir/src/serialize-xml.C.o
[  6%] Building CXX object common/CMakeFiles/common.dir/src/util.C.o
[  6%] Building CXX object common/CMakeFiles/common.dir/src/Node.C.o
[  6%] Building CXX object common/CMakeFiles/common.dir/src/Graph.C.o
[  6%] Building CXX object common/CMakeFiles/common.dir/src/Edge.C.o
[  6%] Building CXX object common/CMakeFiles/common.dir/src/DOT.C.o
[  7%] Building CXX object common/CMakeFiles/common.dir/src/dyn_regs.C.o
/home/d/detter/Workspace/dyninst/devel/att_syntax/common/src/dyn_regs.C: In member function ‘void Dyninst::MachRegister::getROSERegister(int&, int&, int&)’:
/home/d/detter/Workspace/dyninst/devel/att_syntax/common/src/dyn_regs.C:816:20: error: ‘zr’ is not a member of ‘Dyninst::aarch64’
      if(baseID == (aarch64::zr & 0xFF) || baseID == (aarch64::wzr & 0xFF))
                    ^
common/CMakeFiles/common.dir/build.make:608: recipe for target 'common/CMakeFiles/common.dir/src/dyn_regs.C.o' failed
make[2]: *** [common/CMakeFiles/common.dir/src/dyn_regs.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:255: recipe for target 'common/CMakeFiles/common.dir/all' failed
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ssunny7** [comment]
@jdetter  Did you merge att_syntax into master or the other way round?

**Comment by jdetter** [comment]
I merged master into AT&T syntax but it shouldn't matter should it?

**Comment by ssunny7** [comment]
Not really, just wanted to makes sure I understood correctly.

**Comment by ssunny7** [comment]
Well, it went past dyn_regs.C for me (merged att_syntax into master). How had you resolved the merge conflicts? I had a total of three conflicts.

**Comment by ssunny7** [comment]
Merging att_syntax into master and resolving all merge conflicts correctly does not create any build issues. However, merging master into att_syntax brings up the issue you reported.

The commit where this gets broken is https://github.com/dyninst/dyninst/commit/897f0c4a7fd30a34f9b711274c9628b3d76f29ea. I'm not sure how this commit came into the branch, possibly a merge? We should get together and talk about this.

**Comment by ssunny7** [comment]
This is no longer an issue - the build goes through fine. It is the tests that fail after merge, and we already have a PR open for that (https://github.com/dyninst/dyninst/pull/244).

@jdetter I think this can be closed.

**Comment by nathanhjay** [comment]
@ssunny7 Does this issue still exist on the att syntax branch? I pulled the att_syntax branch and ran into the same bug with that branch alone. I don't have any local changes to Dyninst, so I used

`git checkout att_syntax`
`git reset --hard origin/att_syntax`

to pull a fresh copy of the branch and this issue persists.

**Comment by jdetter** [comment]
@nathanhjay Can you post the build issues?

**Comment by nathanhjay** [comment]
@jdetter here is the build issue:

```
/nobackup/local_builds/dyninst/common/src/dyn_regs.C: In member function ‘void Dyninst::MachRegister::getROSERegister(int&, int&, int&)’:
/nobackup/local_builds/dyninst/common/src/dyn_regs.C:816:20: error: ‘zr’ is not a member of ‘Dyninst::aarch64’
      if(baseID == (aarch64::zr & 0xFF) || baseID == (aarch64::wzr & 0xFF))
                    ^
make[2]: *** [common/CMakeFiles/common.dir/src/dyn_regs.C.o] Error 1
```

Is there any other info you need?

**Comment by jdetter** [comment]
@ssunny7 Are we still using this branch or are we using the new branch? Nathan is having the original merge issue.

**Comment by ssunny7** [comment]
@nathanhjay I'd advise using `att_syntax_merge`. That branch has all merge issues fixed and will also merge cleanly into `master`. (It is also our branch going ahead for syntax fixes and will renamed to `att_syntax` later when the current branch of the same name is deleted).

**Comment by nathanhjay** [comment]
Okay, thanks.
