### ISSUE TITLE
[ARM Decoding] Bad shift amounts.

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#233]
Instructions and addressing modes with shifting should not allow shift amounts greater than the register width. The following 3 instructions are examples. All of them should be invalid because of the shift field. Verify with the manual what should be done.

Bytes: `13 c4 4 4b`
Output: `sub w19, w0, w4, lsl 0x31`

Bytes: `05 b2 6b 53`
Output: `ubfx w5, w16, 0x2b, 0x2`

Bytes: `fc cf 17 33`
Output: `bfxil w28, wzr, 0x17, 0x1d`

**Comment by ssunny7** [comment]
@nathanhjay The latter two need to be invalid here. However, the first one is correct per the manual. This is a `Subtract (shifted register)` variant of `SUB` for which the manual says `For the 32-bit variant: is the shift amount, in the range 0 to 31, defaulting to 0 and encoded in the "imm6" field.`. Can you re-check this instruction?

**Comment by nathanhjay** [comment]
@ssunny7 I think the first one is invalid too. Looking at the manual, it has the line:

"if sf == '0' && imm6<5> == '1' then ReservedValue();"

The size field is bti 31, which is zero. imm6<5> is bit 15 (the first '1' in '11000100' from the byte 0xC4), which is '1'. The shift amount is too large for the size of the registers as a result. (This shift amount is 49 bits, but the registers are 32 bits).

**Comment by ssunny7** [comment]
My bad, you're right.

**Comment by ssunny7** [comment]
Fixed by f236c311f4e41b17595e6d7266a8974a10df7f72.
