### ISSUE TITLE
[ARM Decoding] Convert instruction immediate should not be larger than the register size

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#240]
Bytes: `48 7b 18 1e`
Output: `fcvtzs w8, s26, 0x22`
ASM Error: immediate value out of range 1 to 32 at operand 3

This instruction should be invalid.

**Comment by ssunny7** [comment]
Fixed by 60416ae685b3f3ce0580c9721a1c11898e4c9ec0.
