### ISSUE TITLE
Update build requirements: drop libelf.so.0 support

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#242]
libelf.so.0 is not amenable to proper endian-swapping of Elf_Data regions, and is generally being ill-behaved. I believe it's time to pull the plug on it and require folks to use elfutils; this requires both CMake changes (don't grab libelf.so.0, grab elfutils if possible) and documentation.

Relatedly, we should deprecate Elf_X and use the standard gelf routines for our 32/64 support.

**Comment by cuviper** [comment]
Hmm.  *Not* requiring elfutils was one of the ~~excuses~~ reasons I had for not working too hard to port from libdwarf to libdw, namely because elfutils doesn't support freebsd.  But freebsd in dyninst has been broken for a while anyway -- can we go ahead and nuke that?  Then perhaps we can aim for libdw in dyninst 10.

**Comment by wrwilliams** [comment]
I will reopen that discussion with Bart. We're not getting paid to support BSD any longer and we have really good reasons at this point to want to use the tools that are supported by larger teams.

**Comment by cuviper** [comment]
FWIW, it's also conceivable to port elfutils to freebsd, and I even started poking at that last year.  There are a lot of GNU-isms that will have to be abstracted though, and I didn't care enough to see it through.

**Comment by wrwilliams** [comment]
We're officially deprecating old libelf and allowing it to break in 9.3, so we're clear to move to a full elfutils stack in 10.x, including libdw. And we've got exception handling working without DWARF rewriting, but we'll still want a libdw producer at some point.

**Comment by cuviper** [comment]
> including libdw

yay!

> but we'll still want a libdw producer at some point.

When you're ready, please start a discussion for this on the elfutils mailing list.
