### ISSUE TITLE
[ARM Decoding] Paired memory accesses must access aligned memory

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#245]
The following instruction should be invalid because the memory access is not offset by a multiple of  (meaning it wont be aligned, I think).

Bytes: `fc cf 17 68`
Output: `stnp x28, x19, [sp, 0xbc]`
ASM Error: immediate value should be a multiple of 8 at operand 3

**Comment by ssunny7** [comment]
Fixed by 8012061aa80b44d6ac176b4662f33bbe52e4c2b1.
