### ISSUE TITLE
[ARM Decoding] REV64 instruction operand 1 should be integer register, not vector

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#246]
The following instruction should be invalid.

Bytes: `42 08 bb 0e`
Output: `rev64 d2, d2`
ASM Error: operand 1 should be an integer register

**Comment by ssunny7** [comment]
What version of the ISA are you compiling the ASM with? I believe the error message says there should be a GPR instead of an FPR, but there is no non-SIMD REV64 instruction in ARMv8 -- probably there is one in 8.1 or 8.2?

In any case, this instruction should be invalid for ARMv8.

**Comment by ssunny7** [comment]
Invalid check added by  a973ef6.

**Comment by mxz297** [comment]
@sashanicolas  Can you double-check if this issue applies to Dyninst 10.1?
