### ISSUE TITLE
[ARM Decoding] Stack pointer used where zero register should be

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#248]
The following instruction should use the zero register for operand 4 instead of the stack pointer.

Bytes: `59 7c 01 1b`
Output: `madd w25, w2, w1, wsp`
Expected Output: `madd w25, w2, w1, wzr`
Expected Output (alias): `mul w25, w2, w1`
ASM Error: operand 4 should be an integer register

**Comment by ssunny7** [comment]
Fixed by 9fd5b32c52bbac9d52937aabf3a6a63b83ee6ce5.
