### ISSUE TITLE
[ARM Decoding] Reserved size value for some vector register instructions is ignored

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#249]
The following instructions should be invalid because their size field must be '11'.

Bytes: `4b 87 a5 5e`
Output: `add s11, s26, s5`

Bytes: `0f 8c a7 7e`
Output: `cmeq s15, s0, s7`

**Comment by ssunny7** [comment]
Fixed by fea0fdbef2bfd52c019bfe1962654bc6803f13d1.

**Comment by ssunny7** [comment]
Use commit d62aa74 for testing.
