### ISSUE TITLE
[ARM Decoding] Some floating point instructions do not appear to match required bits.

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#252]
Below are all examples of instructions that do not appear to fit the manual specification for any form of the opcode:

Bytes: `8e fa b9 8e`
Output: `fabs q14, q20`

Bytes: `8e fa 30 5e`
Output: `frecpx s14, d20`

Bit 20 must be zero, but is 1 for both of the above.

Bytes: `a0 68 bd 7e`
Output: `fcvtxn q0, q5`

Bytes: `10 fe e0 5f`
Output: `fcvtzs q16, q16`

Bytes: `10 8a e1 6e`
Output: `frinta q16, q16`

For the two above, bit 23 should be zero but is 1. The same bit is wrong for
FDIV.

Bytes: `76 90 14 4f`
Output: `fmul q22, q3, d20`

Bytes: `76 fc 14 4f`
Output: `fcvtzs q22, q3, 0xc`

Bit 28 should be 1 but is 0.

Bytes: `03 ef b6 5f`
Output: `scvtf q3, q24`

Bit 12 should be 0 but is 1.

If you know other instructions where bits are just not checked appropriately, those would be good to fix too. I'll catch as many as I can, but it seems like a systematic error, so perhaps there's a systematic solution that could fix a lot of this.

**Comment by mxz297** [comment]
@sashanicolas  Can you double-check if this issue applies to Dyninst 10.1?
