### ISSUE TITLE
[ARM Decoding] Floating point instructions can have mismatched operand sizes

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#253]
Bytes: `3a fb 30 e`
Output: `fabs s26, d25`

The above instruction is invalid for ARMv8, but it will have a valid variant in
ARMv8.1, using the 'h' registers.

Bytes: `bb 41 66 1e`
Output: `frinta s27, d13`
Expected Output: `frinta d27, d13`

Bytes: `bb c1 67 1e`
Output: `frinti h27, d13`
Expected Output: `frinti d27, d13`

Bytes: `04 40 64 1e`
Output: `frintn s4, d0`
Expected Output: `frintn d4, d0`

This goes for all of the FRINT* instructions.

Bytes: `9a c3 61 1e`
Output: `fsqrt h26, d28`
Expected Output: `fsqrt d26, d28`

**Comment by ssunny7** [comment]
All issues reported in the description, except the first one, fixed by 5cc151bb4b5c1261f2be333b01fd91167ec1e44a.

The first one remains to be addressed.

**Comment by nathanhjay** [comment]
I have confirmed that every case other than the first is fixed and that the first case still needs to be fixed.
