### ISSUE TITLE
[ARM Decoding] Incorrect operand size for FCVTXN

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#256]
Bytes: `21 6b 61 2e`
Output: `fcvtxn d1, d25`
Expected Output: `fcvtxn v1.2s, v25.2d`

**Comment by ssunny7** [comment]
The use of 'D' here for the register names is correct - they're just not in the expected SIMD format. This is a known issue for all SIMD instructions and this is one thing I won't be able to get to.
