### ISSUE TITLE
Warnings not being properly disabled under Visual Studio

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#26]
The /wd flags in warnings.cmake are being outputted to the .vcxproj files, but not passed down to the cl.exe command line, causing a flood of warning spam.

**Comment by wrwilliams** [comment]
@pefoley2 Do you have any idea how to ensure that these flags get passed to the build tool appropriately in CMake?

**Comment by pefoley2** [comment]
It looks like the actual issue was an incorrect pragma in InstructionAPI.h causing warning 4251 to be unconditionally enabled
See https://github.com/pefoley2/dyninst/commit/9ea3f33c682c4ed6ad8ceb93b2ef258c5fc4e880

**Comment by wrwilliams** [comment]
Very nice, and a good catch. That was really dumb of past-me.

**Comment by pefoley2** [comment]
It took a while to figure out why the flag wasn't applying, but it was obvious once I figured out what was happening :)

**Comment by wrwilliams** [comment]
Verified that this is fixed on master; closing.
