### ISSUE TITLE
[ARMv8 Decoding] SMADDL and SMSUBL should have 32-bit register for operands 2 and 3

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#266]
Bytes: `97 40 39 9b`
Output: `smaddl x23, x4, x25, x16`
Expected Output: `smaddl x23, w4, w25, x16`

Bytes: `8c b1 3f 9b`
Output: `smsubl x12, x12, xzr, x12`
Expected Output: `smsubl x12, w12, wzr, x12`

**Comment by ssunny7** [comment]
Fixed by c3b108218fc2985b88a485c8b9a62364270d9a46.
