### ISSUE TITLE
[ARMv8 Decoding] SQRSHRN should be SQRSHRN2

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#269]
Bytes: `fc 9e 0b 4f`
Output: `sqrshrn q28, q23, 0x5`
Expected Output: `sqrshrn2 v28.16b, v23.8h, #5`

Other SQSHR* instructions have the same problem.

**Comment by ssunny7** [comment]
Fixed by 4ec677a01ef566c4a5713255c1fa7d390009aefe.

**Comment by nathanhjay** [comment]
It seems like there might be a new issue created by this fix.

Now, the non-SIMD version of the instruction has a "2" at the end when it should not.
Here's an example: 

Bytes:`c0 9f 16 5f`
Dyninst: `sqrshrn2 h0, s30, 0xa`
Expected: `sqrshrn h0, s30, 0xa`

**Comment by ssunny7** [comment]
This issue reported in the last comment should be fixed by ff4ffd9.
