### ISSUE TITLE
AppVeyor having issues downloading boost

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#270]
I'm not sure who is in charge of the AppVeyor, but it's having issues downloading and building boost during the build stage:

```
CUSTOMBUILD : error : downloading 'http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.7z' failed [C:\projects\dyninst\boost.vcxproj]
```

@wrwilliams Can you point someone at this who knows how to fix this?

**Comment by jdetter** [comment]
I'm not seeing this issue anymore after triggering a rebuild. Source Forge may have been having issues?

**Comment by pefoley2** [comment]
They seem to have unreliable infrastructure, but they're still the official source according to http://www.boost.org/
