### ISSUE TITLE
BPatch_binaryEdit::writeFile() fails for stack diversification

### ISSUE THREAD

**Issue by morehouse** [dyninst/dyninst#311]
Starting at commit 31fcb133, BPatch_binaryEdit::writeFile() returns false and fails to instrument with StackMods when using stack diversification.  Probing further reveals that writeFile() is returning false because AddressSpace::patch() is returning false.

Note that the problematic commit originally fixed #111, so we wouldn't want to just revert it.  It is also possible that the problem originated with earlier changes to codegen-x86.C but was hidden by issue #111 until this commit.

**Steps to reproduce**
Needed files:

- Everything in /p/paradyn/development/mm/projects/performStackMods
- Everything in /p/paradyn/development/mm/projects/utils
- /p/paradyn/development/mm/projects/bashrc

How to compile:

1. Copy necessary folders/files to your own machine.  Keep the relative locations of the performStackMods folder and the utils folder the same.
2. Modify bashrc to point DYNINST_ROOT to your Dyninst install directory and TOOLS_ROOT to the directory containing the performStackMods and utils folders.
3. Execute `. bashrc`
4. Run `make clean && make` inside utils/getExecutableProcedures, utils/getFunction, and performStackMods/

How to run:
`./performStackMods -b tonto-orig -o tonto-rewrite -v -d`

**Comment by jdetter** [comment]
Thank you for the detailed issue. I will start looking at this today!

**Comment by jdetter** [comment]
I can confirm this issue still exists at 78032155bdac8f83e7f4112ff41a47aed68e9822, I think it's likely the issue actually was introduced at the merge fae68e61b8d6b7163adfe94cb5f5b3e3a8743c61. Also I'm not sure why but the reproducer is running really really slow on these older commits (runs taking about 20 minutes). @morehouse  are there any smaller binaries that you can find that reproduce this issue?

**Comment by jdetter** [comment]
@morehouse Any more issues here?

**Comment by morehouse** [comment]
Looks good to merge.  The issues I'm having now are related to StackMod.  This issue is fixed by your pull request.
