### ISSUE TITLE
arm64: test_stack_1 test log

### ISSUE THREAD

**Issue by ikitayama** [dyninst/dyninst#315]
@wrwilliams this is a log of the test test_stack_1 with debugging information.
 
https://gist.github.com/ikitayama/c1e5ac2549cc830d74742d1e1edafdb2

Do you agree that the log indicates the job stops where it should, due to the yet to be implemented features for arm64? The code base can be checked at ikitayama/dyninst:arm64_dev.

**Comment by wrwilliams** [comment]
I'm not positive; DYNINST_DEBUG_PROCCONTROL is I think the wrong set of output here. DYNINST_DEBUG_STARTUP and DYNINST_DEBUG_STACKWALK will be more informative. (Basically, the startup logs will give us better-abstracted data about what Dyninst is doing during process creation and how far we get; the stackwalk logs will, once we reach the point where we can create a process cleanly, show us what we're doing in the unwind process.)

**Comment by ikitayama** [comment]
Running with STACKWALK set to 1:
https://gist.github.com/ikitayama/8715d8b1877664efdc46423e215b78b7

STARTUP set to 1:
https://gist.github.com/ikitayama/4a2e267df3892d10dbc36238cb408586

I think the second patch in #313 at least should be applied to master, otherwise on arm64
this test finishes without success pretty prematurely. The other one is purely cosmetic, but
forbids producing messages unnecessarily.

**Comment by ikitayama** [comment]
@wrwilliams the above two logs seem reasonable to me. Would you check the log when you have time (not urgent at all)?

**Comment by wrwilliams** [comment]
Yes, those look pretty much accurate; we have no emitter so we can't see what's going on.

I've created a project for the ARM codegen implementation; I assume I'll need to toss you a collaborator invite so that you can see it, right?

**Comment by ikitayama** [comment]
Right. Thank you.
