### ISSUE TITLE
GCC7 issues: new warnings, building with cotire causes GCC crash

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#321]
Reported by @wcohen:

Hi All,

I attempted to rebuild the dyninst rpm for Fedora rawhide and it failed (https://koji.fedoraproject.org/koji/taskinfo?taskID=17680868).  Fedora Rawhide now uses GCC 7 to compile code.  There are a number of additional check that are performed and the resulting warnings are treated as errors causing the RPM build to fail.  The build log for x86_64 (https://kojipkgs.fedoraproject.org//work/tasks/894/17680894/build.log) shows a number of warning/errors for "-Wimplicit-fallthrough".  SystemTap had a similar issue that was fixed (https://sourceware.org/git/gitweb.cgi?p=systemtap.git;a=commit;h=575fe913f6b6b81421f7bfda7c72ab8c15ecb8e3).

-Will

**Comment by wrwilliams** [comment]
Follow-up, also from @wcohen: 

There is some information about porting to gcc 7 at:

https://gcc.gnu.org/gcc-7/porting_to.html
https://gcc.gnu.org/gcc-7/changes.html

-Will

**Comment by cuviper** [comment]
I don't think the warnings are being treated as errors -- there's no `-Werror` in use, after all.  If you look further in that log, there's a compiler segfault, which is always a compiler bug.  To that end, I filed:
[rhbz1420551](https://bugzilla.redhat.com/show_bug.cgi?id=1420551).

It's a strange one though, as I got different failures each time, but always on `Ident.C`.  I can't reproduce those problems locally, but since it also happens on several arches, I wouldn't blame the builder hardware either.

Occasionally it gets through, then it reaches this legitimate error:

```
/builddir/build/BUILD/dyninst-9.3.0/testsuite-9.3.0/src/JUnitOutputDriver.cpp:38:39: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
             if(last_group->mutatee != '\0') suitename << "." << last_group->mutatee;
                                       ^~~~
```

It looks like that might want to be a null-pointer check, although it might also intend to check if the first character is NIL, as an empty string.  But I suppose that's one for the testsuite repo...

**Comment by wrwilliams** [comment]
@cuviper is this on testsuite head or on the release tag? I drastically redid the JUnit outputter recently.

**Comment by cuviper** [comment]
@wrwilliams that's on the release tag.  I haven't looked closer at this part yet, not even to see if master has changed that code.  When I can't rely on GCC, little else matters. :)

**Comment by wrwilliams** [comment]
Fair enough, just be warned that I'm writing 9.3.0 off as "considered harmful" per #323.

**Comment by cuviper** [comment]
OK.  Those problems shouldn't matter in the Fedora setting though.

**Comment by cuviper** [comment]
FWIW, the `last_group->mutatee != '\0'` is commented out [here](https://github.com/dyninst/testsuite/blob/a3a09f9326e5b1fbc145a09cdd834a2239fe3827/src/JUnitOutputDriver.cpp#L128) on testsuite master.

I'm still having trouble with GCC itself though.

**Comment by cuviper** [comment]
I ran a build with cotire disabled and that testsuite line patched to `mutatee != nullptr`, and it worked!
https://koji.fedoraproject.org/koji/taskinfo?taskID=17888674

There are still plenty of warnings from GCC7, but nothing outright blocking.

**Comment by wrwilliams** [comment]
Excellent. I'm moving up to GCC 6 for my local testing, but I don't have GCC 7 set up anywhere convenient yet; I'm going to treat the warning cleanup as a real but low priority.

**Comment by cuviper** [comment]
GCC7 isn't even released yet, so it's perfectly reasonable that you don't have it yet.  Rawhide has a pre-release snapshot mostly so we can start rebuilding things, and find potential issues.

Semi-related, DWARF5 was just released, and GCC7 will support a lot of the new forms.  Actually I think even GCC6 has some experimental support.  AFAIK `-gdwarf-4` will still be the default for now.

**Comment by mxz297** [comment]
Outdated because Dyninst 10.0 and master can be compiled with GCC 7
