### ISSUE TITLE
Auto-detect Cilk

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#326]
Dyninst should auto-detect, at CMake time, whether cilk_spawn/cilk_join are available for use, automatically build the Cilk runtime if it's not present, and provide proper macro wrappers so that cilk code works correctly when we're building single-threaded.

Nice to have: allow users to enable/disable use of Cilk if it's present; allow multiple multithreading options (e.g. OpenMP) if it's possible to create a consistent set of wrapper macros/functions for all of them.

**Comment by mxz297** [comment]
Obsoleted
