### ISSUE TITLE
Migrate Dyninst from libdwarf to libdw

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#328]
@cuviper: tagging/assigning you for advisory purposes only; if you have any partial work from previous attempts, can you pass it to @sashanicolas ?

**Comment by cuviper** [comment]
I did some initial (crude) hacking on this, but didn't get very far, just some of the frame parsing.  I'll try to push to a branch for you to see.

**Comment by wrwilliams** [comment]
The frame parsing is actually where we hit some of the big interface differences--I expect that things will line up more closely when we get into the dwarfWalker code itself.

Thanks, Josh.

**Comment by cuviper** [comment]
I was hoping to do more, get it cleaned up, etc., but then you might never see it. 😃 It was mostly before the holidays, so I've forgotten a lot of context already, but I just pushed what I've got to my [libdw branch](/cuviper/dyninst/tree/libdw).

I think the `dwarf/` stuff is mostly there, or at least compiles.  I haven't actually run any of it.  Note there's generally more abstraction to `libdw`'s frame info, which simplified a few things.  I also cleared away some old `#if 0` code.

Under `symtabAPI/`, I mostly just did some of the obvious type replacements, then started porting a few functions.  I think `Object::dwarf_parse_aranges` might be in good shape, but then I got stuck on `read_except_table_gcc3`.  Those same frame abstractions seem to be a hindrance here, and I wasn't sure how to proceed.  I was going to ask on the elfutils list for help, but just didn't get back to it yet.

So there you go.  Feel free to use my changes directly, or just refer to it as you work on your own, whatever you find easier.  And I'm happy to serve an advisory role going forward too.  If you use IRC, you can also find knowledgeable folks on freenode #elfutils -- mjw in particular is our elfutils maintainer.
