### ISSUE TITLE
Seg Fault on PPC64LE during attach

### ISSUE THREAD

**Issue by lee218llnl** [dyninst/dyninst#336]
When running STAT on a PPC64LE system, I am getting seg faults in DynInst on attach. This happens with the 9.3.0 release and with the latest (2/1/2017, commit https://github.com/dyninst/dyninst/commit/86d44d2ccdd94506751a71e83f92f6a665c2eba5). I previously had this working with commit https://github.com/dyninst/dyninst/commit/859cb778e20b619443c943c96dd1851da763142b, so a change in between may have caused this.  Below is a stack trace from the core file. Let me know if you have any thoughts on what is going wrong and how to fix this. 

bash-4.2$ gdb ./opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/bin/STATD ray41-STATD-137571.core 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/bin/STATD...(no debugging symbols found)...done.
[New LWP 137571]
[New LWP 137575]
[New LWP 137576]
[New LWP 137577]
[New LWP 137579]
[New LWP 137578]
[New LWP 137574]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-'.
Program terminated with signal 6, Aborted.
#0  0x00001000016eeb18 in raise () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.ppc64le glibc-devel-2.17-157.el7.ppc64le libgcc-4.8.5-11.el7.ppc64le libstdc++-4.8.5-11.el7.ppc64le munge-libs-0.5.12-1.SAG.ppc64le
(gdb) where
#0  0x00001000016eeb18 in raise () from /usr/lib64/libc.so.6
#1  0x00001000016f0c9c in abort () from /usr/lib64/libc.so.6
#2  0x00001000000dd1b0 in STAT_BackEnd::onCrash(int, siginfo_t*, void*) ()
   from /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/lib/libstatbe.so.0
#3  0x00001000000dccfc in onCrashWrap(int, siginfo_t*, void*) ()
   from /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/lib/libstatbe.so.0
#4  <signal handler called>
#5  Dyninst::Elf_X_Data::d_buf (this=0x3fffffff9a10)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/elf/src/Elf_X.C:833
#6  0x0000100000cb9fec in Dyninst::SymtabAPI::Object::loaded_elf (
    this=0x1009f130, txtaddr=@0x3fffffff9d18: 0, dataddr=@0x3fffffff9d10: 0, 
    bssscnp=@0x3fffffff9d50: 0x0, symscnp=@0x3fffffff9d48: 0x0, 
    strscnp=@0x3fffffff9d40: 0x0, stabscnp=@0x3fffffff9d38: 0x0, 
    stabstrscnp=@0x3fffffff9d30: 0x0, stabs_indxcnp=@0x3fffffff9d28: 0x0, 
    stabstrs_indxcnp=@0x3fffffff9d20: 0x0, rel_plt_scnp=@0x3fffffff9d08: 0x0, 
    plt_scnp=@0x3fffffff9d00: 0x0, got_scnp=@0x3fffffff9cf8: 0x0, 
    dynsym_scnp=@0x3fffffff9cf0: 0x0, dynstr_scnp=@0x3fffffff9ce8: 0x0, 
    dynamic_scnp=@0x3fffffff9ce0: 0x0, eh_frame=@0x3fffffff9cd8: 0x0, 
    gcc_except=@0x3fffffff9cd0: 0x0, interp_scnp=@0x3fffffff9cc8: 0x0, 
    opd_scnp=@0x3fffffff9cc0: 0x0)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/Object-elf.C:654
#7  0x0000100000cbfa1c in Dyninst::SymtabAPI::Object::load_object (
    this=0x1009f130, alloc_syms=true)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/Object-elf.C:1523
#8  0x0000100000cc0988 in Dyninst::SymtabAPI::Object::Object (this=0x1009f130, 
    mf_=0x1009f0e0, err_func=<optimized out>, alloc_syms=<optimized out>, 
    st=<optimized out>)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/Object-elf.C:2963
#9  0x0000100000c65964 in Dyninst::SymtabAPI::Symtab::Symtab (this=0x1009df20, 
    filename="\210\336\t\020\000\000\000\000\220\000\t\020\000\000\000\000\350\336\t\020\000\000\000\000\230\314\t\020\000\000\000\000\220\314\t\020\000\000\000\000\220\314\t\020\000\000\000\000\240\314\t\020\000\000\000\000\350\336\t\020\000\000\000\000`\240\377\377\377?\000\000\340\336\t\020\000\000\000\000\220\240\377\377\377?\000\000\220\314\t\020\000\000\000\000Tl\312\000\000\020\000\000\000\202\327\000\000\020\000\000\210\336\t\020\000\000\000\000\377\236\377\377\377?\000\000A\000\000\000\000\000\000\000\340\336\t\020\000\000\000\000`\241\377\377\377?\000\000\260\240\377\377\377?\000\000\000\241\377\377\377?\000\000\000\000\000\000\000\000\000\000\fy\312\000\000\020\000\000\000\202\327\000\000\020\000\000\210\336\t\020\000\000\000\000"...<Address 0x400000000000 out of bounds>, 
    defensive_bin=<optimized out>, err=@0x3fffffff9ff9: false)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/Symtab.C:1270
#10 0x0000100000c65dcc in Dyninst::SymtabAPI::Symtab::openFile (
    obj=@0x1009dee8: 0x0, filename="/opt/ibm/spectrum_mpi/bin/stock/orterun", 
    def_binary=<optimized out>)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/Symtab.C:2105
#11 0x0000100000ca6c54 in Dyninst::SymtabAPI::SymtabReader::SymtabReader (
    this=0x1009dee0, file_=...)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/SymtabReader.C:53
#12 0x0000100000ca790c in Dyninst::SymtabAPI::SymtabReaderFactory::openSymbolReader (this=0x1009cc90, pathname="/opt/ibm/spectrum_mpi/bin/stock/orterun")
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/symtabAPI/src/SymtabReader.C:288
#13 0x0000100000e37604 in Dyninst::FCNode::parsefile (this=0x1009de00)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtra---Type <return> to continue, or q <return> to quit---
nslate-sysv.C:927
#14 0x0000100000e37c9c in Dyninst::FCNode::getInterpreter (this=0x1009de00)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-sysv.C:877
#15 0x0000100000e3cb0c in Dyninst::AddressTranslateSysV::setInterpreter (
    this=0x1009dcd0)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-linux.C:146
#16 0x0000100000e37e58 in Dyninst::AddressTranslateSysV::parseInterpreter (
    this=<optimized out>)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-sysv.C:550
#17 0x0000100000e38114 in Dyninst::AddressTranslateSysV::init (this=0x1009dcd0)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-sysv.C:606
#18 0x0000100000e382cc in Dyninst::AddressTranslateSysV::AddressTranslateSysV (
    this=0x1009dcd0, pid=<optimized out>, reader_=0x1009dbe0, 
    reader_fact=0x1009cc90, exename=..., interp_base=18446744073709551615)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-sysv.C:433
#19 0x0000100000e384b8 in Dyninst::AddressTranslate::createAddressTranslator (
    pid_=<optimized out>, reader_=0x1009dbe0, symfactory_=0x1009cc90, 
    exename=..., interp_base=18446744073709551615)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/common/src/addrtranslate-sysv.C:366
#20 0x00001000005b8e70 in sysv_process::constructTranslator (this=0x10096770, 
    pid_=<optimized out>)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/sysv.C:115
#21 0x00001000005b90c8 in sysv_process::translator (this=0x10096770)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/sysv.C:399
#22 0x00001000005b92bc in sysv_process::initLibraryMechanism (this=0x10096770)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/sysv.C:211
#23 0x00001000005b9cb4 in sysv_process::refresh_libraries (this=0x10096770, 
    added_libs=std::set with 0 elements, rmd_libs=std::set with 0 elements, 
    waiting_for_async=@0x3fffffffa7b0: false, 
    async_responses=std::set with 0 elements)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/sysv.C:244
#24 0x000010000052b690 in int_process::initializeAddressSpace (
    this=0x10096a68, async_responses=std::set with 0 elements)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/process.C:688
#25 0x00001000005c4368 in thread_db_process::post_attach (this=0x100967c0, 
    wasDetached=<optimized out>, aresps=...)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/int_thread_db.C:1069
#26 0x0000100000549dc4 in int_process::attach (ps=0x3fffffffab10, 
    reattach=false)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/process.C:504
#27 0x000010000054ad34 in Dyninst::ProcControlAPI::Process::attachProcess (
    pid=<optimized out>, executable=...)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/proccontrol/src/process.C:6273
#28 0x0000100000414a78 in Dyninst::Stackwalker::ProcDebug::newProcDebug (
    pid=<optimized out>, executable=...)
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/stackwalk/src/sw_pcontrol.C:92
#29 0x00001000003fef94 in Dyninst::Stackwalker::Walker::createDefaultProcess (
    pid=<optimized out>, executable=...)
---Type <return> to continue, or q <return> to quit---
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/stackwalk/src/walker.C:622
#30 0x0000100000400740 in Dyninst::Stackwalker::Walker::newWalker (
    pid=<optimized out>, executable="output")
    at /var/tmp/lee218/spack-stage/spack-stage-8g_xM_/dyninst/stackwalk/src/walker.C:126
#31 0x00001000000e12ec in STAT_BackEnd::attach() ()
   from /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/lib/libstatbe.so.0
#32 0x00001000000df9d0 in STAT_BackEnd::mainLoop() ()
   from /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.8.5/stat-3.0.1b-5tcn7pnw7v3xzsuu5yzkdblpctghyxsz/lib/libstatbe.so.0
#33 0x000000001000527c in main ()
(gdb)

**Comment by wrwilliams** [comment]
This looks like the crashes we've seen when folks use libelf.so.0 with 9.3 and later. 9.3.1 (which should be created off the v9.3.x branch as soon as I have some time to document a few things) will automatically grab elfutils libelf and require libelf.so.1 at configuration time, but if you've got an old build tree that's got libelf.so.0 configured in, it may need its CMake cache cleared in order to do the right thing (and certainly you'll need to specify which libelf to use in 9.3.0, or our automatic download will be wrong).

In any event, I'd recommend updating the spack information for 9.3+ to reflect that dependency change.

**Comment by lee218llnl** [comment]
Thanks @wrwilliams linking against libelf.so.1 does indeed get around this attach issue. I will update Spack accordingly. And as a heads up, I've got another issue coming your way when trying to get line number info.

**Comment by wrwilliams** [comment]
Fixed by #318.
