### ISSUE TITLE
Include code for 'libiberty' in source

### ISSUE THREAD

**Issue by jacksgt** [dyninst/dyninst#342]
Hi,

could you please consider putting `libiberty` into your source code?

From https://gcc.gnu.org/onlinedocs/libiberty/Using.html#Using :
> To date, libiberty is generally not installed on its own. It has evolved over years but does not have its own version number nor release schedule.
> 
> Possibly the easiest way to use libiberty in your projects is to drop the libiberty code into your project’s sources, and to build the library along with your own sources; the library would then be linked in at the end. This prevents any possible version mismatches with other copies of libiberty elsewhere on the system.
>
> For your own projects, an approach which offers stability and flexibility is to include libiberty with your code, but allow the end user to optionally choose to use a previously-installed version instead. In this way the user may choose (for example) to install libiberty as part of GCC, and use that version for all software built with that compiler. (This approach has proven useful with software using the GNU readline library.) 

Also the description of the [Debian package libiberty-dev](https://packages.debian.org/jessie/libiberty-dev) says:
> This library shouldn't be used by other software, but unfortunately already is. There is no guaranty for a stable library API, and no shared library is provided. 

libiberty is [dual licensed under LGPL/BSD](https://gcc.gnu.org/onlinedocs/libiberty/Licenses.html#Licenses)

**Comment by wrwilliams** [comment]
The dual license would make this a feasible thing, definitely. The weird optional dependency dates back to gpl-only days.

One of my TODOs is to make each Dyninst so self-contained, as well, so that there are no funny dependencies to manage and you link exactly what you use. Suspect that's relevant here.

**Comment by jacksgt** [comment]
@wrwilliams Sounds good, please do that! :-)

**Comment by mxz297** [comment]
Dyninst 10.1's new build system has updated handling of libiberty
