### ISSUE TITLE
Test 4_1, 4_2, and 4_4 fail on ppc64

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#35]
Reproduced on vulcan. All modes. 4_3, oddly, passes.

**Comment by wrwilliams** [comment]
All of these are due to a broken exit callback and not receiving the exit code correctly.

**Comment by wrwilliams** [comment]
Needs a cross-check against #50 to see whether there's any common root cause.

**Comment by jdetter** [comment]
Did the test finish due to failure or due to a timeout?

**Comment by wrwilliams** [comment]
On ppc, they're straight failing. Do we get meaningful output on x86 if they're run individually with -verbose -log?

**Comment by jdetter** [comment]
On Fedora 23, it wouldn't terminate even after 20 minutes of run time:

```
[root@localhost testsuite]# ./test_driver -test test4_2 -log -verbose
Commencing test(s) ...
Tue May 17 12:13:19 CDT 2016
Linux localhost.localdomain 4.4.8-300.fc23.x86_64 #1 SMP Wed Apr 20 16:59:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/usr/local/bin/testsuite
[Tests with test4_2.dyn_g++_64_none_none]
-rwxr-xr-x. 1 root root 60944 May 10 17:17 test4_2.dyn_g++_64_none_none*
        linux-vdso.so.1 (0x00007ffd42355000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f19ae0a6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f19adda3000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f19adb8c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f19ad7cb000)
        /lib64/ld-linux-x86-64.so.2 (0x0000559d9cc73000)

Starting "test4_2.dyn_g++_64_none_none"
Process 0x2bbded0 createdProc 0 is pointer 0x2bbded0
Checking 1 threads for terminated status
Thread 0 is not terminated
Mutatee test4_2.dyn_g++_64_none_none [C++]:""
forkFunc called with parent 0xb01f180, child (nil)
in prefork for 2052
Checking 1 threads for terminated status
Thread 0 is not terminated
forkFunc called with parent 0xb01f180, child 0xab42710
in fork of 2052 to 2054
```

I'm rebuilding dyninst on the instructional machines with `-std=c++11` to fix the build issues we talked about. I will have testsuite results from that soon.

**Comment by jdetter** [comment]
Posted in #50.

**Comment by wrwilliams** [comment]
@cuviper: this looks like it could be the same sort of issue as the older x86 test4 issues you wrote about here: https://blog.cuviper.com/2013/11/25/systemtap-monitoring-ptrace-activity/ only at exit time. Kernel 2.6.32 on ppc64; the same kernel on x86_64 is behaving as expected. strace is getting sane exit codes back, so it can't be anything completely broken in ptrace, and we aren't instrumenting exit.

I don't have a ppc64 box that I can run systemtap on, though; if you can confirm whether or not this is fixable by injecting a PTRACE_SYSCALL when we receive the exit event, that would be awesome. (I also suspect that we can replace the check of the ptrace event value with a register read of the syscall argument register, but that seems like it's a gross workaround.)

**Comment by cuviper** [comment]
Good thing I wrote that blog post, so I can recall it more easily. :)

When you say 2.6.32, is this RHEL6?  FWIW in that prior issue, RHEL6 was unaffected due to its utrace adding a delay in firing off the ptrace fork events.  It still could be a similar issue though, and perhaps that old systemtap script is a good start.

I can grab a ppc64 machine from one of our labs to play with this...

**Comment by wrwilliams** [comment]
RHEL6 locally (x86) and CHAOS5 at LLNL (ppc64), which I think is RHEL6-based.

**Comment by cuviper** [comment]
This is an endian issue, oddly enough.  We get a proper-looking `unsigned long` wait status from `PTRACE_GETEVENTMSG`, then use `WEXITSTATUS` on it.  That looks like:

```c
# define WEXITSTATUS(status)    __WEXITSTATUS (__WAIT_INT (status))
```

And `__WAIT_INT` gets fancy under glibc's `__USE_BSD`, later called `__USE_MISC`, which are features enabled by default.

```c
/* Lots of hair to allow traditional BSD use of `union wait'
   as well as POSIX.1 use of `int' for the status word.  */

#  if defined __GNUC__ && !defined __cplusplus
#   define __WAIT_INT(status) \
  (__extension__ (((union { __typeof(status) __in; int __i; }) \
                   { .__in = (status) }).__i))
#  else
#   define __WAIT_INT(status)   (*(__const int *) &(status))
#  endif
```

So we hit the latter version.  Under 64-bit big-endian ppc64, that ends up reading the int from the most significant bits of the long, which are all zero.  Thus the exit code we read is just zero.

If I truncate that long into a local int first, then all tests pass.  I'll send a PR shortly.

**Comment by cuviper** [comment]
With #69, all of these tests pass for me on RHEL6 ppc64.

However, I'm also seeing the effects of #50 on Fedora 23 x86_64.  The same endian issue would not apply, so that will require a different investigation to fix.
