### ISSUE TITLE
add parseapi function callback

### ISSUE THREAD

**Issue by mwkrentel** [dyninst/dyninst#351]
Please add a ParseAPI callback for completion of Function parsing.
That is, a client would call CodeObject::parse() and when the parsing
for each ParseAPI::Function is completed, it would call this callback.

I guess the only argument for the callback would be the Function
pointer.  So, maybe a signature like:

virtual void function_cb(Function *);

Perhaps from the internals of the parse() you might think of something
else that would be needed or useful, I'm not sure.

An example use case would be hpcstruct analyzing a binary in parallel,
using CILK threads.  What we do now, in the serial case, is call
parse() to analyze the entire binary and then iterate through all the
Functions.  This method stores all of the parse info for the entire
binary all in memory all at once.

To do this piecemeal and in parallel, we would again call parse() to
analyze the entire code object.  This would spawn some number of CILK
threads.  When a thread finishes one Function, it would invoke the
callback function in the same thread.  Then, hpcstruct would do its
thing, write out the answer for that Function and delete the ParseAPI
info for that Function.  Besides adding parallelism, this would also
produce a smaller memory footprint.

I have one major technical concern which may be a little off topic.
As I understand things (and I don't understand the details), parsing
one Function can uncover new pieces from other Functions.  That is, I
might finish Function A, move on to Function B, and then discover new
things inside A.

Can you characterize what things can potentially change in a
previously finished Function?

Is it only new Function entry points, or can it include new
instructions in old Functions?

Don't forget to update the ParseAPI manual.

Thanks,

Mark Krentel

**Comment by wrwilliams** [comment]
@mxz297 can be more authoritative on this one, I think, but I'll take a stab anyway:

The parsing of functions can and does occur in an interleaved manner normally: reach a call site, parse the call target to determine whether it can return, continue parsing the caller with a return edge or lack thereof as appropriate. We should not be finalizing a function at the user callback level until we've finished this fixed point analysis. Also, discovering new code post-function finalization if you parse a CodeObject in a single parse() call would typically only occur when doing gap parsing or when we encounter shared code (or possibly if a call from elsewhere splits the function).

Post-finalization, assuming that we're not dealing with self-modifying code, there are three transformations I can think of that are legal at present:

1) One or more blocks in a function may have become shared, and acquired new in-edges.
2) One or more blocks in a function may have been split, with the second half of the original block acquiring new in-edges. Unless we're dealing with overlapping instructions, this also implies case 1.
3) We may have determined that some portion of the function is not properly treated as shared code, but as a tail call from F->G, and split the function. (I'm not sure if this is implemented, but we would consider it legal.)

There should be no case where, given a finalized F that was completely parsed, we subsequently discover new address ranges belonging to F, or where we determine that address ranges belonging to F are not in (F + F's callees). There should also be no case where an edge in F's CFG is removed from the final interprocedural CFG.

**Comment by mxz297** [comment]
As Bill mentioned, parsing functions is typically interleaved for the purpose of identifying whether functions will return or not. So, the earliest time for invoking the callback for function F is when the return status of F is determined. 

I also think this is also a good time for invoking a function callback because later parsing should not change the boundary of F. As Bill's 1 & 2, discovering new shared blocks should not change the boundary of F, so we do not have to delay delivering a function callback. 

Bill's 3 is currently not implemented. Right now, ParseAPI tries to determine whether a jump instruction is inter-procedural or intra-procedural the first time we encounter it. And we will not revise this decision. I agree that we may actually want to revisit this design in the future, though.

**Comment by mwkrentel** [comment]
Ok, I think I can (mostly) deal with that.

I'll know more when I try the callback functions and see what answers
I get.  There will surely be unforeseen complications with threads when
we're adding to the info in one function while concurrently deleting
another.

For my purposes, I don't really care if a block is split or joined.
All I really care about is the partition of functions into loops and
loops into instructions.  The partition of blocks into instructions
and edges doesn't really matter, as long as it doesn't change the loop
nesting.

Adding edges can create new loops, of course.  But if they're
interprocedural edges, then it probably doesn't change the loop
structure.  At least not until compilers become very sophisticated
about their interprocedural loop optimization. :-(

**Comment by wrwilliams** [comment]
@mwkrentel is the `newfunction_retstatus` callback I mentioned in email working okay for your purposes?

**Comment by mwkrentel** [comment]
Sorry, I haven't had a chance to try it yet, but hopefully soon.
busy, busy, busy, ...

**Comment by mwkrentel** [comment]
I started looking at newfunction_retstatus().  The first thing I
discovered was that this callback is only ever called when defensive
mode is turned on.

I'm guessing I probably don't want defensive mode.  Right?  So, the
question is: is there any reason to restrict the callback to defensive
mode?  That is, if the callback were always available, would anything
bad happen?

It's a simple edit to always run it.  I tired that and I got function
callbacks as I expected.

So now I can test it more seriously.  The key question is how complete
are the incremental callbacks compared to, "parse the whole thing and
then iterate through the functions."

Sometimes, there's a bit of, "until you know everything, you don't
know anything."  And I have to check if there's anything significant
that's missing before we know everything.

Time for the next unit test ...  :-)

**Comment by wrwilliams** [comment]
You do not want defensive mode, and there's no reason to restrict this callback. Sounds like you're planning to check:

1) for which function do we receive this callback more than once?
2) what changes in the CFG between callbacks for those functions?

That sounds like a pretty solid test to me.

**Comment by mwkrentel** [comment]
Actually, I was going to open the Symtab twice and compute the set of
basic blocks for each ParseAPI Function twice: once all at the end,
and once incrementally via the callbacks.  Then, see if the
incremental version is missing any functions or blocks.

But those sound like good things to check as well.

So, is that how I'd find out if something has changed in a previously
finalized function, I'd receive the callback multiple times?

**Comment by wrwilliams** [comment]
Yep. If you get the callback once and only once for a given function, the callback-time CFG and the big batch parsed CFG should be equal (also good to test, but I'm pretty confident that the callback is 1:1 with finalize calls at the function level).

**Comment by mwkrentel** [comment]
I've pushed my callback.cpp unit test to the hpctoolkit-tests repo on
github.  This program tests two things:

1. Does CodeObject::parse() survive threads (currently no).

2. Show what functions receive multiple callbacks, and test if the
function has grown (more basic blocks and instructions).

The problem in (1) is that if the callback function calls
getLoopTree(), then the thread deadlocks on a lock it holds itself.
main calls parse which calls parse_frames which calls
newfunction_retstatus which calls getLoopTree which calls findFuncs
which calls parse and this deadlocks.

This happens both with threads on the parallel-parsing branch and also
without threads on the v9.3.x branch.

I added the option './callback -B' to skip getLoopTree() and treat a
function as just a list of basic blocks (no loop structure).  With
this option, the parallel-parsing branch seems to survive threads.

As for (2), roughly 1/3 of the functions receive a second callback.
I'm guessing over the change in the return status of something it
calls.  A tiny fraction (maybe 0.1%) of the functions actually grow
and add new blocks.

**Comment by mxz297** [comment]
@mwkrentel Is this still relevant?

**Comment by mwkrentel** [comment]
@mxz297  Probably not still relevant.

This was from an earlier design, but as you know, we ended going in a
different direction.  Plus, there's the whole issue of convergence,
that is, when can you count on the answer.  The problem being, until
you know everything, you don't know anything.

So, feel free to close.

**Comment by mxz297** [comment]
Thanks!
