### ISSUE TITLE
compile errors (intel 32bit)

### ISSUE THREAD

**Issue by vanhauser-thc** [dyninst/dyninst#352]
from the current github state I get compile errors, all concerning read_val_of_type missing a type casting (just one example):

Building CXX object symtabAPI/CMakeFiles/symtabAPI.dir/src/Object-elf.C.o
/prg/tmp/dyninst/symtabAPI/src/Object-elf.C: In function 'bool read_except_table_gcc2(Dyninst::Elf_X_Shdr*, std::vector<Dyninst::SymtabAPI::ExceptionBlock>&, const mach_relative_info&)':
/prg/tmp/dyninst/symtabAPI/src/Object-elf.C:3645:52: error: invalid conversion from 'Dyninst::Offset* {aka unsigned int*}' to 'long unsigned int*' [-fpermissiv]
             i += read_val_of_type(DW_EH_PE_udata4, &try_start, datap + i, mi);

/prg/tmp/dyninst/symtabAPI/src/Object-elf.C:3225:12: note:   initializing argument 2 of 'int read_val_of_type(int, long unsigned int*, const unsigned char*, const mach_relative_info&)'
 static int read_val_of_type(int type, unsigned long *value, const unsigned char *addr,
            ^~~~~~~~~~~~~~~~

**Comment by cuviper** [comment]
Probably the same as #343.  There's a fix already on the `v9.3.x` branch, and #350 includes that fix for the `master` branch.

**Comment by vanhauser-thc** [comment]
Yes #350 fixes this and a other compiler errors I encountered. thanks!
