### ISSUE TITLE
Make Dyninst .sos self-contained

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#354]
Dyninst's shared library targets have a fair number of dependencies, both internal and external. At a minimum, users should not need to worry about .so conflicts between our external dependencies and their project's use of those dependencies. Therefore, we should ensure we link against static/PIC versions of the following:

* libelf
* libdwarf/libdw
* boost libs (thread, system, etc)
* libiberty
* threaddb

Pthreads is, I think, okay to link shared, as are the standard C/C++ libs.

**Comment by cuviper** [comment]
Please make this **optional**.  We don't want static linking in distro packages.

You'll also have to be careful that the symbol visibility is correct, to be sure you don't end up providing those static symbols to anyone else.

When it comes to stuff like boost which is in Dyninst's public API, can you really internalize this?  You say only for boost libs, but if `shared_ptr` et al. already have to match the user, the libs are a minor point.

**Comment by wrwilliams** [comment]
I can certainly make this optional, and making the symbol visibility correct is essential or it doesn't meet anyone's goals for anything.

WRT boost specifically, there's still a significant dropoff from systems that have boost headers installed to systems that have boost libraries installed, and most of the use of boost libraries that we have (I won't swear all) is de facto, if not de jure, not public. And the goal here is to ensure that Dyninst libs can be built on (for example) front-end nodes with a full development environment and used on compute nodes with a more minimal set of packages.

**Comment by jdetter** [comment]
Could we make an option in the CMake where you can specify a list of libraries you want to link against statically? That way if you only have issues with boost, then you can just specify boost. To keep the old behavior by default, we would just make this list empty by default. 

I think this would help a lot of people who don't want to mess around with installing boost with a prefix in their home directory and then using LD_LIBRARY_PATH to use that version of boost dyninst. This would also allow you to build dyninst on a system that has a rich build environment and move it to a system that has a minimal build environment. You could make this argument for any of the dependent libraries but I think boost is generally the largest source of build and runtime compatibility issues for dyninst.

That's my opinion as a user and obviously I don't know what issues people are having in distributed/enterprise environments but as a user I would benefit from this feature.

**Comment by fche** [comment]
A possibly-related problem is that with dyninst 10, boost::system link dependencies appear when a dyninst mutator just uses some of the header files.  It's not enough to link against -ldyninstAPI; one has to link clients against -lboost_system too.  (This on fedora rawhide/30 and its linker defaults.)

**Comment by mxz297** [comment]
Dyninst 10.1's new build system has significantly improvement on installing dependencies and setting RPATH.
