### ISSUE TITLE
assert fails at insnCodeGen::generateBranchViaTrap

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#356]
insnCodeGen::generateBranchViaTrap on ppc linux using dyninst 9.3.1.1 can get an assertion failure.
Seen in e.g. test1_4, test1_10
(gdb) list
	    if (ABS(disp) <= MAX_BRANCH) {
	        // We shouldn't be here, since this is an internal-called-only func.
	        return generateBranch(gen, disp, isCall);
	    }
	    assert (isCall == false); // Can't do this yet

(gdb) bt 10
#0  0x00003fffb7750f50 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00003fffb7752f58 in __GI_abort () at abort.c:90
#2  0x00003fffb7746cac in __assert_fail_base (fmt=0x3fffb789bc00 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x3fffb75f7b08 "isCall == false", 
    file=0x3fffb75f7ab0 "/builddir/build/BUILD/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/codegen-power.C", line=<optimized out>, 
    function=<optimized out>) at assert.c:92
#3  0x00003fffb7746d9c in __GI___assert_fail (assertion=0x3fffb75f7b08 "isCall == false", 
    file=0x3fffb75f7ab0 "/builddir/build/BUILD/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/codegen-power.C", line=<optimized out>, 
    function=0x3fffb75f74d8 <insnCodeGen::generateBranchViaTrap(codeGen&, unsigned long, unsigned long, bool)::__PRETTY_FUNCTION__> "static void insnCodeGen::generateBranchViaTrap(codeGen&, Dyninst::Address, Dyninst::Address, bool)") at assert.c:101
#4  0x00003fffb75b56d8 in insnCodeGen::generateBranchViaTrap (gen=..., from=234946896, to=to@entry=268507212, 
    isCall=<optimized out>) at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/codegen-power.C:259
#5  0x00003fffb75b6c40 in insnCodeGen::modifyJump (target=268507212, insn=..., gen=...)
    at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/codegen-power.C:771
#6  0x00003fffb75bde8c in Dyninst::Relocation::CFPatch::apply (this=0x15d4fe40, gen=..., buf=0x15d0eaf8)
    at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/Relocation/Widgets/CFWidget-ppc.C:141
#7  0x00003fffb759f204 in Dyninst::Relocation::CodeBuffer::BufferElement::generate (this=this@entry=0x15d4fcd0, 
    buf=buf@entry=0x15d0eaf8, gen=..., shift=@0x15d0ec8c: 328, regenerate=@0x3fffffffdd97: true)
    at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/Relocation/CodeBuffer.C:117
#8  0x00003fffb759f4f0 in Dyninst::Relocation::CodeBuffer::generate (this=0x15d0eaf8, baseAddr=<optimized out>)
    at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/Relocation/CodeBuffer.C:274
#9  0x00003fffb7566a78 in Dyninst::Relocation::CodeMover::relocate (this=<error reading variable: value has been optimized out>, 
    addr=<optimized out>) at /usr/src/debug/dyninst-9.3.1/dyninst-9.3.1/dyninstAPI/src/Relocation/CodeMover.C:180

**Comment by wrwilliams** [comment]
So, a few things here:

1) We should be able to emulate a call as a MTLR/trap combination if we really need to. It'll obviously be slow, and we don't want to do that.
2) We should not, ordinarily, need to emulate a call just because we relocated something. Output from running with DYNINST_DEBUG_RELOCATION and DYNINST_DEBUG_INFMALLOC set to 1 in your environment will be helpful in finding why we're not putting this code appropriately near its original copy.
3) Anything that we could emulate as a MTLR/trap, we could also emulate as a "construct CFT in scratch register, move to count register, bctrl" sequence given that we're relocating anyway and can expand the bytes.

**Comment by wrwilliams** [comment]
Fixed by #361, so I'm closing this issue.
