### ISSUE TITLE
update member function names in dyninst programmer's guide release 9.2 

### ISSUE THREAD

**Issue by zygyz** [dyninst/dyninst#357]
In section 4.27.1 of the dyninst programmer's guide release 9.2, the member function names 
'isALoad_NP()' and 'isAStore_NP()'  should be changed to 'isALoad' and 'isAStore' due to the member function name changes in the DynInst source code release of version 9.3.0 .

**Comment by hainest** [comment]
No documentation mentions isA[Load|Store]_NP anymore.
