### ISSUE TITLE
Misc. x86 Decoding Issues

### ISSUE THREAD

**Issue by nathanhjay** [dyninst/dyninst#372]
Below is a gist with remaining issues on dyninst AT&T syntax. Example instructions for each issue are given, but are not exhaustive (some issues affect addressing modes, so including all opcodes would be pretty excessive).

Most remaining issues have to do with:
old VEX encodings (or VEX2 and VEX3 instructions that have been extended),
uncommon prefixes,
mod/rm,
or formatting that may be a result of the switch to AT&T syntax (operand order, size included in opcode)

https://gist.github.com/nathanhjay/5b74260849233fba2a4ff37c956641e1

**Comment by jdetter** [comment]
New issue reported by rice:

```
62 e1 7f 00 2a c3       vcvtsi2sd %ebx,%xmm16,%xmm16
```

This is decoded as No_Entry.

**Comment by jdetter** [comment]
The majority of these issues have been fixed and I haven't been able to reproduce the rest, most likely because the issue was generated from a version of dyninst that didn't have the fix.
