### ISSUE TITLE
Compilation issue wrt to libdwarf an then zlib

### ISSUE THREAD

**Issue by thomasdullien** [dyninst/dyninst#373]
Hey there,

I am trying to compile dyninst 9.3.2 on an ubuntu-derived machine. I ran into the issue documented at https://www-auth.cs.wisc.edu/lists/dyninst-api/2015/msg00152.shtml (libdwarf.a not compiled with -fPIC); compiled libdwarf from scratch with -fPIC, and then tried to proceed.

Unfortunately, I now have the issue that the libdwarf.a that is compiled with -fPIC wishes to obtain a zlib.a that is also compiled with -fPIC, and I would like to avoid a rat's tail of dependencies that need to be recompiled. What's the best way to proceed? :)

Cheers,
Thomas

**Comment by wrwilliams** [comment]
The best option here is to build a shared libdwarf if you want to avoid that rat's tail.

**Comment by thomasdullien** [comment]
Ok, will do :-) - whats the easiest way to tell the dyninst build process
to use the .so instead of the .a?

Cheers,
Thomas

Am 02.06.2017 19:09 schrieb "Bill Williams" <notifications@github.com>:

**Comment by wrwilliams** [comment]
-DLIBDWARF_LIBRARIES=/path/to/libdwarf.so

**Comment by wrwilliams** [comment]
@thomasdullien is this resolved to your satisfaction?

**Comment by wrwilliams** [comment]
Closing as obsolete due to libdw
