### ISSUE TITLE
libelf install not copying libelf-0.168.so

### ISSUE THREAD

**Issue by chriscz** [dyninst/dyninst#375]
Hi There,

I cannot clone this repository to submit a fix, it's a bit too big.

Anyhow, I realised during compilation that `libelf-0.168.so` isn't copied to the installation directory, while the `libelf.so` symlinks were. So here is a patch file to fix `CMakeLists.txt`.

[cmakelistsfix.txt](https://github.com/dyninst/dyninst/files/1084444/cmakelistsfix.txt)

**Comment by mxz297** [comment]
@sashanicolas You were working on fixing copying installation files. Is this now fixed?

**Comment by sashanicolas** [comment]
This suggestion was implemented in March 2018 (1c068645ed65b7686d3f4fe0268edb30a3f9a2fc). And d87dae5a72b2afbe621738241f708f8c7c87f812 fixes the same problem for libdw*.
