### ISSUE TITLE
Is there any APIs that can be used for finding the indirect calls?

### ISSUE THREAD

**Issue by jianghaizhi** [dyninst/dyninst#378]
Hi,

I want to use Dyninst for CFI instrumentation. 
Is there any APIs that can be used for finding the indirect calls? 

Thank you.

**Comment by mxz297** [comment]
Assume that you already find the function you want to instrument and get a BPatch_function pointer `f`, then you first get all call site instrumentation point and only instrument at the points that are dynamic (indirect calls). Below is an example to show the idea and relevant function calls. I do not guarantee the example can work without some changes.

```
BPatch_Vector<BPatch_point *> * callPoints = f->findPoint(BPatch_locSubroutine);
for (auto pit = callPoints->begin(); pit != callPoints->end(); pit++) {
    BPatch_point* p = *pit;
    if (p->isDynamic()) {
         // Find an indirect call. Do your instrumentation
    }
}
```

**Comment by jianghaizhi** [comment]
Thank you, @mxz297 .  
I want to get indirect calls that it has the call address stored in a register or a memory location. Does isDynamic() work for this?
