### ISSUE TITLE
Thunk call judgement condition

### ISSUE THREAD

**Issue by eastmoutain** [dyninst/dyninst#379]
Hi,

    Am confused with the logic to assert whether a flow control is thunk call with function 
```
bool PCSensitiveTransformer::insnIsThunkCall(InstructionAPI::Instruction::Ptr insn,
					     Address addr,
					     Absloc &destination) 
{
    ...
    // Check for a call to a thunk function
    if (target == (addr + insn->size())) {
        destination = Absloc(0, 0, NULL);
        return true;
    }
    ...

}
```
Here is my understanding: 
If the destination of "jump" or "call" follows the instruction itself, then it's a thunk call, right ? 

At What situation shall the compiler generate thunk call which meets the condition as the snippet shows above?

Thank you very much, waiting for your reply

Thomas

**Comment by wrwilliams** [comment]
This is a fairly common idiom on architectures without PC-relative addressing modes; either a direct "call next instruction/pop return address" sequence or a call to a stub that will move the RA into a register and return can be generated. x86-64, unlike its 32-bit ancestor, doesn't need this, so it's become much less common these days.

**Comment by wrwilliams** [comment]
Closing as answered.
