### ISSUE TITLE
The address of instructions

### ISSUE THREAD

**Issue by jianghaizhi** [dyninst/dyninst#380]
std::vector<Dyninst::InstructionAPI::Instruction::Ptr> insns;
        block->getInstructions(insns);
        std::vector<Dyninst::InstructionAPI::Instruction::Ptr>::iterator insn_iter;
        for (insn_iter = insns.begin(); insn_iter != insns.end(); ++insn_iter) {
            Dyninst::InstructionAPI::Instruction::Ptr insn = *insn_iter;
        }

I have got the instructions by this method, may I know how to get the correspond memory address in the binary for each instruction?   I tried insn->ptr(), but the results seem like 0x13b4ff8, not 0x400800.

Thank you.

**Comment by wrwilliams** [comment]
You want the version that gets <address, instruction> pairs (`getInsnAddrs` iirc).

**Comment by jianghaizhi** [comment]
I am new to Dyninst, could you explain this with a little more details？Thank you so much! @wrwilliams

**Comment by jianghaizhi** [comment]
I tried using the address of the first instruction in the block add the length of each instruction to get the address of each instruction. It worked. Thank you.

**Comment by wrwilliams** [comment]
In ParseAPI Blocks (and I believe also in BPatch_basicBlocks) there are methods like getInstructions that hand back either a vector of <Offset, Instruction::Ptr> or a map<Offset, Instruction::Ptr>, but your approach works fine too. Closing this one out.
