### ISSUE TITLE
Some executables do not produce expected output after relocation on ARMv8

### ISSUE THREAD

**Issue by ssunny7** [dyninst/dyninst#383]
Once relocation is performed on an executable on ARMv8, the relocated executable generated works fine in most cases. However, there are instances when it gives some sort of error or just doesn't give the correct output for valid input.

For example, the `find` executable built manually from the `findutils` package gives the following error when its relocated version is run: `failed to sort the costlookup array`. `du` gives the following output: `fts_read failed: '': Not a directory`.

I haven't found a pattern among the binaries that error out, although I didn't get the chance to investigate this issue fully. There may be some patterns, and it may be the case some scenario is not being handled in the relocation code or there is an off-by-one error.

**Comment by mxz297** [comment]
@sashanicolas Is this issue resolved?
