### ISSUE TITLE
parseAPI shouldn't segfault if c++filt cannot demangle a symbol

### ISSUE THREAD

**Issue by paulhaile** [dyninst/dyninst#390]
running SymtabAPI::Symtab::openFile(symTab, binaryPathStr), causes a segfault when c++filt is unable to demangle a symbol in the binary. We came accross this problem when the following symbol from our binary caused a segault: 
`_ZSt7forwardIZN7voltron19validator_node_bodyclISt5tupleIJN3tbb4flow10interface98internal20multifunction_outputIN5steel10solace_ptrIN8protocol10parametron28vol_spline_parameters_updateEEEEENS8_INS0_12update_errorISD_EEEEEEEEvSt7variantIJSE_St3setImSt4lessImESaImEEEERT_EUlSS_E_EOSR_RNSt16remove_referenceISR_E4typeE`

**Comment by mxz297** [comment]
Can I get a stack trace for this?

**Comment by paulhaile** [comment]
from backtrace command
`#18674 0x00007ffff5a93218 in P_cplus_demangle (
    symbol=0x8d4598 "_ZSt7forwardIOZN7voltron19validator_node_bodyclISt5tupleIJN3tbb4flow10interface98internal20multifunction_outputIN5steel10solace_ptrIN8protocol10parametron28vol_spline_parameters_updateEEEEENS8_INS0_12"..., nativeCompiler=<optimized out>, includeTypes=<optimized out>)
    at /sandbox/dyninst-master/common/src/linuxKludges.C:241








#18675 0x00007ffff6386cda in Dyninst::SymtabAPI::Symbol::getTypedName (this=0x8d46e0)
    at /sandbox/dyninst-master/symtabAPI/src/Symbol.C:125
#18676 0x00007ffff63a6085 in operator() (this=0x6705f0, x=...)
    at /usr/include/boost/multi_index/mem_fun.hpp:63
#18677 operator()<Dyninst::SymtabAPI::Symbol::Ptr> (this=0x6705f0, x=...)
    at /usr/include/boost/multi_index/mem_fun.hpp:58
#18678 boost::multi_index::detail::hashed_index<boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getTypedName() const)>, boost::hash<std::string>, std::equal_to<std::string>, boost::multi_index::detail::nth_layer<5, Dyninst::SymtabAPI::Symbol::Ptr, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol::Ptr, Dyninst::SymtabAPI::Symbol*, &(Dyninst::SymtabAPI::Symbol::Ptr::get() const)>, mpl_::na>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::offset, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, unsigned long, &(Dyninst::SymtabAPI::Symbol::getOffset() const)>, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::mangled, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getMangledName() const)>, mpl_::na, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::pretty, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getPrettyName() const)>, mpl_::na, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::typed, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getTypedName() co---Type <return> to continue, or q <return> to quit---
nst)>, mpl_::na, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<Dyninst::SymtabAPI::Symbol::Ptr> >, boost::mpl::v_item<Dyninst::SymtabAPI::Symtab::typed, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::hashed_non_unique_tag>::find_bucket (this=0x6705f0, v=...)
    at /usr/include/boost/multi_index/hashed_index.hpp:976
#18679 0x00007ffff63a6bd6 in insert_ (x=0x13d9e70, v=..., this=0x6705f0)
    at /usr/include/boost/multi_index/hashed_index.hpp:697
#18680 insert_ (x=0x13d9e70, v=..., this=0x6705f0)
    at /usr/include/boost/multi_index/hashed_index.hpp:701
#18681 insert_ (x=0x13d9e70, v=..., this=0x6705f0)
    at /usr/include/boost/multi_index/hashed_index.hpp:701
#18682 insert_ (x=0x13d9e70, v=..., this=0x6705f0)
    at /usr/include/boost/multi_index/ordered_index.hpp:633
#18683 insert_ (x=0x13d9e70, v=..., this=0x6705f0)
    at /usr/include/boost/multi_index/ordered_index.hpp:633
#18684 boost::multi_index::multi_index_container<Dyninst::SymtabAPI::Symbol::Ptr, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol::Ptr, Dyninst::SymtabAPI::Symbol*, &(Dyninst::SymtabAPI::Symbol::Ptr::get() const)>, mpl_::na>, boost::multi_index::ordered_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::offset, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, unsigned long, &(Dyninst::SymtabAPI::Symbol::getOffset() const)>, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::mangled, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getMangledName() const)>, mpl_::na, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::pretty, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getPrettyName() const)>, mpl_::na, mpl_::na>, boost::multi_index::hashed_non_unique<boost::multi_index::tag<Dyninst::SymtabAPI::Symtab::typed, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::const_mem_fun<Dyninst::SymtabAPI::Symbol, std::string, &(Dyninst::SymtabAPI::Symbol::getTypedName() const)>, mpl_::na, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<Dyninst::SymtabAPI::Symbol::Ptr> >::insert_ (this=0x6705e0, v=...) at /usr/include/boost/multi_index_container.hpp:488
#18685 0x00007ffff639a030 in final_insert_ (x=..., this=<optimized out>)
    at /usr/include/boost/multi_index/detail/index_base.hpp:150
#18686 insert (x=..., this=<optimized out>) at /usr/include/boost/multi_index/ordered_index.hpp:275





#18687 Dyninst::SymtabAPI::Symtab::addSymbolToIndices (this=this@entry=0x670490, sym=<optimized out>, 
    undefined=undefined@entry=false) at /sandbox/dyninst-master/symtabAPI/src/Symtab.C:866
#18688 0x00007ffff639a0a1 in Dyninst::SymtabAPI::Symtab::createIndices (this=this@entry=0x670490, 
    raw_syms=..., undefined=undefined@entry=false)
    at /sandbox/dyninst-master/symtabAPI/src/Symtab.C:765
#18689 0x00007ffff639b126 in Dyninst::SymtabAPI::Symtab::extractInfo (this=this@entry=0x670490, 


    linkedFile=0x673b40) at /sandbox/dyninst-master/symtabAPI/src/Symtab.C:1561
#18690 0x00007ffff639be16 in Dyninst::SymtabAPI::Symtab::Symtab (this=0x670490, filename=..., 
    defensive_bin=<optimized out>, err=@0x7fffffffd05e: false)
    at /sandbox/dyninst-master/symtabAPI/src/Symtab.C:1278
---Type <return> to continue, or q <return> to quit---
#18691 0x00007ffff639c2a7 in Dyninst::SymtabAPI::Symtab::openFile (obj=@0x7fffffffd208: 0x0, 
    filename=..., def_binary=Dyninst::SymtabAPI::Symtab::NotDefensive)
    at /sandbox/dyninst-master/symtabAPI/src/Symtab.C:2105
#18692 0x00007ffff730e763 in fetchPatchAddrInAllFunc (
    objectFilePath=0x670458 "/sandbox/voltron-gcc-release/test/voltron_tests", container=..., type=1)
    at /sandbox/intern_2017/hotpatch/libs/patch/parser.cpp:219
#18693 0x0000000000405ced in main (argc=3, argv=<optimized out>)
    at /sandbox/intern_2017/hotpatch/patch/akunatrace/main.cpp:106
`

**Comment by mxz297** [comment]
Closed by #396
