### ISSUE TITLE
ebx should be callee-saved

### ISSUE THREAD

**Issue by melsabagh** [dyninst/dyninst#399]
Shouldn't ebx on x86_32 be callee-saved? It seems to be incorrectly added to callWritten due to the assignment at this line: [https://github.com/dyninst/dyninst/blob/master/dataflowAPI/src/ABI.C#L222](https://github.com/dyninst/dyninst/blob/master/dataflowAPI/src/ABI.C#L222). This results in inconsistent slicing behavior when ebx is involved.

We discussed this some while ago on the mailing list. It seems the fix never made it to master.

**Comment by mxz297** [comment]
Closed by #425
