### ISSUE TITLE
InstructionAPI disassembly should match AT&T syntax

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#4]
* Addresses should be in bracket/paren form depending on architecture
* Binary functions in SIB expressions should evaluate to commas
* Immediates should get architecture-appropriate decorators
* Implicit operands should be hidden from disassembly
* Most appropriate register name should be chosen based on the instruction
* Dereference sizes should decorate dereferences appropriately.

**Comment by jdetter** [comment]
Should we make a separate branch for this since it's not going into 9.2.x?

**Comment by wrwilliams** [comment]
Sure. We can of course make incremental changes and port them over but this deserves a topic branch.

**Comment by jdetter** [comment]
Made new branch `att_syntax`, I will start working on this this weekend.

**Comment by jdetter** [comment]
@wrwilliams Should I resolve symbols for jumps and calls like objdump or is just printing the address good enough?

**Comment by wrwilliams** [comment]
Address is sufficient for now. If symbols are easy and non-expensive in the grand scheme of things, that may be sensible as an option, but let's get the version that Fleece can use working first.

**Comment by wrwilliams** [comment]
Obviated by specific disassembly issues.
