### ISSUE TITLE
failure processing linux-vdso64.so.1 image

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#406]
Seen on ppc64 on Fedora 26

The attached test fails.  One possibility is an attempt is made to get an image for linux-vdso64.so.1:
[sysv.C:279-U] - Found library /root/396/call-ifunc.x at 0
[sysv.C:279-U] - Found library /lib64/ld64.so.1 at 7fffb04f0000
[sysv.C:281-U] - Creating new library object for /lib64/ld64.so.1
[sysv.C:279-U] - Found library linux-vdso64.so.1 at 7fffb04d0000
[sysv.C:281-U] - Creating new library object for linux-vdso64.so.1
[sysv.C:307-U] - Didn't find old library /usr/lib64/ld-2.25.so at 7fffb04f0000, unloading

and subsequently stat is called and of course doesn't find it:
(gdb) fra
#0  MappedFile::check_path (this=0x1028e910, filename="linux-vdso64.so.1")
    at /usr/src/debug/dyninst-9.3.2/dyninst-9.3.2/common/src/MappedFile.C:226
226       if (0 != stat(filename.c_str(), &statbuf)) { 

Looking at the same test on x8664, linux-vdso64.so.1, also in the dynamic library list, is not handled
[396.zip](https://github.com/dyninst/dyninst/files/1352818/396.zip)

**Comment by wrwilliams** [comment]
In addrTranslate-sysV.C, in the `refresh` method we're explicitly skipping `linux-vdso` and `linux-gate` by name as libraries that are reported in the address space but don't have disk backing in the usual way; . However, we're doing a brittle exact match that doesn't include the 64-bit forms (and also doesn't accommodate any version other than .1).

The quick approach is a prefix regex match for these two pseudolibraries, but if anyone has a better plan than name matching here I'm all ears. (In particular, is there a useful distinction between "known" failures in address translation like these and "unknown" failures where we would explicitly want to halt & fail if a library refresh contains something we can't find on disk? It seems we'd only care for purposes of determining whether we need to create a memory-backed symtab/codesource; if the system tells us that a chunk of the address space has a name that doesn't exist on disk, I'd think we should believe it even if it's weird.)

Tagging @mplegendre and @cuviper specifically for their thoughts on the above, but happy to hear input from anyone else too.

**Comment by mplegendre** [comment]
VDSO detection has been annoying for a long time, and has remained a moving target as the kernel upgrades.  @DavidPoliakoff and I recently put some VDSO detection in Gotcha: https://github.com/LLNL/GOTCHA/blob/develop/src/gotcha_auxv.c
In short, you can try to detect it through /proc/PID/maps, AUXV, or the names in the link map.  I'd suspect that the AUXV approach may be the most future proof, but detecting names in the link maps is so trivial that it's tempting to just keep the list of possible names up-to-date as new kernels come out.

It's not clear to me what other situations would produce a link map with a not-present file, so I don't know how the case should be generally handled.  Are there any JIT systems that try to add their created code to link maps (perhaps to aid debuggers)?   If that happens, it might be an argument towards associating the link map with memory-backed symtab.

**Comment by wrwilliams** [comment]
Looking at the Gotcha code, I do like the AUXV approach, as it should(?) be the most general for VDSO detection. And the cases I can think of where we'd get a link map with a non-file entry are as follows:

1) VDSO
2) non-VDSO JIT
3) chrooted or otherwise heterogeneous tool/target environment s.t. the tool can't properly find a file in the way the target specifies it

It's that last case where I'm thinking we want to degrade gracefully rather than a hard fail.

**Comment by cuviper** [comment]
> 3. chrooted or otherwise heterogeneous tool/target environment s.t. the tool can't properly find a file in the way the target specifies it

e.g. with containers?  This will be more and more common...

Does `/proc/PID/map_files` (since kernel 3.3) help you?   I just found when looking at a chroot process from outside, those links *look* broken, but `stat -L` dereferencing them does show the same inode that the chroot process sees.  In other words, you can't get a working path with `readlink`, `canonicalize_file_name`, or the like, but it still works to access the file through that link.

**Comment by wrwilliams** [comment]
Hadn't even considered containers, but we've seen chroot used to handle the difference between login and compute nodes and their appropriately-optimized libraries. `/proc/PID/map_files` should handle any situation where the whole system isn't going to break down, as long as we make that the primary way of getting the files.

**Comment by mxz297** [comment]
@stanfordcox Is this still a problem in Dyninst 10.1?

**Comment by stanfordcox** [comment]
@mxz297 it is okay as  AddressTranslateSysV::refresh() is skipping it now:
      if (obj_name == "linux-vdso.so.1" ||
          obj_name == "linux-vdso64.so.1" ||
          obj_name == "linux-gate.so.1") 
      {
         continue;
      }

**Comment by mxz297** [comment]
Thanks!
