### ISSUE TITLE
dyninstAPI documentation typo

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#41]
In the description of the BPatch class, the documentation contains the api call
void setInstrStackFrame(bool) instead of void setInstrStackFrame**s**(bool)

**Comment by jdetter** [comment]
Fixed by 73da5f143551ea4311a14c310372c82c17c90d75

**Comment by jdetter** [comment]
VEX will hopefully be merged into master before the release of 9.2.X. If this is not the case, I will make a pull request to cherry pick this documentation fix into master for the release.

**Comment by jdetter** [comment]
fixed by #102
