### ISSUE TITLE
make failing in latest branch

### ISSUE THREAD

**Issue by tusharkarumudi** [dyninst/dyninst#419]
Hi All,
I am trying to use Dyninst for static instrumentation. I cloned the master branch and did a cmake and then when executing the make command its failing.
I am using an ubuntu 16.04  x86_64 os
Please find below the log
[  2%] Built target boost
[  4%] Built target LibIberty
[  4%] Building DyninstRT
[ 50%] Built target dyninstAPI_RT
[100%] Built target dyninstAPI_RT_static
[  4%] Built target DyninstRT
[  5%] Built target LibElf
[  5%] Linking CXX shared library libcommon.so
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_date_time
collect2: error: ld returned 1 exit status
common/CMakeFiles/common.dir/build.make:1088: recipe for target 'common/libcommon.so.9.3.2' failed
make[2]: *** [common/libcommon.so.9.3.2] Error 1
CMakeFiles/Makefile2:408: recipe for target 'common/CMakeFiles/common.dir/all' failed
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yuedeji** [comment]
Hi There, I meet the same issue. How did you fix it?

**Comment by huaguang** [comment]
me,too

**Comment by aruncgowda** [comment]
i am facig same problem 
how to fix it??
