### ISSUE TITLE
make[2]: *** No rule to make target `libiberty/libiberty.a', needed by `common/libcommon.so.9.3.2'.  Stop.

### ISSUE THREAD

**Issue by XL64** [dyninst/dyninst#420]
Hello,

when I try to compile dyninst trough spack on my linux SUSE i get the following error :+1: make[2]: *** No rule to make target `libiberty/libiberty.a', needed by `common/libcommon.so.9.3.2'.  Stop.

libiberty.a is correctly installed in build directory but I still get the error :+1: 

-- Could not find libiberty; downloading binutils and building PIC libiberty.
-- Using libiberty /tmp/j0489939/spack-stage/spack-stage-Z4IbKl/dyninst-9.3.2/spack-build/libiberty/libiberty.a

The complete path is given when declaring common to cmake but it seems cmakes removes it...
-- Building common...
-- Processing dependent target /tmp/j0489939/spack-stage/spack-stage-Z4IbKl/dyninst-9.3.2/spack-build/libiberty/libiberty.a...
-- CXX target common cotired without unity build.

I don't know if it is a cmake or dyninst build system error and I don't know what to do to finish my installation.

Can you please help me ?

Regards,

XL.

**Comment by wrwilliams** [comment]
Unless you are certain that the gcc demangler is insufficient, I'd toggle USE_GNU_DEMANGLER on and ignore libiberty; we're planning to do the same project-wide, and last I looked, PGI compilers were the only things that would generate names that cxa_demangle couldn't handle.

**Comment by XL64** [comment]
Thanks for the answer, it seems that changing the compiler in spack solved
the issue.

Best regards,

XL
