### ISSUE TITLE
Consolidate examples

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#421]
- [ ] Move to examples/ directory in this repo, preserving pointers to them from docs
- [ ] Add CMakeLists that builds each example
- [ ] Add link from README.md to examples
- [ ] Extract examples from Word to separate source docs (is there a good way to include source file contents by reference in a word doc yet?)
- [ ] Examples documentation/description page (wiki/website?)

**Comment by mxz297** [comment]
Make unstrip work again, but still need to integrate its build system into CMake.

**Comment by mxz297** [comment]
Add unstrip and codeCoverage to the example directory. Still need to add documentation and references for these two examples.
