### ISSUE TITLE
testsuite failures with separate debuginfo

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#423]
Our build environment builds separate debuginfo which has historically been overridden when building the dyninst testsuite.  I notice dyninst supports separate debuginfo in Elf_X::findDebugFile so I  tried running the testsuite using separate debuginfo and received a couple of errors that I don't see with infile debuginfo.  

test5_5
Type.C:1465: void Dyninst::SymtabAPI::fieldListType::fixupComponents(): Assertion `superclass != __null' failed.

#3  0x00007ffff6252074 in __GI___assert_fail (assertion=0x7ffff42e7125 "superclass != __null", 
    file=0x7ffff42e7148 "symtabAPI/src/Type.C", line=1465, 
    function=0x7ffff42e72a0 <Dyninst::SymtabAPI::fieldListType::fixupComponents()::__PRETTY_FUNCTION__> "void Dyninst::SymtabAPI::fieldListType::fixupComponents()") at assert.c:101
#4  0x00007ffff427170b in Dyninst::SymtabAPI::fieldListType::fixupComponents (this=0x42bf220)
    at symtabAPI/src/Type.C:1465
#5  0x00007ffff4271725 in Dyninst::SymtabAPI::fieldListType::getComponents (this=0x42bf220)
    at symtabAPI/src/Type.C:1441
#6  0x00007ffff5c2f357 in BPatch_type::getComponents (this=0x3c33fa0)
    at dyninstAPI/src/BPatch_type.C:232
#7  0x00007ffff5c2436b in BPatch_variableExpr::getComponents (this=0x88018b0)
    at dyninstAPI/src/BPatch_snippet.C:1472
#8  0x00007ffff271ea0b in test5_5_Mutator::executeTest (this=0x18ca1e0)
    at testsuite-9.3.0/src/dyninst/test5_5.C:125
#9  0x0000000000412f3e in executeTest (tester=0x18bec20, group=0x145bd00, test=0x145c380, param=std::map with 51 elements = {...})
    at test_driver.C:289

and
test1_24
dyninstAPI/src/BPatch_snippet.C[261]: non-integer array index type 
dyninstAPI/src/BPatch_snippet.C:264: AstNodePtr generateArrayRef(const BPatch_snippet&, const BPatch_snippet&): Assertion `0' failed.

#3  0x00007ffff6252074 in __GI___assert_fail (assertion=0x7ffff5d68d8b "0", 
    file=0x7ffff5d5a6b0 "dyninstAPI/src/BPatch_snippet.C", 
    line=264, 
    function=0x7ffff5d5b960 <generateArrayRef(BPatch_snippet const&, BPatch_snippet const&)::__PRETTY_FUNCTION__> "AstNodePtr generateArrayRef(const BPatch_snippet&, const BPatch_snippet&)") at assert.c:101
#4  0x00007ffff5c1ef7e in generateArrayRef (lOperand=..., rOperand=...)
    at /dyninstAPI/src/BPatch_snippet.C:264
#5  0x00007ffff5c23ad0 in BPatch_arithExpr::BPatch_arithExpr (this=0x7fffffffda90, op=<optimized out>, lOperand=..., rOperand=...)
    at dyninstAPI/src/BPatch_snippet.C:448
#6  0x00007ffff271f084 in test1_24_Mutator::executeTest (this=0x18c9290)
    at /usr/src/debug/dyninst-9.3.2/testsuite-9.3.0/src/dyninst/test1_24.C:171
#7  0x0000000000412f3e in executeTest (tester=0x18bec10, group=0x12617d0, test=0x1262d50, param=std::map with 51 elements = {...})
    at test_driver.C:289

**Comment by sashanicolas** [comment]
@stanfordcox I believe I fixed this issue with commit 0c3eb945180d2643858a4b303343356a10f07075. You can test and let me know.
