### ISSUE TITLE
Patch without libdyninstAPI_RT.so

### ISSUE THREAD

**Issue by jakkdu** [dyninst/dyninst#428]
Hi. 
I want to do some binary patch with dyninst.
I added very simple check to my program.
After that, I knew that to run my binary I need libdyninstAPI_RT.so.
Is there a way to patch the binary without the runtime library?
Thanks.

**Comment by wrwilliams** [comment]
Not without significant work; you'd need an entirely new patching mechanism.

**Comment by jakkdu** [comment]
Thanks.
