### ISSUE TITLE
BPatch_point.h:  typo in function name  getInsnAtPoint() 

### ISSUE THREAD

**Issue by zygyz** [dyninst/dyninst#431]
A member function in BPatch_point.h:  Dyninst::InstructionAPI::Instruction::Ptr getInsnAtPoint() may actually be Dyninst::InstructionAPI::Instruction::Ptr getInstructionAtPoint() according to dyninstAPI manual.

**Comment by sashanicolas** [comment]
@zygyz I don't see your pull request to fix it. Can you paste the link here?

**Comment by zygyz** [comment]
@sashanicolas 
Thanks for the reply. I didn't make a pull request. The file is https://github.com/dyninst/dyninst/blob/master/dyninstAPI/h/BPatch_point.h at line 232 
I used this function at it works the only issue is that the function name does not match the name described in DynInst manual.   I suggest it might be also ok to change the documentation instead of source codes.

**Comment by sashanicolas** [comment]
@zygyz That's very unfortunate. I apologize for the inconvenience. 
But anyway, you can collaborate by submitting a pull request correcting the manual too.
Feel free and encouraged to do so.

**Comment by sashanicolas** [comment]
@zygyz That's very unfortunate. I apologize for the inconvenience. 
But anyway, you can collaborate by submitting a pull request correcting the manual too.
Feel free and encouraged to do so.
