### ISSUE TITLE
dyninst not saving/restoring a register used in insertSnippet

### ISSUE THREAD

**Issue by vanhauser-thc** [dyninst/dyninst#434]
libImage -> opened image of a shared library
appBin -> opened image of a program that will get a function from libImage patched in

The function that will be patched is:
void bbCallback(uint16); // function parameter handed over in edi/rdi register

Code looks like this:
```
BPatch_function *bbCallback = findFuncByName(libImage, (char *) "bbCallback");
unsigned short = rand() % 0xffff;
BPatch_Vector < BPatch_snippet * >instArgs;
BPatch_constExpr bbId(randID);
instArgs.push_back(&bbId);
...
BPatch_funcCallExpr instIncExpr(*instBBIncFunc, instArgs);
BPatchSnippetHandle *handle = appBin->insertSnippet(instIncExpr, *bbEntry, BPatch_callBefore, BPatch_lastSnippet);
```

The problem is that dyninst (current github repository state) does not always saves and restores the edi/rdi register when this snippet is inserted.
That is then a problem when the function that gets the libary call patched in is receiving a parameter passed via that register.

the following screen grab of such an issue is here (see the comments beside the affected asm instructions):
![bug](https://user-images.githubusercontent.com/7396244/36629941-0c26c132-195e-11e8-81ce-dec92582edff.JPG)

**Comment by mxz297** [comment]
Thanks for reporting this issue. In principle, Dyninst should be able to realize that rdi is live and used after the instrumentation. This indicates that the register liveness analysis went wrong in this case. Is it possible to share your programs with me so that I can debug this problem?

**Comment by vanhauser-thc** [comment]
sure, its complicated though.

```
git clone https://github.com/vanhauser-thc/afl-dyninst
wget http://lcamtuf.coredump.cx/afl/releases/afl-2.52b.tgz
tar xzf afl-2.52b.tgz
cd afl-2.52b
make
cd ../afl-dyninst
ln -s ../afl-2.52b/ afl
make
```

then:
```
./afl-dyninst.sh -i unrar -o unrar_instr
./unrar_instr 
```
unrar_instr will crash because of rdi

unrar is attached (Linux x64)
[unrar.gz](https://github.com/dyninst/dyninst/files/1754768/unrar.gz)

I wrote a workaround for that bug in afl-dyninst (-f option) but that hurts perfmance.

**Comment by mxz297** [comment]
OK. There is one unfortunately conditional compilation that is not working.  It is easy to work around on linux x64 (See the changes: https://gist.github.com/mxz297/7a5da3db05c4b6bcfe7f24f5de8b11af). I will need to further make sure it will work on other architectures before committing it.

Now it crashes at a different point:

``` ./unrar_instr 
Error getting shm
terminate called after throwing an instance of 'RAR_EXIT'
Aborted (core dumped)
```
And I have the following backtrace:

```
#0  0x00007ffff6f84428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6f8602a in __GI_abort () at abort.c:89
#2  0x00007ffff7ae484d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ae26b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ae2701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ae2919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555559408f7 in ?? ()
#7  0x0000000000000000 in ?? ()
```

To further debug this, what functions are you instrumenting and with what kinds of instrumentation? One quick thought is that while Dyninst is able to correctly identify the locations of try/catch code blocks, Dyninst does not likely instrument exception handling correctly.

**Comment by vanhauser-thc** [comment]
I spend a day analyzing this weird crash.
This is rather an issue with unrar as it has weirdness in its ExitHandler stuff.
By little changes in the original unrar code I can produce the same issue. So its not a dyninst thing, it just makes the bug in unrar look different.

thanks for fixing the rdi issue, if I spot more dyninst issues I will open new ones :)

**Comment by vanhauser-thc** [comment]
I see that your fix seems not to be in the repository yet.
when will that be included?
its a critical bug ...

**Comment by mxz297** [comment]
Should be merged in this week or next. It is in pull request #437  and going through the normal testing process.
