### ISSUE TITLE
cannot find -ldwarf? 

### ISSUE THREAD

**Issue by 1Husin-Alhaj** [dyninst/dyninst#439]
I have a simple patch.cpp file uses Dyninst functions. 
I got an error during compile time,
$ g++ -L/home/husien/Downloads/DYN-API/dwarf -ldwarf patch.cpp -o patch
**/usr/bin/ld: cannot find -ldwarf**

What are the required dependencies to compile Dyninst cpp files correctly?
I have tested a lot of command line. Is there any makefile?

Thanks in advance

**Comment by mxz297** [comment]
Which version of Dyninst are you using? If you use a recent one such as the master branch from github, then we have switched to use libdw rather than libdawrf. So maybe you can try to change "-ldwarf" to "-ldw".

**Comment by 1Husin-Alhaj** [comment]
After installing Dyninst (really I do not know why it consumed about 4 hours), I have the following folder. 
README file says, in this folder, lib and include should be exsist?!! 
nothing here!!
So, assume I have a simple patch.cpp file which includes Dyninst API. 
How can I compile this file? why it is so complicated in your tool? why we need a huge dependencies? Can you offer to me a simple makefile or command line to comiple the target file? 

please in simple fashion
I have the patch.cpp file
How can I compile it?
What are the dependencies that should be used?
What are the environment variables that should be set and where the path of them?

Thanks

![g](https://user-images.githubusercontent.com/17450624/37412655-9b117a76-27ba-11e8-8031-41a0f830d979.jpg)

**Comment by 1Husin-Alhaj** [comment]
I tried -ldw 
but the error still appear!

![gg](https://user-images.githubusercontent.com/17450624/37413196-babd6348-27bb-11e8-9509-e4f11c82de2b.jpg)

**Comment by mxz297** [comment]
To your comments,

1. "really I do not know why it consumed about 4 hours":  You can speed up compilation by using the -j option, which will compile the project in parallel. For example, if your machine has 4 processors, you can use "make -j4" to compile it in parallel.

2. "README file says, in this folder, lib and include should be exsist?!! nothing here!!": I am not sure which version of Dyninst you are referring to. But in the README file I see from master, it says "Libraries will be installed into CMAKE_INSTALL_PREFIX/INSTALL_LIB_DIR, and headers will be installed into CMAKE_INSTALL_PREFIX/INSTALL_INCLUDE_DIR." So, what is your CMAKE_INSTALL_PREFIX? You configured cmake to set these variables. 

3.  From your command line "g++ patch.cpp -o patch -ldw", you are not including the the search path for the include files and libraries (I do not know where you installed Dyninst because you specified it in CMake). In addition, you are using the dyninstAPI component, so you will also need -ldyninstAPI.

**Comment by 1Husin-Alhaj** [comment]
Thank you very much Mr. mxz297
The version of Dyninst is Dyninst 9.3.2
During building Dyninst, an error occurred because of boost library. In order to overcome this error, I had been build Dyninst like this:
cmake  /path/to/dyninst/source   -D BOOST_ROOT=/path/to/boost 

I have not used CMAKE_INSTALL_PREFIX option in build process.!
Is it required?

**Comment by mxz297** [comment]
I see. If you did not specify CMAKE_INSTALL_PREFIX, it should be installed at default locations such as /usr/local

While it is not required, I would recommend that you use "ccmake", which is a gui interface for cmake and it gives a clear idea of what CMake variable are used and their default values. If you are using ubuntu, then "sudo apt-get install cmake-curses-gui" should install ccmake.

**Comment by 1Husin-Alhaj** [comment]
I re-built Dyninst according to the following command line:
Then from the Dyninst-master/example/codecoverage/
I got the makefile and readed it in order to test it on my example.
This makefile says:
" Make sure to set the DYNINST_ROOT environment variable to the directory where . Dyninst is installed. The directory should contain the include and $(PLATFORM)/lib directories"

The directory where I installed Dynins dos not contain both the include and  $(PLATFORM)/lib directories, never ever".

As a result there is no need to set the DYNINST_ROOT. 

I edited this make file just to compile my example (patch.cpp).
here is the makefile after modified:

```
#
# A GNU Makefile
#
# This Makefile builds the codeCoverage Dyninst mutator
#

# Make sure to set the DYNINST_ROOT environment variable to the directory where
# Dyninst is installed. The directory should contain the include and
# $(PLATFORM)/lib directories

# Or uncomment the following line and change the path accordingly
# DYNINST_ROOT = /change/me

 

DYNINST_INCLUDE =/usr/include
DYNINST_LIB =/usr/local/lib

# These should point to where libelf and libdwarf are installed
LOCAL_INC_DIR = /usr/include
LOCAL_LIBS_DIR = /usr/local/lib

LIBELF=/usr/local/lib
LIBDWARF=/usr/local/lib

CXX = g++
CXXFLAGS = -g -Wall
LIBFLAGS = -fpic -shared

CC = gcc
CFLAGS = -Wall -pedantic -g -std=gnu99

all: patch

patch: patch.o
	$(CXX) $(CXXFLAGS) -L$(DYNINST_LIB) \
		-L$(LIBELF) -L$(LIBDWARF) \
		-lcommon \
		-ldyninstAPI \
		-lpthread \
		-o patch patch.o

 

clean:
	rm -f patch

```


and here is the result:


![zxx](https://user-images.githubusercontent.com/17450624/37465449-627fdeda-2870-11e8-9e14-5a5e31926d65.jpg)

Thanks

**Comment by mxz297** [comment]
OK. Could you send me your patch.cpp? You can send it to me through email

**Comment by 1Husin-Alhaj** [comment]
I downloaded it from here:
[https://github.com/dyninst/dyninst/files/1143430/Dyninst-test-case.zip](url)

and I just try to compile patch.cpp correctly. 
I used Netbeans and manual compiling in terminal, but I filed.

**Comment by mxz297** [comment]
Try to add "-I/usr/local/include" in your compilation command? The patch.cpp itself is fine.

**Comment by 1Husin-Alhaj** [comment]
didn't work!!
I typed in terminal this command:
g++ patch.cpp -o patch -ldyninstAPI
I got the executable patch file correctly. 
then, I got another error:

![zxxc](https://user-images.githubusercontent.com/17450624/37467445-75af0378-2875-11e8-953c-4856ace573b5.jpg)

**Comment by mxz297** [comment]
Suggests from this post are helpful https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

**Comment by 1Husin-Alhaj** [comment]
I have set the environment variables as follow:
```
export LD_LIBRARY_PATH=/usr/local/lib
export DYNINSTAPI_RT_LIB=/usr/local/lib/
```

Also, I have gained some useful information from this
[http://www.paradyn.org/tracetool.html](url)
& from the link you offered.

I have read the Dyninst Programmer Guide (6/29/2016).
In our case, the mutator is the **patch** file, and the mutatee in the binary file on disk, i.e. **hello**. 
The function that we aim to inject (code_to_inject) it into hello file, in defined in lib.h and implemented in lib.cpp file. 
Therefore, we should generate shared library to be injected.

How can we do that? 
I have generated a shared library by adding some lines to makefile like below

`LIB     = -ldyninstAPI  -lparseAPI  -linstructionAPI -lsymtabAPI  -lsymLite  -ldynDwarf -ldynElf -lcommon -lpcontrol -ldwarf

CXXFLAG = -std=c++11 -Dos_linux -Darch_x86_64 -Darch_64bit -Dx86_64_unknown_linux2_4  -Dcap_ptrace -Dcap_stripped_binaries -Dcap_async_events -Dcap_threads -Dcap_dynamic_heap -Dcap_relocation -Dcap_dwarf -Dcap_32_64 -Dcap_liveness -Dcap_fixpoint_gen -Dcap_noaddr_gen -Dcap_mutatee_traps -Dcap_binary_rewriter -Dcap_registers -Dcap_instruction_api -Dcap_serialization -Dcap_instruction_replacement -Dcap_tramp_liveness -Dbug_syscall_changepc_rewind -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS

CA_DEP = patch.cpp

all: patch lib.so

lib.so:	lib.cpp
	g++ -shared $< -o lib.so

patch: patch.cpp /usr/local/lib/libdyninstAPI.so.9.3
	g++ -o $@ -L/usr/local/lib/ -I/usr/local/include/ -I/usr/local/include $(CXXFLAG) $< $(LIB)

clean:
	rm -f patch lib.so`

I executed it but I got this error:
![zxco](https://user-images.githubusercontent.com/17450624/37474614-046224aa-2886-11e8-9fb0-700bc2e78887.jpg)

**Comment by 1Husin-Alhaj** [comment]
Thanks for help dear mxz297
I have resolved the previous issue (shared library). But another error is occurred. I am afraid that these errors occurred due "not good" build and install Dyninst.
here is the error:

![v1](https://user-images.githubusercontent.com/17450624/37518532-c3e094f2-292a-11e8-9273-3c74e2057a05.jpg)


another problem is that, there are different type of **libdyninstAPI.so** file. In the sense that there are **libdyninstAPI.so,** **libdyninstAPI.so.9.3** and **libdyninstAPI.so.9.3.2**. which of them should be selected?

Thanks in advance

**Comment by mxz297** [comment]
I just ran this example with the current Dyninst master. It seems to be working fine. We are approaching a major release, and we have added many bug fixes since 9.3.2. It would be better for you to temporarily work with the Dyninst master. 

To your another question, all these libdyninstAPI.so are pointing to the same file. Many of them are symbol links so that you can easily switch to different versions of Dyninst

**Comment by 1Husin-Alhaj** [comment]
Hello Mr.Meng

I have installed Dyninst-master and after 3 days I couldn't solve the
following problem




I just need to insert a code taken from a loaded library (I think you have
tested this code without any errors).
Can you help me to solve this error? the reason of this error what is?

Thanks

**Comment by mxz297** [comment]
I guess your post includes an image that shows the problem, but I cannot see that image.

**Comment by 1Husin-Alhaj** [comment]
Sorry,
