### ISSUE TITLE
Heuristics to determined prologues

### ISSUE THREAD

**Issue by junxzm1990** [dyninst/dyninst#454]
I am trying to reason how DynInst find functions in raw data such as gap between normal functions. One thing I saw is the attempt on finding prologues. I am wondering what and where are the heuristics for prologue identification in the source code.

**Comment by mxz297** [comment]
For identifying function entry points, the corresponding source files are parseAPI/src/IdiomModelDesc.C, which contains the description of a pre-trained machine learning model, and parseAPI/src/ProbabilisticParser.C, which contains the code to use the model to find entry points.
