### ISSUE TITLE
InsertSnippet does not check if "when" parameter is legal

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#455]
Currently when attempting to insert a snippet at an illegal location (such as inserting a snippet after a jump expression), insertsnippet will return a non-null value and attempt to insert the snippet at insertion set completion. The result is a crash in relocation since you obviously cannot do something after a jump instruction in the same basic block. 

InsertSnippet should return a NULL value when an illegal "when" condition is detected and not include the snippet in the insertion set.

**Comment by sashanicolas** [comment]
Closing cause commit a58103f fixed it.
