### ISSUE TITLE
how to print the instruction which contains “cmp”

### ISSUE THREAD

**Issue by zzzssseee** [dyninst/dyninst#465]
Hi，
I‘m trying to instrument the binary and want to get the operand of the instruction which contains “cmp”. But I was stuck in the first step to print the instruction which contains "cmp". The code contains an error "undefined reference to symbol '_ZNK7Dyninst14InstructionAPI9Operation6formatB5cxx11Ev". Here is the key code.
```
    BPatch_basicBlock *cmpblock = *iter;
    std::vector<Dyninst::InstructionAPI::Instruction::Ptr> insns;
    cmpblock->getInstructions(insns);
    for (auto insn_iter = insns.begin(); insn_iter!=insns.end(); ++insn_iter){
      InstructionAPI::Instruction::Ptr insn = *insn_iter;
      InstructionAPI::Operation op = insn->getOperation();
      if (op.format().find("cmp"))
        cout << "test cmp output:" << op.format() << endl;
    }
```
I am a newbie to dyninst, maybe it's a stupid question but I really appreciate if anyone can give me some help. Thanks a lot!

**Comment by mxz297** [comment]
A few possible reasons:
1. Did you link instructionAPI by passing -linstructionAPI and specify the correct path to instructionAPI.so?
2. It also seems like that you code wants a cxx11 abi version of Dyninst (the suffix cxx11EV of the symbol name indicates this). It is possible that you compiled Dyninst without the cxx11 abi. So, you can try to add "-D_GLIBCXX_USE_CXX11_ABI=0" (or set it to 1 if 0 does not work) to your compilation flag to recompile your code.
3. You may have multiple & incompatible installations of Dyninst.

**Comment by zzzssseee** [comment]
Oh, thank you so much!
