### ISSUE TITLE
Segmentation Fault after inserting call and instrumenting blocks.

### ISSUE THREAD

**Issue by javiertejedorm** [dyninst/dyninst#471]
Hello,

I am using this script to instrument a binary to make it working with AFL-Fuzzer.
https://github.com/vanhauser-thc/afl-dyninst/blob/master/afl-dyninst.cpp

I am able to run it successfully with small programs, but I am trying to instrument a big application and I am having several errors.

After instrumenting the binary, it triggers a segmentation fault when running it

For example, if I add a function call to a library (using afl-dyninst.cpp) there is a segmentation fault here:
0x00460d04 in fileno@plt ()
```
=> 0x460d04 <fileno@plt>:     jmp    DWORD PTR [ebx+0xc]
 | 0x460d0a <fileno@plt+6>:   push   0x0
 | 0x460d0f <fileno@plt+11>:  jmp    0x460cf4
 | 0x460d14 <fputs@plt>:      jmp    DWORD PTR [ebx+0x10]
 | 0x460d1a <fputs@plt+6>:    push   0x8
```
```
gdb$ x/xw $ebx+0xc
0x8a6000: 0xb80f9510
gdb$ x/xi 0xb80f9510
0xb80f9510:  Cannot access memory at address 0xb80f9510
```
`Invalid $PC address: 0xb80f9510`

Could be the PLT table corrupted?

I am having other problems, depending of if I add more instrumentation or less. For example:

```
jmp 0xb8200510

#0  0xb8200510 in ?? ()
#1  0x005fad8c in targ1f9c50 ()
#2  0x005fc0ab in targ1fb050 ()
#3  0x005eddc0 in targ1ecc70 ()
#4  0x005ef119 in targ1ee050 ()
#5  0x005d6192 in targ1d5000 ()

Invalid $PC address: 0xb8200510
```
It seems that dyninst has added an invalid jump.

I am using 9.3.2 version of dyninst. 

Thank you,
Javier.

**Comment by javiertejedorm** [comment]
Could be all errors related to some corruption in the relocation tables? Have a look at the next error:

**Trying to write in .bss section**

Assembly
`=> mov    DWORD PTR ds:0x580770,edx`

Memory Section of 0x560770
`[26]     From 0x4d26e0 to 0x59565c: .bss ALLOC`

**Comment by javiertejedorm** [comment]
Analysing more the error I see that when the dynamic linker is resolving the addresses of PLT table is setting incorrect addresses which point (some of them) to a non mapped memory zones.

Is there any known bug in .dynamic segment?

**Comment by mxz297** [comment]
Hi, I am sorry for the late response. There are some fixes related to .dynamic section about the alignment and some other issues. But I don't recall any issues about pointing to a non-mapped memory location.

@sashanicolas: in your previous fixes to the .dynamic section, are there any fixes related?

**Comment by javiertejedorm** [comment]
Thank you for the response.

I debugged yesterday the part where the PLT addresses table are resolved (GLibc _dl_relocate_object()_). 
I managed to create a correct dyninst application and it resolves the addresses in this way (in short):

1st: Sets the relative value of the address to the plt table.
2nd: Adds the base address of the binary to that value.

But when I add a function call with dyninst to that binary it performs the next steps:

1st: Sets the relative value of the address to the plt table
**2nd: Overwrites that value in the plt with a valid address which belongs to ld-linux.so library. (0xb7e00510)**
3rd: Adds the base address of the binary to that value setting a Non-mapped address.

I think 2nd step is wrong and it shouldn't be done, but I don't know why is doing it. Also it happens only in few addresses but not all of them.

**Comment by mxz297** [comment]
Are you working with 32-bit binaries? If it is the case, I am guessing that there is a wrong value in ebx, which causes the crashes. Can you confirm this?

**Comment by javiertejedorm** [comment]
Yes, I am working with 32-bit binaries in Ubuntu 16.04 32-bits.

**Comment by mxz297** [comment]
OK. On 32-bit platforms, there is no pc-relative addressing mode. So, to do any pc-relative operation, the code will first make a call to a special thunk function, which will move the return address into ebx, which is also the pc of the call instruction. 

When Dyninst instruments code, dyninst will relocate the function to a different address. So, the value in ebx will change. Dyninst is supposed to take care of this, but there could be some bugs. And that's why it would be nice to see if there is a wrong value in ebx

**Comment by javiertejedorm** [comment]
I have checked the ebx issue but I don't see anything related to it. I am convinced that there is something wrong when resolving the plt table.
I have compiled one small library from the project that I am having the issues. Again, when calling to the functions from the plt it jumps to non-mapped addresses.
I set a breakpoint in main(), I have fixed two addresses manually with gdb and it run perfectly.

These are the steps that it is taking to resolve the plt of malloc():

**1) It resolves the malloc address correctly and sets it in the plt (at address 0xb7fe6971)**

```
EAX: 0xb7e52f9c --> 0xb7e4bd90 (push   ebp)
EBX: 0xb7f573a0 --> 0x1d 
ECX: 0x2 
EDX: 0xb7e4b420
ESI: 0x7 
EDI: 0xb7e4bd90
EBP: 0xbffff578
ESP: 0xbffff4c0
EIP: 0xb7fe6973 (<_dl_relocate_object+2259>:    jmp    0xb7fe6930 <_dl_relocate_object+2192>)
[-------------------------------------code-------------------------------------]
   0xb7fe6968 <_dl_relocate_object+2248>:       mov    eax,DWORD PTR [ebp-0x64]
   0xb7fe696b <_dl_relocate_object+2251>:       mov    edi,DWORD PTR [ebp-0x88]
   0xb7fe6971 <_dl_relocate_object+2257>:       mov    DWORD PTR [eax],edi
=> 0xb7fe6973 <_dl_relocate_object+2259>:       jmp    0xb7fe6930 <_dl_relocate_object+2192>
 | 0xb7fe6975 <_dl_relocate_object+2261>:       mov    DWORD PTR [ebp-0x88],0x0

gdb-peda$ x/5xi $edi
   (malloc) 0xb7e4bd90:  push   ebp
   (malloc) 0xb7e4bd91:  push   edi
   (malloc) 0xb7e4bd92:  push   esi
   (malloc) 0xb7e4bd93:  push   ebx
   (malloc) 0xb7e4bd94:  call   0xb7e4ba50
```

**2) Next it adds another value (at address 0xb7fe6249) to the correct malloc address setting a Non-Mapped (invalid in this case) address:**

```
EAX: 0x0 
EBX: 0xb7f5796c --> 0x2f9c 
ECX: 0x2 
EDX: 0x7 
ESI: 0xb7e52f9c --> 0x6fc9bd90 
EDI: 0xb7e50000 (jg     0xb7e50047)
EBP: 0xbffff578 --> 0xbffff638 --> 0x2c (',')
ESP: 0xbffff4c0 --> 0xb7fff000 --> 0x23f3c 
EIP: 0xb7fe624b (<_dl_relocate_object+427>:     add    ebx,0x8)
[-------------------------------------code-------------------------------------]
   0xb7fe6241 <_dl_relocate_object+417>:        test   eax,eax
   0xb7fe6243 <_dl_relocate_object+419>:        jne    0xb7fe6620 <_dl_relocate_object+1408>
   0xb7fe6249 <_dl_relocate_object+425>:        add    DWORD PTR [esi],edi
=> 0xb7fe624b <_dl_relocate_object+427>:        add    ebx,0x8

gdb-peda$ x/10xi $esi
   0xb7e52f9c:  nop
   0xb7e52f9d:  mov    ebp,0x5f006fc9
   0xb7e52fa2:  (bad)  
   0xb7e52fa3:  mov    bh,0x0
   0xb7e52fa5:  push   ecx
   0xb7e52fa6:  sti    
   0xb7e52fa7:  mov    bh,0xce
   0xb7e52fa9:  pop    ss
   0xb7e52faa:  add    BYTE PTR [eax],al
   0xb7e52fac:  ficom  WORD PTR [edi]
```

**3) Calling malloc it jumps to that Non-Mapped address (at address)**

```
EAX: 0xbffeecbc
EBX: 0xb7e52f90
ECX: 0xbffeecbc
EDX: 0xb7e52fd4
ESI: 0xbffeecbc
EDI: 0xbfff2d78
EBP: 0xbffeec58
ESP: 0xbffeec2c
EIP: 0xb7e517a8 (<malloc@plt>:  jmp    DWORD PTR [ebx+0x10])
[-------------------------------------code-------------------------------------]
   0xb7e51798 <dlsym@plt>:      jmp    DWORD PTR [ebx+0xc]
   0xb7e5179e <dlsym@plt+6>:    push   0x0
   0xb7e517a3 <dlsym@plt+11>:   jmp    0xb7e51788
=> 0xb7e517a8 <malloc@plt>:     jmp    DWORD PTR [ebx+0x10]
 | 0xb7e517ae <malloc@plt+6>:   push   0x8
 | 0xb7e517b3 <malloc@plt+11>:  jmp    0xb7e51788
 | 0xb7e517b8 <pthread_mutex_init@plt>: jmp    DWORD PTR [ebx+0x14]
 | 0xb7e517be <pthread_mutex_init@plt+6>:       push   0x10
 |->   Cannot evaluate jump destination

gdb-peda$ x/xw 0xb7e52f90+0x10
	0xb7e52fa0:     0x6fb55f00

gdb-peda$ x/10xi 0x6fb55f00
   0x6fb55f00:  Cannot access memory at address 0x6fb55f00
```

As you can see, something is wrong at the plt resolution.

**Comment by javiertejedorm** [comment]
And this happens when I load a library into the binary:

`appBin->loadLibrary(instLibrary)`

If I skip the load, it runs perfectly.

**Comment by sashanicolas** [comment]
@mxz297 I checked the fixed I did, and it's not related to .bss or .dynamic

**Comment by aalmamuncse** [comment]
Hi, I am trying to compile the example codes given in dyninstAPI.pdf (for dyninst version 10.1), on Appendix section. First example (instrumenting a function, example 1.1, page 67), I get segmentation fault error when I compile the example. I am trying to instrument a very simple hello.cc file with a hello function. Could you please point any direction to get rid of this error?
