### ISSUE TITLE
Spack Build Fails with missing dependency on libiberty

### ISSUE THREAD

**Issue by schulzm** [dyninst/dyninst#473]
Trying to build dyninst with Spack, which fails with the error line:
No rule to make target 'libiberty/libiberty.a', needed by 'common/libcommon.so.9.3.2'.

System:
Linux i10se5 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Complete Spack build log:
==> Staging archive: /u/home/schulzm/software/spack/var/spack/stage/dyninst-9.3.2-7x6kw2ktas2thyivzs5gnmgsej2dlm5g/dyninst-9.3.2.tar.gz
==> Created stage in /u/home/schulzm/software/spack/var/spack/stage/dyninst-9.3.2-7x6kw2ktas2thyivzs5gnmgsej2dlm5g
==> No patches needed for dyninst
==> Building dyninst [Package]
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

3 errors found in build log:
     748     -1
     749     checking for vfork.h... no
     750     checking for fork... [ 11%] Building CXX object common/CMakeFiles/common.dir/src/addrtra
             nslate-auxv.C.o
     751     yes
     752     cd /tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-build/common && /u/home/sch
             ulzm/software/spack/lib/spack/env/gcc/g++  -DBOOST_ALL_NO_LIB=1 -DBOOST_MULTI_INDEX_DISA
             BLE_SERIALIZATION -DCOMMON_LIB -DUSE_PARSE_API -DWITHOUT_SYMLITE -DWITH_SYMTAB_API -Darc
             h_64bit -Darch_x86_64 -Dbug_force_terminate_failure -Dbug_syscall_changepc_rewind -Dcap_
             32_64 -Dcap_async_events -Dcap_binary_rewriter -Dcap_dwarf -Dcap_dynamic_heap -Dcap_fixp
             oint_gen -Dcap_liveness -Dcap_mutatee_traps -Dcap_noaddr_gen -Dcap_ptrace -Dcap_register
             s -Dcap_stack_mods -Dcap_stripped_binaries -Dcap_thread_db -Dcap_threads -Dcap_tramp_liv
             eness -Dcommon_EXPORTS -Dos_linux -Dx86_64_unknown_linux2_4 -I/u/home/schulzm/software/s
             pack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/elfutils-0.170-vslqrelqlkhmbwpozuons5o
             2hv57gb32/include/libelf -I/u/home/schulzm/software/spack/opt/spack/linux-ubuntu16.04-x8
             6_64/gcc-5.5.0/libdwarf-20180129-k5z6dden3glufefqjzhxqk6kvprqpwdd/include -I/u/home/schu
             lzm/software/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/boost-1.66.0-rk6dd2u2xnq
             oanpkij2dwctk2ashbjcp/include -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spac
             k-build -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-build/common/h -I/tm
             p/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/common/h -I/tmp/schulzm/spack-stage/spa
             ck-stage-sQL6Mj/dyninst/dataflowAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyni
             nst/dyninstAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/instructionAPI/h 
             -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/parseAPI/h -I/tmp/schulzm/spack-st
             age/spack-stage-sQL6Mj/dyninst/patchAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/
             dyninst/proccontrol/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/stackwalk/h 
             -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/symtabAPI/h -I/tmp/schulzm/spack-s
             tage/spack-stage-sQL6Mj/dyninst/dwarf/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dy
             ninst/elf/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/symlite/h -I/tmp/schul
             zm/spack-stage/spack-stage-sQL6Mj/dyninst -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/
             dyninst/external -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/common/src  -std=
             c++11  -fvisibility=hidden -fvisibility-inlines-hidden -W -Wall -Wpointer-arith -Wcast-q
             ual -Woverloaded-virtual -Wcast-align -Wno-non-template-friend -Wno-unused-local-typedef
             s -Wno-deprecated-declarations -O2 -g  -fPIC   -Winvalid-pch -include /tmp/schulzm/spack
             -stage/spack-stage-sQL6Mj/dyninst/spack-build/common/cotire/common_CXX_prefix.hxx -o CMa
             keFiles/common.dir/src/addrtranslate-auxv.C.o -c /tmp/schulzm/spack-stage/spack-stage-sQ
             L6Mj/dyninst/common/src/addrtranslate-auxv.C
     753     checking for vfork... yes
  >> 754     checking for working fork... make[2]: *** No rule to make target 'libiberty/libiberty.a'
             , needed by 'common/libcommon.so.9.3.2'.  Stop.
     755     make[2]: *** Waiting for unfinished jobs....
     756     [ 11%] Building CXX object common/CMakeFiles/common.dir/src/addrtranslate-linux.C.o
     757     cd /tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-build/common && /u/home/sch
             ulzm/software/spack/lib/spack/env/gcc/g++  -DBOOST_ALL_NO_LIB=1 -DBOOST_MULTI_INDEX_DISA
             BLE_SERIALIZATION -DCOMMON_LIB -DUSE_PARSE_API -DWITHOUT_SYMLITE -DWITH_SYMTAB_API -Darc
             h_64bit -Darch_x86_64 -Dbug_force_terminate_failure -Dbug_syscall_changepc_rewind -Dcap_
             32_64 -Dcap_async_events -Dcap_binary_rewriter -Dcap_dwarf -Dcap_dynamic_heap -Dcap_fixp
             oint_gen -Dcap_liveness -Dcap_mutatee_traps -Dcap_noaddr_gen -Dcap_ptrace -Dcap_register
             s -Dcap_stack_mods -Dcap_stripped_binaries -Dcap_thread_db -Dcap_threads -Dcap_tramp_liv
             eness -Dcommon_EXPORTS -Dos_linux -Dx86_64_unknown_linux2_4 -I/u/home/schulzm/software/s
             pack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/elfutils-0.170-vslqrelqlkhmbwpozuons5o
             2hv57gb32/include/libelf -I/u/home/schulzm/software/spack/opt/spack/linux-ubuntu16.04-x8
             6_64/gcc-5.5.0/libdwarf-20180129-k5z6dden3glufefqjzhxqk6kvprqpwdd/include -I/u/home/schu
             lzm/software/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/boost-1.66.0-rk6dd2u2xnq
             oanpkij2dwctk2ashbjcp/include -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spac
             k-build -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-build/common/h -I/tm
             p/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/common/h -I/tmp/schulzm/spack-stage/spa
             ck-stage-sQL6Mj/dyninst/dataflowAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyni
             nst/dyninstAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/instructionAPI/h 
             -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/parseAPI/h -I/tmp/schulzm/spack-st
             age/spack-stage-sQL6Mj/dyninst/patchAPI/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/
             dyninst/proccontrol/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/stackwalk/h 
             -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/symtabAPI/h -I/tmp/schulzm/spack-s
             tage/spack-stage-sQL6Mj/dyninst/dwarf/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dy
             ninst/elf/h -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/symlite/h -I/tmp/schul
             zm/spack-stage/spack-stage-sQL6Mj/dyninst -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/
             dyninst/external -I/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/common/src  -std=
             c++11  -fvisibility=hidden -fvisibility-inlines-hidden -W -Wall -Wpointer-arith -Wcast-q
             ual -Woverloaded-virtual -Wcast-align -Wno-non-template-friend -Wno-unused-local-typedef
             s -Wno-deprecated-declarations -O2 -g  -fPIC   -Winvalid-pch -include /tmp/schulzm/spack
             -stage/spack-stage-sQL6Mj/dyninst/spack-build/common/cotire/common_CXX_prefix.hxx -o CMa
             keFiles/common.dir/src/addrtranslate-linux.C.o -c /tmp/schulzm/spack-stage/spack-stage-s
             QL6Mj/dyninst/common/src/addrtranslate-linux.C
     758     yes
     759     checking for working vfork... (cached) yes
     760     checking for _doprnt... no

     ...

     1106    /u/home/schulzm/software/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/cmake-3.11.4
             -f7akh3i2fycsmnymohi5l4vwoavtsxey/bin/cmake -E touch /tmp/schulzm/spack-stage/spack-stag
             e-sQL6Mj/dyninst/spack-build/CMakeFiles/LibIberty-complete
     1107    /u/home/schulzm/software/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/cmake-3.11.4
             -f7akh3i2fycsmnymohi5l4vwoavtsxey/bin/cmake -E touch /tmp/schulzm/spack-stage/spack-stag
             e-sQL6Mj/dyninst/spack-build/binutils/src/LibIberty-stamp/LibIberty-done
     1108    make[2]: Leaving directory '/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-bu
             ild'
     1109    [ 12%] Built target LibIberty
     1110    make[2]: Leaving directory '/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-bu
             ild'
     1111    CMakeFiles/Makefile2:336: recipe for target 'common/CMakeFiles/common.dir/all' failed
  >> 1112    make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
     1113    make[1]: Leaving directory '/tmp/schulzm/spack-stage/spack-stage-sQL6Mj/dyninst/spack-bu
             ild'
     1114    Makefile:132: recipe for target 'all' failed
  >> 1115    make: *** [all] Error 2

**Comment by bwelton** [comment]
What version of Spack are you using? About 2-3 weeks ago, the guys over at OpenSpeedShop pushed up an update to the dyninst spack package. This may not solve your issue, but if you haven't updated in a while you should give it a try.

**Comment by mxz297** [comment]
@sashanicolas: I remember that you have already fixed this issue. If it is the case, please go ahead and close this issue. Otherwise, please comment the status of this issue.

**Comment by sashanicolas** [comment]
As soon as my PR is accepted in the Spack repository, I will close this issue.

**Comment by sashanicolas** [comment]
Now fixed and merged with https://github.com/spack/spack/pull/8806
