### ISSUE TITLE
PCWidget::PCtoReturnAddr sets LR unnecessarily on non-x86 architectures

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#474]
PCWidget::PCtoReturnAddr will emit instructions (including creating a stack frame) to set the value of LR even in cases in which link register does not need to be set (i.e. a non-returning branch). This effects Power (and likely ARM). 

On POWER, the result is a smashed LR value on non-returning branches. This may have a similar result on ARM. @sashanicolas you may want to test this on ARM by creating a small test number of "B" (branch's without setting LR's) in a row. Similar to the following:

int test1(){
/// asm with 3 branch w/o link instructions
}

int main() {
  test1();
}

The solution to this problem may be to add function to insn (or insncodegen) to check if the instruction requires the link register to be set.

**Comment by sashanicolas** [comment]
@bwelton are you talking about this call: https://github.com/dyninst/dyninst/blob/70f036ce3e07a8566c6f7325dbcdd24bf290ff06/dyninstAPI/src/Relocation/Widgets/PCWidget.C#L119

It is not implemented yet for ARM.
