### ISSUE TITLE
Segmentation fault after instrument BasicBlocks

### ISSUE THREAD

**Issue by lcytxw** [dyninst/dyninst#476]
When I use the example binary 'codeCoverage' to instrument mutatees such as nasm and dwarfdump with '-b' options,  I got Segmentation fault after execute such instrumented binary. 

$ ./nasm-cov id0  
Segmentation fault
But under normal circumstances, It doesn't contain any output:
$ ./nasm id0  
$

**Comment by mxz297** [comment]
Hi, Dyninst 10.0 is released. If you still see the same problem with Dyninst 10.0, please let me know and I will fix it. Thanks!

**Comment by mxz297** [comment]
Closed due to inactivity.
