### ISSUE TITLE
SymtabAPI dumps core when reading an exception table for a KNL (provided) binary

### ISSUE THREAD

**Issue by jmellorcrummey** [dyninst/dyninst#477]
The binary: https://rice.box.com/s/0dik9l6lyngooiwms4inq2ekj38itjb0

 Symtab::openFile fails to open the binary available at the link above. The symptom:

open: /home/johnmc/pkgs-src/dyninst/symtabAPI/src/Object-elf.C:3552: int read_except_table_gcc3(const unsigned char*, mach_relative_info&, Dyninst::Elf_X_Shdr*, Dyninst::Elf_X_Shdr*, std::vector<Dyninst::SymtabAPI::ExceptionBlock>&): Assertion `low_pc_val==pc_begin_val' failed.
Aborted (core dumped)

I don't know anything about reading FDEs. Since @sashanicolas authored this code, he would probably have the easiest time understanding how to address this error.

The binary was compiled with the Intel compiler (probably version 2018) by an HPCToolkit user at ANL. This problem causes HPCToolkit's hpcfnbounds to fail.

This problem occurs with Dyninst master. It doesn't occur for Dyninst 9.3.2.

**Comment by sashanicolas** [comment]
@jmellorcrummey  I know about this bug, but haven't fixed it yet, need to debug more the FDEs. This happens also with lulesh2.0.

**Comment by jgalarowicz** [comment]
@sashanicolas Hi Sasha - is the lulesh2.0 issue, the one I sent in?

**Comment by sashanicolas** [comment]
@jgalarowicz This issue has been fixed.
