### ISSUE TITLE
Handling Relocation of Power 8 Function Preamble 

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#479]
There are three issues that must be addressed to properly handle function preambles on Power 8 for relocation:

1. Detect the presence of the preamble in a function.
    - Check for the two instructions that compose the preamble. An example can be found here: https://github.com/bwelton/dyninst/blob/f3f7f83a554b3dcaf39c2b8ab09d7a8f716b16ca/dyninstAPI/src/addressSpace.C#L1708

2. Prevent the relocation of the preamble. 
    - Add a _powerPreamble flag to dyninstAPI block.C.
    - In addressapace.C, iterate over all functions selected to relocation to determine which has the preamble. If the function has a preamble, set the _powerPreamble flag of first block in that function to true.
    - In RelocBlock.C, when creating reloc blocks. If the block contains a preamble, generate the relocation block at +0x8 and exclude those two instructions from being inserted into the relocaiton block ( see here: https://github.com/bwelton/dyninst/blob/f3f7f83a554b3dcaf39c2b8ab09d7a8f716b16ca/dyninstAPI/src/Relocation/CFG/RelocBlock.C#L71 )
    
3. Prevent the insertion of instrumentation in both the power preamble BPatch_Function and non-preamble version of bpatch_function (you can instrument one or the other, not both). 
     - I currently do this by creating a map<entryBlockAddr, bpatch_function> (which is sorted on key) then iterating over the map to see if an address at +0x8 exists in the map. If it does, I discard instrumentation to this (the preambled) function. This is employed when finding overlapping functions (tr and makes the assumption that the user isn't instrumenting both functions (see here: https://github.com/bwelton/dyninst/blob/f3f7f83a554b3dcaf39c2b8ab09d7a8f716b16ca/dyninstAPI/src/addressSpace.C#L1752 ).

**Comment by mxz297** [comment]
Closed by #485
