### ISSUE TITLE
ERROR: failed bind/eval

### ISSUE THREAD

**Issue by cuviper** [dyninst/dyninst#48]
I'm seeing a lot of these errors:

```
$ ./runTests -test test1_1
ERROR: failed bind/eval at 7fcabd8b19ed
ERROR: failed bind/eval at 7fcabd8b1b6f
ERROR: failed bind/eval at 7fcabd8b1b80
ERROR: failed bind/eval at 407038
TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
test1_1                    g++    none 64  create   NA      dynamic nonPIC  PASSED
ERROR: failed bind/eval at 407038
test1_1                    g++    none 64  rewriter NA      dynamic nonPIC  PASSED
```

FWIW, the two places this error is printed in `Movement-adhoc.C` are not new.

Using master (4b3163b2 + #46 + #47) on Fedora 23 x86_64.

**Comment by wrwilliams** [comment]
This crept in as I cleaned out the ppc32/ppc64 mess; it appears there must be something rotten on x86 as well. It should just be something using x86 when it should be using x86_64; I'll try to track it down.
