### ISSUE TITLE
Power support for code generation of long branch calls  (i.e.  branch with link to SPR)

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#481]
Long branch call support is non-functional in dyninst where if a long branch is needed to replace a call an attempt is made to use a trap (which is unsupported for calls on Power). 

The solution I have devised for this uses a new Power 8 SPR called TAR (target address register) to create scratch register space to construct the jump address. The fix in question can be viewed here: https://github.com/bwelton/dyninst/blob/f3f7f83a554b3dcaf39c2b8ab09d7a8f716b16ca/dyninstAPI/src/codegen-power.C#L488 

However the TAR register role is uncertain in that compilers do not emit it currently and it is marked for tool use only (and may be limited by the OS kernel for use by privileged applications). However in practice it appears to be generally available on linux platforms.

**Comment by mxz297** [comment]
Closed by #485
