### ISSUE TITLE
Missing Vector Instructions and Reused Opcodes in Power 8

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#483]
The new category of vector instructions have been added to Power that are currently not detected by dyninst (decoded as invalid instructions). 

Some of these instructions however reuse opcodes of existing instructions that were deprecated sometime between Power 2 and Power 8. This list is the most pressing since it will break relocation when these instructions are encountered (if they are instrumented at least). The reused opcode appear in section A.32.2 of the Power 8 ISA on pg 1355, see http://pages.cs.wisc.edu/~welton/Power8ISA_subsection.pdf for the specific page with the instructions in question.

**Comment by bwelton** [comment]
Expect a patch to this issue in the next two or so weeks. We currently have someone working on adding the new power 8/9 vector instructions (and removing the deprecated older instructions).

**Comment by mxz297** [comment]
Fixed by #498
