### ISSUE TITLE
Power 8 Instrimentation stack frame generation destroys vector register values

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#484]
The save/restore of FPR in stack generation when inserting instrumentation results in the vector register overlapping the FPR to be wiped. i.e. FPR0 (8 byte size) overlaps VSX0 (16 byte size) on the first 8 bytes. A restore of FPR0 will result in the bottom non-overlapping 8 bytes of VSX0 to be reset to 0. 

The only way I have discovered to save the FPRs without this side effect is to save the vector register itself. An example of which can be seen in saveVectors/restoreVectors located here: https://github.com/bwelton/dyninst/blob/f3f7f83a554b3dcaf39c2b8ab09d7a8f716b16ca/dyninstAPI/src/codegen-power.C#L346 (note: there are 128 vector registers, only the first 32 are needed to be saved to prevent the overlap issue above from occurring).

**Comment by mxz297** [comment]
Closed by #485
