### ISSUE TITLE
[ARM Decoding] Abort using cfg_to_dot

### ISSUE THREAD

**Issue by valour01** [dyninst/dyninst#492]
I am using Dyninst to do binary analysis in ARM architecture

I download and compile the latest version of Dyninst and use the cfg_to_dot inside the examples to analysis one ARM binary(400.perbench, which is a binary in SPEC CPU2006).

However, I come across the following crash message
```
cfg_to_dot: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Dyninst::InstructionAPI::InstructionDecoderImpl; typename boost::detail::sp_member_access<T>::type = Dyninst::InstructionAPI::InstructionDecoderImpl*]: Assertion `px != 0' failed.
Aborted
```

Is it because that dyninst doesn't have a very good support on ARM at this moment? I would like to use the dyninst to help me to extract the cfg, cg, function boundary and disassemble the instructions. Does it support ARM well? Many Thanks

**Comment by valour01** [comment]
I would like to use dyninst to analysis ARM binaries. I use the latest version by `git clone https://github.com/dyninst/dyninst.git`
I need to extract the control flow graph, call graph, function start address and the instruction boundary.
Using the `cfg_to_dot` is just the first try to get the control flow graph. I only get the below exception

```
jmh@jmh-SYS:~/Downloads/dyninst/build/examples$ ./cfg_to_dot ~/C/400.perlbench.O0
cfg_to_dot: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Dyninst::InstructionAPI::InstructionDecoderImpl; typename boost::detail::sp_member_access<T>::type = Dyninst::InstructionAPI::InstructionDecoderImpl*]: Assertion `px != 0' failed.
Aborted
```
Feel free if you need more information. Thank you very much for your help.

**Comment by sashanicolas** [comment]
ARM is still being developed. You should `git checkout` the branch `arm64/feature/relocation` to get to the latest implementation of ARMv8.
To get the complete backtrace you should run with gdb.
