### ISSUE TITLE
'repfunc' error

### ISSUE THREAD

**Issue by geanoeban** [dyninst/dyninst#499]
Testing with dyninst often results in the following error:

mutator: /home/.../dyninst-9.3.2/dyninstAPI/src/binaryEdit.C:979: bool BinaryEdit::replaceTrapHandler(): Assertion `repfunc' failed.
Aborted (core dumped)

How can we solve it?

**Comment by mxz297** [comment]
Hi, Sorry for the late response. Can you try with Dyninst 10.0.0 and see if the same problem exists?

**Comment by geanoeban** [comment]
Thank you. Currently, no errors occur and it works very well. Thank you very much!!!
