### ISSUE TITLE
Slicing does not correctly apply ABI

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#5]
Currently, the ABI is used to kill registers whenever a call instruction is reached, regardless of whether users want to perform inter-procedural slicing or not.

The correct behavior is to apply ABI along with CALL_FT edges. If the user wants to perform inter-procedural slicing, the slicer should not follow CALL_FT edges.

**Comment by wrwilliams** [comment]
Did this ever get fixed?

**Comment by mxz297** [comment]
I don't think so... I should have time to work with this issue this Friday.
