### ISSUE TITLE
function return value destroyed when instrumented function access the input parameters at return statement only

### ISSUE THREAD

**Issue by vysocky** [dyninst/dyninst#501]
I have inserted printf functions at the selected functions BPatch_locEntry and stored a new binary. 
If the instrumented function contains just a return statement, the function return value get lost.

Example instrumented function works fine only when compiled with -DDEBUG:
```
int funcC(int a, int b)
{
	#ifdef DEBUG
	std::cout << "C: " << a  << std::endl;
	#endif
	return a+b;
}
```

Instrumentation:
```
std::vector<BPatch_point *> *points;
points = curFunc->findPoint(BPatch_locEntry);
if (!points || points->size() == 0)
{
	std::cerr << "No entry points for " << funcName << std::endl;
}

std::vector<BPatch_snippet*> printfArgs;
BPatch_snippet* fmt1 = new BPatch_constExpr("func %s\n");
BPatch_snippet* fmt2 = new BPatch_constExpr(funcName);
printfArgs.push_back(fmt1);
printfArgs.push_back(fmt2);

std::vector<BPatch_function*> printfFuncs;
appImage->findFunction("printf", printfFuncs);
if (printfFuncs.size() == 0)
{
	std::cerr<< "Could not find printf\n";
}
else
{
	BPatch_funcCallExpr printfCall(*(printfFuncs[0]), printfArgs);
	if (!appBin->insertSnippet(printfCall, *points))
	{
		std::cerr << "insertSnippet "<< funcName <<" failed\n";
	}
}

...
	
// Output the instrumented binary
if (!appBin->writeFile ("newTest"))
{
	std::cerr << "Failed to write output binary\n";
	return EXIT_FAILURE;
}
```

Linux Dyninst-9.3.2

**Comment by vysocky** [comment]
This error happens also with Dyninst-10.0.0. I have prepared [basic Dyninst tool and minimum test case](https://github.com/vysocky/testcases) so you can debug it.

I have disassembled the binaries to see the difference in the funcC:

# No instrumentation
```
0000000000400526 <_Z5funcCii>:
  400526:	55                   	push   %rbp
  400527:	48 89 e5             	mov    %rsp,%rbp
  40052a:	89 7d fc             	mov    %edi,-0x4(%rbp)
  40052d:	89 75 f8             	mov    %esi,-0x8(%rbp)
  400530:	8b 55 fc             	mov    -0x4(%rbp),%edx
  400533:	8b 45 f8             	mov    -0x8(%rbp),%eax
  400536:	01 d0                	add    %edx,%eax
  400538:	5d                   	pop    %rbp
  400539:	c3                   	retq   
```
# Instrumented (cause error)
```
0000000000400526 <_Z5funcCii>:
  400526:	e9 ef 02 30 00       	jmpq   70081a <funcC_dyninst>
  40052b:	7d fc                	jge    400529 <_Z5funcCii+0x3>
  40052d:	89 75 f8             	mov    %esi,-0x8(%rbp)
  400530:	8b 55 fc             	mov    -0x4(%rbp),%edx
  400533:	8b 45 f8             	mov    -0x8(%rbp),%eax
  400536:	01 d0                	add    %edx,%eax
  400538:	5d                   	pop    %rbp
  400539:	c3                   	retq 
```

# -DDEBUG, No instrumentation
```
0000000000400526 <_Z5funcCii>:
  400526:	55                   	push   %rbp
  400527:	48 89 e5             	mov    %rsp,%rbp
  40052a:	48 83 ec 10          	sub    $0x10,%rsp
  40052e:	89 7d fc             	mov    %edi,-0x4(%rbp)
  400531:	89 75 f8             	mov    %esi,-0x8(%rbp)
  400534:	8b 55 f8             	mov    -0x8(%rbp),%edx
  400537:	8b 45 fc             	mov    -0x4(%rbp),%eax
  40053a:	89 c6                	mov    %eax,%esi
  40053c:	bf 34 06 40 00       	mov    $0x400634,%edi
  400541:	b8 00 00 00 00       	mov    $0x0,%eax
  400546:	e8 b5 fe ff ff       	callq  400400 <printf@plt>
  40054b:	8b 55 fc             	mov    -0x4(%rbp),%edx
  40054e:	8b 45 f8             	mov    -0x8(%rbp),%eax
  400551:	01 d0                	add    %edx,%eax
  400553:	c9                   	leaveq 
  400554:	c3                   	retq   
```
# -DDEBUG, Instrumented
```
0000000000400526 <_Z5funcCii>:
  400526:	e9 d5 00 30 00       	jmpq   700600 <funcC_dyninst>
  40052b:	83 ec 10             	sub    $0x10,%esp
  40052e:	89 7d fc             	mov    %edi,-0x4(%rbp)
  400531:	89 75 f8             	mov    %esi,-0x8(%rbp)
  400534:	8b 55 f8             	mov    -0x8(%rbp),%edx
  400537:	8b 45 fc             	mov    -0x4(%rbp),%eax
  40053a:	89 c6                	mov    %eax,%esi
  40053c:	bf 34 06 40 00       	mov    $0x400634,%edi
  400541:	b8 00 00 00 00       	mov    $0x0,%eax
  400546:	e8 b5 fe ff ff       	callq  400400 <printf@plt>
  40054b:	e9 c9 01 30 00       	jmpq   700719 <funcC_dyninst+0x119>
  400550:	f8                   	clc    
  400551:	01 d0                	add    %edx,%eax
  400553:	c9                   	leaveq 
  400554:	c3                   	retq 
```

**Comment by mxz297** [comment]
Thanks! I will take a look today.

**Comment by vysocky** [comment]
here's the complete [dump](https://github.com/vysocky/testcases/blob/master/dumpWithError.S)

**Comment by vysocky** [comment]
Here is the output I have:
```
$ gcc bug.cpp -o dynstTest
$ ./dyninst_bug dynstTest 
<> Inserting instrumentation for following application functions
<>	_fini
<>	_Z5funcCii
<>	main
<>	_init
<>	__libc_csu_init
<>	__libc_csu_fini
<>	targ400420
<>	_start
<>	__do_global_dtors_aux
<>	frame_dummy
<> NEW binary writing -  newBin 
<> Static Binary Instrumentation successfully finished
andrew@andrewer:~/prog/pool/Dyninst$ ./newBin 
func _start
func __libc_csu_init
func _init
func frame_dummy
func main
func _Z5funcCii
10 + 100 = 2
func __do_global_dtors_aux
func _fini
$ 
```

**Comment by vysocky** [comment]
And here is the output from our x86 cluster:
```
$ ./newBin 
func _start
func __libc_csu_init
func _init
func call_gmon_start
func frame_dummy
func main
func _Z5funcCii
10 + 100 = -134250496
func __do_global_dtors_aux
func _fini
$ 
```
Also tested with gcc6.3.0. Which compiler do you use?

**Comment by mxz297** [comment]
I am using gcc5.4.0. I know what's wrong based on your dump: dyninst did not save/restore the values of esi and edi, which are used for passing parameters. 

However, on my side, Dyninst indeed saved/restored esi and edi. 

While I am using gcc5.4.0, the func in the test program has the same instruction sequences as the ones posted by you.

**Comment by vysocky** [comment]
Do you have an idea what may cause the difference? I may try to recompile Dyninst with different set of modules, however recompilation of the application didn't help.

**Comment by mxz297** [comment]
Not sure what caused the difference yet... Can you run the following command on your system:

```DYNINST_DEBUG_PARSING=parsing_log ./dyninst_bug dynstTest```

This will generate a bunch of parsing_log files. Send those files to me and I will take a look.

Meanwhile, can you try compile Dyninst itself with different compilers and see if the same problem shows up?

I appreciate your helps on debugging this issue!

**Comment by vysocky** [comment]
Here is the [log](https://www.dropbox.com/s/pipr23odzceqeoh/dyninst_parsing.log?dl=0). Let me know when I may delete it.

I am trying compilation of Dyninst-10.0.0 with different set of modules (I will see if it overcome #503 ), let you know what is the result (it might be tomorrow).

**Comment by mxz297** [comment]
Thanks! I have downloaded the log file and you can delete it now.

**Comment by mxz297** [comment]
@sashanicolas @bwelton Hi guys, I cannot reproduce this issue on a ubuntu 16 machine with gcc 5.4.0 or on a Red hat 7 machine with gcc 7.3.1. Can you try and see if you can reproduce this problem with dyninst 10.0.0 on your machines? Thanks!

**Comment by bwelton** [comment]
I have not been able to reproduce this issue on my machine. However, the problem might be with liveness analysis instead of parsing (which may be caused by a parsing issue). 

If this isn't in the log files already, @vysocky should run with the environment variable DATAFLOW_DEBUG_LIVENESS set to 1 to dump this information.

**Comment by vysocky** [comment]
Btw if I compile the application to instrument with Intel compiler, than it works fine. I know that it is totally different story, but if you would like to see the dumps or anything else, just say.

**Comment by mxz297** [comment]
@vysocky Do you generate the liveness and parsing logs with Dyninst 9.3.2 or Dyninst 10.0.0?

**Comment by vysocky** [comment]
Dyninst 9.3.2 on the CentOS, I can generate it with Dyinst 10.0.0 on Ubuntu.

**Comment by mxz297** [comment]
Can you generate the same logs with Dyninst 10.0.0?

**Comment by vysocky** [comment]
here is the [log for Dyninst 10.0.0](https://github.com/vysocky/testcases/blob/master/dyninst10_liveness.log).

**Comment by mxz297** [comment]
Is it possible that you have multiple different versions of Dyninst installed on your system and at runtime different versions of dyninst components are loaded?

In your liveness log for Dyninst 10.0.0,  instructions are printed in an old format:

```push RBP, RSP @ 400526```

Dyninst 10.0.0 should print instructions in AT&T syntax, such as

```push %rbx @ 4005aa```

In addition, the parsing log of Dyninst 10.0.0 should be in multiple files, one log file per thread. It is unlikely that your system has only one core. 

Therefore, I am guessing you are still running with Dyninst 9.3.2.

**Comment by vysocky** [comment]
You are right, I have in my system 9.3.2 and 10.0.0. I have specified LD_LIBRARY_PATH, but linker found the 9 anyway. Is there a script in the repository, that will remove all Dyninst files from the system?

**Comment by mxz297** [comment]
Unfortunately no... You probably have to find where Dyninst 9.3.2 is installed and delete it.

**Comment by vysocky** [comment]
OK I have finally install removed all the dependencies to Dyninst-9.3.2 and run the the instrumented app:
```
$ ./newBin 
func _start
func __libc_csu_init
func _init
func frame_dummy
func main
func _Z5funcCii
10 + 100 = 110
func __do_global_dtors_aux
func _fini
```
So it looks that this problem is solved. Thank you for your time you have spent with this issue!
I would like to ask you to focus on #503, because otherwise I cannot compile Dyninst-10.0.0 on our CentOS system, thank you.
