### ISSUE TITLE
dyninst 10 hangs on ppcle at bpatch.processAttach

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#502]
Given the example below
% make
% make clean
% make test
./mutatee & DYNINSTAPI_RT_LIB=/usr/lib64/dyninst//libdyninstAPI_RT.so ./mutator $!
FUNCTION EXECUTED. VALUE = 0
before bpatch.processAttach
<HANGS>
^Z
% /usr/bin/gdb -p 10173
(gdb) bt
#0  0x00007fff9f93227c in futex_wait_cancelable (private=0, expected=0, futex_word=0x0)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fff98000c18, cond=0x7fff98000c40) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fff98000c40, mutex=0x7fff98000c18) at pthread_cond_wait.c:655
#3  0x00007fff9faeab44 in __pthread_cond_wait (cond=<optimized out>, mutex=<optimized out>) at forward.c:149
#4  0x00007fff9f36e3e8 in boost::condition_variable_any::wait<Mutex<false> > (m=..., this=0x7fff98000c18)
    at /usr/include/boost/thread/pthread/mutex.hpp:127
#5  CondVar<Mutex<false> >::wait (this=0x7fff98000c18) at /root/dyninst-10/src/common/src/dthread.h:125
#6  MailboxMT::dequeue (this=0x7fff98000b20, block=<optimized out>) at /root/dyninst-10/src/proccontrol/src/mailbox.C:156
#7  0x00007fff9f3a46e4 in int_process::waitAndHandleEvents (block=<optimized out>)
    at /root/dyninst-10/src/proccontrol/src/process.C:1060
#8  0x00007fff9f41ef84 in Dyninst::ProcControlAPI::Injector::inject (this=<optimized out>, libname=...)
    at /root/dyninst-10/src/proccontrol/src/loadLibrary/injector.C:92
#9  0x00007fff9f3995e8 in Dyninst::ProcControlAPI::Process::addLibrary (this=<optimized out>, 
    library="/usr/lib64/dyninst/libdyninstAPI_RT.so") at /usr/include/c++/8/bits/basic_string.h:927
#10 0x00007fffa00eb5c0 in PCProcess::loadRTLib (this=this@entry=0x100359a5de0) at /usr/include/c++/8/bits/basic_string.h:927
#11 0x00007fffa00ec7cc in PCProcess::bootstrapProcess (this=this@entry=0x100359a5de0)
    at /root/dyninst-10/src/dyninstAPI/src/dynProcess.C:435
#12 0x00007fffa00ee1f4 in PCProcess::attachProcess (progpath=..., pid=<optimized out>, analysisMode=<optimized out>)
    at /root/dyninst-10/src/dyninstAPI/src/dynProcess.C:159
#13 0x00007fffa000c158 in BPatch_process::BPatch_process (this=0x1003572e710, path=0x0, pid=<optimized out>, mode=<optimized out>)
    at /root/dyninst-10/src/dyninstAPI/src/BPatch_process.C:328
#14 0x00007fff9ffdd0d0 in BPatch::processAttach (this=<optimized out>, path=0x0, pid=<optimized out>, mode=<optimized out>)
    at /root/dyninst-10/src/dyninstAPI/src/BPatch.C:1260
#15 0x00000000100020a8 in main (argc=2, argv=0x7fffc4049768) at mutator.cpp:43

Environment:
tested on upcoming RHEL 18 release; have not tried f28
(kernel is 4.18.0-32, glibc-2.28-18)
(by comparison f28 kernel is 4.18.16-200, glibc-2.27-32)
[dyn-mut.zip](https://github.com/dyninst/dyninst/files/2586386/dyn-mut.zip)

**Comment by mxz297** [comment]
From the stack trace, it looks like Dyninst has a deadlock inside proccontrolAPI. We do not have any major changes to proccontrol between Dyninst 9.3.2 and Dyninst 10.0.0. 

To proceed, can you test older version of Dyninst on your upcoming RHEL 18 release? At the same time, can you test Dyninst 10 on your older systems? 

We will have to first identify whether the changes on RHEL system exposes the deadlock, or whether changes insides Dyninst causes the deadlock.

**Comment by mxz297** [comment]
Closed by #519
