### ISSUE TITLE
Rewriting of binaries with GNU_RELRO segment fails on master

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#52]
```
test5_1                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_2                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_3                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_4                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_5                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_7                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_8                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_9                    g++    none 64  create   NA      dynamic nonPIC  PASSED
test5_1                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_2                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_3                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_4                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_5                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_7                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_8                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
test5_9                    g++    none 64  rewriter NA      dynamic nonPIC  FAILED (Group Teardown)
```
Gist of debugging output available here: https://gist.github.com/jdetter/03f64facb53081cd19ae9ede5a5e5657

**Comment by wrwilliams** [comment]
@jdetter: please retitle to "Rewriting of binaries with GNU_RELRO segment fails on master"
@cuviper: can you give this a sanity check? Valgrind says that we're writing uninitialized memory (allocated as part of a loadable segment) to disk; that memory is showing up (per readelf) at the end of the phdrs and stomping the GNU_RELRO entry. But my math says there shouldn't be a collision, SYMTAB_DEBUG_REWRITE says that we're copying the GNU_RELRO entry correctly, and the phdrs are updated after/written before the actual sections. (Also, the section should damn well have data throughout, as it gets filled by memcpy....even if it's overwriting the last phdr it shouldn't be overwriting with uninitialized memory). I'd debug myself but I'm in the weeds on #15...

**Comment by cuviper** [comment]
Sure, I will take a look.

**Comment by cuviper** [comment]
See #54 and dyninst/testsuite#7 for valgrind fixes, but that was a red herring.

**Comment by jdetter** [comment]
I am building #54 and I will see if we are passing the series 5 tests.

**Comment by cuviper** [comment]
They're still failing for me, but they're clean now as far as valgrind is concerned.

**Comment by jdetter** [comment]
Does the rewriter still put junk into the program header table?

**Comment by cuviper** [comment]
Yep:

```
Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x00000000003ff040 0x00000000003ff040 0x000230 0x000230 R E 0x8
  INTERP         0x000238 0x0000000000400238 0x0000000000400238 0x00001c 0x00001c R   0x1
	[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x000000 0x00000000003ff000 0x00000000003ff000 0x00b898 0x00b898 R E 0x1000
  LOAD           0x00bd98 0x000000000060ad98 0x000000000060ad98 0x000610 0x000920 RW  0x1000
  LOAD           0x00d000 0x0000000000700000 0x0000000000700000 0x005501 0x005501 RWE 0x1000
  DYNAMIC        0x012311 0x0000000000705311 0x0000000000705311 0x0001f0 0x0001f0 RW  0x8
  NOTE           0x001254 0x0000000000400254 0x0000000000400254 0x000044 0x000044 R   0x4
  GNU_EH_FRAME   0x00a090 0x0000000000409090 0x0000000000409090 0x0004ac 0x0004ac R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
  LOOS+40463407  0x2d78756e696c2d64 0x732e34362d363878 0x0000000000322e6f 0x000000 0x000000 RW  0x0
```

**Comment by wrwilliams** [comment]
The first chunk of mysterious hex, in ascii, is:
s.46-68x-xunil-ds.46-68x

Looks to me like it's a substring of the interp (d-linux-x86-64.s) reversed and repeated, somehow. And the PHDR/INTERP offset difference does not correspond to the virtual/physical address difference...INTERP needs to move up a page in the file. It's obviously going to be something in the section layout code...

**Comment by cuviper** [comment]
Ha, I just realized this too!  INTERP at 0x238 is after the 64-byte EHDR + 9 * 56-byte PHDRs.  It did not shift in the rewritten binary, so the 10th PHDR overlaps it.

**Comment by cuviper** [comment]
I think the apparent reversing is just little-endian byte swaps, and perhaps repeating is from some offset math in libelf.  Open the binary in a hex editor, and see 0x238 is clearly just the INTERP string.

**Comment by cuviper** [comment]
I get zero for `library_adjust` here:

```
        else if (old->p_type == PT_INTERP && movePHdrsFirst
                 && old->p_offset && newEhdr->e_phnum >= oldEhdr->e_phnum) {
            Elf_Off interp_shift = library_adjust; //(Elf_Off) oldEhdr->e_phentsize * (Elf_Off)(newEhdr->e_phnum - oldEhdr->e_phnum);
            newPhdr->p_offset += interp_shift;
            newPhdr->p_vaddr += interp_shift;
            newPhdr->p_paddr += interp_shift;
        }
```

**Comment by cuviper** [comment]
RE shifting INTERP up a page, note you also left this comment:

```
             * This is necessary because the INTERP header must be located within in
             * the first page of the file -- if the section is moved to the next
             * page the object file will not be parsed correctly by the kernel.
```

**Comment by cuviper** [comment]
I think I've got INTERP shifted correctly -- see my [issue52](https://github.com/cuviper/dyninst/tree/issue52) branch ([comparison](https://github.com/dyninst/dyninst/compare/master...cuviper:issue52?expand=1)).

However the test *still* fails.  There's no obvious corruption in the headers now, but it appears that the dynamic linker can't find a few symbols for some reason.

```
$ ldd -r binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none
        linux-vdso.so.1 (0x00007fffd8956000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4004fb3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4004cb0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4004a99000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f40046d8000)
        /home/jistone/paradyn/root/lib/libdyninstAPI_RT.so (0x00007f4003446000)
        /lib64/ld-linux-x86-64.so.2 (0x000056017eeeb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4003242000)
undefined symbol: logstatus     (binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none)
undefined symbol: _Z10setRunTestPKc     (binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none)
undefined symbol: test_fails    (binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none)
```

But all three of those show up in both `nm` and `nm -D`. :confused:

**Comment by wrwilliams** [comment]
I know I've seen this before and my off-the-cuff recollection is that there's likely non-printable garbage at the end of the symbol needed such that it doesn't match the symbol provided. Unfortunately I don't remember where it came from (nor is it guaranteed to be the same problem). But check the strings carefully.

**Comment by cuviper** [comment]
The strings look OK -- at least, every place they appear in the binary has a `NUL` terminator.

It appears `.rela.dyn` is corrupted.  See how the four `X86_64_COPY` entries kept the same offset but changed value and name.  The first new name is a weak `W` symbol that can probably be resolved elsewhere, and the other three match my `ldd -r` failures.   But I expect these shouldn't have changed at all, should have just added the two new targ relocations.

The two `.rela.plt` changes look pretty weird too.

```diff
--- /dev/fd/63	2016-05-25 13:17:56.207699914 -0700
+++ /dev/fd/62	2016-05-25 13:17:56.208699905 -0700
@@ -1,14 +1,16 @@
-# eu-readelf -r dyninst_cxx_group_test.dyn_g++_64_none_none
+# eu-readelf -r binaries/rewritten_dyninst_cxx_group_test.dyn_g++_64_none_none
 
-Relocation section [ 9] '.rela.dyn' at offset 0x3d48 contains 5 entries:
+Relocation section [33] '.rela.dyn' at offset 0x11e19 contains 7 entries:
   Offset              Type            Value               Addend Name
   0x000000000060aff8  X86_64_GLOB_DAT 000000000000000000      +0 __gmon_start__
-  0x000000000060b3c0  X86_64_COPY     0x000000000060b3c0      +0 _ZTVN10__cxxabiv117__class_type_infoE
-  0x000000000060b418  X86_64_COPY     0x000000000060b418      +0 _ZTVN10__cxxabiv120__si_class_type_infoE
-  0x000000000060b480  X86_64_COPY     0x000000000060b480      +0 stderr
-  0x000000000060b488  X86_64_COPY     0x000000000060b488      +0 stdout
+  0x000000000060b3c0  X86_64_COPY     0x0000000000405606      +0 _ZN8arg_testD4Ev
+  0x000000000060b418  X86_64_COPY     0x0000000000406dd4      +0 logstatus
+  0x000000000060b480  X86_64_COPY     0x0000000000404616      +0 _Z10setRunTestPKc
+  0x000000000060b488  X86_64_COPY     0x000000000040789b      +0 test_fails
+  0x00000000007000b8  X86_64_GLOB_DAT 0x0000000000404400      +0 targ404400
+  0x00000000007000c0  X86_64_GLOB_DAT 0x0000000000404300      +0 targ404300
 
-Relocation section [10] '.rela.plt' for section [12] '.plt' at offset 0x3dc0 contains 46 entries:
+Relocation section [34] '.rela.plt' at offset 0x11ec1 contains 46 entries:
   Offset              Type            Value               Addend Name
   0x000000000060b018  X86_64_JUMP_SLOT 000000000000000000      +0 fileno
   0x000000000060b020  X86_64_JUMP_SLOT 000000000000000000      +0 dup2
@@ -36,7 +38,7 @@ Relocation section [10] '.rela.plt' for
   0x000000000060b0d0  X86_64_JUMP_SLOT 000000000000000000      +0 strerror
   0x000000000060b0d8  X86_64_JUMP_SLOT 000000000000000000      +0 sigaction
   0x000000000060b0e0  X86_64_JUMP_SLOT 000000000000000000      +0 atoi
-  0x000000000060b0e8  X86_64_JUMP_SLOT 0x00000000004043e0      +0 __cxa_pure_virtual
+  0x000000000060b0e8  X86_64_JUMP_SLOT 0x0000000000405530      +0 _ZN13cpp_test_utilD4Ev
   0x000000000060b0f0  X86_64_JUMP_SLOT 000000000000000000      +0 fread
   0x000000000060b0f8  X86_64_JUMP_SLOT 000000000000000000      +0 __errno_location
   0x000000000060b100  X86_64_JUMP_SLOT 000000000000000000      +0 strdup
@@ -51,7 +53,7 @@ Relocation section [10] '.rela.plt' for
   0x000000000060b148  X86_64_JUMP_SLOT 000000000000000000      +0 __cxa_begin_catch
   0x000000000060b150  X86_64_JUMP_SLOT 000000000000000000      +0 fwrite
   0x000000000060b158  X86_64_JUMP_SLOT 000000000000000000      +0 realloc
-  0x000000000060b160  X86_64_JUMP_SLOT 0x00000000004044d0      +0 __gxx_personality_v0
+  0x000000000060b160  X86_64_JUMP_SLOT 0x00000000004087b0      +0 _ZTS16sample_exception
   0x000000000060b168  X86_64_JUMP_SLOT 000000000000000000      +0 fprintf
   0x000000000060b170  X86_64_JUMP_SLOT 000000000000000000      +0 write
   0x000000000060b178  X86_64_JUMP_SLOT 000000000000000000      +0 _Unwind_Resume
```

**Comment by cuviper** [comment]
All of these `.rela` swaps correspond to matching indexes in the old and new `.dynsym` tables.  For example, `stdout` was at index 202 but moved to 215, and the new 202 is `test_fails`.

**Comment by cuviper** [comment]
There's a comment in `createSymbolTables` stating that `.dynsym` is not meant to be regenerated, only appended.  However, I'm seeing extra symbols inserted in the table for alternate constructors and destructors.

For example, the original dynsym has `_ZN15derivation_testD0Ev`, but in the rewritten binary there is a sibling `_ZN15derivation_testD4Ev`.  They have the same `getIndex()` result, so when `allDynSymbols` is sorted by index, these duplicates are placed next to each other, and the actual placement written out are off by one.  These errors accumulate for several similar instances of rogue C4 and D4 functions.

(From `gcc/cp/mangle.c`, these names are for old-style "[unified]" constructors and destructors.)

In the original, the D4 variant only exists in debuginfo:

```
 [  823f]      subprogram
               external             (flag_present) Yes
               name                 (strp) "~derivation_test"
               linkage_name         (strp) "_ZN15derivation_testD4Ev"
               virtuality           (data1) virtual (1)
               containing_type      (ref4) [  81cf]
               artificial           (flag_present) Yes
               accessibility        (data1) public (1)
               declaration          (flag_present) Yes
               object_pointer       (ref4) [  8252]
```

```
 [  86a0]    subprogram
             specification        (ref4) [  823f]
             decl_file            (data1) 1
             decl_line            (data1) 200
             inline               (data1) declared_not_inlined (2)
             object_pointer       (ref4) [  86b0]
             sibling              (ref4) [  86c3]
```

```
 [  86ef]    subprogram
             abstract_origin      (ref4) [  86a0]
             linkage_name         (strp) "_ZN15derivation_testD0Ev"
             low_pc               (addr) 0x0000000000406568 <_ZN15derivation_testD0Ev>
             high_pc              (data8) 38 (0x000000000040658e <_ZN13cpp_test_util8call_cppEi>)
             frame_base           (exprloc) 
              [   0] call_frame_cfa
             object_pointer       (ref4) [  8712]
             GNU_all_tail_call_sites (flag_present) Yes
             sibling              (ref4) [  871b]
```

So this same function is effectively getting two values of `linkage_name`, but should we only want to write the one that was already in `.dynsym`.

**Comment by wrwilliams** [comment]
Cute. And yes, we do not want to pollute dynsym with debugging info.

**Comment by cuviper** [comment]
AFAICT in `Aggregate::addMangledName()`, if the thing has any dynamic symbol already defined, then the new name is also added as a dynamic symbol.  Perhaps some new method is needed for the dwarf-walker to use which doesn't do this?

**Comment by wrwilliams** [comment]
Yeah, I see the problem here and its genesis. I should have useful thoughts by the time I get to the office and look at code in-depth.

**Comment by wrwilliams** [comment]
Okay, here's what existed previously, why it was wrong, and how to make it right:

Previously, when we added names to Aggregates from DWARF we'd add them, demangled, as pretty or typed names, and not create new symbols for them. When we went to lazy demangling and every name (outside of inlines) backed by a symbol, I threw everything in as mangled and symbol-backed.

What we actually want, I believe, is for all names to be added as mangled (as running a demangled name through a demangler should be the identity function), but for all names (not just inlines) added from DWARF to be added as explicitly non-symbol-backed names. The problem, of course, is that the range interfaces get tricky when we're merging symbol-backed and string-backed names together on the fly.

**Comment by cuviper** [comment]
What if we let it be `Symbol`-backed, but mark that such that it won't go in either `.symtab` or `.dynsym`?  Something like `Aggregate::addDebugName()` (or a defaulted `isDebug` parameter on the existing `add*Name` methods), create a `Symbol` with a new `bool isDebug_=true`, then let `Symbol::isInSymtab()` and `Symbol::isInDynSymtab()` both return false for debug symbols.

I know `Symbol` and `Aggregate` are both public interfaces, but I think this is a reasonable addition.  We can make it friend-protected if you don't want public exposure though.

**Comment by wrwilliams** [comment]
I don't see an immediate problem (nor do I see a problem with the interface being public)--give it a shot and see how it works.
