### ISSUE TITLE
Add relocation entry for external functions

### ISSUE THREAD

**Issue by sashanicolas** [dyninst/dyninst#522]
Allows ARMv8 instrumentation to make call to external functions.

**Comment by mxz297** [comment]
@sashanicolas @LER0ever Is this done in ARMv8, but not in master yet?

**Comment by LER0ever** [comment]
> @sashanicolas @LER0ever Is this done in ARMv8, but not in master yet?

This is essentially #545, which will be merged to ARMv8 soon.

**Comment by mxz297** [comment]
Great! Thanks for associating the PR here.
