### ISSUE TITLE
Bpatch_effectiveAddress truncates memory addresses to bottom 32 bits (PPC Only)

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#524]
On PowerPC, Bpatch_effectiveAddress only copies the bottom 32 bits of the memory address used in a load/store operation in certain circumstances. 

The problem is a result of how the memory address are captured by Bpatch_effectiveAddress. The effective address calculated using the following approach (for POWER):

1. Set the immediate value of the load/store instruction into a scratch register.
2. Add register ra, a register containing a portion of the memory address, to the scratch register (if it exists, instruction dependent).
3. Add register rb, a register containing a portion of the memory address, to the scratch register (if it exists, instruction dependent)).

Our code makes the assumption that ra/rb are stored in an instrumentation frame and that a load from the frame at a specific offset will yield the correct values. 

There is one known issue with this and a potential issue that needs to be explored:

[Known Issue] The read of ra/rb only reads the bottom 32bits of value originally stored in those registers, resulting in a truncated memory address (at best) or a wrong memory address (at worst). Commit 319513795d706380db4b18dcbb2150a1574067c5  is a solution to this issue.  

[Potential issue] If instrumentation frames are not used (i.e. they are disabled), the effective address is likely is just wrong since there appears to be no handling of this case in the code (requires ra/rb are on the stack at a fixed offset in an instrumentation frame).

**Comment by mxz297** [comment]
@bwelton I believe that instrumentation frames by default are on, and can only be disabled by doing stack modification. 

So, I think cherry-pick your commit should resolve this problem. I will do that soon.

**Comment by mxz297** [comment]
The fix is in #564

**Comment by hainest** [comment]
Should this be included in 10.1?

**Comment by bwelton** [comment]
Yes, EA calculations on Power will not function correctly without this change.

Ben

On Thu, Mar 7, 2019 at 12:23 PM Tim Haines <notifications@github.com<mailto:notifications@github.com>> wrote:

Should this be included in 10.1?
