### ISSUE TITLE
Update README for build help

### ISSUE THREAD

**Issue by vanhauser-thc** [dyninst/dyninst#525]
I was able to build dyninst10 and then update my afl-dyninst project to build with dyninst10.

it was painful and I would have hoped to have some guideance in the README.

So these were my steps, and maybe it makes it easier for others to build or to grab some of these things to update the README.

Building dyninst 10:
1. remove elfutils if installed as distribution package
2. download the newest elfutils, make and (!) make install
3. install libboost-all-dev for the distribution
4. dyninst cmake looks for boost -mt multithreadded libs and otherwise downloads it and installs it locally. Makes building a project must harder. So we link everything to have -mt libs there to be found: (depending where libboost is installed, for me its /usr/lib/x86_64-linux-gnu):
```
cd /usr/lib/x86_64-linux-gnu && for i in libboost*.so libboost*.a; do
  n=`echo $i|sed 's/\./-mt./'`
  ln -s $i $n
done
```
5. then run cmake, make, make install

Building against dyninst 10:
With 9.3.2 I needed (among other things): -liberty -lcommon to compile.
With dyninst10 I need the following instead: -I/path/to/dyninst/build/tbb/src/TBB/src/include -lboost_system -L/path/to/dyninst/build/tbb/lib -ltbb -Wl,-rpath /path/to/dyninst/build/tbb/lib

**Comment by hainest** [comment]
It looks like you are building from source. We strongly recommend installing DynInst using spack as the number and specific versions of the dependencies are cumbersome to get correct. That said, I recently installed dyninst:HEAD from source on Linux Mint, and didn't encounter these issues. Could you describe your build environment in more detail?

>remove elfutils if installed as distribution package

Which version was installed as a system package?

>install libboost-all-dev for the distribution

DynInst comes with its own Boost distro. I recommend using that one as we've had issues with newer versions of Boost not compiling correctly. This will also bypass the need to manually create the mt libs.

**Comment by hainest** [comment]
The handling of third-party libraries has substantially changed in today's 10.1 release. The documentation has been substantially updated to reflect these changes.
