### ISSUE TITLE
Any support for ARM32 and MIPS

### ISSUE THREAD

**Issue by yuedeji** [dyninst/dyninst#538]
Great works on the Dyninst project! Thank you all for sharing this.

I was using Dyninst for a while. Recently, I plan to analyze some binaries under different architectures. I realize you are actively developing an ARM64 branch, but do you have any versions to support ARM32 and MIPS?

Thanks,
Yuede

**Comment by sashanicolas** [comment]
@yuedeji You're welcome!
For aarch32 you should checkout @rchyena fork of Dyninst. https://github.com/rchyena/dyninst
I can't tell you anything about that porting, but maybe Ray can help you.

Sasha

**Comment by sashanicolas** [comment]
@yuedeji We don't support MIPS anymore. You could try older versions of Dyninst.

**Comment by yuedeji** [comment]
Hi Sasha,
Thanks so much for the response. I will look into that and see.

**Comment by tthtlc** [comment]
I got a crash when analysing ARM32:
![image](https://user-images.githubusercontent.com/179509/106705666-5757db80-6629-11eb-8f3c-23ec86fec3dd.png)

And the location of source code is here:

![image](https://user-images.githubusercontent.com/179509/106705707-69d21500-6629-11eb-9561-5cb4e3f3dd5d.png)

So yes, confirmed, it is unimplemented for ARM32, and same goes for Ray Chen tree as well.
