### ISSUE TITLE
Springboards can trample function data due to incorrect range

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#551]
When generating springboards within a single function (i.e. at entries to basic blocks),  the valid range calculation makes the assumption that any gaps between basic blocks within the function (i.e. ones that that do not contain valid instructions) are free to be used as spillover when writing a springboard (the springboard can extend into that region if necessary). 

However, this behavior can cause problems if the gap space contains data. An example from PPC:

Block Begin:
    101c9b4c:   5d ff 22 3d     addis   r9,r2,-163
    101c9b50:   68 17 29 39     addi    r9,r9,5992
    101c9b54:   64 17 07 79     rldicr  r7,r8,2,61
    101c9b58:   aa 3a e9 7c     lwax    r7,r9,r7
    101c9b5c:   14 4a 27 7d     add     r9,r7,r9
    101c9b60:   a6 03 29 7d     mtctr   r9
    101c9b64:   20 04 80 4e     bctr
End Block / Start Data:
    101c9b68:   38 01 00 00     .long 0x138
    101c9b6c:   18 00 00 00     .long 0x18
    101c9b70:   18 00 00 00     .long 0x18
    101c9b74:   48 00 00 00     .long 0x48
    101c9b78:   48 00 00 00     .long 0x48
Next Block in same function:
    101c9b7c:   00 00 42 60     ori     r2,r2,0
    101c9b80:   78 fb e3 7f     mr      r3,r31
 
The springboard for 101c9b4c extends into the region of 101c9b68 corrupting the data in that region (101c9b68 is read by the block 101c9b4c and used as the jump address to 101c9b7c, why the compiler chose to do this is another story). 

The simplest fix is to enforce strict bounds on springboard generation to fall within the block only (or another blocks free space). However this has the downside where single block functions with empty gaps within them might be required to rely on traps.

**Comment by mxz297** [comment]
On power, jump table data are typically put immediately after the indirect jump; so the jump table data are embedded in .text. This is very common on power, but not so for x86 or ARM. 

I took at the related code in Dyninst. The code comments are describing the right thing to do, however the code after the comment does not match the comments.

https://github.com/dyninst/dyninst/blob/05cc087cf5adb3c5e96f47f6d47c75f7182917e1/dyninstAPI/src/Relocation/Springboard.C#L182

The comment says that we can extend block to include nops. However, the Dyninst code will only check whether the bytes after a block end is contained by any other block. If Dyninst code checks whether the bytes are indeed nop or not, Dyninst would not include jump table data into the current block.

For your work around, you can simply comment out the while loop at line 188

https://github.com/dyninst/dyninst/blob/05cc087cf5adb3c5e96f47f6d47c75f7182917e1/dyninstAPI/src/Relocation/Springboard.C#L188

Then spring boards in this case will be traps. I am a little surprised that 7 instructions are not sufficient for spring boards. Maybe we need to revisit this as well.

**Comment by bwelton** [comment]
This is the fix I am trying out (along with disabling all non-required springboards).

7+ instruction jumps are not that uncommon right now. In the best case for long jumps the loading of the immediate takes anywhere from 2-5 instructions + an instruction to load tar + the branch itself. In the moderate (and most likely case) we add an instructions to cache an r register to either lr or ctr (so we have a free register to place the immediate into) + an instruction to restore before jumping (bringing the total to as many as 9 instructions). In the worst case (CTR,LR,and all R registers are used), we have to create a mini-frame to temporarily store an r register to have a free register to calculate the immediate (+2 additional instructions, total of 11). Dyninst master right now does not handle the worst case other than by using a trap.

**Comment by mxz297** [comment]
@bwelton After changing the size back to 1, it still has about the same amount of regressions.
