### ISSUE TITLE
Mask register operands for 9.2.X release?

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#56]
I think we should either add a `MaskRegister` class or add functionality to the current `Register` class in `InstructionAPI` so that we can deal with the syntactical differences between mask register operands and normal register operands. This will make it much easier for us to output our instructions in AT&T syntax. The only major changes to the `Register` would be adding a property (something like `isMask`) and adding getter/setter methods for the property.

I think it would be a cleaner implementation to have a `MaskRegister` class that extends the `Register` class.

Here is an example of the syntax for a mask register (the last operand):

```
     vrcp28sd %xmm0, %xmm0, %xmm0 {%k1}
```

@wrwilliams do you have any suggestions as to which is the better solution?

**Comment by wrwilliams** [comment]
Add a MaskRegister class that formats appropriately, and you shouldn't need to mess with properties.
