### ISSUE TITLE
isPCRelData: Assertion `res.defined' failed

### ISSUE THREAD

**Issue by djwatson** [dyninst/dyninst#566]
Trying to use afl-dyninst with dyninst v9.3.2 tag from github.  (I haven't gotten the correct deps to build current master yet (old boost version), but this codepath appears to be unchanged).

On one binary, I am hitting the assert in Movement-adhoc.C:isPCRelData : res.defined, ~line 285.

I added a cerr print of the insn->format():

Error: bind PC !res.defined in vpand XMM4, XMM4, [RIP + 1711723].

The bind appears to succeed, but res.defined is false.  

Any hints on how to proceed?  Thanks

**Comment by mxz297** [comment]
The current master has the following code in the `isPCRelData` function:

```
      Result res = exp->eval();
      if (!res.defined) {
	cerr << "ERROR: failed bind/eval at " << std::hex << ptr->addr() << endl;
        continue;
      }
      assert(res.defined);
```

I believe this assert will not hit any more. Whether Dyninst can continue to work normally afterwards is a different question... So, I would recommend that you try to use Dyninst current master which will soon be Dyninst 10.1.

In terms of old deps, Dyninst should automatically download missing dependencies. You can delete the old boost installed and let Dyninst pulls all the dependencies.

**Comment by mxz297** [comment]
@djwatson Dyninst 10.1 was released a week ago. If after you update Dyninst and still see the same problem, please let me know and I will try to fix it.
