### ISSUE TITLE
libboost_system.so.1.58.0: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by RosenZhu** [dyninst/dyninst#579]
When I used Dyninst to instrument, I got the following error. As I notice, it may be related to libboost_system.so,  which should be the libboost_system-mt.so.  But when I build Dyninst, I leave the PATH_BOOST empty, it seems that Dyninst doesn't automatically build libboost_system-mt.so. 
So how can I build libboost_system-mt.so manually? 
When I try to download it, it seems that the "-mt" version only exists on Centos.
My system is ubuntu16.04, x86_64 and CPU is AMD.

`g++ -g -Wall -O3 -std=c++11 -I/usr/local/include -I/home/nsc2s/Apps/buildDyn10/include -I/home/nsc2s/Apps/buildDyn10/tbb/include  -c afl-dyninst.cpp
g++ -g -Wall -O3 -std=c++11 -L/home/nsc2s/Apps/buildDyn10/lib \
	-L/usr/local/lib \
	-o afl-dyninst afl-dyninst.o \
	-lcommon \
	-liberty \
	-ldyninstAPI` 
`/usr/bin/ld: afl-dyninst.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line`
`collect2: error: ld returned 1 exit status
Makefile:24: recipe for target 'afl-dyninst' failed
make: *** [afl-dyninst] Error 1
`

also, I found that it trigger some errors when using parallel building such as "make install -j8".  Some errors related to "tbb/**.h  doesn't exist", I cannot remember exactly. But when building on only one process, it could build successfully.

**Comment by hainest** [comment]
I recently ran into this same issue when using a custom-built Boost-1.69. For some reason, it sometimes fails to find the symbol for the `boost::system::system_category()` function. I don't yet have an explanation (I have used that install of Boost many times in the past without incident). The workaround for now is to force Dyninst to build Boost from source. The easiest way to do that is to add `set(Boost_NO_SYSTEM_PATHS ON);` on line 136 in [packages.cmake](https://github.com/dyninst/dyninst/blob/1bd663ff8ff13220c11a6b0cfc0af96d8fddf45f/cmake/packages.cmake#L136). I am currently working on several fixes and upgrades to how we handle Boost. I hope to have these changes merged into master this week.

There is a [PR](https://github.com/dyninst/dyninst/pull/570) to fix the TBB dependency ordering issues. I hope to get this merged into master this week, as well. It all depends on how quickly I can get the testsuite to work with the new Boost system.

**Comment by RosenZhu** [comment]
@hainest Thanks for your advice. 
I have one more question, can I get the value of flag register (such as CF,ZF,SF) by instrumentation?
For example, 

`cmp     eax, DWORD PTR [rbp-8]`
  `jge     .L5`

I want to instrument at the point between `cmp` and `jge`, and the code I inserted is intended to use the result of `cmp`, i.e. the state of flag register. 

As I learn from dyninst papers, dyninst seems to replace one or more instructions at the instrumentation point. This means, the `cmp` instruction in the example will be executed after my inserted code is executed, which is not what I want.  Is that right?

**Comment by RosenZhu** [comment]
@mxz297  Thanks very much.
 What we want to do is to check whether the conditional jump instructions jump successfully or not, and do something according to the result. 
and as to the indirect jumps, we want to get the address that the jump instruction will jump to. and do something according to the result.

**Comment by mxz297** [comment]
> What we want to do is to check whether the conditional jump instructions jump successfully or not, and do something according to the result.

Dyninst supports CFG edge instrumentation, meaning that you can instrument the condition-taken branch and condition-not-taken branch separately. You need to get `BPatch_edge` objects by traversing `BPatch_flowGraph`. From `BPatch_edge`, you can get instrumentation points for that edge.

> and as to the indirect jumps, we want to get the address that the jump instruction will jump to. and do something according to the result.

For most indirect jumps, Dyninst can resolve them statically (jump tables). For indirect tail calls, you can instrument them before the indirect jumps take places. See `BPatch_dynamicTargetExpr()`

**Comment by RosenZhu** [comment]
@mxz297 Thanks very much!
