### ISSUE TITLE
Is the possible to insert a snippet statically and then delete the same snippet?

### ISSUE THREAD

**Issue by RosenZhu** [dyninst/dyninst#580]
I want to do something like:
-- 1 get a binary
-- 2 insert some snippets (e.g. 100 snippets) into the binary
-- 3 save the instrumented binary
-- 4 execute the instrumented binary for several times and stop executing
-- 5 delete some of the instrumented snippets (e.g. delete 10 snippets) 
-- 6 save the binary that was deleted some snippets
-- goto 4

So, my question is, how to find the inserted snippets in the saved binary?
I've search for some examples, but they delete the inserted snippets dynamically, i.e. they save a BPatchSnippetHandle *handle, and delete the handle when necessary.

**Comment by mxz297** [comment]
Based on my knowledge, Dyninst currently will not re-instrument binaries that have been rewritten by Dyninst. 

You are right that it is possible to do dynamic instrumentation insertion and deletion, but to do iterative binary rewriting, there needs to be some changes made to Dyninst.

**Comment by mxz297** [comment]
By the way, I am happy to have a collaboration based on what exactly you plan to do.

**Comment by RosenZhu** [comment]
@mxz297 
> By the way, I am happy to have a collaboration based on what exactly you plan to do.

That's great!  can I get your personal email?

**Comment by mxz297** [comment]
> That's great! can I get your personal email?

You can just contact me by my gmail, which is in my github profile.

**Comment by mxz297** [comment]
Closed due to inactivity.
