### ISSUE TITLE
Cobwebs on the Documentation and boost 1.70.0 issues.

### ISSUE THREAD

**Issue by ianamason** [dyninst/dyninst#585]
@mxz297 is there any updated documentation for the patchAPI classes?
The doc area looks quite old, and the only example findPoint looks to be
quite out of date.

As an aside, I tried spack installing on a clean ubuntu 18.0.4 box again yesterday,
but it failed this time. Seems boost has gone from 1.69.0 to 1.70.0 and dyninst no longer 
compiles against this version.  I got around it with the `^boost@1.69.0` hack, but ...

**Comment by hainest** [comment]
> As an aside, I tried spack installing on a clean ubuntu 18.0.4 box again yesterday,
> but it failed this time. Seems boost has gone from 1.69.0 to 1.70.0 and dyninst no longer
> compiles against this version. I got around it with the ^boost@1.69.0 hack, but ...

We just found this a couple of days ago. Someone is working on a patch. I hope to have it merged soon (definitely before the 10.1 release).

**Comment by ianamason** [comment]
Thanks @hainest
