### ISSUE TITLE
Trying to get a very simple PatchAPI example working

### ISSUE THREAD

**Issue by ianamason** [dyninst/dyninst#587]
Hi there, Me again.

I'm trying to piece together a simple patchAPI example from the existing 
documentation.  I have managed to succeed in getting it to compile,
but not to actually edit the given binary. I am sure it is something 
simple (well actually, I am *hoping* it is something simple).

I put the code [here](https://github.com/ianamason/patchAPI), and be delighted if
someone could point out where I am going wrong.

Thanks in advance ...

**Comment by ianamason** [comment]
Even it appears that I am talking to myself here, but for completeness I should mention that I added a hybrid approach (using both DyninstAPI and PatchAPI) that does seem to work.

**Comment by mxz297** [comment]
@ianamason I am really sorry that we are not being responsive. Mixing DyninstAPI and PatchAPI is indeed a good way to build a sophisticated mutator. 

Are you willing to contribute your example by creating a PR? Again, I am sorry that this is something we should have done better, but we are hunting down bugs for Dyninst 10.1. 

We would greatly appreciate your contributions of updating a PatchAPI example.

**Comment by ianamason** [comment]
Sure @mxz297  I can do that sometime this week.

**Comment by mxz297** [comment]
Closed via #588.
