### ISSUE TITLE
BPatch_addressSpace replaceFunctionCall does not set R12 on Power

### ISSUE THREAD

**Issue by bwelton** [dyninst/dyninst#589]
replaceFunctionCall appears to be using a different path than inserting a function call that does not set R12  (causing the TOC to be miscalculated by the replaced function call).

**Comment by mxz297** [comment]
@bwelton  test1_14 in the testsuite tests this functionality and that test is passing on power.  I just read the source code of the tests. I guess the problem of the test is that it only tests replaces function call with a call to a function in the same binary. It does not test replacing calls to a function in a shared library.

Are you replacing function call to a function in a shared library?

**Comment by mxz297** [comment]
@bwelton Which branch are you using? For your new project, do you think it may be better to use dyninst master?

**Comment by bwelton** [comment]
This may effect master as well as my branch (i have not run the test suite with master).

The test suite's replace function test for shared libraries may be too simple. The function call that is being replaced is not accessing any static data within the shared object (either literals or globals). Thus it is very likely never trying to read anything from R2 (you can confirm this by objdumping libA and looking at function test1_14_call2_libA). A simple reproducer for this would be to modify test1_14_call2_libA to add a global variable with a value of 2 and setting var using that variable.

On Thu, Apr 25, 2019 at 10:39 AM Xiaozhu Meng <notifications@github.com<mailto:notifications@github.com>> wrote:

@bwelton<https://github.com/bwelton> Which branch are you using? For your new project, do you think it may be better to use dyninst master?

**Comment by mxz297** [comment]
@bwelton I see. I will then augment the test and fix the problem.

**Comment by mxz297** [comment]
@bwelton Are we certain that this is not a problem for master branch?
