### ISSUE TITLE
Altering input operand of an instruction

### ISSUE THREAD

**Issue by vahldiek** [dyninst/dyninst#590]
Hi,

I've been using DynInst in a project to rewrite certain x86 binary sequences.

The issue I've run into, is that I'd like to change the input operand of an x86 instruction lets say mov EDX, 0x55555555 into mov EDX, ECX. I've build instructions around it to make sure that the right value is in ECX, so don't worry about that. I've looked through the API and tried several ways to update the register without me requiring to assemble a new mov instruction.

The closest in the API I found is the BPatch_insnExpr Snippet which even provides a small example to override the store address (simply switched to the inputs and I would have my solution). Unfortunately this instruction takes as an input a BPatch_instruction and I've not been able to generate one of these. Hence, my question, what is the best way to build a BPatch_instruction or use the BPatch_insnExpr Snippet.

Any help would be greatly appreciated!

Thanks,
Anjo

**Comment by vahldiek** [comment]
I thought that I found a way to get a BPatch_instruction out of a BPatch_point via getMemoryAccess, but mov instructions are not memory accesses it seems only load and stores. Is there anyway to use the BPatch_insnExpr for instructions different than memoryAccesses out of a BPatch_point?

Thanks.

**Comment by mxz297** [comment]
@vahldiek I looked into our code base. I only find code to modify the addressing mode of a memory operand, but I don't find any code to modify an operand from one type of memory operand, immediate, or register, to other types.

**Comment by vahldiek** [comment]
Thanks, I'm now assembling a new mov instruction. I thought there may be a nice way to do it with the BPatch_insnExpr by overriding the source/destination.
