### ISSUE TITLE
Segementation fault

### ISSUE THREAD

**Issue by hirouka** [dyninst/dyninst#602]
I get this .
gdb ./instrumentFunc 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./instrumentFunc...done.
(gdb) run
Starting program: /home/nadia/install/dyninst-9.3.2/testDyn/instrumentFunc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
[New Thread 0xb7014b40 (LWP 12423)]
avant process create
[New Thread 0xb66ffb40 (LWP 12426)]
[New Thread 0xb5efeb40 (LWP 12427)]

Program received signal SIGSEGV, Segmentation fault.
0xb7b6d803 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/i386-linux-gnu/libstdc++.so.6

**Comment by hainest** [comment]
I see you are using Dyninst-9.3.2. I would recommend upgrading to Dyninst-10.1 and trying again. If you see the same result, please also post a stack trace.

**Comment by hirouka** [comment]
thank you, it works with  Dyninst-10.1, but I have another problem, my mutator does not create another executable,  it's supposed to
the  example ; https://github.com/dyninst/docs/blob/master/dyninstAPI/examples/instrumentFunc.C
