### ISSUE TITLE
Local variable 

### ISSUE THREAD

**Issue by hirouka** [dyninst/dyninst#604]
Hello, 
I have question,I want to get all the local variables in my function , and i have write this code 
***********************************************************************************************
 std::vector<BPatch_point*>* routiPoint = 
        findPoint(app, interestingFuncName, BPatch_entry); // trouver un point d'entree de la fonction 
    if (!entryPoint || entryPoint->size() == 0) { // verification de point (existe ou non )
        fprintf(stderr, "No entry points for %s\n", interestingFuncName);
        exit(1);
    } 
  std::vector<BPatch_point*> a = routiPoint[0];
    BPatch_function *fu = a[0]->getFunction(); 
    std::string s = fu->getName(); // s =InterestingProcedure
    BPatch_localVar* varloc = fu->findLocalVar(nomVar); 
    std::vector<BPatch_variableExpr*>* variabetrouvee = fu->findVariable(nomVar); //nomVar = b 
*******************************************************************************************************
/////////////////////////////////////////////////////////////prog.c/////////////////////////////////////////////////////////////////////////////
#include <stdio.h>
#include <stdlib.h>
int c =20 ; 
void InterestingProcedure(int i)
{ 
    int b ; 
    b=0; 
    b=b+1;
    printf("\t  procedure  %i \n",i);
}

int main(){
    int a ; 
    printf("début de main\n");
    for(int i = 0; i<3 ; i++){
        InterestingProcedure(i);
    } 
    printf("variable c =  <%i> \n",c);   

    return 0;
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
but i get this :  
--SERIOUS-- #100: Unable to find variable: b
--SERIOUS-- #100: Unable to find variable: b

**Comment by hainest** [comment]
Even at the lowest optimization levels, compilers will perform [DCE](https://en.wikipedia.org/wiki/Dead_code_elimination). Hence, `b` is never entered into the dwarf information. Try adding it to the `printf` statement in `interrestingProcedure`.

**Comment by hirouka** [comment]
thank you , i have another question , 
I want to create a variable of type "struct timespec" but  it doesn't work with findType

**Comment by hainest** [comment]
I'm afraid I don't know how to help with that. Could @bwelton, @sashanicolas, or @mxz297 jump in?

**Comment by mxz297** [comment]
@hirouka I don't quite understand what you try to do. Do you want to create a new variable in the mutatee with type "struct timespec"? If that is what you want to do, we recommend that you declare the variable in your instrumentation library, and use Dyninst to load that library into the mutatee. 

Meanwhile, it is possible that you cannot find "struct timespec" if no such debugging information is available in your mutatee.

**Comment by hirouka** [comment]
thank you, 
this code inject the snippets at the entry or the exit  of the interested function,
How can we inject a snippets at a specific  instruction?


#include <stdio.h>
#include "BPatch.h"
#include "BPatch_addressSpace.h"
#include "BPatch_function.h"
#include "BPatch_binaryEdit.h"
#include "BPatch_point.h"

int main(int argc, const char *argv[]) {
    
    // Use BPatch_* classes to initialize
    BPatch bpatch;
    BPatch_addressSpace *app = bpatch.openBinary("hello", true);
    bool flag = false; 
    flag = app->loadLibrary("liblib.so");
    
    BPatch_image* image = app->getImage();
  
    std::vector<BPatch_function*> func;
    image->findFunction("code_to_inject", func);
    
    std::cout<<"\nFunction is: "<<func[0]->getName()<<std::endl;
    
    std::vector<BPatch_snippet*> openArgs;
    BPatch_funcCallExpr enter_call(*(func[0]), openArgs);
    
    func.clear();
    std::vector<BPatch_point *> *points;
    image->findFunction("foo1", func);
    points = func[0]->findPoint(BPatch_entry);
    
    app->insertSnippet(enter_call, *points);
    
    BPatch_binaryEdit *appBin = dynamic_cast<BPatch_binaryEdit *>(app);
    
    appBin->writeFile("newbinary");
      
    return 0;
}
