### ISSUE TITLE
Handling of PIE binaries

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#605]
On recent Linux distributions, the system compiler will by default generate position independent executables (PIEs). Dyninst currently has at least two issues when dealing with PIE:

1. A few interface checks whether a binary is a shared library. Such check will wrongly return that PIEs are shared libraries. The boundary between shared library and PIE is indeed blur. We need to come up with a reliable way to distinguish PIE from shared libraries.

2. Static PIE was not legal until recently. To generate static PIE, flag "-static-pie" should be used rather than two flags "-static" and "-fie". Dyninst currently cannot correctly identify static PIE as static binary. Static pie contains necessary dynamic information for relocation, so Dyninst treats static PIE as dynamically linked. This will be the first step towards correctly instrumenting static PIE.

**Comment by mxz297** [comment]
#586 is a use reported issue on this topic.

**Comment by n738cu** [comment]
@mxz297 and @hainest : What's the status here?

**Comment by mxz297** [comment]
@n738cu 
> 1. A few interface checks whether a binary is a shared library. Such check will wrongly return that PIEs are shared libraries. The boundary between shared library and PIE is indeed blur. We need to come up with a reliable way to distinguish PIE from shared libraries.

Sasha @sashanicolas has some code for this, I believe they are merged.

> 2. Static PIE was not legal until recently. To generate static PIE, flag "-static-pie" should be used rather than two flags "-static" and "-fie". Dyninst currently cannot correctly identify static PIE as static binary. Static pie contains necessary dynamic information for relocation, so Dyninst treats static PIE as dynamically linked. This will be the first step towards correctly instrumenting static PIE.

We did not do work on this aspect.

**Comment by hainest** [comment]
`isSharedLib` currently gets confused between executable shared objects and position-independent executables. The proposal is to replace `isSharedLib` with something like `is_external` which will reply "true" if the requested function is located in an binary object external to the current context. There are several definitions of `isSharedLib` throughout the codebase, so we need to make certain they all exhibit the same behavior.

`BPatch_function::isSharedLib`
`BPatch_module::isSharedLib`
`mapped_object::isSharedLib`
`int_library::isSharedLib()`
`Library::isSharedLib()`

This was previously #679.

**Comment by woodard** [comment]
in recent versions of elfutils there is a program called eu-elfclassify it captures some nuance in a practical way that maps well into how we as users tend to think of ELF as opposed to how ELF actually works. Inside of dyninst, it may be better to express characteristics of particular ELF files as opposed to having concepts that are more how humans tend to think of programs rather than being characteristics of ELF itself. 

For example (not too carefully thought through examples):
isPositionIndependent
isExecutable - i.e. does it have a main
hasDebuginfo
hasText

or something like that vs. isSharedLib

**Comment by n738cu** [comment]
Right.  We'll look at this in detail soon.

Remember that this can't be ELF-specific, as we have to provide
abstractions that work on other platforms including Windows.

--bart

**Comment by hainest** [comment]
There was a recent [article](https://www.ret2rop.com/2020/05/canary-pie-byte-bruteforce.html) about defeating Linux fortifications like ASLR which requires detecting PIE. They were doing that using the [checksec](https://www.trapkit.de/tools/checksec.sh) script which just does some very simple parsing of readelf's output. I did a quick test using gcc-4.4, gcc-9.1, clang-3.9, and clang-10 and it worked on all of them. We'll need to translate it to elfutils interface calls, but it's a good jumping-off point.

In searching for the source of checksec, I also ran across a Windows version, [winchecksec](https://github.com/trailofbits/winchecksec) that uses [pe-parse](https://github.com/trailofbits/pe-parse) to do its magic.

**Comment by hainest** [comment]
Code places to check:

    BPatch_function::isSharedLib
    BPatch_module::isSharedLib
    mapped_object::isSharedLib
    int_library::isSharedLib()
    Library::isSharedLib()
    image::isSharedObject()
    image::isSharedObj()
    image::isShared()
    pdmodule::isShared()
    Module::isShared()

    # not sure if these two have same meaning as "Shared library"
    parse_block::isShared()
    PatchBlock::isShared()


    # related calculations
    Object::Object (for at least Object-elf.C)
    image::determineImageType()
    Symtab::isExec()
    image.C:492  // The entirety of image::findMain is suspicious...
    image.C:1515

**Comment by hainest** [comment]
@kupsch We should also make sure the memory tests can be re-enabled once we get this working (see https://github.com/dyninst/testsuite/issues/40).
