### ISSUE TITLE
When using parseAPI, the file you read may need to be compiled without "-g"

### ISSUE THREAD

**Issue by lzhfromustc** [dyninst/dyninst#606]
I learnt from the examples in "ParseAPI Programmer's Guide" and wrote my simple program that could count the number of loops in a given program. 
However, when I tried to run my program on a mysql program (/install/libexec/mysqld), the following error jumped out:
`Now abort() in libdwarf. No error argument or handler available.
Aborted`
Now I find out that whenever I want to run this program on a program compiled with gcc "-g" parameter, this error will show up. The fix is to remove "-g" parameter, e.g., during mysql `./configure`, you may want to use parameter `--with-debug=no`

**Comment by lzhfromustc** [comment]
Besides, the error is caused by `sts = new SymtabCodeSource(binaryPath);` at line 40 of the first example in "ParseAPI Programmer's Guide".

**Comment by mxz297** [comment]
@lzhfromustc Based on the error message that libdwarf is mentioned, I guess you are using Dyninst 9.3.2 or even an earlier version of Dyninst. These versions are at least 2 to 3 years old. I would recommend that you upgrade to Dyninst 10.1 and re-compile your code.

**Comment by lzhfromustc** [comment]
@mxz297 Sorry I missed this message because I temporarily changed my research project. I was using Dyninst 10.1.0 (2019-05-15) and a quite new libdwarf (2019-05-05). Maybe some other dependencies caused this problem since I was running it on a relatively old server.
I am not able to repeat this now because I am out for another project. However, I may go back for this two months later. Feel free to close this issue if you want.
For those who use parseAPI and faced with the similar issue (and using an old server): try to compile your program without "-g"
