### ISSUE TITLE
Memory Leak with DYNINST_DEBUG_DISASS enabled

### ISSUE THREAD

**Issue by mothran** [dyninst/dyninst#611]
When running tooling to instrument a binary with the BPatch API, if the DYNINST_DEBUG_DISASS=1 env var is enabled a memory causes the program to OOM while printing instructions on large binaries.

Dyninst version:
fdc4d6a2a82726f1c2d71cac47ae66c204f9c1ea

cmake command:
cmake -DBUILD_RTLIB_32=ON -DCMAKE_INSTALL_PREFIX=/usr/dyninst ../..

System:
ubuntu 18.04
gcc:
Ubuntu 7.4.0-1ubuntu1~18.04

Reference repo:
https://github.com/mothran/dyninst-bb-patch

Dependencies:
```bash
gcc
```

build sets (in reference repo):
```bash
export DYNINST_ROOT=/usr/dyninst/
export LD_LIBRARY_PATH=${DYNINST_ROOT}/lib
export DYNINSTAPI_RT_LIB=${LD_LIBRARY_PATH}/libdyninstAPI_RT.so
make
```

Triggering the memory leak, I am using cc1 provided by gcc but any large binary should work:

```bash
DYNINST_DEBUG_DISASS=1 ./patcher /usr/lib/gcc/x86_64-linux-gnu/7/cc1 ./cc1 >& /dev/null
```

Watching memory usage with top/htop, it appears to grow and grow until the OOM killer is triggered.

**Comment by mxz297** [comment]
We are aware that Dyninst uses more memory than we hope.  How much memory is on your machine and how large is binary?

**Comment by mothran** [comment]
The cc1 binary is 22MB and the system has 16GB of memory.

Running the 'patcher' utility without the DYNINST_DEBUG_DISASS=1 does not OOM.  The issue is specifically when turning on 'DYNINST_DEBUG_DISASS=1', will it OOM and be killed.

It seems there is a memory leak somewhere in the code that is enabled by DYNINST_DEBUG_DISASS
