### ISSUE TITLE
dyninst.org points to older news about Dyninst version 9.3.2

### ISSUE THREAD

**Issue by rashawnLK** [dyninst/dyninst#616]
In the descriptive paragraph of Dyninst at dyninst.org, it would be helpful to mention the github repository there. The news section to the right has not been updated recently. There seems to be many pointers to Dyninst 9.x on the website which I think may cause a degree of confusion and mislead folks to acquiring up to date information or the current release.

**Comment by rchyena** [comment]
I will update the website tonight and close this issue when complete.

**Comment by rchyena** [comment]
Website is now up to date.  Thanks for the report, Rashawn!
