### ISSUE TITLE
Deprecate/remove BG/Q support

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#617]
Seqouia: No longer receiving updates.
Mira: HPCToolkit uses Dyninst (9.3.2) on BG/Q
JUQUEEN: Powered off May, 2018

**Comment by mwkrentel** [comment]
Actually, hpctoolkit has two methods for installing on Blue Gene.
The simple method uses the existing GCC 4.4 compilers and Dyninst
9.3.2.

The advanced method involves building GCC 4.8 (via spack) and then
using Dyninst 10.x.  As of today (late June 2019), this method still
works, although it requires several extra steps.

When I visited Argonne in early May 2019, I installed the advanced
method with Dyninst 10.0.0 on mira and vesta.

http://hpctoolkit.org/software-instructions.html#Blue-Gene

**Comment by hainest** [comment]
>GCC 4.4

I've not tested it, but will Dyninst compile on gcc-4.4? That's super old, and only supports -std=c++0x which is an incomplete implementation of the standard.

>The advanced method involves building GCC 4.8 (via spack) and then using Dyninst 10.x.

I want to double-check this because John mentioned that HPCToolkit froze Dyninst at 9.3.2 for BGQ. Is HPCToolkit officially supporting building with Dyninst 10.1 on BGQ?

**Comment by bwelton** [comment]
What was not mentioned on the call but should be brought up. 

If we are planning on adding a "deprecated" warning in the next release (10.X), we will have to leave BGQ specific code in place until that release takes place. This may change the approach to the elf work @sashanicolas is performing if his patch is needed in the release with BGQ support still around. We cant just ignore BGQ's corner cases (which seemed to be the working assumption) if this patch is included in the last BGQ release.

**Comment by mwkrentel** [comment]
> I've not tested it, but will Dyninst compile on gcc-4.4? 

Dyninst 10.x no, but 9.3.2 does.

> Is HPCToolkit officially supporting building with Dyninst 10.1 on BGQ?

With our old hpctoolkit-externals (to build our prereqs), we tagged a
snapshot for Blue Gene that used Dyninst 9.3.2 and built with gcc 4.4.

Now that we use spack, we can support Dyninst 10.x on Blue Gene, but
it's on life suppport.  And it requires building the 4.8 compiler.

**Comment by hainest** [comment]
@bwelton Sasha's work is precisely why I want to deprecate now, so that we don't have to continue to expend energy on a platform that we don't need to actively support anymore. The question is whether we can kick out a point release that deprecates BGQ support _before_ @sashanicolas's work goes into mainline. I was hoping @jmellorcrummey or @n738cu could give feedback on that idea.
