### ISSUE TITLE
Test suite does not dynamically adjust test lists based on build environment

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/dyninst#62]
pc_tls is our prototypical example here. The problem, in short:
- We have a 32-bit build environment present
- We have thread_db present
- We lack a 32-bit thread_db

pc_tls expects that if thread_db is present, it may run, and that it may run in all valid run modes for the test/system statically. We don't want to say that thread_db is intrinsically required for all 32-bit tests, nor do we want to say that pc_tls never should run in 32-bit mode, but we do want to skip it in any mode where it can't possibly pass.

**Comment by jdetter** [comment]
These are the only tests failing on Ubuntu 16.04, can these be ignored due to this issue?
```
pc_tls                     g++    none 64  create   SPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  create   MPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  create   SPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  create   MPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  attach   SPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  attach   MPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  attach   SPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     g++    none 64  attach   MPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  create   SPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  create   MPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  create   SPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  create   MPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  attach   SPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  attach   MPST    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  attach   SPMT    static  nonPIC  FAILED (Group Teardown)
pc_tls                     gcc    none 64  attach   MPMT    static  nonPIC  FAILED (Group Teardown)

```

**Comment by wrwilliams** [comment]
Is there no static libthread_db.a on the system? If so, then yes.

A -verbose -log run should show all threads with the same TLS value as the first one, rather than an increasing series, if this is indeed what's wrong. Otherwise it needs investigation.

**Comment by jdetter** [comment]
@wrwilliams Should this instead be an issue in the testsuite repository?

**Comment by pefoley2** [comment]
If https://github.com/dyninst/dyninst/pull/28 gets merged, then I'd assume it should go on this repo.

**Comment by jdetter** [comment]
@pefoley2 Ok sounds good.
