### ISSUE TITLE
Symtab::getContainingInlinedFunction() is generating non-deterministic results

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#629]
@mwkrentel has reported non-deterministic results where sometimes an instruction is reported as inlined, but sometimes that instruction is not. I believe the root cause of this issue is in `Symtab::getContainingInlinedFunction()`. 

First of all, I agree with the comments at https://github.com/dyninst/dyninst/blob/7e6b7685bef61ca5465e3f17a5e6b014eb4a29b4/symtabAPI/src/Symtab-lookup.C#L900

stating that the goal of this function is to find the most inlined function given an offset. I thought this function should iterate over all found function ranges and identify the range that is closet to the input offset. 

However, the implementation of this function seems to be doing something else. @mplegendre You wrote this code 7 years ago, so it is likely that you forgot the rationals behind this code. It would be nice if you can take a look at at the implementation of this loop and see:

https://github.com/dyninst/dyninst/blob/7e6b7685bef61ca5465e3f17a5e6b014eb4a29b4/symtabAPI/src/Symtab-lookup.C#L902

The non-deterministic results are caused by `Symtab::getContainingInlinedFunction()` sometimes returning the most inlined function, while sometimes returning the least inlined function...

Of course, `Symtab::getContainingInlinedFunction()` returning non-deterministic results means the range lookup returns function ranges non-deterministically. But I believe the root cause of this issue is that the algorithm in  `Symtab::getContainingInlinedFunction()`  for finding most inlined function is problematic.

**Comment by n738cu** [comment]
@mxz297 and @mwkrentel : Did this get resolved?

**Comment by mxz297** [comment]
@n738cu  No, I couldn't identify the root cause of this problem.

**Comment by hainest** [comment]
@mxz297 Do we have an example that can reproduce this?

**Comment by mxz297** [comment]
#686 contains steps for reproducing this problem.
