### ISSUE TITLE
ppcle detach removes snippets

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#634]
The Red Hat release process has a smoke test which essentially does:
insertSnippet
continueExecution
detach
This works fine on x8664 and aarch64 but not on a ppcle box (POWER8 kernel-4.1 8.0-112.el8 glibc-2.28-66.el8)
On ppcle there is no instrumented call to incr; the call to detach removes the instrumented call. If you add a waitForStatusChange before detach (or simply just sleep) then ppcle hits the snippet call to incr just fine.

Here is the example run:

./mutatee -v 10 & LD_LIBRARY_PATH=/usr/lib64/dyninst DYNINSTAPI_RT_LIB=/usr/lib64/dyninst/libdyninstAPI_RT.so ./mutator $!
[1] 106821
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
MUTATION DONE. MUTATOR IS GOING...
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 0

(adjust DYNINST in Makefile, make all ; make test)

[smoke-test.zip](https://github.com/dyninst/dyninst/files/3506845/smoke-test.zip)

**Comment by mxz297** [comment]
@stanfordcox I am really sorry that I have not got this issue. I will definitely start to debug this problem today. Thanks for reminding me.

**Comment by stanfordcox** [comment]
@mxz297 Ah, I'm just catching up after 3 week vacation in Hawaii.

**Comment by mxz297** [comment]
@stanfordcox Below is a run with the Dyninst master branch on the power vm (rh-power-vm07.fit.vutbr.cz). It seems like the instrumentation runs fine without waitForStatusChange. I only changed the makefile in smoke-test.zip.

```
[xmeng@rh-power-vm07 issue634]$ ./mutatee -v 10 & ./mutator $!
[1] 31521
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 1
MUTATION DONE. MUTATOR IS GOING...
[xmeng@rh-power-vm07 issue634]$ FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1
FUNCTION EXECUTED. VALUE = 1

[1]+  Done                    ./mutatee -v 10
```

**Comment by stanfordcox** [comment]
@mxz297 
mutator.cpp adds a call to incr(), which increments a, to function_name(), which is called n times.  So on x8664 and aarch64 I see:

% ./mutatee -v 10 & LD_LIBRARY_PATH=/usr/lib64/dyninst DYNINSTAPI_RT_LIB=/usr/lib64/dyninst/libdyninstAPI_RT.so ./mutator $!
[1] 7187
FUNCTION EXECUTED. VALUE = 0
FUNCTION EXECUTED. VALUE = 1
MUTATION DONE. MUTATOR IS GOING...
/work/scox/dyn/smoke-test/dynamic
FUNCTION EXECUTED. VALUE = 2
FUNCTION EXECUTED. VALUE = 3
FUNCTION EXECUTED. VALUE = 4
FUNCTION EXECUTED. VALUE = 5
FUNCTION EXECUTED. VALUE = 6
FUNCTION EXECUTED. VALUE = 7
FUNCTION EXECUTED. VALUE = 8
FUNCTION EXECUTED. VALUE = 9

**Comment by mxz297** [comment]
I see. Thanks! I will start to debug this issue.

**Comment by mxz297** [comment]
Copied from the mailing list:

It turns out that in this case, a trap springboard is used to transfer program execution from original code to instrumentation. In dynamic instrumentation, all trap instructions generated by Dyninst are also considered as software break points by Dyninst, and Dyninst decides to remove all software break points when it detaches from the mutatee.

I am not sure how many and when software break points are used in Dyninst, but a springboard trap does not serve the purpose as a software break point and should not be removed during detaching. 

So, my plan is to simply generate a trap instruction when a trap springboard is needed, without registering this trap as a software break point.
