### ISSUE TITLE
Dyninst::BPatch_function 's function bool isSharedLib() always return true

### ISSUE THREAD

**Issue by AmyZhang9** [dyninst/dyninst#640]
when i used the function: bool isSharedLib() from Dyninst::BPatch_function , the Dynisnt manual says This function returns true if the function is defined in a shared library. but the return true for every function, even for main function. So is this any wrong with this function?
 I used it in Ubuntu 18.04 with Dyninst 9.3.1

**Comment by hainest** [comment]
Dyninst 9.3.1 isn't really supported anymore since there have been so many changes since then. We recommend upgrading to the most recent version (10.1). Please let us know if the problem persists after upgrading.

**Comment by mxz297** [comment]
Closed via #605

**Comment by AmyZhang9** [comment]
the problem is solved in  the most recent version (10.1), thanks.

**Comment by AmyZhang9** [comment]
This problem arises because in compilation **gcc**  uses the default **pie** parameter, so generates the dynamic library instead of the ELF. When compiling file for instrumentation with gcc,  explicitly specifing the **-no-pie** parameter will not cause the same problem。thanks for all the help.
