### ISSUE TITLE
fetching local variables from a .debug file causes crashes in dyninst

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#646]
The easiest but not most minimal way to reproduce this is:
git clone https://github.com/woodard/dwqual.git
make it
then run on some debuginfo file for example one from binutils-debuginfo-2.31.1-29.fc30.x86_64
./whichvars.O2 /usr/lib/debug/usr/lib64/libbfd-2.31.1-29.fc30.so-2.31.1-29.fc30.x86_64.debug

this leads to a backtrace like:

#0  tbb::internal::concurrent_vector_base_v3::internal_push_back (this=this@entry=0x50, element_size=element_size@entry=40, ind\
ex=@0x7fffffffc788: 10452480) at ../../src/tbb/concurrent_vector.cpp:420
#1  0x00007ffff7ee94f3 in tbb::concurrent_vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::alloca\
tor<char> >, int>, tbb::cache_aligned_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocat\
or<char> >, int> > >::push_back_helper::push_back_helper (vector=..., this=0x7fffffffc780) at /usr/include/tbb/tbb_stddef.h:340
#2  tbb::concurrent_vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int>, tbb\
::cache_aligned_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > >::\
push_back (item=..., this=0x48) at /usr/include/tbb/concurrent_vector.h:844
#3  Dyninst::SymtabAPI::typeEnum::addConstant (this=0x0, constName="BFD_RELOC_AARCH64_TLSLE_LDST64_TPREL_LO12_NC", value=2009) \
at /usr/src/debug/dyninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/Type.C:356
#4  0x00007ffff7f56c63 in Dyninst::SymtabAPI::DwarfWalker::parseEnumEntry (this=this@entry=0x7fffffffcdd0) at /usr/src/debug/dy\
ninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.h:277
#5  0x00007ffff7f5ce4b in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffcdd0, e=..., p=false) at /usr/src/debug/dy\
ninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:426
#6  0x00007ffff7f5e197 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffcdd0, func_type=<optimized out>) at \
/usr/src/debug/dyninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.h:127
#7  0x00007ffff7f5ceff in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffcdd0, e=..., p=true) at /usr/src/debug/dyn\
inst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:385
#8  0x00007ffff7f5d070 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffcdd0, e=..., p=true) at /usr/src/debug/dyn\
inst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:477
#9  0x00007ffff7f5d070 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffcdd0, e=..., p=true) at /usr/src/debug/dyn\
inst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:477
#10 0x00007ffff7f5d404 in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffffcdd0, moduleDIE=..., fixUnknownMod=@0x7f\
ffffffcd80: 0x73fbf0) at /usr/src/debug/dyninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:280
#11 0x00007ffff7f5d87e in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7fffffffcfe0) at /usr/src/debug/dyninst-10.0.0-7.fc30.\
x86_64/dyninst-10.0.0/symtabAPI/src/dwarfWalker.C:187
#12 0x00007ffff7f0a798 in Dyninst::SymtabAPI::Object::parseTypeInfo() () at /usr/src/debug/dyninst-10.0.0-7.fc30.x86_64/dyninst\
-10.0.0/symtabAPI/src/Object-elf.C:4515
#13 0x00007ffff7eab3b7 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x446220) at /usr/src/debug/dyninst-10.0.0-7.fc30.x86_64\
/dyninst-10.0.0/symtabAPI/src/Symtab.C:2358
#14 0x00007ffff7e9eb6e in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x465900, params_=std::vector of length 0, capacity\
 0) at /usr/src/debug/dyninst-10.0.0-7.fc30.x86_64/dyninst-10.0.0/symtabAPI/src/Function.C:122
#15 0x0000000000403860 in main (argc=<optimized out>, argv=<optimized out>) at whichvars.C:74

----

The code up to this point is:
  Symtab *obj = NULL;
  // Parse the object file                                                                                                      
  bool err = Symtab::openFile(obj, file);
  if (!obj->getAllFunctions(funcs))
    exit(EXIT_NOFUNCS);
  for( auto i: funcs) {
    vector <localVar *> lvars;
    i->getParams(lvars);
}

So there is something that dyninst doesn't like about split debuginfo.

**Comment by mxz297** [comment]
@woodard Are you using the latest Dyninst? You stack trace says that Dyninst-10.0.0.

**Comment by hainest** [comment]
@sashanicolas I'm fairly certain this is the same issue that you are fixing now, but I want to make sure we include it in our testing.

**Comment by woodard** [comment]
Verified that this is fixed by sasha's latest sasha/dwarf-redhat-issues as of 121f55075d5a5cfe86b0a8d882e4988b293ec3c3. 

Feel free to close this when that is merged into the trunk.
