### ISSUE TITLE
Segfault during PIE rewriting

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#65]
Submitted via the dyninstapi mailling list:

In the latest version of Dyninst, rewriting a PIE binary (not a library) results in an executable that immediately segfaults. This happens even if no instrumentation was done at all. Simply opening the binary and saving it reproduces the problem. Here's a sample backtrace: 

dl_main at rtld.c:172
_dl_sysdep_start at ../elf/dl-sysdep.c:249
_dl_start_final at rtld.c:332
dl_start at rtld.c:558
_start() from /lib64/ld-linux-x86_64.so.2

I am having this issue on both Ubuntu 14.04 and Ubuntu 16, the x86_64 versions.

**Comment by wrwilliams** [comment]
Should be fixed as of d737198ad43248ce1db452190f758acb6de9a4c7, but reopen if it's not.
