### ISSUE TITLE
localVar::getLocationLists always returns empty on Power8

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#669]
I've been experiencing [crashes](https://bottle.cs.wisc.edu/results/CRASHED/144) and [failures](https://bottle.cs.wisc.edu/results/FAILED/144) on Power8 (ray.llnl.gov) consistently and independent of which commit of Dyninst or the test suite I use. Debugging shows the common error is that [`localVar::getLocationLists`](https://github.com/dyninst/dyninst/blob/master/symtabAPI/src/Variable.C#L386) always returns an empty list.

This is not a problem on [x86](https://bottle.cs.wisc.edu/commit/b7c9eee605e6067bd4744f38c96527134c01a9a7) (I can't get Zeroah to run right now, so not sure about ARM).

@mxz297 Do you have any thoughts?

**Comment by mxz297** [comment]
`getLocationLists` should get variables from DWARF. This seems like a DWARF parsing problem. Is ray.llnl.gov a big endian or a little endian power 8?

**Comment by hainest** [comment]
It's little endian, ppcle64. My P9 machine is back up today, so I'm going to try it there. I'll let you know what happens.

**Comment by hainest** [comment]
Rebuilding elfutils-0.176 from source on ray got rid of the issue. I will continue to test, but it appears to be fixed.

**Comment by hainest** [comment]
After many builds/runs on Power8 and Power9, I've not seen this again. Closing.
