### ISSUE TITLE
CodeCoverage example not working

### ISSUE THREAD

**Issue by Roinard** [dyninst/dyninst#672]
I am a new user of DyninstAPI and I wanted to test the example provided with the source code. I compiled and installed Dyninst in /usr/local and run CodeCoverage with the given example and got :
`
$ codeCoverage -sb testcc test2

Instrumenting module: libInst.C
Inserting instrumention at function entry of initCoverage
Instrumenting Basic Block 0xf50 of initCoverage
Instrumenting Basic Block 0xf92 of initCoverage
Instrumenting Basic Block 0xf94 of initCoverage
Instrumenting Basic Block 0xfa1 of initCoverage
Instrumenting Basic Block 0xfb8 of initCoverage
Instrumenting Basic Block 0xfc5 of initCoverage
Instrumenting Basic Block 0xfca of initCoverage
Instrumenting Basic Block 0xfd6 of initCoverage
Instrumenting Basic Block 0xfdb of initCoverage
Instrumenting Basic Block 0xfe4 of initCoverage
Instrumenting Basic Block 0xfea of initCoverage
Instrumenting Basic Block 0xff1 of initCoverage
Instrumenting Basic Block 0x1023 of initCoverage
Instrumenting Basic Block 0x1025 of initCoverage
Instrumenting Basic Block 0x1035 of initCoverage
Instrumenting Basic Block 0x1070 of initCoverage
Instrumenting Basic Block 0x107d of initCoverage
Instrumenting Basic Block 0x1082 of initCoverage
//210000 lines of Instrumenting logs
Instrumenting Basic Block 0x1382f8 of getprotobyname
Instrumenting Basic Block 0x1382fa of getprotobyname
Instrumenting Basic Block 0x138302 of getprotobyname
Instrumenting Basic Block 0x138315 of getprotobyname
Instrumenting Basic Block 0x13831c of getprotobyname
Instrumenting Basic Block 0x138330 of getprotobyname
Instrumenting Basic Block 0x138340 of getprotobyname
Instrumenting Basic Block 0x13834a of getprotobyname
Instrumenting Basic Block 0x138350 of getprotobyname
Instrumenting Basic Block 0x13836a of getprotobyname
Instrumenting Basic Block 0x13837d of getprotobyname
Instrumenting Basic Block 0x138382 of getprotobyname`
(I enclose the full ouput in output.txt)

And when I run 
`./test2`
I got no output.

From what I see, I think there may be a problem with initSkipLibraries() because libInst.C is instrumented and for one reason or another, all modules are considered shared, so initCoverage and exitCoverage are not inserted anywhere.

[output.txt](https://github.com/dyninst/dyninst/files/3761391/output.txt)

**Comment by hainest** [comment]
Which version of Dyninst are you using?
What compiler and version are you using?
Which version of libc are you using (if on linux, run `ldd --version` for this)?

**Comment by Roinard** [comment]
I use Dyninst10.1.0 provided by the siteweb.
To compile codeCoverage I use this Makefile : 

```
#DYNINST_INCLUDE and DYNINST_LIB should be set to locations
 #where Dyninst header and library files were installed, respectively
CC = gcc
DYNINST_INCLUDE= /usr/local/include
DYNINST_LIB = /usr/local/lib
CXX = g++
CXXFLAGS = -g -Wall
LIBFLAGS = -fpic -shared
CFLAGS = -Wall -pedantic -g -std=gnu99
LD_LIBRARY_PATH = ./
all: codeCoverage libInst.so testcc

codeCoverage.o: codeCoverage.cpp
	$(CXX) -c -o codeCoverage.o -I$(DYNINST_INCLUDE) codeCoverage.cpp -shared

codeCoverage: codeCoverage.o
	$(CXX) codeCoverage.o -L$(DYNINST_LIB) -ldyninstAPI -o codeCoverage  -lboost_system

libInst.so: libInst.C
	$(CXX) $(CXXFLAGS) $(LIBFLAGS) libInst.C -o libInst.so

libtestcc.so: libtestcc.c libtestcc.h
	$(CC) $(CFLAGS) $(LIBFLAGS) -o libtestcc.so libtestcc.c

testcc: libtestcc.so testcc.c
	$(CC) $(CFLAGS) -o testcc testcc.c ./libtestcc.so

clean:
	rm codeCoverage testcc *.o *.so -f

```
As compiler I use : 
` gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
` g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
And my glibc version is : ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

Thank you in advance for your help.

**Comment by Roinard** [comment]
And here is my compiler configuration : 
```
   Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
```

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
```

**Comment by mxz297** [comment]
Your compiler is configured with `--enable-default-pie`. This is a known issue #605 . Before we get it fixed, you can work around this issue by adding `-no-pie` to the `testcc` compilation command line.

**Comment by Roinard** [comment]
Thanks for your help !
