### ISSUE TITLE
error while loading shared libraries: unexpected reloc type oxb2

### ISSUE THREAD

**Issue by AmyZhang9** [dyninst/dyninst#673]
I used dyninst10.1.0 for static instrumentation, all i did is instrument a printf function in the entry point of the function main(). The binary rewrite file was successfully obtained, named test-re. but when i execute it ,  
./ test-re
error while loading shared libraries: unexpected reloc type oxb2

nomarly, error like that will show the shared libraries'name,like :
"error while loading shared libraries: **libxxxxx.so** unexpected reloc type xxx. "
The question I was faced with didn't  mention the shared library's name. so i don't know how solve it. any help whill be apperieciate!

**Comment by sashanicolas** [comment]
Interesting, I couldn't even find where that kind of message could be in the code base.
Can you share your binary and/or test code?
What platform are you doing this?
Does dynamic instrumentation work?

**Comment by AmyZhang9** [comment]
i use dyninst10.1.0 in Ubuntu 16.04.6 LTS. the intrumentation code test.cpp is below 
------------------------------------------------------------------------------------------------------------------------------
//test.cpp : static instrumentation
#include <stdio.h>
#include "BPatch.h"
#include "BPatch_addressSpace.h"
#include "BPatch_process.h"
#include "BPatch_binaryEdit.h"
#include "BPatch_point.h"
#include "BPatch_function.h"
#include "BPatch_flowGraph.h"
#include "BPatch_basicBlock.h"


#include <vector>
#include <cstring>
#include "string.h"

using namespace std;
using namespace Dyninst;

// Create an instance of class BPatch
BPatch bpatch;

// Different ways to perform instrumentation
typedef enum {
	create,
	attach,
	open
} accessType_t;

// Attach, create, or open a file for rewriting
BPatch_addressSpace* startInstrumenting(accessType_t accessType, const char* name,int pid,const char* argv[]) {
	BPatch_addressSpace* handle = NULL;
	switch(accessType) {
		case create:
			handle = bpatch.processCreate(name, argv);
			if (!handle) { printf("processCreate failed\n"); }
			break;
		case attach:
			handle = bpatch.processAttach(name, pid);
			if (!handle) { printf("processAttach failed\n"); }
			break;
		case open:
		// Open the binary file and all dependencies
			handle = bpatch.openBinary(name, true);
			if (!handle) { printf("openBinary failed\n"); }
			break;
	}
	return handle;
}

void finishInstrumenting(BPatch_addressSpace* app, const char* newName)
{
	BPatch_process* appProc = dynamic_cast<BPatch_process*>(app);
	BPatch_binaryEdit* appBin = dynamic_cast<BPatch_binaryEdit*>(app);
	if (appProc) {
		if (!appProc->continueExecution()) {
			printf("continueExecution failed\n");
		}
		while (!appProc->isTerminated()) {
			bpatch.waitForStatusChange();
		}
	} else if (appBin) {
		if (!appBin->writeFile(newName)) {
			printf("writeFile failed\n");
		}
	}
}


// Find a point at function "name"
std::vector<BPatch_point*>* findPoint(BPatch_addressSpace* app,const char* name,BPatch_procedureLocation loc) {
	std::vector<BPatch_function*> functions;
	std::vector<BPatch_point*>* points;
	// Scan for functions named "name"
	BPatch_image* appImage = app->getImage();
	appImage->findFunction(name, functions);
	if (functions.size() == 0) {
		printf("No function %s\n", name);
		return points;
	} else if (functions.size() > 1) {
		printf("More than one %s; using the first one\n", name);
	}
	// Locate the relevant points
	points = functions[0]->findPoint(loc);
	if(points == NULL){
		printf("no point for function %s\n",name);
	}	
	return points;
}

//myFindFuntion find function named "name" 
void myFindFuntion(BPatch_addressSpace* app, const char *name, std::vector<BPatch_function*> &funcs){
	BPatch_image * appImage = app->getImage();
	appImage->findFunction(name, funcs);
	if (funcs.size() == 0) {
    	printf("error:Could not find function %s\n",name);
	}else{
        printf("find %s\n",name);
        printf("the function's name is %s\n",funcs[0]->getName().c_str());
	}
}


//createAndInsertSnippet instrument a printf in the entry point of main
bool createAndInsertSnippet(BPatch_addressSpace* app){   
   BPatch_image* appImage = app->getImage();
	//Find the printf function
 	std::vector<BPatch_function*> printfFuncs;
    myFindFuntion(app, "printf", printfFuncs);
    //param for printf
    std::vector<BPatch_snippet*> printfArgs;
    BPatch_snippet* param1 = new BPatch_constExpr("for test\n");
 	printfArgs.push_back(param1);  
 	BPatch_funcCallExpr printfCall(*(printfFuncs[0]), printfArgs);
 	
	//find the entry point of main
	std::vector<BPatch_point*>* entryPoint =findPoint(app, "main", BPatch_entry);
    //instrumentation
    if (!app->insertSnippet(printfCall, *entryPoint)) {
      		printf( "insertSnippet failed\n");
      		return false;
    }
    return true;
    
}

int main(int argc, char * argv[]) {
	// Set up information about the program to be instrumented
	const char* progName = argv[1];
	int progPID = atoi(argv[2]);
	const char* progArgv[] = {argv[1],argv[3],argv[4],argv[5],argv[6],argv[7],NULL};
	accessType_t mode = open;
	// Create/attach/open a binary
	BPatch_addressSpace* app = startInstrumenting(mode, progName, progPID, progArgv);
	if (!app) {
		printf("startInstrumenting failed\n");
		exit(1);
	} else{
     	printf("startInstrumenting successful\n");
	}
	
	createAndInsertSnippet(app);
	
	//finished instrumentation
	char* progName2 = argv[1];
	strcat(progName2, "-re");
	finishInstrumenting(app, progName2);
	printf("program end\n");
      
	return 0;
}
------------------------------------------------------------------------------------------------------------------------------

# makefile 
LIBS = -L/usr/local/lib -ldyninstAPI  -lparseAPI -linstructionAPI -lsymtabAPI  -ldwarf  -lcommon -ldynElf -lboost_system
src = $(wildcard *.cpp)
tar = target

$(tar):$(src)
	g++ -std=c++0x -o $@ $^ $(LIBS)

.PRONY:
	clean
clean:
	 rm -rf *.o $(tar)

**Comment by bwelton** [comment]
@sashanicolas The error message seen by @AmyZhang9 is likely being generated by the loader itself. @AmyZhang9 does this message appear when you run "ldd" on the binary outputted by dyninst?

**Comment by AmyZhang9** [comment]
this message didn't appear when i run "ldd" on the binary outputted by dyninst.
such error only appear in one test case, the function seems fine for other testcases. so i'going to ingnore it for the moment.thanks for all the help.

**Comment by AmyZhang9** [comment]
I didn't found any regularity about the appearance of the error. so this question still hopes to be anwered.

**Comment by hainest** [comment]
@AmyZhang9

1. What arguments are you passing to your mutator?
2. What compiler and version are you using?

**Comment by AmyZhang9** [comment]
**1. What arguments are you passing to your mutator?**
the arguments i passing to my mutator is 
./myMutator  binaryname  pid
for example, test1 is the binary that i want to instrument,
./myMutator  test1 42

**2. What compiler and version are you using?**
gcc version : gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
dyninst version : dyninst10.1.0
linux version :  Ubuntu 16.04.6 LTS \n \l (32bit)

**Comment by AmyZhang9** [comment]
my whole program is in [https://github.com/AmyZhang9/static-instrumentation-error.git](url),  there is much more details about the problem i 'm faceing

**Comment by mxz297** [comment]
32bit platform is likely the cause of this issue. We don't really have the resource to test 32-bit platforms in recent years. Do you have access to a 64-bit linux machine?

**Comment by AmyZhang9** [comment]
the binary i need to instrument is 32-bit, so i using 32-bit platform. can i instrument 32-bit binary in 64-bit linux machine?

**Comment by mxz297** [comment]
In principle you can execute 32-bit binaries on 64-bit systems, but I doubt binary rewriting will work. I guess Dyninst is always generating 64-bit relocation entries that 32-bit loader cannot work with.
