### ISSUE TITLE
Some questions about edge typing

### ISSUE THREAD

**Issue by stevenagy** [dyninst/dyninst#677]
So after going through the manuals the following edge types still aren't very clear to me:

- CALL_FT
- CALL

1. I assume CALL_FT are meant to be the fallthrough edges for conditional calls; but since I'm on x86 I can safely ignore these because conditional calls aren't supported. (Right?)

2. I assume CALL encompasses both direct and indirect call edges. Is there any way to precisely distinguish between direct and indirect? I was trying to look at the opcode's and match them to the types listed here (https://www.felixcloutier.com/x86/call), but this gave me erroneous results. Does anyone have any ideas, or is this just not supported? 

Any help would be greatly appreciated!

Best wishes,
-Stefan

**Comment by mxz297** [comment]
CALL_FT represents a control flow summary edge that the control flow will return to the call site after the function call. A call to a non-returning function will not have a CALL_FT edges. I am not sure about the correlation between CALL_FT and conditional calls. I have not encountered any conditional calls recent years. In most cases, you should not ignore CALL_FT edges.

An indirect call will have a sink edge as we do not know where it goes. I think `ParseAPI::Edge::sinkEdge()` tells you whether an edge goes to sink or not. A direct call will not have any sink edge.

**Comment by stevenagy** [comment]
> CALL_FT represents a control flow summary edge that the control flow will return to the call site after the function call. 

If I'm understanding correctly, CALL_FT doesn't translate to an explicit CFG edge? Wouldn't the actual return edge from the function be encompassed by the RET edge type?

I'll take a look at the sink edge parsing. Thank you!

**Comment by mxz297** [comment]
> If I'm understanding correctly, CALL_FT doesn't translate to an explicit CFG edge? 

Yes, CALL_FT is not an actual CFG edge.

> Wouldn't the actual return edge from the function be encompassed by the RET edge type?

There are RET edge from return blocks to their direct call sites.

**Comment by stevenagy** [comment]
Got it, thank you!

Something isn't making sense to me about sink edges. My end goal is to identify critical edges in the CFG; an edge can only be critical if its source block has 2 or more outgoing edges, and its target block has 2 or more incoming edges. So by definition this is limited to conditional jumps, or any indirect edge. 

After separating direct/indirect call edges based on sinkEdge()'s output, what I'm seeing is that direct call edges are being classified as critical. This doesn't make any sense. Any ideas?

**Comment by mxz297** [comment]
Well... Based on your definition, for a direct call edge, its source block can have two outgoing edges, the CALL and the CALL_FT edge; its target block can have multiple incoming CALL edges, meaning the callee can be called by at multiple call sites.

You are getting what you defined. Whether this is what your want or not is under your discretion.

**Comment by stevenagy** [comment]
I think I see where I went wrong - I should have excluded CALL_FT edges because they aren't actual CFG edges. Thank you!

**Comment by hainest** [comment]
Solved issue; closing.
