### ISSUE TITLE
Still not able to build dyninst statically. So sad :(

### ISSUE THREAD

**Issue by expnkx** [dyninst/dyninst#685]
g++ -o dyn dyn.cc -Ofast -std=c++2a -s -ldyninstAPI_static -static -ldynElf_static -lpatchAPI_static -linstructionAPI_static -ltbbmalloc_static -ltbbmalloc_proxy_static -lpthread -ldl -lcommon_static -ldynC_API_static -ldynDwarf_static -lparseAPI_static -lboost_filesystem -lboost_system -lsymtabAPI_static -lsymLite_static -lelf -ltbb_static

**Comment by hainest** [comment]
You have provided identically no information about what you have tried, how you built Dyninst, or what error messages you are seeing. I'm not sure how we will be able to help you.

**Comment by expnkx** [comment]
> You have provided identically no information about what you have tried, how you built Dyninst, or what error messages you are seeing. I'm not sure how we will be able to help you.

Linker error. Cannot find xxx libs error.

**Comment by hainest** [comment]
Closing due to insufficient information. If you continue to have problems, please submit a new issue with [complete information](https://github.com/dyninst/dyninst/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
