### ISSUE TITLE
How to build dyninst for android emulator??

### ISSUE THREAD

**Issue by expnkx** [dyninst/dyninst#687]
I still do not understand how to do this. Any good guidelines???

**Comment by expnkx** [comment]
I want to instrument instructions on android.

**Comment by expnkx** [comment]
I tried static linking but I failed. Can you make a video about how to do this???

**Comment by mxz297** [comment]
Android is not a supported platform.

**Comment by expnkx** [comment]
> Android is not a supported platform.

Is that possible to support this? My research is all about android.

**Comment by expnkx** [comment]
> Android is not a supported platform.


Are you Chinese?

**Comment by mxz297** [comment]
Dyninst works with native executables (applications written in C and C++). Android applications are mostly written in Java and executed by the JVM.

**Comment by expnkx** [comment]
> Dyninst works with native executables (applications written in C and C++). Android applications are mostly written in Java and executed by the JVM.

I am just working on analyzing C++ projects for android like zygote.

**Comment by expnkx** [comment]
http://harmful.cat-v.org/software/dynamic-linking/

**Comment by expnkx** [comment]
> Dyninst works with native executables (applications written in C and C++). Android applications are mostly written in Java and executed by the JVM.


Here was the last issue I put 11 days ago. Unfortunately, no one could answer my question.
https://github.com/dyninst/dyninst/issues/685

**Comment by mxz297** [comment]
Dyninst currently supports x86, Power, and ARM64, and binary rewriting for ARM64 is not complete. In terms of operating system, Dyninst works best with Linux. I have no clue how Dyninst would behave on an Andriod OS. 

Static linking of Dyninst is not a use case that we needed before. I personally have not tried to build Dyninst with static linking. 

I feel adding support for Android is going to be a significant task, probably a multi-month to a year. We currently do not have the resource to support Android. As an open source software, we welcome your contribution for your need. But honestly, I have little experience with Android, so I am unlikely to provide useful feedback.

**Comment by bwelton** [comment]
> Android emulator requires statically compiled executable. 

An emulator may be very different in terms of system structure than a native install. Getting dyninst to run on any emulator, even with a supported OS, would be challenging (if not impossible). 

As for native android, I have in the past built Dyninst on Lineage OS ARM (using the normal build process). However I performed no testing and LineageOS is not a stock Android OS (the exact system I built on has additional modifications by myself, which may/may not impact its ability to be built). As @mxz297 said, we do not support Andorid and its current functionality status is unknown (being able to be built != fully (or even partly) functional).

And to head of the inevitable question, I cannot help you build Dyninst on Lineage OS/Android. If you go down this route, you will have to get your hands dirty. My only advice is to use the absolute most recent version of the Android kernel you can (newer kernels are closer to the stock linux kernel) and install as much of the standard linux environment you can on the system (system utilities, etc).

**Comment by expnkx** [comment]
> > Android emulator requires statically compiled executable.
> 
> An emulator may be very different in terms of system structure than a native install. Getting dyninst to run on any emulator, even with a supported OS, would be challenging (if not impossible).
> 
> As for native android, I have in the past built Dyninst on Lineage OS ARM (using the normal build process). However I performed no testing and LineageOS is not a stock Android OS (the exact system I built on has additional modifications by myself, which may/may not impact its ability to be built). As @mxz297 said, we do not support Andorid and its current functionality status is unknown (being able to be built != fully (or even partly) functional).
> 
> And to head of the inevitable question, I cannot help you build Dyninst on Lineage OS/Android. If you go down this route, you will have to get your hands dirty. My only advice is to use the absolute most recent version of the Android kernel you can (newer kernels are closer to the stock linux kernel) and install as much of the standard linux environment you can on the system (system utilities, etc).

Then what about other tools like pintool?

**Comment by bwelton** [comment]
To my knowledge, pintool only supports x86(-64). I have no idea on the support they have for Android in general though. 

Android binary instrumentation/modification support is generally extremely limited. Xposed exists that allows simple interposition/interception instrumentation on Dalvik bytecode (but not native binaries written in languages like C/C++). Samsung's ADBI use to allow for standard interposition based instrumentation but its development was discontinued in 2016 (to my knowledge at least). 

As for using Dyninst, your best bet to get something on Android functional is to use an x86-64 version of Android (get an Android X86 VM) in combination with binary rewriting (to avoid the complexities of dealing with getting Dyninst process control functional on Android). If you perform binary rewriting on dynamically linked libraries, you may have a decent chance of getting this to work given that their loading process and structure is very close to standard linux (if not identical). 

Also a side note, if you are performing these tasks on commercial binaries/applications, be very aware that some of the more popular commercial binaries typically have checks to validate the execution environment they are running in has not been tampered (such as safetynet). You will likely need to build bypasses for these applications if you choose to use them (or fake an environment that will pass something like safetynet).

**Comment by expnkx** [comment]
> To my knowledge, pintool only supports x86(-64). I have no idea on the support they have for Android in general though.
> 
> Android binary instrumentation/modification support is generally extremely limited. Xposed exists that allows simple interposition/interception instrumentation on Dalvik bytecode (but not native binaries written in languages like C/C++). Samsung's ADBI use to allow for standard interposition based instrumentation but its development was discontinued in 2016 (to my knowledge at least).
> 
> As for using Dyninst, your best bet to get something on Android functional is to use an x86-64 version of Android (get an Android X86 VM) in combination with binary rewriting (to avoid the complexities of dealing with getting Dyninst process control functional on Android). If you perform binary rewriting on dynamically linked libraries, you may have a decent chance of getting this to work given that their loading process and structure is very close to standard linux (if not identical).
> 
> Also a side note, if you are performing these tasks on commercial binaries/applications, be very aware that some of the more popular commercial binaries typically have checks to validate the execution environment they are running in has not been tampered (such as safetynet). You will likely need to build bypasses for these applications if you choose to use them (or fake an environment that will pass something like safetynet).

Well. They did say they have android support before. However, I've never tried that. Can you affirm this so I could tell my professor, no it is not possible?
https://software.intel.com/sites/default/files/article/256671/pindroid-tutorial-01_1.pdf

**Comment by hainest** [comment]
Android is not a supported platform. Closing.
