### ISSUE TITLE
Segfault when calling bpatch.processCreate with DYNINST_DEBUG_STARTUP=1

### ISSUE THREAD

**Issue by nisargshah95** [dyninst/dyninst#688]
**Intention**
Run a simple mutatee with DYNINST_DEBUG_STARTUP=1

**Describe the bug**
Got a segfault during call to processCreate (complete output - [dyninst-segfault.txt](https://github.com/dyninst/dyninst/files/4017655/dyninst-segfault.txt))

This does not happen without DYNINST_DEBUG_STARTUP=1 set:
```
[nisargs@melange] (218)$ LD_LIBRARY_PATH=/nobackup/nisargs/dyninst-project/dyninst-install/lib/  ./mutator /nobackup/nisargs/simple_class _ZN11SimpleClass5printEv
Inserted snippet
Hello World
```

**To Reproduce**
Mutatee file - [simple_class.txt](https://github.com/dyninst/dyninst/files/4017665/simple_class.txt)
Compile: `g++ simple_class.cpp -o simple_class`

Mutator file - [mutator.txt](https://github.com/dyninst/dyninst/files/4017706/mutator.txt)
Compile: `g++ mutator.cpp -g -o mutator -I<DYNINST_INSTALL_PREFIX>/include/ -L<DYNINST_INSTALL_PREFIX>/lib/ -ldyninstAPI -lelf -ldw -lboost_system -std=c++11`

Execute mutator:
`LD_LIBRARY_PATH=<DYNINST_INSTALL_PREFIX>/lib/  DYNINST_DEBUG_STARTUP=1 ./mutator <mutatee binary> <function name>`

**Expected behavior**
Expected mutator to run without any failures, as observed when run without `DYNINST_DEBUG_STARTUP=1`.

**System (please complete the following information):**
System: Ubuntu 18.04.3 with Linux kernel 4.15.0-72-generic
dyninst commit: master (commit 0dffe9f69384b49858006c21667387053d3abcf2 Nov 17)
libc-bin 2.27-3ubuntu1

**Additional context**
N/A

**Comment by mxz297** [comment]
I encountered a similar problem recently. Please try the following patch:

```
diff --git a/dyninstAPI/src/unix.C b/dyninstAPI/src/unix.C
index 770d0f748..f5d96fe56 100644
--- a/dyninstAPI/src/unix.C
+++ b/dyninstAPI/src/unix.C
@@ -504,7 +504,7 @@ bool PCProcess::hasPassedMain()
         return false;
      }
    } else {
-     startup_printf("{%s:%u] - there is no .opd section. The entry offset is the entry\n");
+     startup_printf("{%s:%u] - there is no .opd section. The entry offset is the entry\n", FILE__, __LINE__);
    }
 
    if( entry_addr < ldso_start_addr ) {
```

**Comment by nisargshah95** [comment]
Thanks Xiaozhu! This fix addresses the issue.
