### ISSUE TITLE
134|generic_x86_64:/data # ./ld-linux-x86-64.so.2 --library-path /data ./bpatch  18101                                                                                                     bpatch: /home/cqwrteur/dyninst/symtabAPI/src/SymtabReader.C:175: virtual Dyninst::Offset Dyninst::SymtabAPI::SymtabReader::getSymbolOffset(const Dyninst::Symbol_t&): Assertion `sym.v2' failed. Aborted 

### ISSUE THREAD

**Issue by expnkx** [dyninst/dyninst#690]
**Intention**
Use dyninst on android

When I run dyninst

```cpp
#include"fast_io.h"
#include"fast_io_legacy.h"
#include"BPatch.h"


int main(int argc,char** argv)
try
{
	if(argc!=2)
	{
		print(fast_io::err,"Usage: ",*argv," <process id>\n");
		return 1;
	}
	BPatch bp;
	BPatch_process *appProc(bp.processAttach(nullptr,fast_io::to<int>(argv[1])));
	BPatch_addressSpace *app(appProc);
	std::vector<BPatch_point *> *points;
	BPatch_image *appImage = app->getImage();
	BPatch_Vector<BPatch_function *> vfunctions = *appImage->getProcedures(true);

	println("found functions: ",vfunctions.size());
}
catch(std::exception const& e)
{
	println(e);
	return 1;
}
```

134|generic_x86_64:/data # ./ld-linux-x86-64.so.2 --library-path /data ./bpatch  18101                                                                                                    
bpatch: /home/cqwrteur/dyninst/symtabAPI/src/SymtabReader.C:175: virtual Dyninst::Offset Dyninst::SymtabAPI::SymtabReader::getSymbolOffset(const Dyninst::Symbol_t&): Assertion `sym.v2' failed.
Aborted

**Comment by expnkx** [comment]
root         18278  2893   11724   7196 sigsuspend          0 S sh
root         18287 17314    5920   2416 0                   0 R ld-linux-x86-64+
root         18302 18278   14596   7320 0                   0 R ps
inux-x86-64.so.2 --library-path /data/ ./bpatch 18287                         <
bpatch: /home/cqwrteur/dyninst/common/src/addrtranslate-linux.C:266: Dyninst::LoadedLib* Dyninst::AddressTranslateSysV::getAOut(): Assertion `phdr_vaddr != (Address) -1' failed.
Aborted

**Comment by hainest** [comment]
As was noted [previously](https://github.com/dyninst/dyninst/issues/687#issuecomment-569735463), Dyninst does not support Android. As such, we cannot offer support for failures on that platform.

**Comment by expnkx** [comment]
"Assertion `sym.v2' failed.
Aborted"

But what does this mean?
