### ISSUE TITLE
Obtaining module name from ParseAPI

### ISSUE THREAD

**Issue by stevenagy** [dyninst/dyninst#696]
Hello all,

I'm using ParseAPI for some inter-/intra-procedural CFG analysis.

One thing I'm trying to do is blacklist shared libraries. In the BPatch API I could easily determine this via the `BPatch_module` class. How can this be done in ParseAPI? 

Thanks,
-Stefan

**Comment by mxz297** [comment]
I actually can't find an interface for getting the name of an object in ParseAPI. I guess that's probably because to ParseAPI, you need to specify which path to open, so you should know which shared libraries you are dealing with.

**Comment by stevenagy** [comment]
> you need to specify which path to open, so you should know which shared libraries you are dealing with.
I'm not sure I understand. I'm just passing in the path to some binary, similarly how I do with the BPatch API.

ParseAPI-based snippet:
```
	/* Set up Dyninst objects and verify input binary. */

	cout << "## Parsing binary: " << basename(originalBinary) << endl;
	SymtabCodeSource *appSym;
	CodeObject *appCode;
	appSym 	= new SymtabCodeSource(originalBinary);
	appCode = new CodeObject(appSym);

	if (appSym == NULL or appCode == NULL) {
		cerr << "Failed to open binary!" << endl;
		return EXIT_FAILURE;
	}

	/* Iterate through the binary's functions. */

	appCode->parse();
	const CodeObject::funclist& funcs = appCode->funcs();
```

BPatchAPI-based snippet:
```
	appBin = bpatch.openBinary(originalBinary, false);
	
	if (appBin == NULL) {
		cerr << "Failed to open binary" << endl;
		return EXIT_FAILURE;
	}

	BPatch_image *appImg = appBin->getImage();

	/* Iterate through the binary's modules. */

	vector <BPatch_module *> *mods = appImg->getModules();
```

**Comment by stevenagy** [comment]
I ended up just replacing the initial loop with the BPatch API with ParseAPI conversion. It works!
