### ISSUE TITLE
The slicing and symbolic evaluation in the dataflowAPI.pdf manual do not compile

### ISSUE THREAD

**Issue by wcohen** [dyninst/dyninst#699]
When learning to use the dataflowAPI I copied the examples from the manual in the git repository and attempted to compile them with dyninst-10.1.0-4.fc30.x86_64 on Fedora 30.  The liveness example compiled, but the slicing and symbolic evaluation examples did not.

**Describe the bug**

Copied the body of code for the examples into slice.cc and symbol_eval.cc from Slice.tex and SymEval.tex.  The compile fails with a number of errors.

**To Reproduce**

g++ -I/usr/include/dyninst -c slice.cc
slice.cc: In member function ‘virtual bool ConstantPred::endAtPoint(Dyninst::Assignment::Ptr)’:
slice.cc:15:26: error: base operand of ‘->’ has non-pointer type ‘Dyninst::InstructionAPI::Instruction’
   15 |         return ap->insn()->writesMemory();
      |                          ^~
slice.cc: In function ‘void AnalyzeJumpTarget(Dyninst::ParseAPI::Function*, Dyninst::ParseAPI::Block*)’:
slice.cc:32:34: error: invalid use of incomplete type ‘class Dyninst::ParseAPI::Block’
   32 |          (const unsigned char*) b->obj()->cs()->getPtrToInstruction(b->last());
      |                                  ^~
In file included from /usr/include/dyninst/AbslocInterface.h:39,
                 from /usr/include/dyninst/slicing.h:50,
                 from slice.cc:3:
/usr/include/dyninst/Absloc.h:58:11: note: forward declaration of ‘class Dyninst::ParseAPI::Block’
   58 |     class Block;
      |           ^~~~~
slice.cc:32:70: error: invalid use of incomplete type ‘class Dyninst::ParseAPI::Block’
   32 |          (const unsigned char*) b->obj()->cs()->getPtrToInstruction(b->last());
      |                                                                      ^~
In file included from /usr/include/dyninst/AbslocInterface.h:39,
                 from /usr/include/dyninst/slicing.h:50,
                 from slice.cc:3:
/usr/include/dyninst/Absloc.h:58:11: note: forward declaration of ‘class Dyninst::ParseAPI::Block’
   58 |     class Block;
      |           ^~~~~
slice.cc:35:8: error: invalid use of incomplete type ‘class Dyninst::ParseAPI::Block’
   35 |       b->obj()->cs()->getArch());
      |        ^~
In file included from /usr/include/dyninst/AbslocInterface.h:39,
                 from /usr/include/dyninst/slicing.h:50,
                 from slice.cc:3:
/usr/include/dyninst/Absloc.h:58:11: note: forward declaration of ‘class Dyninst::ParseAPI::Block’
   58 |     class Block;
      |           ^~~~~
slice.cc:36:39: error: conversion from ‘Dyninst::InstructionAPI::Instruction’ to non-scalar type ‘Dyninst::InstructionAPI::Instruction::Ptr’ {aka ‘boost::shared_ptr<Dyninst::InstructionAPI::Instruction>’} requested
   36 |     Instruction::Ptr insn = dec.decode();
      |                             ~~~~~~~~~~^~
slice.cc:39:32: error: no matching function for call to ‘Dyninst::AssignmentConverter::AssignmentConverter(bool)’
   39 |     AssignmentConverter ac(true);
      |                                ^
In file included from /usr/include/dyninst/slicing.h:50,
                 from slice.cc:3:
/usr/include/dyninst/AbslocInterface.h:125:18: note: candidate: ‘Dyninst::AssignmentConverter::AssignmentConverter(bool, bool)’
  125 |  DATAFLOW_EXPORT AssignmentConverter(bool cache, bool stack) : cacheEnabled_(cache), aConverter(false, stack) {};
      |                  ^~~~~~~~~~~~~~~~~~~
/usr/include/dyninst/AbslocInterface.h:125:18: note:   candidate expects 2 arguments, 1 provided
/usr/include/dyninst/AbslocInterface.h:123:7: note: candidate: ‘Dyninst::AssignmentConverter::AssignmentConverter(const Dyninst::AssignmentConverter&)’
  123 | class AssignmentConverter {
      |       ^~~~~~~~~~~~~~~~~~~
/usr/include/dyninst/AbslocInterface.h:123:7: note:   no known conversion for argument 1 from ‘bool’ to ‘const Dyninst::AssignmentConverter&’
/usr/include/dyninst/AbslocInterface.h:123:7: note: candidate: ‘Dyninst::AssignmentConverter::AssignmentConverter(Dyninst::AssignmentConverter&&)’
/usr/include/dyninst/AbslocInterface.h:123:7: note:   no known conversion for argument 1 from ‘bool’ to ‘Dyninst::AssignmentConverter&&’
slice.cc:41:23: error: invalid use of incomplete type ‘class Dyninst::ParseAPI::Block’
   41 |     ac.convert(insn, b->last(), f, b, assignments);
      |                       ^~
In file included from /usr/include/dyninst/AbslocInterface.h:39,
                 from /usr/include/dyninst/slicing.h:50,
                 from slice.cc:3:
/usr/include/dyninst/Absloc.h:58:11: note: forward declaration of ‘class Dyninst::ParseAPI::Block’
   58 |     class Block;
      |           ^~~~~

g++ -I/usr/include/dyninst -c symbol_eval.cc
symbol_eval.cc:5:39: error: expected class-name before ‘{’ token
    5 | class ConstVisitor: public ASTVisitor {
      |                                       ^
symbol_eval.cc:8:5: error: ‘Address’ does not name a type
    8 |     Address target;
      |     ^~~~~~~
symbol_eval.cc:12:13: error: ‘AST’ does not name a type; did you mean ‘AST_H’?
   12 |     virtual AST::Ptr visit(DataflowAPI::ConstantAST * ast) {
      |             ^~~
      |             AST_H
symbol_eval.cc:20:13: error: ‘AST’ does not name a type; did you mean ‘AST_H’?
   20 |     virtual AST::Ptr visit(DataflowAPI::VariableAST *) {
      |             ^~~
      |             AST_H
symbol_eval.cc:24:13: error: ‘AST’ does not name a type; did you mean ‘AST_H’?
   24 |     virtual AST::Ptr visit(DataflowAPI::RoseAST * ast) {
      |             ^~~
      |             AST_H
symbol_eval.cc: In constructor ‘ConstVisitor::ConstVisitor()’:
symbol_eval.cc:9:38: error: class ‘ConstVisitor’ does not have any field named ‘target’
    9 |     ConstVisitor() : resolved(true), target(0){}
      |                                      ^~~~~~
symbol_eval.cc: At global scope:
symbol_eval.cc:36:1: error: ‘Address’ does not name a type
   36 | Address ExpandSlice(GraphPtr slice, Assignment::Ptr pcAssign) {
      | ^~~~~~~

**Expected behavior**
I expected the code examples can  compile into .o files.

**System (please complete the following information):**
 - Fedora 30 on x86_64  dyninst-10.1.0-4.fc30.x86_64 rpm used to compile things
 - examples from commit a0afdbb7993cb046edf404d556e32b4ead2374b7

**Comment by mxz297** [comment]
@wcohen #700 contains the code changes needed to compile. Please copy the updated code from dataflowAPI/doc/Examples.tex. The PDF is not updated yet, but will be updated soon.

**Comment by mxz297** [comment]
Closed via #700
