### ISSUE TITLE
Trouble converting BPatch_module to PatchObject

### ISSUE THREAD

**Issue by stevenagy** [dyninst/dyninst#702]
Hello all,

I'm trying to convert a `BPatch_module` object to a `PatchAPI::PatchObject` using the `convert()` functionality described in the PatchAPI manual: https://www.dyninst.org/sites/default/files/manuals/dyninst/patchAPI.pdf.

I'm parsing the binary as `BPatch_module`'s and converting each to a `PatchObject`, as follows: 
```
BPatch bpatch;
BPatch_binaryEdit *appBin = bpatch.openBinary(originalBinary, false);
BPatch_image *appImg = appBin->getImage();
vector <BPatch_module *> *mods = appImg->getModules();
auto modIter = mods->begin();
for(; modIter != mods->end(); modIter++) {
	BPatch_module *bp_mod = (*modIter);
	PatchAPI::PatchObject *mod = PatchAPI::convert(bp_mod);
}
```
However, compiling this fails with a ton of errors. 

Interestingly, converting a `BPatch_basicBlock` to a `PatchBlock` works just fine: 
```
BPatch_basicBlock *bp_block;
PatchAPI::PatchBlock *block = PatchAPI::convert(bp_block);
```

Any help would be much appreciated!

**Comment by hainest** [comment]
@mxz297 or @sashanicolas Could you take a look at this?

**Comment by mxz297** [comment]
It looks like the manual is wrong. Based on code at https://github.com/dyninst/dyninst/blob/master/dyninstAPI/h/BPatch_object.h#L69, we can convert `BPatch_object` to `PatchObject` instead of `BPatch_module`.

**Comment by n738cu** [comment]
@hainest and @sashanicolas : Did the manual get updated to fix this?

**Comment by hainest** [comment]
@stevenagy Does Xiaozhu's suggested change make the example work for you?

**Comment by stevenagy** [comment]
Yes, that's what I've been using. Thank you!

**Comment by hainest** [comment]
@mxz297 I can't find anywhere in the documentation or the code that indicates that a `BPatch_module` is convertible to a `PatchObject`. They all indicate that only a `BPatch_object` is convertible to a `PatchObject` and a `BPatch_module` convertible to a `SymtabAPI::Module`. Am I missing something in the type hierarchy?

@stevenagy Could you update the example code you posted to include the fix you are using to convert a `BPatch_module` to a `PatchObject`?

**Comment by stevenagy** [comment]
From looking at my code (it's been a few months :P) it seems I abandoned PatchObject entirely and switched to a BPatch-based implementation, with some ParseAPI sprinkled in.

**Comment by hainest** [comment]
@stevenagy Ah, ok. That's what I assumed. Thanks for your help!

There is nothing to change in the documentation. Closing.
