### ISSUE TITLE
Is there a simple way to iterate over the instructions in a basic block?

### ISSUE THREAD

**Issue by wcohen** [dyninst/dyninst#713]
It seems pretty easy to iterate over function and basic blocks in a parsed binary.  However, when trying to iterate over the instructions in basic block I didn't find it so easy to iterate over the instructions.  Below is outline of the code from https://github.com/wcohen/quality_info/blob/master/dyninsttools/liveness.C.  I ended up using an Instructiondecoder to find the size of each instruction and step through the instructions.  Surely there is a more direct way to iterate through the instructions in a basic block. Any suggestions on how to more cleanly iterate through the instructions in a basic block? -Will

```
  SymtabCodeSource *sts;
  CodeObject *co;
  sts = new SymtabCodeSource( argv[1] );
  co = new CodeObject( sts );
  co->parse();
  for( auto f: co->funcs()) {
	  for (auto b = f->blocks().begin(); b != f->blocks().end(); ++b) {

        // Q: is there a nice way to iterate over the instructions in the basic block?
        // Seems like there should be an easy way to directly get an iterator from basic block instance
        //  However,  could seem to find something that worked and restored to using instruction
        // decoder to step through the instructions.
        for (auto i=???; i!=b->???(); i++) {
            }
         }
  }
```

**Comment by mxz297** [comment]
The typical way I iterate all instructions in a block is illustrated here:

https://github.com/mxz297/dyninst-tools/blob/master/CodeDump/CodeDump.cpp#L30

It is not as clean as you would hope, but should be better than constructing the decoder.

**Comment by wcohen** [comment]
The link was very helpful.  I revised my code to use the getInsns() method. Thanks.
