### ISSUE TITLE
Can't create Symtab object for PE file on linux

### ISSUE THREAD

**Issue by bin2415** [dyninst/dyninst#715]
Hi, I am trying to parse `PE` file on Ubuntu 18.04. 

Piece of my code is attached:

```c++
 auto symtab_cs = std::make_shared<ParseAPI::SymtabCodeSource>(input_file);
 CHECK(symtab_cs) << "Error during creation of ParseAPI::SymtabCodeSource!";

  auto code_obj = std::make_shared<ParseAPI::CodeObject>(symtab_cs.get());
```
 And I got this error:

```
[SymtabCodeSource.C] FATAL: can't create Symtab object for file
```
Is there a proper way to handle `PE` file on `Linux` platform?

Thanks in advance!

**Comment by mxz297** [comment]
Unfortunately we do not support cross OS analysis. So, it is not possible to handle PE files on Linux platforms.

**Comment by bin2415** [comment]
Thanks! I will try to build dyninst on windows 10.
