### ISSUE TITLE
test_reloc rewriter mode is failing on x86-64, Red Hat 7.3.1-2, with libc-2.25

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#722]

**Comment by hainest** [comment]
I re-ran current HEAD (4f6f3db) on cayenne three times using the same binaries, and found that test_reloc passed in two of them ([561](https://bottle.cs.wisc.edu/results/FAILED/56), [561](https://bottle.cs.wisc.edu/results/FAILED/561)) and failed in one ([562](https://bottle.cs.wisc.edu/results/FAILED/562)).

@mxz297 Could you try running your version on cayenne a few times to see if you can reproduce this behavior?

**Comment by mxz297** [comment]
@hainest You are right. I ran the rebased code 5 more times. They all passed.

**Comment by mxz297** [comment]
@hainest Do we still have any known `test_reloc` failures on x86-64?

**Comment by hainest** [comment]
@mxz297 Almost. I just saw a new one on [quartz](https://bottle.cs.wisc.edu/results/CRASHED/685). I'm re-running to verify.

**Comment by hainest** [comment]
I just noticed test_reloc in rewriter mode has always been failing on [Cori@NERSC](https://bottle.cs.wisc.edu/results/CRASHED/695) with the message

    ./binaries/rewritten_test_reloc.dyn_g++_64_none_none: Relink `/lib64/libdl.so.2' with `./binaries/libc.so.6' for IFUNC symbol `strcpy'
    Group teardown failed: 
    [Tests with test_reloc.dyn_g++_64_pic_none]
    -rwxr-xr-x 1 thaines thaines 80416 Apr 12 21:19 test_reloc.dyn_g++_64_pic_none*
	    linux-vdso.so.1 (0x00002aaaaaad3000)
	    libstdc++.so.6 => /opt/cray/pe/gcc-libs/libstdc++.so.6 (0x00002aaaaaedb000)
	    libm.so.6 => /lib64/libm.so.6 (0x00002aaaab264000)
	    libgcc_s.so.1 => /opt/cray/pe/gcc-libs/libgcc_s.so.1 (0x00002aaaab59c000)
	    libc.so.6 => /lib64/libc.so.6 (0x00002aaaab7b4000)
	    /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)

**Comment by mxz297** [comment]
@hainest This is the same error on mic.cs.rice.edu, which is a loader bug as Ben Woodard and I have discussed:

> 
> You might find more information here:
> https://sourceware.org/bugzilla/show_bug.cgi?id=20839 which is the upstream version of the bug. The problem is unlikely to get fixed in RHEL7 because the problem isn’t fixed upstream yet. As you can see someone just posted a patch earlier today. It hasn’t been reviewed and committed. However, this isn’t the first time that someone has posted a patch. Other attempts to fix the problem had some unacceptable side effects and were not committed. We won’t consider backporting the patch until it is accepted upstream and by the time that works through the process, we’re kind of done with RHEL7 except for critical problems.
> 
> The way that this bug manifests is when there is library which has NODELETE has been loaded but subsequently there is some kind of failure loading a library and so the whole dependency change should be unloaded. However because of the NODELETE that lib wasn’t unloaded leaving it in an incompletely relocated state. After thinking through it carefully it seems to be agreed that NODELETE shouldn’t take effect until after the full dependency chain is loaded and relocated.
> 
> I suspect that the problem that you are running into is some sort of failure and the incompletely relocated libpthread.
> 

I don't think we can do anything related to this error.

**Comment by hainest** [comment]
@mxz297 Yeah, that's definitely not something we can fix. I am seeing test_reloc [crashes](https://bottle.cs.wisc.edu/results/CRASHED/687) on Theta@ANL (which is a KNL machine) when I run #732, but not on the head of master. It's OS is Suse, so these shouldn't be the same issue. I'll try to debug it a bit and let you know what I find.

**Comment by hainest** [comment]
We're passing everywhere now, so I'm going to close this.
