### ISSUE TITLE
BPatch_boolExpr with long type operands.

### ISSUE THREAD

**Issue by bjchan9an** [dyninst/dyninst#727]
I have a global variable `` target_inst`` in the shared library, which is given an instruction address at runtime. I use ``BPatch_ifExpr``  at  ``Bpatch_point`` to check if the current address is equal to ``target_inst``. When consulting the documentation, I found that ``BPatch_originalAddressExpr()`` is used to represent the address of the current instrumentation point, but when I created a Boolean expression:
```CPP
BPatch_variableExpr* target_inst_var = appImage->findVariable("target_inst"); 
BPatch_boolExpr addrcheck(BPatch_eq ,*target_inst, BPatch_originalAddressExpr());
instArgs.push_back(&addrcheck);
```
The error is as follows when i try to instrument:
> WARNING: LHS type long unsigned int not compatible with RHS type long
[BPatch_addressSpace.C:915] - Type error inserting instrumentation

I tried using other types ``target_inst``, but I found that the ``long`` type of ``BPatch_originalAddressExpr`` seem not to be the ``long int`` type of cpp.

Hope to get suggestions : )

**Comment by bjchan9an** [comment]
I do type conversion on rvalue in instrumentation code：
```CPP
BPatch_boolExpr addrcheck(BPatch_eq ,*target_addr, BPatch_constExpr((unsigned long)addr));
```
And in shared library to be loaded:
```CPP
unsigned long target_addr;
```
It failed again and the error information is:
> WARNING: LHS type long unsigned int not compatible with RHS type unsigned long
[BPatch_addressSpace.C:915] - Type error inserting instrumentation

what is the difference between long unsigned int and unsigned long?

I found that when it comes to the type ``long``, even when using the same type on both sides, problems still occur. But when I use ``int`` ``unsigned int`` etc., this problem does not appear.

**Comment by hainest** [comment]
@bjchan9an What version of Dyninst are you using? What is the compiler and version? How did you build Dyninst (specifically, what options did you pass to `cmake`)?

@mxz297 Do you have any thoughts on this?

**Comment by hainest** [comment]
Closed due to inactivity. Please file another issue if this problem has not been resolved.
