### ISSUE TITLE
Power8 rewriter with static linking is failing

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#733]
#732 has introduced regressions on ray at LLNL. The previous run with #731 gave the output

    Failed to find libgcc.a, which can be needed by libc.a on certain platforms
    Set LD_LIBRARY_PATH to the directory containing libgcc.a

which means that it could not find libgcc.a, yet somehow the test "passed". Now that it *can* find libgcc.a, it's failing. These tests have also been failing on [poman.po.rice.edu](https://bottle.cs.wisc.edu/search?hostname=poman.po.rice.edu) since at least early March.

Power9 appears unaffected by this (thus far...).

**Comment by mxz297** [comment]
The tests passed on Power8 means that rewriting static linked binaries in our test suite on Power8 does not really need libgcc.a. However, once we can find libgcc.a, we may fail to analyze libgcc.a in some fashion. I believe that Dyninst does not check whether libgcc.a is needed or not before pulling it in. Only pulling libgcc.a when necessary is good thing to have but I doubt we will get to it.

Power9 appearing unaffected means that the Dyninst can analyze the libgcc.a on that Power9 system. I feel this has more to do with the versions of libgcc.a rather than Power8 vs Power9.

**Comment by sashanicolas** [comment]
How to check whether libgcc.a is needed?

**Comment by mxz297** [comment]
@sashanicolas I think if libc.a contains unresolved reference, then it is an indication that we need libgcc.a. However, IIRC, we are resolving references in .a in symtabAPI and we will directly throw an error when we find an unresolved reference. It will be quite some code changes to allow symtabAPI to feedback this information to BPatch.

**Comment by hainest** [comment]
@mxz297 

>Power9 appearing unaffected means that the Dyninst can analyze the libgcc.a on that Power9 system. I feel this has more to do with the versions of libgcc.a rather than Power8 vs Power9.

Sorry, yes, I didn't mean to imply that it was necessarily a P8 vs P9 issue. I just found it odd that ray (P8) and lassen (P9) use the same compiler and glibc, but give different results. Since all of the entries in the dashboard for poman have seen static rewriter failures, I'm curious if that PR would fix them. @sashanicolas Could you run it there when you have some time? I should really get access to that machine since I only have one P8, currently.

**Comment by hainest** [comment]
@sashanicolas 

>How to check whether libgcc.a is needed?

Aside from Ray, the testing so far shows that it including it doesn't negatively effect the results. I'm not sure if that is just a happy coincidence, or actually demonstrates that it's generally acceptable to include it even when it's not expressly needed.

**Comment by hainest** [comment]
@mxz297 Using Ben's suggestion, I checked that location of libgcc.a on both ray and lassen. They point to the same file: `/usr/tce/packages/gcc/gcc-7.3.1/rh/usr/bin/../lib/gcc/ppc64le-redhat-linux/7/libgcc.a`. The failures I'm seeing aren't coming from differences in the libgcc.a, then. Combined with the failures on [poman](https://bottle.cs.wisc.edu/results/FAILED/661)(even as recent as today), this suggests these failures are real. I confess, however, that I have no explanation as to why they were previously working on ray.

**Comment by hainest** [comment]
The failures on ray are intermittent. They passed when I ran PR729, but failed when I ran the head of master (those two are the same set of commits). This is consistently failing on poman. Could someone debug it there? I don't have access to that machine.

**Comment by mxz297** [comment]
For po.rice.edu, does your script handle the weird gcc/cc problem:

On po, I first load gcc/6.4.0, then `gcc` will have the correct version, but `cc` still report the old version with 4.8.5:

```
[xm13@poman ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/apps/software/Core/GCCcore/6.4.0/libexec/gcc/powerpc64le-unknown-linux-gnu/6.4.0/lto-wrapper
Target: powerpc64le-unknown-linux-gnu
Configured with: ../configure --enable-languages=c,c++,fortran --enable-lto --enable-checking=release --disable-multilib --enable-shared=yes --enable-static=yes --enable-threads=posix --enable-gold=default --enable-plugins --enable-ld --with-plugin-ld=ld.gold --prefix=/opt/apps/software/Core/GCCcore/6.4.0 --with-local-prefix=/opt/apps/software/Core/GCCcore/6.4.0 --enable-bootstrap --with-isl=/dev/shm/ee19/GCCcore/6.4.0/dummy-/gcc-6.4.0/stage2_stuff
Thread model: posix
gcc version 6.4.0 (GCC) 
[xm13@poman ~]$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.5/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --enable-targets=powerpcle-linux --disable-multilib --with-cpu-64=power8 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
```

cmake seems to find gcc 4.8.5 in my case.

**Comment by mxz297** [comment]
@hainest I find that on po.rice.edu, the failed cases are static PIC. Recall that before certain gcc version, on power, the compiler will generate broken binaries when it is forced to generate static PIC binaries.

**Comment by mxz297** [comment]
When I attempt to execute the static pic test mutatee, the mutatee cannot run:

```
[xm13@poman testsuite]$ ./dyninst_group_test.stat_g++_64_pic_none
-bash: ./dyninst_group_test.stat_g++_64_pic_none: /usr/lib/ld.so.1: bad ELF interpreter: No such file or directory
```

**Comment by hainest** [comment]
@mxz297 

>For po.rice.edu, does your script handle the weird gcc/cc problem:

No, but you can set the compiler using --cmake-args="-DCMAKE_CXX_COMPILER=...". It looks like Sasha has been using gcc-6.4.0 for his [runs](https://bottle.cs.wisc.edu/hostname/poman.po.rice.edu).

>Recall that before certain gcc version, on power, the compiler will generate broken binaries when it is forced to generate static PIC binaries.

On ray, I'm using gcc-7.3.0. Do you happen to know if this version is affected? I'll install gcc-9.2 there and re-run.

>When I attempt to execute the static pic test mutatee, the mutatee cannot run:

When I execute the same on ray, I do get it to run...

    [haines8@ray23:tests]$ ./dyninst_group_test.stat_g++_64_none_none
        Mutatee ./dyninst_group_test.stat_g++_64_none_none [C++]:""
        no tests specified, exiting

**Comment by mxz297** [comment]
> No, but you can set the compiler using --cmake-args="-DCMAKE_CXX_COMPILER=...". It looks like Sasha has been using gcc-6.4.0 for his [runs](https://bottle.cs.wisc.edu/hostname/poman.po.rice.edu).

Yes, I built dyninst and the testsuite with gcc-6.4.0 in this way and got broken static pic executables.

> On ray, I'm using gcc-7.3.0. Do you happen to know if this version is affected? I'll install gcc-9.2 there and re-run.

Not really. I remembered that you told that `-static-pie` is the new option needed to actually generate static pie. 

You can definitely try install gcc-9.2 and see how things go. But we have never done anything in Dyninst to support static pie. I doubt it will work. 

> 
> When I execute the same on ray, I do get it to run...
> 
> ```
> [haines8@ray23:tests]$ ./dyninst_group_test.stat_g++_64_none_none
>     Mutatee ./dyninst_group_test.stat_g++_64_none_none [C++]:""
>     no tests specified, exiting
> ```

`dyninst_group_test.stat_g++_64_none_none` is the static non-pie version. `dyninst_group_test.stat_g++_64_pie_none` is the static pie version.

**Comment by mxz297** [comment]
By the way, I don't think we even use `--static-pie` flag in the test suite.

**Comment by hainest** [comment]
>Not really. I remembered that you told that -static-pie is the new option needed to actually generate static pie.

Right, but we are interested in `-static -fpic`. We explicitly disable PIE with `-fno-pie` on all mutatee builds.

>dyninst_group_test.stat_g++_64_none_none is the static non-pie version. 

Whoops. Grabbed the wrong one. I get the same result with the PIC version.

    [haines8@ray23:tests]$ ././dyninst_group_test.stat_g++_64_pic_none
    Mutatee ././dyninst_group_test.stat_g++_64_pic_none [C++]:""
    no tests specified, exiting

**Comment by mxz297** [comment]
> Right, but we are interested in `-static -fpic`. 

I don't think so. I don't understand what `-fpic` brings when we disable PIE. 

> 
> Whoops. Grabbed the wrong one. I get the same result with the PIC version.
> 
> ```
> [haines8@ray23:tests]$ ././dyninst_group_test.stat_g++_64_pic_none
> Mutatee ././dyninst_group_test.stat_g++_64_pic_none [C++]:""
> no tests specified, exiting
> ```

Then we need to check whether the compiler is indeed emitting a static pic executable. If you run objdump on it and you saw small addresses then it is indeed static pie. Otherwise, the compiler is simply emitting a static non-pie.

**Comment by hainest** [comment]
>I don't think so. I don't understand what -fpic brings when we disable PIE.

I would expect the compiler to behave as if though it had not been built with `--enable-default-pie` (i.e., it generates a statically-linked library that is PIC). We should definitely verify this is what is happening.

>Then we need to check whether the compiler is indeed emitting a static pic executable. If you run objdump on it and you saw small addresses then it is indeed static pie. Otherwise, the compiler is simply emitting a static non-pie.

I will do that. I'm building gcc-9.3 right now, so it might be a while.

**Comment by mxz297** [comment]
> > I don't think so. I don't understand what -fpic brings when we disable PIE.
> 
> I would expect the compiler to behave as if though it had not been built with `--enable-default-pie` (i.e., it generates a statically-linked library that is PIC). We should definitely verify this is what is happening.

I see. 

> 
> > Then we need to check whether the compiler is indeed emitting a static pic executable. If you run objdump on it and you saw small addresses then it is indeed static pie. Otherwise, the compiler is simply emitting a static non-pie.
> 
> I will do that. I'm building gcc-9.3 right now, so it might be a while.

By the way, are you building gcc-9.3 with spack? I find that gcc built with spack behaves quite different from the system compiler even they are the same versions. I guess the spack build gcc with a different set of configuration flags.

**Comment by hainest** [comment]
>I find that gcc built with spack behaves quite different from the system compiler even they are the same versions. I guess the spack build gcc with a different set of configuration flags.

Yes, I am using spack. I'll diff the configure flags once it gets built. I would imagine that gcc delivered via system packages could well have some more specific flags enabled since they are more aware of the details of the system libraries. The one built by spack is intended to be fairly generic.

**Comment by hainest** [comment]
Here's the objdump for dyninst_group_test.stat_g++_64_pic_none. It doesn't look like PIC, but I'm not sure.

    ./dyninst_group_test.stat_g++_64_pic_none:     file format elf64-powerpcle

    Disassembly of section .init:

    0000000010000328 <_init>:
        10000328: 0f 10 40 3c   lis     r2,4111
        1000032c: 00 7d 42 38   addi    r2,r2,32000
        10000330: a6 02 08 7c   mflr    r0
        10000334: 10 00 01 f8   std     r0,16(r1)
        10000338: a1 ff 21 f8   stdu    r1,-96(r1)
        1000033c: 00 00 00 60   nop
        10000340: 08 80 02 e8   ld      r0,-32760(r2)

**Comment by mxz297** [comment]
> Here's the objdump for dyninst_group_test.stat_g++_64_pic_none. It doesn't look like PIC, but I'm not sure.
> 
> ```
> ./dyninst_group_test.stat_g++_64_pic_none:     file format elf64-powerpcle
> 
> Disassembly of section .init:
> 
> 0000000010000328 <_init>:
>     10000328: 0f 10 40 3c   lis     r2,4111
>     1000032c: 00 7d 42 38   addi    r2,r2,32000
>     10000330: a6 02 08 7c   mflr    r0
>     10000334: 10 00 01 f8   std     r0,16(r1)
>     10000338: a1 ff 21 f8   stdu    r1,-96(r1)
>     1000033c: 00 00 00 60   nop
>     10000340: 08 80 02 e8   ld      r0,-32760(r2)
> ```

Yeah, this is not PIE.....

**Comment by sashanicolas** [comment]
> 
> > For po.rice.edu, does your script handle the weird gcc/cc problem:
> 
> No, but you can set the compiler using --cmake-args="-DCMAKE_CXX_COMPILER=...". It looks like Sasha has been using gcc-6.4.0 for his [runs](https://bottle.cs.wisc.edu/hostname/poman.po.rice.edu).
> 

Indeed, I have. The script fails get the gcc 6.4 I load with the command module, and CC will still point to the old version. I have to fix it manually.

**Comment by hainest** [comment]
This went away when #729 was merged. Closing.
