### ISSUE TITLE
Add debuginfod support to dyninst

### ISSUE THREAD

**Issue by aaronmerey** [dyninst/dyninst#734]
Debuginfod is a lightweight web service that indexes ELF/DWARF debugging resources by build-id and serves them over HTTP. Debuginfod support enables dyninst to query debuginfod servers for a file's separate debuginfo when it otherwise cannot be found. Debuginfod is distributed with elfutils, for more information see https://sourceware.org/elfutils/Debuginfod.html

[debuginfod.diff](https://github.com/dyninst/dyninst/files/4441085/debuginfod.txt)
This patch adds debuginfod support to dyninst. It calls the debuginfod client library function for fetching separate debuginfo within Elf_X::findDebugFile(). It also adds a cmake option ENABLE_DEBUGINFOD to control whether dyninst is built with debuginfod support. This requires either having the debuginfod client library libdebuginfod and its header file installed or disabling sterile builds (debuginfod will be downloaded along with the rest of elfutils). 

Currently the patch does not include any tests for debuginfod support since it was not clear to me how to best integrate it into the testsuite. A typical test would involve stripping the mutatee's debuginfo, storing it in a location that dyninst cannot find it on its own, initializing a server that indexes the debuginfo and then running the mutatee. Should the test driver contain special handling for stripping the mutatee's debuginfo and initializing a server? Or maybe this should be carried out in a separate executable within the testsuite. Any suggestions are appreciated.

**Comment by mxz297** [comment]
@aaronmerey  Thanks for your patch! This indeed looks very interesting. I am not familiar with Debuginfod, so I will need to get familiar with it to make comments.

@hainest Are you familiar with Debuginfod?

**Comment by hainest** [comment]
@aaronmerey Could you make this a Pull Request? If you could cite this issue in that PR, that would be great. Also, we are phasing out having Dyninst build it's own dependencies. As such, we no longer are making changes to the build system to support that.

@mxz297 I am a little familiar with it. It was a feature added in 0.178. It won't build in spack, so we can't turn it on by default.
