### ISSUE TITLE
Support for GNU dwarf extensions

### ISSUE THREAD

**Issue by mplegendre** [dyninst/dyninst#735]
I'm trying to inspect DWARF-produced local variables from gcc 8.1, but Dyninst isn't able to parse the GNU locviews extension to DWARF.  I most recently saw these emitted in the RAJA ltimes example: https://github.com/LLNL/RAJA/blob/develop/examples/ltimes.cpp

I've extracted ltimes' main function, and when compiled with gcc 8.1 and -O3 this produces GNU locviews.  You can dwarfdump the executable, and search for the DW_AT_GNU_locviews code 0x2137 to find addresses/variables where they occur.

`
#include <string>
#include <iostream>
#include <vector>
#include <cstring>

#define RAJA_UNUSED_ARG(X)
#define RAJA_RESTRICT __restrict__

int main(int RAJA_UNUSED_ARG(argc), char **RAJA_UNUSED_ARG(argv[]))
{
  std::cout << "\n\nRAJA LTIMES example...\n\n";

//----------------------------------------------------------------------------//
// Define array dimensions, allocate arrays, define Layouts and Views, etc.

  const unsigned long num_m = 25;
  const unsigned long num_g = 48;
  const unsigned long num_d = 80;
  const unsigned long num_z = 64*1024;

  std::cout << "num_m = " << num_m << ", num_g = " << num_g <<
               ", num_d = " << num_d << ", num_z = " << num_z << "\n\n";

  const unsigned long L_size   = num_m * num_d;
  const unsigned long psi_size = num_d * num_g * num_z;
  const unsigned long phi_size = num_m * num_g * num_z;

  std::vector<double> L_vec(num_m * num_d);
  std::vector<double> psi_vec(num_d * num_g * num_z);
  std::vector<double> phi_vec(num_m * num_g * num_z);

  double* L_data   = &L_vec[0];
  double* psi_data = &psi_vec[0];
  double* phi_data = &phi_vec[0];

  for (unsigned long i = 0; i < L_size; ++i) {
    L_data[i] = i+1;
  }

  for (unsigned long i = 0; i < psi_size; ++i) {
    psi_data[i] = 2*i+1;
  }

  // Note phi_data will be set to zero before each variant is run.

//----------------------------------------------------------------------------//

  std::cout << "\n Running baseline C-version of LTimes...\n";

  std::memset(phi_data, 0, phi_size * sizeof(double));

  // Using restrict doesn't make much of a difference for most compilers.
  double * RAJA_RESTRICT L = L_data;
  double * RAJA_RESTRICT psi = psi_data;
  double * RAJA_RESTRICT phi = phi_data;

  for (int m = 0; m < num_m; ++m) {
    for (int d = 0; d < num_d; ++d) {
      for (int g = 0; g < num_g; ++g) {
        for (int z = 0; z < num_z; ++z) {
          phi[m*num_g*num_z + g*num_z + z] +=
            L[m*num_d + d] * psi[d*num_g*num_z + g*num_z + z];
        }
      }
    }
  }

  return 0;
}
`

**Comment by sashanicolas** [comment]
After some work done on this, and our last call, it's clear that there's no need of DW_AT_GNU_locviews info.
