### ISSUE TITLE
error: ‘class BPatch_module’ has no member named ‘insertFiniCallback’

### ISSUE THREAD

**Issue by 9DemonFox** [dyninst/dyninst#738]
codeCoverage.C:380:23: error: ‘class BPatch_module’ has no member named ‘insertInitCallback’
  380 |   if (!defaultModule->insertInitCallback (initSequence))
      |                       ^~~~~~~~~~~~~~~~~~
codeCoverage.C:399:23: error: ‘class BPatch_module’ has no member named ‘insertFiniCallback’
  399 |   if (!defaultModule->insertFiniCallback (instExitExpr))

**Comment by hainest** [comment]
Unable to reproduce. Closing. If this problem persists, please submit a new issue with all of the requisite details included.
