### ISSUE TITLE
/src/emitElf.C:273: std::string phdrTypeStr(Elf64_Word): Assertion `0' failed.

### ISSUE THREAD

**Issue by 9DemonFox** [dyninst/dyninst#743]
I use the example static instrucment  in your manual, but it failed to write the binary file. And it produced an empty file named InterestingProgram-rewrittenVkBOSI whitch ends with "VKBOSI" or "HCk1Bn" or something like these.
HELP HELP HELP

**Comment by sashanicolas** [comment]
That is probably the temporary file, which was not deleted due to incomplete emission of the rewritten binary. 
What branch/commit, platform (x86, power, aarch64) you're at?
What is the ```phdr_type``` passed that caused the assertion?

> std::string phdrTypeStr(Elf64_Word phdr_type)

**Comment by 9DemonFox** [comment]
I have installed the Dyninst by the source download from [https://github.com/dyninst/dyninst/releases/tag/v9.3.2] and spack,i.e. Dyninst 10.1.0.
my ubuntu version is:
 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 GNU/Linux,.

**phdrTypeStr :** 0x7ffff7214ea0<phdrTypeStr[abi:cxx11](unsigned int)>

**Comment by 9DemonFox** [comment]
I have tried to debug it and the value of *0x7ffff7214ea0 is -98693133

**Comment by sashanicolas** [comment]
> [https://github.com/dyninst/dyninst/releases/tag/v9.3.2] and spack,i.e. Dyninst 10.1.0.

So you're using version 9.3 or 10.1? The version 9.3 is old, not supported anymore.
What are you trying to do?

**Comment by 9DemonFox** [comment]
I have tried both of the two versions.
I want to realize a shadow stack which used for protecting buffer flow. and it needs  static instrucment.
So I use the example in [Dyninst manual](https://github.com/dyninst/dyninst/blob/master/dyninstAPI/doc/dyninstAPI.pdf). And the example is the first example of Appendix A .

**Comment by sashanicolas** [comment]
@9DemonFox 

> Elf64_Word phdr_type

 is supposed to be unsigned. Valid numbers for it would be:
```
 709 /* Legal values for p_type (segment type).  */
 710 
 711 #define PT_NULL         0               /* Program header table entry unused */
 712 #define PT_LOAD         1               /* Loadable program segment */
 713 #define PT_DYNAMIC      2               /* Dynamic linking information */
 714 #define PT_INTERP       3               /* Program interpreter */
 715 #define PT_NOTE         4               /* Auxiliary information */
 716 #define PT_SHLIB        5               /* Reserved */
 717 #define PT_PHDR         6               /* Entry for header table itself */
 718 #define PT_TLS          7               /* Thread-local storage segment */
 719 #define PT_NUM          8               /* Number of defined types */
 720 #define PT_LOOS         0x60000000      /* Start of OS-specific */
 721 #define PT_GNU_EH_FRAME 0x6474e550      /* GCC .eh_frame_hdr segment */
 722 #define PT_GNU_STACK    0x6474e551      /* Indicates stack executability */
 723 #define PT_GNU_RELRO    0x6474e552      /* Read-only after relocation */
 724 #define PT_LOSUNW       0x6ffffffa
 725 #define PT_SUNWBSS      0x6ffffffa      /* Sun Specific segment */
 726 #define PT_SUNWSTACK    0x6ffffffb      /* Stack segment */
 727 #define PT_HISUNW       0x6fffffff
 728 #define PT_HIOS         0x6fffffff      /* End of OS-specific */
 729 #define PT_LOPROC       0x70000000      /* Start of processor-specific */
 730 #define PT_HIPROC       0x7fffffff      /* End of processor-specific */
```

Did you get a different one from this list?

**Comment by sashanicolas** [comment]
@9DemonFox this also seems to be only used to print out the name of the section for debug purpose. A quick fix would be to comment out the assertion or the the remove com print out.

**Comment by bbiiggppiigg** [comment]
@sashanicolas 
I'm seeing similar issue with glibc-2.31
In my case the constant is 0x7474e553

According to this thread
https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1748802
The problems seems to be a newly added PT_GNU_PROPERTY

**Comment by sashanicolas** [comment]
@bbiiggppiigg Macros not available in elf.h are usually added to the dyninst file that use it.
As I said, that assertion does not need to be there, since that function is merely being used to return a string representation of the PT_* value, and only being used at another debug print out call.
That's a straight fix.
