### ISSUE TITLE
Dyninst 10.0.0 building codecoverage tool- error $PLATFORM not set

### ISSUE THREAD

**Issue by tosanjay** [dyninst/dyninst#744]
Hello,
I am new to Dyninst and have installed Dyninst 10.1. 0. Build process went fine. I started looking at Examples directory and thought of following codecoverage tool. when running make -f Makefile.afs, i got the error that $PLATFORM not set. Did I miss anything. Also, i see in Makefile that a path $(DYNINST_ROOT)/$(PLATFORM)/lib is being accessed. In my installation directory structure, I don't see any path of this sort. I have $(DYNINST_ROOT)/lib, $(DYNINST_ROOT)/include, $(DYNINST_ROOT)/bin, and $(DYNINST_ROOT)/share. Did I do something wrong OR am I doing something wrong?

**Comment by hainest** [comment]
By default, the examples are built when Dyninst is built, so you don't need to build them yourself. The binaries should be in the Dyninst build directory under "examples".

**Comment by tosanjay** [comment]
Ok. Thanks @hainest . As coming from Intel Pin user community, I immediately felt that an example makefile (like the one given with Pin) wherein all we have to do is to indicate our target and just run `make` would make it great.

**Comment by hainest** [comment]
I've not used Intel Pin before. Could you elaborate on how you use their Makefiles to run their examples?

**Comment by tosanjay** [comment]
Ok. So here is how it works in Pin:
When you download Pin, there are several examples comes with it (e.g. if you check ~/pin-3.7/source/tools/ManualExamples). In that directory, there is a Makefile like the below and another (sort makefile) makefile.rules. All I have to do it to set environment variable PIN_HOME (or PIN_ROOT) and just add the name of the target (lib to be compiled) in the makefile.rules  and run 

`make`

Thus, I just need these two files (Makefile and makefile.rules) and everything works.

Makefile.rules
```

##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
**TEST_TOOL_ROOTS := mypintool #this is the name of my pintool that i want to build**

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
.....
.....

```

Makefile
```

##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################

# If the tool is built out of the kit, PIN_ROOT must be specified in the make invocation and point to the kit root.
ifdef PIN_ROOT
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
CONFIG_ROOT := ../Config
endif
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules

##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################
```

**Comment by hainest** [comment]
Ah,ok. Thanks for this. Quite by happenstance, we now have someone dedicated to porting our examples to their own repository (https://github.com/dyninst/examples), so I'll definitely keep this example in mind when designing the build structure there. It will be a while before everything is up and running over there, but definitely let us know if you encounter any other issues.
