### ISSUE TITLE
parseapi missing several no-return functions

### ISSUE THREAD

**Issue by mwkrentel** [dyninst/dyninst#745]
It seems that ParseAPI's list of non-returning functions is
incomplete.  Off the top of my head, it's missing _exit(), err()
and errx().  But you probably want to scan /usr/include for a more
complete list.

----------

Here's one example from my dlstress.c test in the repo:
https://github.com/HPCToolkit/hpctoolkit-tests/tree/master/stress/dlstress

The mk_thread_args() function has two ways to return: normal return at
end of function (returns void), or errx() if something earlier fails.
The function immediately following this is do_loop().

Compiled with -O, objdump reports:

```
0000000000400b54 <mk_thread_args>:
  400b54:       83 3d a5 18 20 00 07    cmpl   $0x7,0x2018a5(%rip) 
  400b5b:       7e 4e                   jle    400bab <mk_thread_args+0x57>
  400b5d:       48 c7 07 38 11 40 00    movq   $0x401138,(%rdi)
  400b64:       c7 47 08 01 00 00 00    movl   $0x1,0x8(%rdi)
  ...
  400baa:       c3                      retq   
  400bab:       48 83 ec 08             sub    $0x8,%rsp
  400baf:       be a8 12 40 00          mov    $0x4012a8,%esi
  400bb4:       bf 01 00 00 00          mov    $0x1,%edi
  400bb9:       b8 00 00 00 00          mov    $0x0,%eax
  400bbe:       e8 3d fc ff ff          callq  400800 <errx@plt>

0000000000400bc3 <do_loop>:
  400bc3:       41 57                   push   %r15
  400bc5:       41 56                   push   %r14
  400bc7:       41 55                   push   %r13
  400bc9:       41 54                   push   %r12
  ...
```

So, do_loop() is a real function and nm reports a T symbol.  But dyninst
computes the last block of mk_thread_args() as a normal call.  My
struct debug output says that parseapi reports this block with two out
edges, including a call/fall-through edge to 0x400bc3.

```
block:
stmt:  0x400bab (4)  l=188  f='/home/krentel/struct/hpctoolkit-tests/stress/dlstress/dlstress.c'
stmt:  0x400baf (5)  l=190  f='/home/krentel/struct/hpctoolkit-tests/stress/dlstress/dlstress.c'
stmt:  0x400bb4 (5)  l=190  f='/home/krentel/struct/hpctoolkit-tests/stress/dlstress/dlstress.c'
stmt:  0x400bb9 (5)  l=190  f='/home/krentel/struct/hpctoolkit-tests/stress/dlstress/dlstress.c'
stmt:  0x400bbe (5)  l=190  f='/home/krentel/struct/hpctoolkit-tests/stress/dlstress/dlstress.c'
out edges:  0x400800 (call, interproc)  0x400bc3 (call-ft)
```

As a result, hpcstruct puts the entire body of do_loop() inside
mk_thread_args() and the results in the viewer look bad.

```
  <P i="123" n="do_loop" l="212" v="{[0x400bc3-0x400bc4)}">
  </P>
```

It looks like parseapi is missing errx() as noreturn.  The <err.h>
header file has:

```
extern void errx (int __status, const char *__format, ...)
     __attribute__ ((__noreturn__, __format__ (__printf__, 2, 3)));
```

This is from a recent dyninst master.

**Comment by hainest** [comment]
See also #150

**Comment by mwkrentel** [comment]
I looked into how to automate finding the noreturn functions.  There
are two general approaches.  One is to scan /usr/include for attribute
`__noreturn__`.  This is possible to get about 80-90% accuracy with the
rest by manual inspection.

A better way is to use the dwarf info and the DW_AT_noreturn
attribute.  Build glibc and gcc/g++ with debug info, dump the dwarf
info, and it's easy to pick out the noreturn names.  For example:

```
 <2><16c43f>: Abbrev Number: 22 (DW_TAG_subprogram)
    <16c440>   DW_AT_external    : 1
    <16c440>   DW_AT_name        : (indirect string, offset: 0x5e1a3): __throw_range_error
    <16c444>   DW_AT_decl_file   : 1
    <16c445>   DW_AT_decl_line   : 105
    <16c446>   DW_AT_decl_column : 3
    <16c447>   DW_AT_linkage_name: (indirect string, offset: 0x5e31a): _ZSt19__throw_range_errorPKc
    <16c44b>   DW_AT_noreturn    : 1
    <16c44b>   DW_AT_declaration : 1
    <16c44b>   DW_AT_sibling     : <0x16c455>
```

Anyway, I'm finishing up a script to do this.
What's a good machine to try this on at Wisconsin?
I can build gcc and glibc, run the script and show you what it does.

I think we're pretty close to a good solution, so I'm going to start
pushing to get the results into the next release.

@hainest  @mxz297

**Comment by hainest** [comment]
If DWARF has the noreturn information, then why do we need a pre-populated list? Does that DWARF information only show up with special builds of gcc/glibc?

**Comment by mwkrentel** [comment]
It's Dwarf, not Elf.  So yes, you do need a special build with '-g'.

/usr/lib64/libc.so, libstdc++.so, etc are stripped and thus won't have
any of this info.

**Comment by mwkrentel** [comment]
Ok, I finished my script (almost) and ran it on coriander.
Results are in:

```
coriander:  /home/krentel/noreturn
```

The libc, libstdc++, etc libraries are in Files.  The results are in
out-*, so maybe 70 new functions missing from `CodeSource::non_returning_funcs`.

```
$ wc out-*
  10   10  244 out-gfortran
   3    3   41 out-gomp
  44   44  663 out-libc
   9    9  153 out-pthread
  34   34  980 out-stdc++
 100  100 2081 total
```

Assuming you're generally ok with this, I'll put together a PR to add
the new functions.  Some notes:

1. The libstdc++ functions that we both have, eg, `_ZSt16__throw_bad_castv`
agree in the spelling of the mangling.  (good)

2. The only real difference I see is in the gfortran names.  For
example, CodeSource.C has `_gfortran_os_error`, but I have
`_gfortrani_os_error` (with an 'i').  I think you have to go back very
far to find the old names.

3. There are a few names in CodeSource.C that I've never heard of:
`fancy_abort`, `ExitProcess`, `__sys_exit`, etc.  They sound plausible,
but I've never heard of them.

**Comment by mxz297** [comment]
`ExitProcess` is a Windows API... Not sure about `fancy_abort` or `__sys_exit`.

**Comment by mwkrentel** [comment]
Ok, fair enough.  I'm too linux/unix centric.  :-)
