### ISSUE TITLE
ParseAPI unable to parse a firefox shared object

### ISSUE THREAD

**Issue by stanfordcox** [dyninst/dyninst#747]
A user is unable to use the systemtap dyninst backend to probe firefox

The problem is parsing libxul.so.  This is a  large shared objects, over 100M; by comparison libc is 3M. 

The problem is independent of systemtap and can be easily reproduced as shown in:
 https://scox.fedorapeople.org/dyninst/libxul.readme

Hopefully once libxul.so can be parsed then dyninst will be able to probe it which should get the systemtap dyninst backend working.

I have tried the above, with identical results (see libxul.readme) on fedora 31 and rhel 8.2 both x86_64 so seems independent of libc, tbb, boost version.

**Comment by mxz297** [comment]
@stanfordcox Is this a new problem or the same one that can be resolved by #746 ?

**Comment by stanfordcox** [comment]
It is a different problem.  The summary is at:
 https://scox.fedorapeople.org/dyninst/libxul.readme
libxul.so is a _really big_ shared library: 128M 
No other shared library on my fedora 31 box comes close to being this
size, next closest is /usr/lib64/libclang-cpp.so.9 (CodeDump works
fine on libclang-cpp)  Those two are much larger than any other .so

 https://scox.fedorapeople.org/dyninst/libxul.so.1 
 works (with pull/746)
 from firefox 75

 https://scox.fedorapeople.org/dyninst/libxul.so.2
 from firefox 76

 https://scox.fedorapeople.org/dyninst/libxul.so.3 
 from rhel 8 /  firefox-68
 fails for a totally different reason than libxul.so.

All the above behave the same way on both f31 and rhel8 so seemsa independent of library .so versions.
