### ISSUE TITLE
test_reloc failing on ulna.llnl.gov (ARM/ThunderX2)

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#753]
https://bottle.cs.wisc.edu/regressions?id=783

    $ gdb --args test_driver -none -64 -rewriter -dynamiclink -nonpic -g++ -v -debugPrint -test test_reloc -log tmp.log

    <snip>
	test_lib_mutateeStart.C[268]:  starting rewritten process './binaries/rewritten_test_reloc.dyn_g++_64_none_none [Detaching after fork from child process 52490]
	test_lib_mutateeStart.C[283]:  after waitForCompletion: crashed, result = 11
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/rewritten_test_reloc.dyn_g++_64_none_none
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/ld-linux-aarch64.so.1
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/libc.so.6
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/libgcc_s.so.1
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/libm.so.6
	test_lib_mutateeStart.C[77]:  unlinking ./binaries/libstdc++.so.6
	TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
	test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)
	[Thread 0x400001e1f1e0 (LWP 52421) exited]
	[Thread 0x40000229f1e0 (LWP 52422) exited]
	[Inferior 1 (process 52393) exited with code 05]

[Full gdb output](https://github.com/dyninst/dyninst/files/4674776/ulna.test_reloc.debug.log)

The test suite log from "-log" is

	Commencing test(s) ...
	Sun May 24 18:09:16 PDT 2020
	Linux ulna2 4.14.0-115.19.1.1chaos.ch6a.aarch64 #1 SMP Mon Apr 27 09:32:25 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
	TESTDIR=/g/g20/haines8/workspace/ulna/paradyn/rappOsTt/testsuite/tests
	[Tests with test_reloc.dyn_g++_64_none_none]
	-rwxr-xr-x 1 haines8 haines8 114056 May 24 15:38 test_reloc.dyn_g++_64_none_none*
		linux-vdso.so.1 =>  (0x0000400000050000)
		libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00004000000a0000)
		libm.so.6 => /lib64/libm.so.6 (0x00004000001d0000)
		libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000400000290000)
		libc.so.6 => /lib64/libc.so.6 (0x00004000002d0000)
		/lib/ld-linux-aarch64.so.1 (0x0000400000000000)

	Group teardown failed:

~~I'm also seeing this consistently fail on cori (x86 as NERSC), but nowhere else. I know we've been down this road at least twice before on these relocation issues, but they just refuse to go away.~~ The x86 issues on Cori were fixed by #754 

@sashanicolas @mxz297

**Comment by mxz297** [comment]
@sashanicolas The key of my fix #754 is that glibc seems to contain several sections for storing code pointers. During my work on a particular x86-64 machine, I identified a few sections that contain code pointers, so the contents of these sections should be adjusted by a page. You may want to examine the libc.so on ARM to see if there are other customized sections that contain code pointers.

**Comment by hainest** [comment]
Subsumed by #762.
