### ISSUE TITLE
test_reloc failing on quartz.llnl.gov (x86_64)

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#761]
`test_reloc` is consistently failing on [quartz](https://bottle.cs.wisc.edu/search?hostname=quartz&since_date=2020-05-20), but gdb isn't much use in tracking down the problem (an example output is below). This is gcc-8.1 and glibc-2.17.

@sashanicolas @mxz297 Any suggestions on what to try next?

	Starting program: ./test_driver -64 -rewriter -g++ -dynamiclink -nonpic -test test_reloc -log tmp.log
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib64/libthread_db.so.1".
	[Detaching after fork from child process 28978]
	[Detaching after fork from child process 28980]
	[Detaching after fork from child process 28982]
	[Detaching after fork from child process 28984]
	[New Thread 0x2aaab19e8700 (LWP 28994)]
	[New Thread 0x2aaab1ff1700 (LWP 28995)]
	[Detaching after fork from child process 28996]
	[Detaching after fork from child process 28998]
	[Detaching after fork from child process 28999]
	[Detaching after fork from child process 29007]
	[Detaching after fork from child process 29008]
	[Detaching after fork from child process 29009]
	[Detaching after fork from child process 29010]
	[Detaching after fork from child process 29011]
	[Detaching after fork from child process 29012]
	[Detaching after fork from child process 29013]
	[Detaching after fork from child process 29014]
	[Detaching after fork from child process 29015]
	[Detaching after fork from child process 29016]
	[Detaching after fork from child process 29017]
	[Detaching after fork from child process 29018]
	[Detaching after fork from child process 29019]
	[Detaching after fork from child process 29020]
	[Detaching after fork from child process 29021]
	[Detaching after fork from child process 29022]
	[Detaching after fork from child process 29023]
	[Detaching after fork from child process 29024]
	[Detaching after fork from child process 29045]
	TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
	test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)
	[Thread 0x2aaab19e8700 (LWP 28994) exited]
	[Thread 0x2aaab1ff1700 (LWP 28995) exited]
	[Inferior 1 (process 28974) exited with code 05]

**Comment by mxz297** [comment]
@hainest Try:

1. `DYNINST_REWRITER_NO_UNLINK=1 ./test_driver -64 -rewriter -g++ -dynamiclink -nonpic -test test_reloc -log tmp.log`

2. Go to the binary or binaries directory. 

3. Run `./rewritten_test_reloc... -run test_reloc`

If you see things like

```
./rewritten_test_reloc.dyn_gcc_64_none_none_26423467: Relink
/lib64/libdl.so.2' with ./libc.so.6' for IFUNC symbol `strcpy'
Segmentation fault (core dumped)
```

Then it is the loader bug we have encountered several times.

**Comment by hainest** [comment]
It only segfaults when I add '.' to LD_LIBRARY_PATHS.

	$ export OMP_NUM_THREADS=2
	$ export DYNINSTAPI_RT_LIB=...
	$ export my_ld_paths=$(pwd):$(pwd)/../dyninst/lib

	$ LD_LIBRARY_PATH=$my_ld_paths:$LD_LIBRARY_PATH DYNINST_REWRITER_NO_UNLINK=1 ./test_driver -64 -rewriter -g++ -dynamiclink -nonpic -test test_reloc -log tmp.log

	$ cd binaries
	$ ./rewritten_test_reloc.dyn_g++_64_none_none_24810000 -run test_reloc
	All tests passed.

	$ LD_LIBRARY_PATH=.:$my_ld_paths:$LD_LIBRARY_PATH ./rewritten_test_reloc.dyn_g++_64_none_none_24810000 -run test_reloc
	Segmentation fault (core dumped)

**Comment by mxz297** [comment]
> It only segfaults when I add '.' to LD_LIBRARY_PATHS.

Right. Add "." to LD_LIBRARY_PATH will cause the test to use the instrumented libraries. Otherwise, the test will run with the original system libraries and will pass normally. 

> $ LD_LIBRARY_PATH=.:$my_ld_paths:$LD_LIBRARY_PATH ./rewritten_test_reloc.dyn_g++_64_none_none_24810000 -run test_reloc
> Segmentation fault (core dumped)
> ```

Then it looks like that this is not the loader problem. Honestly, being able to reliably instrumenting system libraries will need significant more work...

**Comment by hainest** [comment]
>Then it looks like that this is not the loader problem. Honestly, being able to reliably instrumenting system libraries will need significant more work...

I think Sasha was running into this previously, as well, on some ARM work he was doing. I will see if I get the same results when I try this on #753. If so, I'll merge them and we can leave it as a reminder issue for future work.

**Comment by hainest** [comment]
Subsumed by #762.
