### ISSUE TITLE
libstackwalk.so.10.1: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by Villyli** [dyninst/dyninst#765]
$ make
g++ -g -Wall -std=c++11  modify.cpp  -ldyninstAPI -lelf -ldw  -lpthread -lrt   -o modify 
/usr/bin/ld: /tmp/ccVKf1u9.o: undefined reference to symbol '_ZNK7Dyninst11Stackwalker5Frame7getNameERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
//usr/local/lib/libstackwalk.so.10.1: error adding symbols: DSO missing from command line
collect2: error：ld return 1
Makefile:7: recipe for target 'modify' failed
make: *** [modify] Error 1

Is there any link order wrong?
Code： 
`Walker* walker = Walker :: newWalker ();
    walker->walkStack ( stackwalk );
    for( unsigned i =0; i < stackwalk . size (); i ++) {
        stackwalk[i].getName(s);
        cout << " Found function " << s << endl ;
    }`

lib and includes are install and fine linked as API tell me ot do.

**Comment by hainest** [comment]
You need to add a linker flag for each Dyninst module you use (and often `libcommon`). Something like

    g++ -g -Wall -std=c++11 modify.cpp -ldyninstAPI -lstackwalk -lcommon -llelf -ldw -lpthread -lrt -o modify

**Comment by Villyli** [comment]
I changed my code to use like MachRegisters::86_x64, and it works while using -lcommon and -lboost_system.

However, while using stackwalker, I added these link provided by [issue#440](https://github.com/dyninst/dyninst/issues/440), which includes -lconmon and it still doesn't work.
`-ldyninstAPI -lparseAPI -linstructionAPI -lsymtabAPI -lsymLite -ldynDwarf -ldynElf -lcommon -lpcontrol -ldwarf`

And I use (dyninst is installed)
`find /usr/local/ -name "*" | xargs grep "_ZNK7Dyninst11Stackwalker5Frame7getNameERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE"`
libdyninstAPI.so* and libstackwalk.so* both match. 

I rebuild my ubuntu vm-os 3 times, using libboost-1.6.1 or  libboost-1.7.3 or  libboost-all-dev in apt and GCC 7.* or GCC 8.4. :(

:) When I type this, I try to -l all file-folder name in build, -lstackwalk works!!!!
Here are these link I've tried yesterday and that before(blindly)
-lStackwalkerAPI -lStackWalkerAPI -lstackwalkerAPI -lswalkAPI and balabala without API
I don't know how to get -l list I can use, ld --library is just a check, where I can get -l configs?

**Comment by hainest** [comment]
>However, while using stackwalker, I added these link provided by issue#440, which includes -lconmon and it still doesn't work.

What is the specific error you are getting?

>And I use (dyninst is installed)... libdyninstAPI.so* and libstackwalk.so* both match.

I think your installation is bad. You should remove all of the Dyninst libraries and re-install (preferably version 10.1).

>When I type this, I try to -l all file-folder name in build, -lstackwalk works!!!! Here are these link I've tried yesterday and that before(blindly) -lStackwalkerAPI -lStackWalkerAPI -lstackwalkerAPI -lswalkAPI and balabala without API

The name of the library file is `libstackwalk.so`, so the linker flag is `-lstackwalk`. This is the convention used by linux linkers (at least all the ones I've seen).

>I don't know how to get -l list I can use, ld --library is just a check, where I can get -l configs?

Right now, you can't. Eventually, we want to update our build system to export namespace-qualified library targets so that you can just add the line

    add_target_library(my_program Dyninst::StackWalker)

to your CMake build, and everything will "just work". But that likely won't happen before the 11.0 release. Until then, you'll have to specify them manually.
