### ISSUE TITLE
support for all x86 instruction extensions？

### ISSUE THREAD

**Issue by adahsuzixin** [dyninst/dyninst#767]
Hi, I have a question for instruction decoding support for x86 instruction extensions.
Do we support all the following extensions instructions in x86?
- SSE
- SSE2
- SSE3
- SSSE3
- SSE4.1
- SSE4.2
- AVX
- AVX2
- AVX512

**Comment by mxz297** [comment]
Dyninst's current home grown instruction decoder for x86/64 covers many of the instructions you mentioned, but does not have a robust and complete support. We are in the process of moving to use external instruction decoders such as Capstone for instruction decoding. This effort is in progress (see PR #638).

**Comment by adahsuzixin** [comment]
Yes, [#638](https://github.com/dyninst/dyninst/pull/638) is a significant improvement.
I hope this PR can be merged ASAP. ^_^

**Comment by mxz297** [comment]
#638 is waiting for Capstone to merge my improvement to Capstone (https://github.com/aquynh/capstone/pull/1604). Current Capstone misses lots of instruction operand read and write information.

**Comment by adahsuzixin** [comment]
cool~
Waiting for your good new!

**Comment by hainest** [comment]
Closing. We hope to be using Capstone soon, but we are still waiting for them to accept our changes. Please let us know if you have any other questions.
