### ISSUE TITLE
facing problem configuration

### ISSUE THREAD

**Issue by aruncgowda** [dyninst/dyninst#770]
@sashanicolas 

cmake /path/to/dyninst/source -DCMAKE_INSTALL_PREFIX=/path/to/installation

sir iam facing problem in this command
could you please explain this command

configure: error: zlib not found but is required
CMakeFiles/LibElf.dir/build.make:108: recipe for target 'libelf/src/LibElf-stamp/LibElf-configure' failed
make[2]: *** [libelf/src/LibElf-stamp/LibElf-configure] Error 1
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/LibElf.dir/all' failed
make[1]: *** [CMakeFiles/LibElf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

this is the error i am getting

**Comment by sashanicolas** [comment]
you need to install zlib

**Comment by aruncgowda** [comment]
@sashanicolas 
thank u sir

**Comment by aruncgowda** [comment]
@sashanicolas 
now i am facing this problem sir


[ 16%] Linking CXX shared library libcommon.so
/usr/bin/ld: cannot find -lboost_thread
/usr/bin/ld: cannot find -lboost_system
/usr/bin/ld: cannot find -lboost_date_time
collect2: error: ld returned 1 exit status
common/CMakeFiles/common.dir/build.make:1088: recipe for target 'common/libcommon.so.9.3.2' failed
make[2]: *** [common/libcommon.so.9.3.2] Error 1
CMakeFiles/Makefile2:371: recipe for target 'common/CMakeFiles/common.dir/all' failed
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sashanicolas** [comment]
You need to install boost.
If you use [Spack](https://github.com/spack/spack), it will do all the job for you. It seems like you're missing a lot of Dyninst dependencies.
```spack install dyninst```

**Comment by aruncgowda** [comment]
-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so.9.3.2
-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so.9.3
-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so
-- Up-to-date: /home/sharma/.local/include/dynC.h
-- Up-to-date: /home/sharma/.local/include/snippetGen.h
-- Up-to-date: /home/sharma/.local/include/dynC.h
-- Up-to-date: /home/sharma/.local/include/snippetGen.h
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/dynC_APITargets.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/dynC_APITargets-relwithdebinfo.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/DyninstConfig.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/DyninstConfigVersion.cmake


@sashanicolas 
sir ,at last i got like this .
i dont know whether dyninst is installed or what??
how to check whether dyninst is installed or not??
pls help me sir

**Comment by aruncgowda** [comment]
@sashanicolas 
i did not get any response sir 

-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so.9.3.2
-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so.9.3
-- Up-to-date: /home/sharma/.local/lib/libdynC_API.so
-- Up-to-date: /home/sharma/.local/include/dynC.h
-- Up-to-date: /home/sharma/.local/include/snippetGen.h
-- Up-to-date: /home/sharma/.local/include/dynC.h
-- Up-to-date: /home/sharma/.local/include/snippetGen.h
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/dynC_APITargets.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/dynC_APITargets-relwithdebinfo.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/DyninstConfig.cmake
-- Up-to-date: /home/sharma/.local/lib/cmake/Dyninst/DyninstConfigVersion.cmake

i got this  lines after i gave the commad make insatll
