### ISSUE TITLE
Make install failing

### ISSUE THREAD

**Issue by alderson41** [dyninst/dyninst#773]
make install failing

os: ubuntu 18.04 (x86_64)

Error logs:

[  1%] Built target LibDwarf
[  3%] Built target boost
[  3%] Building DyninstRT
[ 50%] Built target dyninstAPI_RT_static
[100%] Built target dyninstAPI_RT
[  3%] Built target DyninstRT
[  5%] Built target LibIberty
[ 15%] Built target common
[ 15%] Built target dynElf
[ 17%] Built target dynDwarf
[ 17%] Built target symLite
[ 26%] Built target symtabAPI
[ 31%] Built target instructionAPI
[ 48%] Built target parseAPI
[ 53%] Built target patchAPI
[ 62%] Built target pcontrol
[ 67%] Built target stackwalk
[ 94%] Built target dyninstAPI
[ 97%] Built target parseThat
[100%] Built target dynC_API
[  1%] Built target LibDwarf
[  3%] Built target boost
[  3%] Building DyninstRT
[ 50%] Built target dyninstAPI_RT_static
[100%] Built target dyninstAPI_RT
[  3%] Built target DyninstRT
[  5%] Built target LibIberty
[ 15%] Built target common
[ 15%] Built target dynElf
[ 17%] Built target dynDwarf
[ 17%] Built target symLite
[ 26%] Built target symtabAPI
[ 31%] Built target instructionAPI
[ 48%] Built target parseAPI
[ 53%] Built target patchAPI
[ 62%] Built target pcontrol
[ 67%] Built target stackwalk
[ 94%] Built target dyninstAPI
[ 97%] Built target parseThat
[100%] Built target dynC_API
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/libdyninstAPI_RT.so.9.3.2
CMake Error at dyninstAPI_RT/cmake_install.cmake:61 (file):
  file INSTALL cannot copy file
  "/home/anirudh/Desktop/dyninst-9.3.2/dyninstAPI_RT/libdyninstAPI_RT.so.9.3.2"
  to "/usr/local/lib/libdyninstAPI_RT.so.9.3.2".
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)

make: *** [Makefile:74: install] Error 1

**Comment by alderson41** [comment]
tried installing through spack, but it wasn't successful.

Log:

==> Installing gettext
==> Searching for binary cache of gettext
==> Warning: No Spack mirrors are currently configured
==> No binary for gettext found: installing from source
==> Fetching https://ftpmirror.gnu.org/gettext/gettext-0.20.1.tar.xz
-=O=- #   #   #    #                                                        
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> Fetching from https://ftpmirror.gnu.org/gettext/gettext-0.20.1.tar.xz failed.
==> Error: FetchError: All fetchers failed for spack-stage-gettext-0.20.1-7pi2rdexyoe3uqnxmflaseb2sjjriidb

/home/anirudh/Desktop/spack/lib/spack/spack/package.py:1079, in do_fetch:
       1076                raise FetchError("Will not fetch %s" %
       1077                                 self.spec.format('{name}{@version}'), ck_msg)
       1078
  >>   1079        self.stage.create()
       1080        self.stage.fetch(mirror_only)
       1081        self._fetch_time = time.time() - start_time
       1082

**Comment by hainest** [comment]
>INSTALL cannot copy file "/home/anirudh/Desktop/dyninst-9.3.2/dyninstAPI_RT/libdyninstAPI_RT.so.9.3.2" to "/usr/local/lib/libdyninstAPI_RT.so.9.3.2"

You need to be root to install in /usr/local/lib. Also, Dyninst 9.X is no longer supported. I would recommend upgrading to Dyninst 10.1.

>curl: (60) SSL certificate problem: certificate has expired

That's weird. I'm able to fetch gettext with curl without any certificate errors. You might just try again. If you continue to have issues, check the output of `spack -d install -v dyninst`.

**Comment by hanushgowrav66** [comment]
@hainest 
What are the commands to install  **_spack_**?
Please mention the commands.

**Comment by alderson41** [comment]
@hainest i tried with sudo, and got same output.
I removed cmake cache and tried again and got same results.

I was trying to build dynist as a frontend for mcsema,
In mcsema requirements they have specified to use dyninst 9.3.2

**Comment by aruncgowda** [comment]
@alderson41 
even i am also trying to build dyninst as a frontend for mcsema,but its not working.
if u find any solution please post it.

**Comment by alderson41** [comment]
Successfully built dyninst through cmake.
Closing this issue
