### ISSUE TITLE
Clean up serialization

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#786]
Serialization was disabled in 2ead336f. The code should either be removed or documented as to why it should remain. There are several tests in the test suite that should be correspondingly updated.

@mplegendre You disabled serialization back in 2012. Is there a reason this code should still be around? For the code that is enabled when `SERIALIZATION_DISABLED` is false, should it stay? Is it part of the public Dyninst API?

**Comment by mplegendre** [comment]
That was old functionality to serialize parsing results to disk, which would make re-opening binaries faster.  It never really worked well or got used.  So I think you can safely kill it.

**Comment by hainest** [comment]
Merged into api_breakages by #805
