### ISSUE TITLE
Update dyninst/common/h/dyn_syscalls.h?

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#808]
The reference files for the system calls are from 2013. Does this need to be updated?

**Comment by bigtrak** [comment]
This is the list of syscalls which dyninst deals with itself, it is not linux syscall numbers.   Browsing the list, it appears to be in sync with linux syscall world for current mainstream systems.   The current syscall formats are no longer compatible with the generateSyscallInformation script.   That needs to be updated to work with current linii include files.   Wait for an issue about syscalls to make changes.
