### ISSUE TITLE
Clean up orphaned code

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#810]
While working on a bug with dlopen, I found that there are many files in the repo that are not part of the build system, `#include`d directly in another file, or part of a file glob. This code is effectively orphaned and no longer part of Dyninst. Some of it is from unsupported platforms (e.g., wtxKludges is for vxworks and BG_AuxvReader is for BlueGene/P ION). I will create separate PRs to remove those.

common/src/BG_AuxvReader.C
common/src/BG_AuxvReader.h
common/src/Ident.C
common/src/List.C
common/src/addrtranslate-static.C
common/src/auxvtypes.C
common/src/debugOstream.C
common/src/int64iostream.C
common/src/mmtimer.c
common/src/timing-bluegene.C
common/src/vectorSet.C
common/src/wtxKludges.C
dataflowAPI/rose/semantics/ByteOrder.C
dataflowAPI/rose/semantics/MemoryMap.C
dataflowAPI/rose/util/FileSystem.C
dataflowAPI/rose/util/rose_strtoull.C
dataflowAPI/tests/inst2ast/inst2ast.C
dyninstAPI/src/BPatch_dependenceGraphEdge.C
dyninstAPI/src/BPatch_dependenceGraphNode.C
dyninstAPI/src/BPatch_templates.C
dyninstAPI/src/Relocation/Transformers/Defensive.C
dyninstAPI/src/Relocation/Widgets/CFPatch.C
dyninstAPI/src/pdwinntDL.C
dyninstAPI/src/syscall-vxworks.C
dyninstAPI/src/vxworks.C
dyninstAPI_RT/src/RTheap-svr4.c
dyninstAPI_RT/src/RTmutatedBinary.c
dyninstAPI_RT/src/RTmutatedBinary_ELF.c
dyninstAPI_RT/src/RTthread-power.c
dyninstAPI_RT/src/RTvxworks.c
instructionAPI/src/InstructionTest.C
instructionAPI/src/MainDocPage.C
instructionAPI/src/test/test_aarch64_decoder.C
parseAPI/src/IA_InstrucIter.C
proccontrol/src/bluegenep.C
stackwalk/src/bg_firstparty.C
stackwalk/src/bluegene-swk.C
stackwalk/src/bluegenel-swk.C
stackwalk/src/bluegenep-swk.C
stackwalk/src/firstparty.C
symtabAPI/src/staticRewrite.C
valueAdded/sharedMem/src/shmSegment-nt.C

common/src/cstring.h
common/src/keylist.h
common/src/klist.h

**Comment by hainest** [comment]
@mxz297 @sashanicolas 

Some of these files have been around since the beginning of Dyninst (e.g., dyninstAPI/src/BPatch_templates.C), so I would think they might have some use. Some were part of previous dead code removal attempts (bbc9ff65590f38dfe7d26e0c881f10c17932b4ec). Do either of you see anything in here that definitely *should* be saved? I'll manually verify when these files were orphaned, but I was curious if might know something that could save me a bit of time.

**Comment by hainest** [comment]
dyninstAPI/dyninstAPIsrc/dummy.C should have been removed by 66207c950

**Comment by mxz297** [comment]
`dyninstAPI/src/Relocation/Transformers/Defensive.C` may be related to malware analysis.

**Comment by hainest** [comment]
common/src/cstring.h is dead
