### ISSUE TITLE
Remove deprecated BPatch_addressSpace::findFunctionByAddr

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#820]
This was deprecated by 7f20129bc880aba7e0a8d3757b21797743ffcc10 in 2010. However, it is still being used by `BPatch_addressSpace::findFunctionByAddr`. I'm not sure if it can actually be removed.

@sashanicolas @mxz297 Is this safe to remove, or should we undeprecate it?

**Comment by mxz297** [comment]
I feel `findFunctionByAddr` seems like a useful operation to keep.

**Comment by hainest** [comment]
@mxz297 Sounds reasonable to me. I'll undeprecate it.

**Comment by hainest** [comment]
Ah, no. This should be deprecated. There is a warning message (https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/BPatch_addressSpace.C#L713) which indicates that function will return an arbitrary result if there is more than one function found, and that there are suitable replacements to use, instead.

**Comment by hainest** [comment]
Merged into api_breakages via #837
