### ISSUE TITLE
Document to access variables in Dyninst

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#833]
Is there any document in Dyninst which explain about how to access the variables from a function. I want to access function parameters and local variables. I understand that for different binaries like C/C++, golang, java there may be different approach to access the variables. I tried BPatch_function'sfindVariable but it gives error while writing output binary. Kindly suggest

**Comment by hainest** [comment]
>I tried BPatch_function'sfindVariable

Could you provide the exact Dyninst code you used to do this?

>but it gives error while writing output binary.

What was the error message?

**Comment by ManojKumarChauhan** [comment]
BPatch_function *currentFunc;//representing a function from which I want to get the variable.
BPatch_function *insertedFunc;//the function which needs to insert. Takes same input argument like currentFunc
BPatch_Vector<BPatch_variableExpr *> vars;
const char *varname="variablename";
if(currentFunc->findVariable(varname,vars))
{
BPatch_Vector < BPatch_snippet * >regArgs;
regArgs.push_back(vars[0]);

BPatch_funcCallExpr instExitExpr (*insertedFunc, regArgs);
vector < BPatch_point * >*funcExit = currentFunc->findPoint (BPatch_exit);//instrument  insertedFunc at the end of currentFunc or any 
//other function which takes same variable as argument.
appBin->insertSnippet (instExitExpr, *funcExit, BPatch_callAfter, BPatch_lastSnippet);
}

appBin->writeFile (outBinary);
//error -> Error: unable to find AST representing variable at 0x6ab7ef. This address is less than the addresses which are in AstVariableNode::ranges_

**Comment by hainest** [comment]
@sashanicolas @mxz297 Do you see anything intrinsically wrong with this code?

**Comment by mxz297** [comment]
I do not have much experiences of using `findVariable`. 

@ManojKumarChauhan Did you compiled your program to be instrumented with debug information (`-g`)?

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297,

Yes it's compile with -g option.

**Comment by sashanicolas** [comment]
I'd have to debug the binary. Can you upload the mutated you're trying to instrument?

**Comment by ManojKumarChauhan** [comment]
[testfunctionvariable.tar.gz](https://github.com/dyninst/dyninst/files/5174624/testfunctionvariable.tar.gz)

**Comment by ManojKumarChauhan** [comment]
The binary contains two functions
github.com/labstack/echo.New
main.printEcho
echo.New creates an object e *Echo. printEcho takes this object as input argument (func printEcho(e *echo.Echo) int{)
When i'm trying to get the variable e from echo.New, pass e to printEcho and instrument printEcho at the BPatch_exit point of echo.New, it's giving following error
Error: unable to find AST representing variable at 6a49d8
Pointer 0x7fc8dfab45e0
Options are: 
	bf8911-bf8921
	bf8911-bf8921

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas,
Should I create a bug for this issue? It's not working even for c/c++ binary.

**Comment by hainest** [comment]
@ManojKumarChauhan This issue will serve as a bug report. There are only three Dyninst developers, and we try to triage bugs accordingly. We thank you for your patience as we try to incorporate your request into our workflows.

What is the source language for the binary you uploaded?

**Comment by ManojKumarChauhan** [comment]
it's golang

**Comment by hainest** [comment]
@mxz297 Do you have an experimental branch with some updates for parsing golang binaries?

**Comment by mxz297** [comment]
@hainest This branch (https://github.com/mxz297/dyninst/tree/layout_opt) contains preliminary support for golang binaries. The key issue for golang binaries is not parsing them, but supporting its built-in stack unwind.

**Comment by hainest** [comment]
@mxz297 Ah, ok. Do you think that would have any effect on the error seen here?

**Comment by mxz297** [comment]
@hainest Unlikely. It is still unclear what exactly the problem is.

@ManojKumarChauhan You mentioned that it does not even for a C/C++ binary. Can you post a complete reproduce, which includes the source code for both the Dyninst mutator (the program that uses Dyninst) and the mutatee (the source program that compiles into the binary to be rewritten)?

**Comment by ManojKumarChauhan** [comment]
[codefile.tar.gz](https://github.com/dyninst/dyninst/files/5194375/codefile.tar.gz)

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
I have uploaded the code for C & golang input binaries with Dyninst code. Please let me know if you need any other information.

**Comment by mxz297** [comment]
@ManojKumarChauhan It does not look like that I can easily reproduce the bug:

```
./testvariables

inside main

GetParamsFromFunction called at first

inside main end 2

./testvariables.inst 

inside main

GetParamsFromFunction called at first
InsertParaminFunction called is 0xdd9010
InsertParaminFunction called at 2

inside main end 2
```

This looks normal to me. Can you also provide your compiled C/C++ mutate binary and post your compiler information?

By the way, can you also simplify your reproducer to be a minimal reproducible example? What you provided contains many codeCoverage code that is not related to this bug.

**Comment by ManojKumarChauhan** [comment]
compiler version Ubuntu 5.4.0-6ubuntu1~16.04.12

I will share the asked information tomorrow. Another code is related to golang binary and I have already uploaded the binary and its code. Can you please check golang binary also?

**Comment by ManojKumarChauhan** [comment]
At my end findvariables did not find the variable 'simple'. It gave following error
'SERIOUS  #100  unable to find variable:simple'
When I checked getvars() & getparams() they are not returning any variable.
This was tested on the fresh code.

When I was using dyninst-10.1.0 or previous branch (not sure which branch) , it was able to find the variable.

**Comment by ManojKumarChauhan** [comment]
[testvariables.tar.gz](https://github.com/dyninst/dyninst/files/5200355/testvariables.tar.gz)

**Comment by mxz297** [comment]
@ManojKumarChauhan This is useful information. Thanks! For golang, the DWARF information is different sections compared to C/C++ binaries. Supporting Golang's DWARF will be a feature enhancement. We will need to first focus on resolving the regression on C/C++ binaries. 

@sashanicolas Based on this information, it looks like DWARF variable parsing has some regression between 10.1 and 10.2. Can you double check whether this is actually the same issue you are investigating?

**Comment by mxz297** [comment]
@sashanicolas Do you have any update on this issue?

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas,

Any update on this?

**Comment by sashanicolas** [comment]
@ManojKumarChauhan the last binary you uploaded was compiled without -g, that's why you thought 10.2 had a regression, but no. @mxz297 I tested 10.1 and 10.2 they both find the variables in the Go binary and the C++ binary.

I got to reproduce your bug, using your codeCoverage modified code. I did: `mutator -p testfunctionvariable out`, I got:
```
searching variable in echo.New
number of variables 1
insertInitCallback on testfunctionvariable
Error: unable to find AST representing variable at 6a49c0
Pointer 0x564b06828010
Options are: 
        bf8911-bf8921
mutator: <path-hidden>/dyninst/dyninstAPI/src/ast.C:3235: virtual void AstVariableNode::setVariableAST(codeGen&): Assertion `found' failed.
Aborted (core dumped)
```
When I run `out`
```
$ out

inside main

GetParamsFromFunction called at first
InsertParaminFunction called is 0xd7212e70
Segmentation fault (core dumped)
```
@ManojKumarChauhan Did you use only `-p` for codeCoverage? I'm investigating what's wrong with the AST representation of the variable.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
Yes I used -p option and same command which you have used.
I found variables for golang binary but not for c binary.

For golang when I try to pass variable in instrumented function then application got crash.

**Comment by sashanicolas** [comment]
@ManojKumarChauhan because the c++ binary you used had no debug symbols, just double check the last binary you uploaded.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
May be I used c binary without -g option. I will check it.  Well i'm able to get the variables for golang binary and the application is crashing when I pass the variable in instrumented function.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas,
After creating c++ binary with -g option, dyninst can find the variable but when I tried to use pass that variable into another function, the program got crashed because the address of the variable is not exactly same which was in original function. Example variable address in the function 0x7f0c44000d30. Variable address which is passed 0x44000d30.

For golang binary, if i create a binary with linkshared option then Dyninst cannot find any variable.
If I create golang binary without linkshared option then Dyninst can find the variable but got crashed when I pass the variable into another function. It gives following error
unable to find AST representing variable at 6b2b00
Pointer 0x7f48fdf7bee0
Options are: 
	c05911-c05921

So I am not able to pass and use variable for C and Golang binaries.

**Comment by sashanicolas** [comment]
Hi @ManojKumarChauhan,
In the case of the C++ binary, the function you are trying to instrument has one exit point. This exit point ends with the instruction LEAVEQ followed by instruction RETQ. 
Dyninst is inserting the instrumentation code after the LEAVEQ, but this is corrupting the stack, clobbering the value of the local variable.
We don't have a solution for this right now, we're discussing about it. But we are trying to have a workaround to help users on cases like this you have encountered.
The Go binary function you tried to instrument has two exit points. One ends as:
```
mov    0xa0(%rsp),%rbp
add    $0xa8,%rsp
retq
```
which is similar to the C++ case, and therefore explains the problem too.

I'll post here when I have another update.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
Thanks. I will wait for the solution.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
Is there any update? Is it going to take long time?

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,

If I do not instrument any function and just go through each function & print the number of arguments for any function then it always give 0 argument.
BPatch_function *curFunc;
BPatch_Vector<BPatch_localVar *> *vars =  curFunc->getVars();
vars->size() is zero for all golang functions

**Comment by sashanicolas** [comment]
Hi @ManojKumarChauhan,  
As for the update you asked, I'm still trying to come up with a workaround for the thing I explained before.
For the parameters you just mentioned, did you use the same go binary? Can you send me the mutator (the program you used to go through the functions and print the arguments) code?

**Comment by ManojKumarChauhan** [comment]
[testcode.tar.gz](https://github.com/dyninst/dyninst/files/5499083/testcode.tar.gz)

**Comment by ManojKumarChauhan** [comment]
Hi Nicolas,
I have attached the code. To test the program please follow the steps:
1. use echoapp or compile it again using 'go build echoapp.go'. Launch echoapp
2. launch codeCoverage and pass echoapp as an argument

It will print the number of variables in each function.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
Hope you are able to reproduce the issue without doing any instrumentation.

**Comment by ManojKumarChauhan** [comment]
Hi @sashanicolas ,
This thread is running since last 4 months. Do you have any plan to fix this issue? OR should I close this?

**Comment by ManojKumarChauhan** [comment]
Closing this issue as it was created a very long time ago and I did not find any solution.
