### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by dengxiansong** [dyninst/dyninst#834]
I in centOS8.1 version x86_64 platform to compile "GCC-Toolset-9-dyninst-10.1.0-1. El8.src.rpm" source package encountered the following error:
`[ 86%] Linking CXX shared library libtestsymtab.so
/usr/bin/c++ -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=c++11 -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -shared -Wl,-soname,libtestsymtab.so -o libtestsymtab.so CMakeFiles/testsymtab.dir/src/symtab/symtab_comp.C.o libtestSuite.so ../install/usr/lib64/dyninst/libsymtabAPI.so.10.1.0 ../install/usr/lib64/dyninst/libcommon.so.10.1.0 /usr/lib64/libboost_system.so -lpthread -ldl /usr/lib64/libxml2.so -l../install/usr/lib64/libtbbmalloc_proxy.so /usr/lib64/libtbbmalloc.so /usr/lib64/libtbb.so
/usr/bin/ld: cannot find -l../install/usr/lib64/libtbbmalloc_proxy.so
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/testsymtab.dir/build.make:94: libtestsymtab.so] Error 1
make[2]: Leaving directory '/home/deng/rpmbuild/BUILD/dyninst-10.1.0/testsuite-10.1.0'
make[1]: *** [CMakeFiles/Makefile2:5950: CMakeFiles/testsymtab.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[gcc-toolset-9-dyninst-10.1.0-1.el8.log](https://github.com/dyninst/dyninst/files/5161706/gcc-toolset-9-dyninst-10.1.0-1.el8.log)

**Comment by hainest** [comment]
We don't maintain any distributions of Dyninst. You'll need to contact the package's author for detailed help. That said, the root error is that the package specified a relative directory location for libtbbmalloc_proxy when building the testsuite. The package should use an absolute path.

You might check if the package supports a configuration flag to not build the testsuite (it's not needed, if you are just using Dyninst).

**Comment by dengxiansong** [comment]
Thank you. My problem has been solved.
