### ISSUE TITLE
How to use copyFunction of PatchAPI in Dyninst

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#839]
Base class CFGMaker contains copyFunction. This is also implemented in derived class DynCFGMaker. copyFunction uses same address which is in  input function. Due to same address it cannot be added in modified function list & cant come in dyninst section of binary.  Using different  address for copyFunction does not work because the copied function contain same blocks which are in input function. I tried to clone blocks but that did not work.
Can Someone suggest a way to use copyFunction?

**Comment by mxz297** [comment]
copyFunction is probably not well implemented. I have not used it before and plan to investigate its usage in the near future. It will take sometime, but will keep you in loop when I find something.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
The expected behavior of copyFunction is to make a copy of funtion (with relocation) in dyninst section of memory but it does not seem to be relocating.

**Comment by mxz297** [comment]
This is more complicated than justing relocating a copied function. Dyninst uses trampolines (typically a branch) that transfers control flow from original code to new instrumentation code, which is the relocated code. For a function A, we denote the relocated version A'. Now, if we need to copy A one more time, which will be relocated as A'', where the trampolines in A should go? Should trampolines go to A' or A''? 

The copyFunction looks like to only make a copy of the function at the CFG level, without handling all the actual difficulties of realizing copying a function from an instrumentation perspective. 

While I plan to develop this idea of copying functions in the future, it is going to take several months of effort.

**Comment by ManojKumarChauhan** [comment]
Tramploines should continue to go to A'. The use of copy function is to create a copy of the original function so that if there is a requirement to execute the original function (typically in wrapper function) then the copied function A'' can be called and executed to fullfill that requirement.

**Comment by mxz297** [comment]
You described one way of using copying functions, where you want one instrumented version and one uninstrumented version. I can also imagine use cases where we want multiple copies of a function, where we instrument each copy in different ways.

You indicated function wrapping, and I am not sure whether that's what you intended to do. But if that's the case, there is existing interface for function wrapping:

https://github.com/dyninst/dyninst/blob/0333d4d2bf40fe9cdc2295562fc19ec2d3f77b0a/dyninstAPI/h/BPatch_addressSpace.h#L296

**Comment by ManojKumarChauhan** [comment]
Yes wrapFunction is there but i believe copyfunction is still required. Let me take an example.
There is a function malloc(). I want to wrap malloc() by another function newmalloc(). Suppose newmalloc() will do some action and finally call malloc().
For this case it's required to create a copy of malloc() using copyfunction.

**Comment by mxz297** [comment]
You are correct that for wrapping a function, we must be able to execute the original code. The implementation of wrapFunction does that without using copyFunction, and is just sufficient for function wrapping. It does not support the generic copyFunction as I described. 

Basically, copyFunction aims to provide more general use cases, but its current implementation is just not there yet. If what you want is function wrapping, then the wrapFunction interface provides that.

**Comment by ManojKumarChauhan** [comment]
I think wrapFunction does not solve the problem which I am facing. In previous example:
If I wrap malloc() by another function newmalloc(). When newmalloc() will call malloc() there will be an infinite loop. If newmalloc() calls the copied part of malloc() then there will not be any loop.
Is there any way to remove this loop without using copyfunction?

**Comment by mxz297** [comment]
wrapFunction wraps functions and what you described is the what exactly wrapFunction needs to handle. I said that wrapFunction handled this by copying the original function, but does not use copyFunction or provide more general copyFunction use cases.

**Comment by ManojKumarChauhan** [comment]
Actually wrapFunction is not handling this, thats why I used copyfunction.
I called wrap function like:

Dyninst::SymtabAPI::Symtab *symtab = Dyninst::SymtabAPI::convert(newmallocfunc->getModule()->getObject());
symtab->findSymbol(syms, "mallocfunc", Dyninst::SymtabAPI::Symbol::ST_UNKNOWN,Dyninst::SymtabAPI::mangledName, false,false,true);
wrapFunction(mallocfunc, newmallocfunc, syms[0]);

This is actually going into infinite loop.

**Comment by mxz297** [comment]
I see. Then this is a bug for wrapFunction. Can you also provide a full reproducer for this one?

**Comment by ManojKumarChauhan** [comment]
[wrapfunc.tar.gz](https://github.com/dyninst/dyninst/files/5226075/wrapfunc.tar.gz)

**Comment by ManojKumarChauhan** [comment]
I have added the C code and codecoverage code. It can be easily reproduce.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
As you said wrapfunction should handle it. Will wrap function create a new function with different blocks?
Which APIs are used by dyninst to create separate blocks for a function?

**Comment by mxz297** [comment]
@ManojKumarChauhan It looks like you are using `wrapFunction` in a way wrong. Here is a minimal example that illustrates how to do function wrapping with Dyninst: 

https://github.com/mxz297/dyninst-tools/tree/master/FunctionWrapping

I have tested this example with Dyninst master branch.

```
$ cat test.c 
#include <stdlib.h>

int main() {
    int* a = (int*) malloc(sizeof(int)*10);
    return 0;
}

$ ./test 

$ ./FuncWrap ./test
Enter malloc_wrapper, allocate 40 bytes
Exit malloc_wrapper
```

**Comment by ManojKumarChauhan** [comment]
Thanks.  It's working
