### ISSUE TITLE
jump table：instruction is not reachable

### ISSUE THREAD

**Issue by ccxiaop** [dyninst/dyninst#845]
We need to analyze a jump table program. However, some jump code is lost during the analysis by using the ParseAPI. How can I restore the code? Or what other effective method?

for example,like switch table
    switch(value){
        case 'a':
        case 'A':
            testValue = 1;
            break;
        case 'b':
        case 'B':        
            testValue = 2;
            break;
        default:
            testValue = 3;
            break;
    }

**Comment by mxz297** [comment]
ParseAPI should be able to fully analyze this jump table. If this is not the case, this sounds like a bug. Can you post the binary as a reproducer?

**Comment by ccxiaop** [comment]
test file is relocatable file.thanks.
[test2.zip](https://github.com/dyninst/dyninst/files/5215726/test2.zip)

**Comment by mxz297** [comment]
@ccxiaop Ah, ParseAPI resolves jump tables based on the actual code. In .o files, the instructions are incomplete where certain fields of the instructions will be filled by the linker during linking based on relocation entries. In your .o file:

```
  1e:   48 8b 04 c5 00 00 00    mov    0x0(,%rax,8),%rax
  25:   00 
  26:   ff e0                   jmpq   *%rax
```

ParseAPI will analyze the move instruction at `1e` and say that the jump table is at address 0x0, which is obviously wrong. I would recommend that you work with executables or shared libraries.

**Comment by hainest** [comment]
Closed due to inactivity. Please reopen this issue or submit a new one if this problem persists.
