### ISSUE TITLE
How can I add a function to the binary?

### ISSUE THREAD

**Issue by Charles-Neil** [dyninst/dyninst#846]
After reading the examples in the document I am able to insert some snippets into the binary. But I didn't find a way to add a function to the binary. How can I accomplish that? Can somebody give me a hint?

**Comment by mxz297** [comment]
I don't think there is an easy way to add a function to a binary. A common way is to write an instrumentation library in C/C++, and use Dyninst to insert function calls to the instrumentation library.

**Comment by Charles-Neil** [comment]
Thanks a lot, I will turn to the instrumentation library approach.
