### ISSUE TITLE
Dyninst - Application got hanged in waitpid call of GeneratorLinux::getEvent

### ISSUE THREAD

**Issue by Yadavdeepak007** [dyninst/dyninst#848]
When I am using dyninst for a running c program, the application got hanged in BPatch_process's loadLibrary function.
sample code
BPatch_addressSpace* app = bpatch.processAttach (NULL, pid); //pid is the process id of running c program
BPatch_process* process = dynamic_cast<BPatch_process*>(app);
const char *instLibrary = "libInst.so";
    if (!process->loadLibrary (instLibrary)) {
        cerr << "Failed to open instrumentation library" << endl;
        return EXIT_FAILURE;
    }
cout << "control does not come here and program is running" << endl;

dyninst branch - 10.1

**Comment by hainest** [comment]
Could you re-run your program with `DYNINST_DEBUG_PROCCONTROL=1` set in the environment, and then attach the log here? It will likely be a lot of logging, so you may want to pipe it directly to a file.

**Comment by Yadavdeepak007** [comment]
[deepak_logs.txt](https://github.com/dyninst/dyninst/files/5222959/deepak_logs.txt)

**Comment by Yadavdeepak007** [comment]
I have attached file with DYNINST_DEBUG_PROCCONTROL=1 .Kindly look into it

**Comment by Yadavdeepak007** [comment]
Instrumenting a  function is also not working when I attach to a process. I created a C binary which contains 2 functions func1 and fun2. When I tried to instrument func1 into func2 then application got hang.

**Comment by Yadavdeepak007** [comment]
Dyninst has a sample program ParseThat. I use parseThat with following arguments
./parseThat -P pidofcprogram -i 1 -S pathofcbinary
parseThat program also got stuck when it tried to insert a function. Last message from parseThat when it tried to instrument a function "Inserting counter-increment snippet into function en".
In brief, processAttach is not working at all.

**Comment by hainest** [comment]
Apologies for the delay. This issue was fixed in 10.2 (see #742 for details).
