### ISSUE TITLE
why is "main" in a shared lib?

### ISSUE THREAD

**Issue by Charles-Neil** [dyninst/dyninst#853]
I find the main function in an executable, but found out the `isSharedLib()` method of class `BPatch_function` is not working as expected. It says 'main' is in a shared lib. I am confused:

**code**:
```
    const char* progName = argv[1];
    const char* funcName = argv[2];

    BPatch_binaryEdit* handle = bpatch.openBinary(progName);

    vector<BPatch_function*> funcs;
    handle->getImage()->findFunction("main", funcs);
    assert(false == funcs[0]->isSharedLib());
```

The above assertion failed and I have no idea why. If I did it the wrong way, could you tell me what is the correct way to determine whether a function is inside a shared library?

**Comment by hainest** [comment]
This is very likely related to #605. We are currently working on fixing this. If you are using gcc, recompile with `-fno-PIE` and re-link with `-no-pie` as a temporary workaround.

**Comment by Charles-Neil** [comment]
The options provided worked for me. Thx.
