### ISSUE TITLE
Build failure on windows

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#86]
https://github.com/dyninst/dyninst/commit/3c38960b1e468579cdb62f67d5f123ea6c2463c8 broke the windows build.

C:\Users\Peter\Source\Repos\dyninst\common\src\addrtranslate-win.C(173): error C2440: 'return': cannot convert from 'HMODULE (__stdcall *)(LPCSTR,HANDLE,DWORD)' to 'Dyninst::Address'

Looks like AddressTranslateWin::getLibraryTrapAddrSysV needs to be changed, but I'm not sure what the correct fix is.

**Comment by wrwilliams** [comment]
Reinterpret cast on the function pointer should be good there. If there's not a patch waiting Monday I'll get it then.
