### ISSUE TITLE
Dyninst- Application is crashing for golang binary created with -linkshared option

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#869]
**Intention**
Created a golang binary with -linkshared option. Instrument/wrap methods in binary.

**Describe the bug**
https://github.com/dyninst/dyninst/issues/807 was fixed for a golang binary which is  not created with -linkshared option.

**To Reproduce**
Open the binary using bpatch.openBinary or attach to the binary using bpatch.processAttach. Application is crashing when trying to switch to another page.

**Expected behavior**
Application should not crash.

**System (please complete the following information):**
 ubuntu 16.04 x86_64
Dyninst 10.2 master/layout_opt branches

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,

For binary edit case, it's searching some runtime function which is available in dependent library. For running process it does not search those functions but still it's not working.

**Comment by mxz297** [comment]
You should be able to first instrument libstd.so, which will instrument the necessary runtime functions, and then instrument your golang binary. Then you need to ensure using the instrumented libstd.so

For dynamic case, you may be able to do the same by instrumenting functions in the libstd.so module. I am currently not interested in the dynamic case.

**Comment by ManojKumarChauhan** [comment]
For dynamic case, is it required to  instrument libstd.so first?
As you said
"For dynamic case, you may be able to do the same by instrumenting functions in the libstd.so module."
could you please suggest how to do that?

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
The latest change is unable to find DYNINSTtrapFunction function when we attach to a process.

For dynamic case, I also tried to instrument some functions of libstd.so but the issue is not solved. In every case it's giving the error
echo: http: panic serving 127.0.0.1:39778: interface conversion: interface {} is *echo.context, not *echo.context (types from different packages)

I did not understand this. Please suggest.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297,
Found some reason for the crash and unexpected behavior for golang binary.
Create 2 golang binaries and wrap one method for each binary.

Precondition->remove the call for replacePLTStub from wrapFunctionPostPatch. This is because replacePLTStub never call bindPLTEntry so I commented out this.
For binary 1, while wrapping a method, the symbol is found using mangledName (Dyninst::SymtabAPI::Symtab->findSymbol). The method is wrapped successfully but the program is crashed when the wrapped method is executed. I do not get why it's wrapped as replacePLTStub is blocked.

For binary 2, while wrapping a method, the symbol is found using anyName and not by mangledName. The method is not wrapped.

**Comment by mxz297** [comment]
@ManojKumarChauhan I am sorry that I don't really understand what you described. I don't have experience with the function wrapping code beyond how to use it. Specifically, I have not looked into its internal implementation. 

In terms debugging, you can set DYNINST_DEBUG_RELOCATION=1 DYNINST_DEBUG_SPRINGBOARD=1, which will prints verbose logging to stderr. If the instrumented program crashed, you can get a core file to see where it is crashed, and lookup the PC in the debug log to see what code is being executed and debug from there.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,

I meant that Wrap functionality does not work correctly for a golang binary. If I create some golang binaries, attach dynst to golang binary and wrap a function then either the wrapped function does not execute or if it executes then the application does not work.

Thanks for sharing the debugging information. I will check it.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297,
After enabling the debugging logs, I did not find anything which is not correct. Wrap code is executed as written but the function did not wrap.
Is there any other logs which can be checked?

**Comment by mxz297** [comment]
@ManojKumarChauhan I don't claim that function wrapping is correctly in every case. It is just that I am not in the position to fix it. Regarding to more debug logs, you can look at here:

https://github.com/dyninst/dyninst/blob/master/dyninstAPI/src/debug.C#L251

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297,

Thanks I will look for the wrapping case. There is one more case which is not related to wrapping and you have already fixed it for golang.

Instrument any function in main.main. This is working when go binary is created without using linkshared option but if we create a go binary with linkshared option then the application is crashing. You were supposed to write 2 functions in that case. A sample application is available in https://github.com/dyninst/dyninst/issues/807.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,

I tried to instrument a function for main.main. Stack unwinding is working in one case but not in others.  I created a golang binary with main function and another function (testfunc) which prints a message.
There are following cases:

1. Create a golang binary without using linkshared (go build appname.go). Open the binary using bpatch.openBinary. Instrument testfunc at the entry point of main.main. 
It's working as stack unwinding is applied.

2. Create a golang binary using linkshared (go build -linkshared appname.go). Open the binary using bpatch.openBinary. Instrument testfunc at the entry point of main.main. 
Application crashed as the stack unwinding does not apply.
To solve the crash, I called instrumentGoRuntimeStackTrace for each function of libstd but it did not solve the problem.

3. Create a golang binary with/without using linkshared. Run golang binary & use AttachProcess to attach to it. Instrument testfunc at the entry point of main.main (it will not execute as the process is already running but did this just for checking stack unwinding). Got below error
RTlinux.c:421: dyninstTrapHandler: Assertion `0' failed.
SIGABRT: abort


Could you please help for above case 2 & case 3.
I think if stack unwinding does not apply then instrumentation or wrapping functionality will not succeed for golang binary.

**Comment by mxz297** [comment]
@ManojKumarChauhan For case 2, I thought that it should work. I will investigate it a little bit in this weekend and see if I can get it working.

For case 3, I have not really aimed for dynamic instrumentation yet. Hopefully in the near future I will get to it.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297,
Did you check it for case 2? Is it possible to support linkshared option?

**Comment by mxz297** [comment]
@ManojKumarChauhan I got some preliminary support working for linkshared. Please try the following steps:

1. Pull from my branch and reinstall 
2. Use the following simple Dyninst program to rewrite `libstd.so`, which is the golang's runtime library for dynamically linked executable:

```
#include "BPatch.h"
#include "BPatch_binaryEdit.h"
using namespace std;
BPatch bpatch;

int main(int argc, char ** argv) {
    BPatch_binaryEdit *binary = bpatch.openBinary(argv[1], false);
    binary->writeFile(argv[2]);
}
```

On my end, the path looks like `./BPatchOpen /usr/lib/golang/pkg/linux_amd64_dynlink/libstd.so libstd.so`

Of course, if you want instrument functions in libstd.so, you can add other code to do so.

3. Instrument your golang binary which is compiled with linkshared option as usual.

4. Run your instrumented golang binary with the rewritten `libstd.so`. Here you must LD_PRELOAD the rewritten libstd.so because golang appends `RPATH` to find the original `libstd.so`:

`export LD_PRELOAD=<PATH_TO_DYNINST_INSTALL>/lib/libdyninstAPI_RT.so:<PATH_TO_LIBUNWIND_INSTALL>/lib/libunwind.so:./libstd.so`

And then you can run the instrumented golang binary.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,

After getting the changes, I created libstd.so and added it in LD_PRELOAD.
But when I run the program for a golang  binary with -linkshared, it gave following error
libstd.so: undefined symbol: main.main

echo $LD_PRELOAD
/opt/temp/dyninst/install/lib/libdyninstAPI_RT.so:/opt/temp/libunwind/install/lib/libunwind.so:/opt/temp/dyninst/install/bin/librungo/libstd.so

**Comment by mxz297** [comment]
I only saw this error when I accidentally run rewritten libstd.so with a non-golang binary:

```
[xm13@iris test]$ cat test.go 
package main
import "log"
import "time"
func Test(){
for i:=0;i<5;i++{
}
}
func main(){
ss :="printtext"
go Test()
log.Println(ss)
time.Sleep(1*time.Second)
}
[xm13@iris test]$ LD_LIBRARY_PATH=.:/home/xm13/projects/libunwind/install/lib:/home/xm13/projects/dyninst/install/lib:$LD_LIBRARY_PATH LD_PRELOAD=/home/xm13/projects/dyninst/install/lib/libdyninstAPI_RT.so:/home/xm13/projects/libunwind/install/lib/libunwind.so:./libstd.so ./test
2020/10/14 07:57:44 printtext
[xm13@iris test]$ LD_LIBRARY_PATH=.:/home/xm13/projects/libunwind/install/lib:/home/xm13/projects/dyninst/install/lib:$LD_LIBRARY_PATH LD_PRELOAD=/home/xm13/projects/dyninst/install/lib/libdyninstAPI_RT.so:/home/xm13/projects/libunwind/install/lib/libunwind.so:./libstd.so /bin/ls
/bin/ls: symbol lookup error: ./libstd.so: undefined symbol: main.main
```

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
You are correct. I was doing something wrong.
Now the output application is not crashing but there are some cases which are not working.

1. If I instrument a function at the entry point of main.main then it's not getting executed. While the instrumentation is working for any other function .
2. If my golang binary has the dependency on 2 libraries say libstd.so and libmystd.so (created by me) then then application is not crashing but instrumentation is not working. In this case I created libstd.so and libmystd.so through dyninst & added them in LD_PRELOAD.

**Comment by ManojKumarChauhan** [comment]
The code is attached. main.main is working but the program is crashing when i access  the webpage with 
[testcode.zip](https://github.com/dyninst/dyninst/files/5380395/testcode.zip)
localhost:port

**Comment by ManojKumarChauhan** [comment]
[testcode3.zip](https://github.com/dyninst/dyninst/files/5402713/testcode3.zip)
