### ISSUE TITLE
compilation error in latest dyninst code

### ISSUE THREAD

**Issue by Yadavdeepak007** [dyninst/dyninst#892]
branch -10.2.1

[compile_error.txt](https://github.com/dyninst/dyninst/files/5401113/compile_error.txt)

**Comment by ManojKumarChauhan** [comment]
[testcode3.zip](https://github.com/dyninst/dyninst/files/5402694/testcode3.zip)

**Comment by hainest** [comment]
>no match for call to ‘(const std::hash<entryID>) (const entryID&)’

`entryID` is an unscoped enum. The C++11 standard requires that a conforming standard library provide a `std::hash` overload for enums. What version of gcc and libstdc++ are you using?

**Comment by Yadavdeepak007** [comment]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
(got this using /sbin/ldconfig -p | grep stdc++)

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
(got this using gcc --version)

**Comment by hainest** [comment]
I ran some tests, and the libstdc++ that comes with gcc-5 does not support this. For now, you'll need to use gcc-6 or newer. I'll start an internal conversation about minimum compiler support.

**Comment by hainest** [comment]
We now explicitly require gcc >= 6 (see #932).
