### ISSUE TITLE
invalid offset or invalid DWARF when processing DWARF

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#896]
**Intention**
Print the location of the parameters of a function.

**Describe the bug**
For some functions in some libraries when you try to process the DWARF there are error messages saying invalid offset or invalid DWARF.

**To Reproduce**
on a standard Fedora 32 machine run the program from issue 894. ./checkabi.C on any of the following system libraries. 
/lib64/sasl2/libanonymous.so.3.0.0 from cyrus-sasl-lib-2.1.27-4.fc32.x86_64 with cyrus-sasl-lib-debuginfo-2.1.27-4.fc32.x86_64 installed

/lib64/libkdb5.so.10.0 or /lib64/libkrad.so.0.0 or /lib64/libkrb5support.so.0.1
from krb5-libs-1.18.2-22.fc32.x86_64 with krb5-libs-debuginfo-1.18.2-22.fc32.x86_64 installed

/lib64/libpcre2-8.so.0.10.0 from pcre2-10.35-7.fc32.x86_64 with pcre2-debuginfo-10.35-7.fc32.x86_64

/lib64/libselinux.so.1 from libselinux-3.0-5.fc32.x86_64 with libselinux-debuginfo-3.0-5.fc32.x86_64 installed

**Expected behavior**
No errors

**System (please complete the following information):**
Fedora 32 x86_64
dyninst@master built by spack

**Additional context**
I checked the DWARF with eu-readelf --debug-dump and in the cases that looked at I didn't see any problems. I think that it has to do with the DWZ compression.

**Comment by hainest** [comment]
@sashanicolas @mxz297 Do either of you have a Fedora 32 machine we can test this on? If not, we should figure out where to install a VM.

**Comment by hainest** [comment]
@woodard To confirm, this is with gcc-10.2, correct?

**Comment by sashanicolas** [comment]
@hainest not that I know of.

**Comment by woodard** [comment]
This problem does not reproduce with the latest head: 4311e94817bf60dffb557c4ffffd19bc04b7df3f on Fedora 33.
