### ISSUE TITLE
assertions processing symtab for /lib64/libcurl.so.4

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#897]
**Intention**
print out the location of a function's parameters. 

**Describe the bug**
This one is extremely unique but it may be a duplicate of the same problem as is in issue 894. 
(gdb) set env OMP_NUM_THREADS 1
(gdb) r
Starting program: /home/ben/Scratch/Work/dwqual/checkabi /lib64/libcurl.so.4.6.0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
checkabi: /home/ben/Scratch/Work/spack/opt/spack/linux-fedora32-skylake/gcc-10.2.1/boost-1.74.0-minplx7hzgl6sj2rf5up3sedrkphvlvy/include/boost/smart_ptr/shared_ptr.hpp:728: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Dyninst::SymtabAPI::Type; typename boost::detail::sp_member_access<T>::type = Dyninst::SymtabAPI::Type*]: Assertion `px != 0' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff77e7895 in __GI_abort () at abort.c:79
#2  0x00007ffff77e7769 in __assert_fail_base (fmt=0x7ffff79550b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7f86c07 "px != 0", 
    file=0x7ffff7f86d98 "/home/ben/Scratch/Work/spack/opt/spack/linux-fedora32-skylake/gcc-10.2.1/boost-1.74.0-minplx7hzgl6sj2rf5up3sedrkphvlvy/include/boost/smart_ptr/shared_ptr.hpp", line=728, function=<optimized out>) at assert.c:92
#3  0x00007ffff77f6e76 in __GI___assert_fail (assertion=assertion@entry=0x7ffff7f86c07 "px != 0", 
    file=file@entry=0x7ffff7f86d98 "/home/ben/Scratch/Work/spack/opt/spack/linux-fedora32-skylake/gcc-10.2.1/boost-1.74.0-minplx7hzgl6sj2rf5up3sedrkphvlvy/include/boost/smart_ptr/shared_ptr.hpp", line=line@entry=728, 
    function=function@entry=0x7ffff7f87018 "typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Dyninst::SymtabAPI::Type; typename boost::detail::sp_member_access<T>::type = Dyninst::SymtabAPI::T"...) at assert.c:101
#4  0x00007ffff7f72123 in boost::shared_ptr<Dyninst::SymtabAPI::Type>::operator-> (this=<optimized out>)
    at /home/ben/Scratch/Work/spack/opt/spack/linux-fedora32-skylake/gcc-10.2.1/boost-1.74.0-minplx7hzgl6sj2rf5up3sedrkphvlvy/include/boost/smart_ptr/shared_ptr.hpp:726
#5  0x00007ffff7f74f08 in boost::shared_ptr<Dyninst::SymtabAPI::Type>::operator-> (this=<optimized out>) at /usr/include/c++/10/bits/stl_deque.h:260
#6  Dyninst::SymtabAPI::DwarfWalker::parseEnumEntry (this=0x7fffffff8e40)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:1273
#7  0x00007ffff7f7d4e8 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffff8e40, e=..., p=false)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:393
#8  0x00007ffff7f7e4ce in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffff8e40, func_type=<optimized out>)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.h:130
#9  0x00007ffff7f7d58d in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffff8e40, e=..., p=true)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:352
#10 0x00007ffff7f7d821 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffff8e40, e=..., p=true)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:444
#11 0x00007ffff7f7d821 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffff8e40, e=..., p=true)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:444
#12 0x00007ffff7f7d821 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffff8e40, e=..., p=true)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:444
#13 0x00007ffff7f7daee in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffff8e40, moduleDIE=..., fixUnknownMod=@0x7fffffff8e28: 0x83c9c0)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:259
#14 0x00007ffff7f7de87 in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) () at /usr/include/c++/10/bits/stl_vector.h:1043
#15 0x00007ffff75c3f46 in GOMP_parallel (fn=0x7ffff7f7dd60 <Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void)>, 
    data=0x7fffffff9730, num_threads=1, flags=0) at ../../../libgomp/parallel.c:171
#16 0x00007ffff7f7a386 in Dyninst::SymtabAPI::DwarfWalker::parse (this=this@entry=0x7fffffff9790)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/dwarfWalker.C:162
#17 0x00007ffff7f2baa1 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x46b6a0)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/Object-elf.C:4538
#18 0x00007ffff7ed7db9 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x4807b0)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/Symtab.C:2345
#19 0x00007ffff7ec8da8 in Dyninst::SymtabAPI::FunctionBase::getParams (this=this@entry=0xf10350, params_=std::vector of length 0, capacity 0)
    at /tmp/ben/spack-stage/spack-stage-dyninst-master-dhrwfx6hfru7wndi6sxs6embml5ky4ec/spack-src/symtabAPI/src/Function.C:122
#20 0x00000000004037b2 in main (argc=<optimized out>, argv=<optimized out>) at checkabi.C:87

**To Reproduce**
run the same reproducer code from issue 894 on /lib64/libcurl.so.4.6.0 with the debuginfo packages installed libcurl-debuginfo-7.69.1-6.fc32.x86_64

**Expected behavior**
It doesn't assert.

**System (please complete the following information):**
Fedora 32 x86_64
dyninst master

**Comment by hainest** [comment]
@woodard Could you try this with the current HEAD of master for Dyninst (4311e9481) and the test sutie (99c376e1). I saw some failures similar to these, but haven't been able to reproduce them with the latest HEAD.

**Comment by woodard** [comment]
With the latest head, I'm not getting the same asserts. However there are a lot of crashes see issue 894.
