### ISSUE TITLE
Very common crash in dwarf_tag when processing DWARF

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#907]
When processing the symtab for /lib64/sasl2/libanonymous.so.3.0.0 from cyrus-sasl-lib-2.1.27-6.fc33.x86_64

with dyninst trunk at commit 4311e94
run with OMP_NUM_THREADS=1
using this test code
[repo1.C.gz](https://github.com/dyninst/dyninst/files/5462049/repo1.C.gz)

I get the following crash
```
Program received signal SIGSEGV, Segmentation fault.
dwarf_tag (die=<optimized out>) at dwarf_tag.c:92
92	  return abbrevp->tag;
#0  dwarf_tag (die=<optimized out>) at dwarf_tag.c:92
#1  0x00007ffff7f7ef18 in Dyninst::SymtabAPI::DwarfWalker::findTag (this=0x7fffffffbf30) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:1393
#2  Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:329
#3  0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf30, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#4  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#5  0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#6  0x00007ffff7f7f99c in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffffbf30, moduleDIE=..., fixUnknownMod=@0x7fffffffbf18: 0x4c6d80) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:259
#7  0x00007ffff7f7fd28 in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) () at /usr/include/c++/10/bits/stl_vector.h:1043
#8  0x00007ffff75c8d36 in GOMP_parallel (fn=0x7ffff7f7fc00 <Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void)>, data=0x7fffffffc820, num_threads=1, flags=0) at ../../../libgomp/parallel.c:171
#9  0x00007ffff7f7c27e in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7fffffffc880) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:162
#10 0x00007ffff7f2de31 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x480bb0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Object-elf.C:4495
#11 0x00007ffff7eda4d9 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x468780) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Symtab.C:2164
#12 0x00007ffff7ecc448 in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x5152f0, params_=std::vector of length 0, capacity 0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Function.C:122
#13 0x000000000040356b in main (argc=<optimized out>, argv=<optimized out>) at repo1.C:64
```
This is an extremely common crash. Making up 260 out 470 of the crashes seen in my testing.
Attached is a file with the libraries affected and the RPMs that they came from.
[dwarf_tag.gz](https://github.com/dyninst/dyninst/files/5462085/dwarf_tag.gz)

**Comment by hainest** [comment]
I ran this several times, and it alternates between a crash and the "Module does not exist" error from #902. I've not been able to replicate the posted backtrace, but here is the one I get when building Dyninst in debug mode (i.e., CMAKE_BUILD_TYPE=Debug):

	> set env OMP_NUM_THREADS=1
	> run
	> bt
	#0  0x00007fa4883e1eb5 in __libdw_find_attr () from /lib64/libdw.so.1
	#1  0x00007fa4883e03bb in dwarf_attr () from /lib64/libdw.so.1
	#2  0x00007fa488d68330 in Dyninst::SymtabAPI::DwarfWalker::findType (this=0x7ffe869c2590, type=..., defaultToVoid=false)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:1606
	#3  0x00007fa488d6445a in Dyninst::SymtabAPI::DwarfWalker::parseVariable (this=0x7ffe869c2590)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:868
	#4  0x00007fa488d626f7 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7ffe869c2590, e=..., p=true)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:364
	#5  0x00007fa488d62a28 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7ffe869c2590, e=..., p=true)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:444
	#6  0x00007fa488d62a28 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7ffe869c2590, e=..., p=true)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:444
	#7  0x00007fa488d61eb7 in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7ffe869c2590, moduleDIE=..., fixUnknownMod=@0x7ffe869c2da8: 0x15e3d20)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:259
	#8  0x00007fa488d6c13a in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) ()
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:169
	#9  0x00007fa48826fd36 in GOMP_parallel () from /lib64/libgomp.so.1
	#10 0x00007fa488d61794 in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7ffe869c3830) at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/dwarfWalker.C:162
	#11 0x00007fa488cd2c20 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x159db90) at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/Object-elf.C:4495
	#12 0x00007fa488c56cd2 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x1585760) at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/Symtab.C:2164
	#13 0x00007fa488c597c6 in Dyninst::SymtabAPI::Symtab::parseTypesNow (this=0x1585760) at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/Symtab.C:3067
	#14 0x00007fa488c33647 in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x1632090, params_=std::vector of length 0, capacity 0)
			at /dyninst/YZa87EBg/dyninst/src/symtabAPI/src/Function.C:122
	#15 0x0000000000403543 in main (argc=<optimized out>, argv=<optimized out>) at repo1.C:64

**Comment by hainest** [comment]
@woodard Could you re-upload the file with all of the libraries+RPMs? For some reason, the one that is here keeps showing 0 bytes when downloaded.

**Comment by woodard** [comment]
Verified that this no longer occurs with sasha's latest dwarf fixes.
Feel free to close this once those are merged with the trunk.
