### ISSUE TITLE
Different cfg generated in X86 and aarch64 with same objfile 

### ISSUE THREAD

**Issue by ZHAZHA33** [dyninst/dyninst#910]
**Intention**
What did you want to do?
using dyninst in arm to analyse x86 objfile

**Describe the bug**
parsre x86 object file in x86-64 or aarch64 env ，find the cfg files are different，which there is a jmp inst；
cfg generated in x86 has more blocks than in aarch64

**To Reproduce**
A command? A code? A binary?

1） file test.c  with c code

static __thread int var = 0;  

void* worker(void* ret){

    int i;

    for (i = 0; i < 100; ++i) {
                var++;
    }
    *((int *)ret) =  var + *((int*)ret);
    var = *((int *)ret);
}

2） using gcc  to generate object file in x86-64  env
       gcc -c test.c -o test.o

3） mv test.o to aar64 env
4) using dyninst  to parse the file in aarch64 env
5) find the cfg lost one block

below is the diff from x86 cfg and aarch64 cfg

x86 cfg 

 blocks {
    ea: 0
    instructions {
      ea: 0
      bytes: "U"
    }
    instructions {
      ea: 1
      bytes: "H\211\345"
    }
    instructions {
      ea: 4
      bytes: "H\211}\350"
    }
    instructions {
      ea: 8
      bytes: "\307E\374\000\000\000\000"
    }
    instructions {
      ea: 15
      bytes: "\353\027"
    }
    successor_eas: 40
  }
  blocks {
    ea: 17
    instructions {
      ea: 17
      bytes: "d\213\004%\000\000\000\000"
      xrefs {
        target_type: DataTarget
        operand_type: MemoryOperand
        location: Internal
        ea: 141
        name: "var"
        add_end: 0
        rel_type: 23
      }
    }
    instructions {
      ea: 25
      bytes: "\203\300\001"
    }
    instructions {
      ea: 28
      bytes: "d\211\004%\000\000\000\000"
      xrefs {
        target_type: DataTarget

aarch64 cfg: block 17 was lost

funcs {
  ea: 0
  blocks {
    ea: 0
    instructions {
      ea: 0
      bytes: "U"
    }
    instructions {
      ea: 1
      bytes: "H\211\345"
    }
    instructions {
      ea: 4
      bytes: "H\211}\350"
    }
    instructions {
      ea: 8
      bytes: "\307E\374\000\000\000\000"
    }
    instructions {
      ea: 15
      bytes: "\353\027"
      xrefs {
        target_type: DataTarget
        operand_type: MemoryOperand
        location: Internal
        ea: 141
        name: "var"
        add_end: -19
        rel_type: 23
      }
    }
    successor_eas: 40
  }
  blocks {
    ea: 40
    instructions {
      ea: 40
      bytes: "\203}\374c"
    }
    instructions {
      ea: 44
      bytes: "~\343"
    }
    successor_eas: 46
  }
  blocks {

**Expected behavior**

same cfg file produced in both x86_64 and ARMv8

**System (please complete the following information):**
 - What platform (x86, x86_64, Power8, Power9, ARMv8)
 X86_64  and ARMv8
 - What commit? (Or branch)

dyninst 10.1.0
 - Maybe libc version

**Additional context**

**Comment by hainest** [comment]
@mxz297 There was recent discussion about whether or not Dyninst fully supports analyzing just object files. Is this related to that discussion?

**Comment by ZHAZHA33** [comment]
@mxz297   any information can help???

**Comment by mxz297** [comment]
@ZHAZHA33 Can you try the head of master branch? If the same problem still occurs, I can take a look.

**Comment by ZHAZHA33** [comment]
@mxz297  I found that the different process between X86 and aarch64 is the cap_stripped binaries defined by  -Dcap_stripped_binaries; which is not available to aarch64;
The related  API is parseGaps, which was only enabled on the x86 and x86-64;

Can you help to explain what is the difference when doing gap heuristic in aarch64, looking forward to your sharing 
TKS

**Comment by mxz297** [comment]
@ZHAZHA33 

> Can you help to explain what is the difference when doing gap heuristic in aarch64;

Currently, there is no gap analysis for aarch64 binaries. 

> Another qustion, if I run dyninst in aarch64 env, it only support to analyse aarch64 mode binary, is it right??

No, ParseAPI should be able to do cross-architecture binary analysis. So, what you have observed is a bug for us to fix. In this case, parseGaps should check the binary's architecture rather than the architecture where it is running. 

For you to work around this problem, you can remove the conditional compilation guards so that you will get gap parsing code invoked when you analyze x86 binaries on aarch64.

**Comment by mxz297** [comment]
@ZHAZHA33 Can you try this branch and see if it resolves your problem?

https://github.com/dyninst/dyninst/tree/gap_parsing_enable

**Comment by ZHAZHA33** [comment]
> @ZHAZHA33 Can you try this branch and see if it resolves your problem?
> 
> https://github.com/dyninst/dyninst/tree/gap_parsing_enable


Thank you for your help, I will try this branch and also I am working to work around this problem by removeing the confitional compilation guards;
I will let you know if anything changes. Thanks again

**Comment by ZHAZHA33** [comment]
@mxz297   We hava found the problem was caused by char which is different in aarch64 and x86 by default;
We need to use   -fsigned-char  in aarch64 env.
Thank you for your help!
