### ISSUE TITLE
support some instructions

### ISSUE THREAD

**Issue by ccxiaop** [dyninst/dyninst#918]
When we use dyninst to decode some instructions, we found that some instructions cannot be parsed normally.For example：

1.roundss
I've slightly modified the code to support this instruction, can you help me review the code,and make sure that this is correct.

diff --git a/common/src/arch-x86.C b/common/src/arch-x86.C
index 33fdfb9..1ed055b 100644
--- a/common/src/arch-x86.C
+++ b/common/src/arch-x86.C
@@ -5883,7 +5883,7 @@ static ia32_entry sseMapTer[][3] =
{ e_roundpd, t_done, 0, true, { Vdq, Wdq, Ib }, 0, s1W2R3R, 0 }
}, { /* SSET0A */
{ e_No_Entry, t_ill, 0, false, { Zz, Zz, Zz }, 0, 0, 0 },
- { e_No_Entry, t_sse_ter_mult, SSET0A_66, false, { Zz, Zz, Zz }, 0, 0, 0 },
+ { e_roundss, t_sse_ter_mult, SSET0A_66, true, { Vss, Wss, Ib }, 0, s1W2R3R, 0 },
{ e_roundss, t_done, 0, true, { Vss, Wss, Ib }, 0, s1W2R3R, 0 },
}, { /* SSET0B */
{ e_No_Entry, t_ill, 0, false, { Zz, Zz, Zz }, 0, 0, 0 },

2.vshufi64x2
I tried to add code to support this instruction in the arch-x86.C file, but it didn't work. Can you add this feature in the new version?

thanks。

**Comment by hainest** [comment]
@ccxiaop We are transitioning our x86 instruction decoding to use Capstone (#690 

@mxz297 Do we want to add these now, or wait until that integration is complete?

**Comment by ccxiaop** [comment]
@hainest Which version can we use this feature?

**Comment by mxz297** [comment]
@ccxiaop You can try this branch: https://github.com/mxz297/dyninst/tree/layout_opt

And follow the instruction here to build that branch:

https://github.com/mxz297/dyninst/blob/layout_opt/branch_build.md

**Comment by ccxiaop** [comment]
@mxz297 Will your version be released in the trunk of dyninst?

**Comment by mxz297** [comment]
@ccxiaop Yes, but it will probably take several months. It will not be in the next release.
