### ISSUE TITLE
Memory Leak in Dyninst

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#921]
**Intention**
Attach to a process using dyninst.

**Describe the bug**
Using codecoverage binary, attach to a process using bpatch.processAttach and print its function.
bpatch.processAttach increase the memory of codeCoverage by 2.5 GB and it never gets decreased.

**To Reproduce**
call bpatch.processAttach and pass a process id. This returns BPatch_process* or BPatch_addressSpace*
Memory did not decrease after deleting BPatch_process* or BPatch_addressSpace*.

**Expected behavior**
There should not be memory leak.

**System (please complete the following information):**
 - What platform x86_64, ubuntu 16.04

**Comment by hainest** [comment]
What version of Dyninst are you using? There are internal Dyninst data structures which are required to be persistent throughout the lifetime of the instrumented process, but will be released once the instrumented process is exited. This is not necessarily a memory leak.

**Comment by ManojKumarChauhan** [comment]
Hi @hainest,
I am using the latest version 10.2.1.
For one process codeCoverage memory is increased by 2.4 gb. This is very high.
I think there is some memory leak. Could you please check.

**Comment by ManojKumarChauhan** [comment]
> What version of Dyninst are you using? There are internal Dyninst data structures which are required to be persistent throughout the lifetime of the instrumented process, but will be released once the instrumented process is exited. This is not necessarily a memory leak.

I am not agree with this. If codecoverage attach to a process, instrument the functions and return after that (means it gets closed itself) then the instrumented functions always work in the running process.

**Comment by ManojKumarChauhan** [comment]
Hi @hainest ,
Are you going to make some change to avoid the memory leak?

**Comment by hainest** [comment]
>I am not agree with this. If codecoverage attach to a process, instrument the functions and return after that (means it gets closed itself) then the instrumented functions always work in the running process.

No. The DyninstAPI_RT is injected into the attached process. This requires parts of Dyninst which have persistent data structures that do not leave memory until the process is exited. There is no memory leak in this case.
