### ISSUE TITLE
static rewriter crashing on Power9 with large thread count

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#930]
When OMP_NUM_THREADS >= 16, test5_1 reliably crashes in static rewriter mode. This occurs both on llnl.cs.rice.edu and lassen.llnl.gov. It does not happen on x86 (it's not implemented on ARM).

	$ gdb --args ./test_driver -none -64 -all -staticlink -rewriter -test test5_1
	(gdb) set env DYNINSTAPI_RT_LIB=/home/th37/paradyn/yeeYSkYq/dyninst/lib/libdyninstAPI_RT.so
	(gdb) set env LD_LIBRARY_PATH=/home/th37/paradyn/yeeYSkYq/testsuite/tests:/home/th37/paradyn/yeeYSkYq/dyninst/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/libiberty-2.33.1-wctqi3hkosjfre2lnp6shfytwykcv45f/lib64:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/libiberty-2.33.1-wctqi3hkosjfre2lnp6shfytwykcv45f/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/llvm-9.0.1-slh652s3kvb3s565gz2yhokiui5d3yup/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/libxml2-2.9.9-frgg7az7zlettkluwbssmtvri6xjcfqw/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/intel-tbb-2020.1-fvpjy5jsiaurff7562usb57fjcvvndup/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/elfutils-0.178-fnaqmvd6rjh757ht3w2sibo35okkr6hs/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/boost-1.70.0-uxbkyhjhacyhddnmhhgqhywb7f3b3lpk/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/perl-5.30.0-55gkrvqdhvu7kclxpcthjo2jfbicpccv/lib:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/gcc-8.3.0-5w4gcptbunerjtgoj724b5pi2okxuooh/lib64:/home/th37/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/gcc-8.3.0-5w4gcptbunerjtgoj724b5pi2okxuooh/lib
	(gdb) set env OMP_NUM_THREADS=16
	(gdb) handle SIGUSR2 nostop

	#0  0x00007ffff74dfc30 in raise () from /lib64/libc.so.6
	#1  0x00007ffff74e1f8c in abort () from /lib64/libc.so.6
	#2  0x00007ffff74d5754 in __assert_fail_base () from /lib64/libc.so.6
	#3  0x00007ffff74d5844 in __assert_fail () from /lib64/libc.so.6
	#4  0x00007ffff54332a4 in Dyninst::ParseAPI::Function::set_retstatus (this=0x1df1ac00, rs=Dyninst::ParseAPI::RETURN)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Function.C:509
	#5  0x00007ffff53aa9dc in Dyninst::ParseAPI::Parser::ProcessCFInsn (this=0x1df13310, frame=..., cur=0x7fffad021f48, ah=0x7fffad020d10)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/ParserDetails.C:485
	#6  0x00007ffff53ce3e0 in Dyninst::ParseAPI::Parser::parse_frame_one_iteration (this=0x1df13310, frame=..., recursive=true)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Parser.C:1837
	#7  0x00007ffff53cb728 in Dyninst::ParseAPI::Parser::parse_frame (this=0x1df13310, frame=..., recursive=true)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Parser.C:1392
	#8  0x00007ffff53c5eec in Dyninst::ParseAPI::Parser::ProcessOneFrame (this=0x1df13310, pf=0x7fffbcebb650, recursive=true)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Parser.C:458
	#9  0x00007ffff53c6d20 in Dyninst::ParseAPI::Parser::SpawnProcessFrame (this=0x1df13310, pf=0x7fffbcebb650, recursive=true)
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Parser.C:651
	#10 0x00007ffff53d64f0 in Dyninst::ParseAPI::Parser::_ZN7Dyninst8ParseAPI6Parser10LaunchWorkEP17LockFreeQueueItemIPNS0_10ParseFrameEEb._omp_fn.1(void) ()
			at /home/th37/paradyn/yeeYSkYq/dyninst/src/parseAPI/src/Parser.C:639
	#11 0x00007ffff4b84328 in gomp_barrier_handle_tasks (state=<optimized out>)
			at /tmp/th37/spack-stage/spack-stage-gcc-8.3.0-5w4gcptbunerjtgoj724b5pi2okxuooh/spack-src/libgomp/task.c:1271
	#12 0x00007ffff4b8dab0 in gomp_team_barrier_wait_end (bar=<optimized out>, state=97352)
			at /tmp/th37/spack-stage/spack-stage-gcc-8.3.0-5w4gcptbunerjtgoj724b5pi2okxuooh/spack-src/libgomp/config/linux/bar.c:116
	#13 0x00007ffff4b8a314 in gomp_thread_start (xdata=<optimized out>)
			at /tmp/th37/spack-stage/spack-stage-gcc-8.3.0-5w4gcptbunerjtgoj724b5pi2okxuooh/spack-src/libgomp/team.c:121
	#14 0x00007ffff72a8cd4 in start_thread () from /lib64/libpthread.so.0
	#15 0x00007ffff75c7e94 in clone () from /lib64/libc.so.6

**Comment by mxz297** [comment]
@hainest I will take a look and try to reproduce it on llnl.cs.rice.edu

**Comment by hainest** [comment]
Subsumed by #1035
