### ISSUE TITLE
Possible bug in AMD GPU architecture handling in DwarfHandle::init_dbg

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#937]
@bbiiggppiigg  @mxz297 

https://github.com/dyninst/dyninst/blob/master/dwarf/src/dwarfHandle.C#L199 was introduced by #900

1. We are returning an enum/int value in a function that returns a `bool`. In gcc, this fires `-Wint-in-bool-context`.
2. The first assert cannot fire because of the `return`
3. We never assign a value to `arch`. I'm assuming that's because this is only preliminary architecture support for AMD and `DwarfDyninst::DwarfFrameParser::create` doesn't know what to do with it.
4. "probabily" -> "probably" on line 213

Sorry I didn't catch these during the initial review. That was a big PR, and I didn't fully grok what was going on in this part.

**Comment by mxz297** [comment]
I see. @bbiiggppiigg It looks like then `arch` should have the architecture enum and the function should return `true`.
