### ISSUE TITLE
Does Dyninst toolchain Origin identify Compiler for 64-bit Windows Executables?

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#943]
I installed Dyninst on Linux and the toolchain "Origin" tool successfully created for idioms and graphlets files of length 1, 2, and 3 of Windows PE file. But the featlists and instances files are zero bytes in length. Furthermore, I got the following error:
traceback (most recent call last):
  File "Origin.py", line 227, in <module>
    endAddr = GetEndAddress(args.binpath, filename)
  File "Origin.py", line 35, in GetEndAddress
    endAddr = open(out, "r").read()[:-1]
IOError: [Errno 2] No such file or directory: '/home/kali/Desktop/origin-output/explorer.exe.range'

"explorer.exe" is the input file.

Thanks

**Comment by mxz297** [comment]
The toolchain origin tool was not tested for PE binaries.

**Comment by mali-arf** [comment]
Thanks for your reply Meng.

**Comment by mali-arf** [comment]
Meng, the compiler provenance labels for Microsoft Visual C++ compiler families (2003, 2005 and 2008) in the Origin Tool were learned on MSVC compiled Binaries. right? Were they not PE binaries?
Can you please clarify my confusion.
Thanks

**Comment by mxz297** [comment]
There are no labels for Microsoft Visual C++ compiler family in the implementation (https://github.com/dyninst/toolchain-origin). 

If you refer to the paper  "Nathan Rosenblum, Barton P. Miller, and Xiaojin (Jerry) Zhu, "Recovering the Toolchain Provenance of Binary Code", International Symposium on Software Testing and Analysis (ISSTA), Toronto, Canada, July 2011", that paper indeed included Microsoft visual C++ compiler families, but that paper was long time ago. Back then, Dyninst worked with PE binaries, but not now.

**Comment by mali-arf** [comment]
Oh I got it now. Thanks for the clarification. Yes, in the current implementation, I didnt find any labels for MSVC but if we manage to run Dyninst on Windows without errors,  will the "Origin" gonna work, apart from just adding the compiler labels?

**Comment by hainest** [comment]
Closing as we do not currently support using Dyninst on Windows
