### ISSUE TITLE
Dyninst 10.2 is throwing error with Boost 1.62 on Ubuntu!

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#945]
Hi there,
This example has been taken from ParseAPI of DynInst Documentation example 3.1, "Functions Disassembly". On line 43, the following error is encountered. Kindly help me to resolve it!
*********************************************************************************************************************
boost::shared_ptr<Dyninst::InstructionAPI::Instruction>’} and ‘Dyninst::InstructionAPI::Instruction’)
   43 |   instr = decoder.decode((unsigned char *)f->isrc()->getPtrToInstruction(crtAddr));
      |                                                                                  ^
In file included from /usr/local/include/boost/shared_ptr.hpp:17,
                 from ............................... /symtabAPI/h/Symbol.h:46,
                 from .............................. /symtabAPI/h/Symtab.h:36,
                 from .............................. /parseAPI/h/CodeObject.h:36,
                 from test.cc:2:
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:524:18: note: candidate: ‘boost::shared_ptr<T>& boost::shared_ptr<T>::operator=(const boost::shared_ptr<T>&) [with T = Dyninst::InstructionAPI::Instruction]’
  524 |     shared_ptr & operator=( shared_ptr const & r ) BOOST_NOEXCEPT
      |                  ^~~~~~~~
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:524:48: note:   no known conversion for argument 1 from ‘Dyninst::InstructionAPI::Instruction’ to ‘const boost::shared_ptr<Dyninst::InstructionAPI::Instruction>&’
  524 |     shared_ptr & operator=( shared_ptr const & r ) BOOST_NOEXCEPT
*********************************************************************************************************************
Thanks

**Comment by bbiiggppiigg** [comment]
Can you try the funcDisassemble example here ?
https://github.com/bbiiggppiigg/examples/blob/master/funcDisassemb/funcDisassemb.C

**Comment by mali-arf** [comment]
Thank you bbiiggppiigg. Its Working fine.
What was the issue?

**Comment by bbiiggppiigg** [comment]
The examples in the documentation might be outdated.
The most up to date examples are in the dyninst/examples repo.
For this problem in particular, probably some misuse of reference.
