### ISSUE TITLE
Dyninst 10.2 run on Windows 10?

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#946]
Can you share your experience of building Dyninst 10.2 on Windows 10?
I used MSys2 64-bit to build TBB on Msy using pacman, Boost 1.66 with gcc and finally DynInst using MinGW but ended up with the error of cmake Policy CMP0004 of trailing spaces.
If I build DynInst with MS Visual Studio then I get the missing TBB errors, however, I have added all paths of the TBB libraries.
Thanks for your support.

**Comment by hainest** [comment]
We do not currently support the Windows platform. I would recommend either building under the Linux Subsystem for Windows or using a virtual machine.

**Comment by mali-arf** [comment]
> We do not currently support the Windows platform. I would recommend either building under the Linux Subsystem for Windows or using a virtual machine.

Can you please explain, how can I use Dyninst for Windows Binary in a VM?
