### ISSUE TITLE
Dyninst - values passed to instrumentation function are not saved

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#947]
**Intention**
Instrument a function at Bpatch_entry level. Add some values and pass in the function.  When the instrumentation function execute, it should have the passed values

**Describe the bug**
insert a function in golang binary.

BPatch_function *curFunc = findFuncByName(libImage, (char *) "bbCallback");
BPatch_function * insertedfunc = findFuncByName(libImage, (char *) "insertfunc");
vector < BPatch_point * >*funcEntry = curFunc->findPoint (BPatch_entry);
BPatch_Vector < BPatch_snippet * >instArgs;
BPatch_constExpr id (5);
instArgs.push_back (&id);
BPatch_funcCallExpr instIncExpr (*insertedfunc, instArgs);
Bpatch_addressspaceobject->insertSnippet (instIncExpr, *funcEntry, BPatch_callBefore,
					BPatch_lastSnippet);

**Expected behavior**
func insertfunc(arg1 int) {
}
When the function "insertfunc" executes, arg1 should contain the value 5 but it shows value 0.
 
**System (please complete the following information):**
 x86_64 ubuntu

**Additional context**
same issue was reported on https://github.com/dyninst/dyninst/issues/434

branch   master
10.2.1

**Comment by ManojKumarChauhan** [comment]
Can someone suggest how to solve this issue?

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,

This issue is partially fixed in layout_opt branch. If I pass integer value argument in insertSnippet then this value persists when the instrumented method is called. But when pass a string argument it does not save.

Could you please share the git hash where you solve the issue for passing integer.

**Comment by mxz297** [comment]
@ManojKumarChauhan I did not do anything specific to fix this problem. I disabled some Dyninst's internal code generation code, which could generate wrong values. However, I don't think my branch itself fixed the problem...

**Comment by mxz297** [comment]
@ManojKumarChauhan If the root cause is that Dyninst does not save and restore registers, my branch provides a separate way to allow the user to specify which registers to save and restore:

https://github.com/iu-parfunc/ShadowGuard/blob/master/src/instrument.cc#L1000

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
It did not work for me. In layout_opt branch I passed one additional parameter (InstSpec is_init) in insertSnippet function and initialize it with SetupInstrumentationSpec. It gave following error
"Error: specific register could not be spilled!"

I did not understand the use of following code. 
Snippet::Ptr stack_push =
        RegisterPushSnippet::create(new RegisterPushSnippet(summary));
    InsertSnippet(function, Point::FuncEntry, stack_push, patcher);

**Comment by ManojKumarChauhan** [comment]
When I call insertSnippet without passing the additional argument then it's not able to store the value because none of the register is available.  I am getting below message

emit-x86.C[1816]: pre-call, register 0 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1810]: pre-call, skipping callee-saved register 3
emit-x86.C[1810]: pre-call, skipping callee-saved register 4
emit-x86.C[1810]: pre-call, skipping callee-saved register 5
emit-x86.C[1816]: pre-call, register 10 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 11 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1810]: pre-call, skipping callee-saved register 12
emit-x86.C[1810]: pre-call, skipping callee-saved register 13
emit-x86.C[1810]: pre-call, skipping callee-saved register 14
emit-x86.C[1810]: pre-call, skipping callee-saved register 15
emit-x86.C[1816]: pre-call, register 8 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 9 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 1 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 2 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 6 has refcount 0, keptValue 0, liveState spilled
emit-x86.C[1816]: pre-call, register 7 has refcount 0, keptValue 0, liveState spilled


This is a bug in all dyninst branches. Someone please suggest a  solution.

**Comment by ManojKumarChauhan** [comment]
Hi,Hope you are doing well. Need some help for this issue.I passed extra argument in insertsnippet but that didn't work.After calling correct function (point) of basetramp from emit-x86 File and using correct registers, the error gone but still the value is not saved.If I use a string value as argument for insertsnippet then it's considered as int.
Could you please suggest how to solve that as I am not completely aware with dyninst code    On Tuesday, 19 January, 2021, 10:44:38 pm IST, Xiaozhu Meng <notifications@github.com> wrote:  
 
 


@ManojKumarChauhan If the root cause is that Dyninst does not save and restore registers, my branch provides a separate way to allow the user to specify which registers to save and restore:

https://github.com/iu-parfunc/ShadowGuard/blob/master/src/instrument.cc#L1000
