### ISSUE TITLE
Compiler warnings for AMD GPU code

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#952]
@bbiiggppiigg

The -Wreorder -Wswitch warnings we definitely want to get fixed before the 11.0 release.

**-Wreorder**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:262
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isModifyPC’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:248
		‘bool Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isSMEM’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:256
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isCall’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:241
		‘unsigned int Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:256
	‘Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::isCall’ will be initialized after 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.h:241
		‘unsigned int Dyninst::InstructionAPI::InstructionDecoder_amdgpu_vega::immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:70
		when initialized here 

**-Wswitch**
dyninst/src/common/src/dyn_regs.C:208
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:380
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:407
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

dyninst/src/parseAPI/src/SymbolicExpression.C:369
	enumeration value ‘Arch_amdgpu_rdna’ not handled in switch 

**-Wtype-limits**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:588
	comparison of unsigned expression in ‘>= 0’ is always true 

**-Wunused-but-set-variable**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:513
	variable ‘mr’ set but not used 

**-Wunused-function**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:177
	‘Dyninst::InstructionAPI::Expression::Ptr Dyninst::InstructionAPI::conditionalAssignment(unsigned int, Dyninst::InstructionAPI::Expression::Ptr, Dyninst::InstructionAPI::Result_Type)’ defined but not used 

**-Wunused-parameter**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:138
	unused parameter ‘immLen’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:157
	unused parameter ‘entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:162
	unused parameter ‘insn_to_complete’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:551
	unused parameter ‘insn_to_complete’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘base’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘offset’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:571
	unused parameter ‘m0’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:67
	unused parameter ‘i’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:86
	unused parameter ‘context’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:86
	unused parameter ‘type’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:87
	unused parameter ‘knownTargets’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘bit’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘ret_addr’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:107
	unused parameter ‘func’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:112
	unused parameter ‘retAddr’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:117
	unused parameter ‘context’ 

dyninst/src/parseAPI/src/IA_amdgpu.C:117
	unused parameter ‘currBlk’ 

**-Wunused-variable**
dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:210
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:321
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:405
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:417
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:454
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:469
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:488
	unused variable ‘insn_entry’ 

dyninst/src/instructionAPI/src/InstructionDecoder-amdgpu-vega.C:498
	unused variable ‘insn_entry’

**Comment by bbiiggppiigg** [comment]
Most of the unused stuff  is related to the fact that they are generated function templates but not really supported yet..
The switch stuff is related to the me adding Arch_rdna as an architecture that will be support in the future, should be an easyfix.
The reorder stuff Ill have to look into them.

**Comment by hainest** [comment]
>Most of the unused stuff is related to the fact that they are generated function templates but not really supported yet..

Yeah, I'm not sure what to do about some of those warnings (there are 75 of them in total). I would like to have the number of warnings down to zero, but it depends on how much work it is to get there.

>The reorder stuff Ill have to look into them.

Those are an easy fix. The C++ standard technically requires that member variables in an initializer list are provided in the same order they are declared in the class. You'll just need to reorder the list.
