### ISSUE TITLE
Unhandled enum values for Intel GPUs

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#953]
@Jokeren 

We'll want to get these cleaned up for the 11.0 release.

dyninst/src/common/src/dyn_regs.C:380
	enumeration value ‘Arch_intelGen9’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:407
	enumeration value ‘Arch_intelGen9’ not handled in switch 
	
dyninst/src/proccontrol/src/process.C:1929
	enumeration value ‘Arch_intelGen9’ not handled in switch 

dyninst/src/parseAPI/src/SymbolicExpression.C:369
	enumeration value ‘Arch_intelGen9’ not handled in switch

**Comment by Jokeren** [comment]
I'll fix these issues soon

**Comment by Jokeren** [comment]
https://github.com/dyninst/dyninst/pull/955

@mxz297 other than getPC, the code is consistent with the cuda register. Do you know why we need to implement getPC for cuda instructions?

**Comment by mxz297** [comment]
@Jokeren I don't remember any particular reason to implement getPC for CUDA. Probably getPC for CUDA was also added to suppress compiler warning.
