### ISSUE TITLE
Implicit fallthrough in switch statements

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#986]
- [x] common/src/arch-x86.C:11434
- [ ] common/src/arch-x86.C:11995
- [ ] dwarf/src/dwarfExprParser.C:337
- [ ] symtabAPI/src/Symtab-edit.C:74
- [ ] symtabAPI/src/parseStab.C:465
- [ ] symtabAPI/src/parseStab.C:1896
- [ ] symtabAPI/src/parseStab.C:1902
- [ ] proccontrol/src/loadLibrary/codegen.C:156
- [ ] proccontrol/src/loadLibrary/codegen.C:175
- [ ] proccontrol/src/linux.C:371
- [ ] proccontrol/src/linux.C:394
- [ ] proccontrol/src/linux.C:652
- [x] patchAPI/src/PatchMgr.C:438
- [ ] stackwalk/src/x86-wanderer.C:108
- [ ] dyninstAPI/src/ast.C:1719
- [x] dyninstAPI/src/codegen.C:639
- [x] dyninstAPI/src/mapped_object.C:909
- [x] dyninstAPI/src/mapped_object.C:912
- [ ] dyninstAPI/src/inst-x86.C:1834
- [ ] dyninstAPI/src/inst-x86.C:1875 
- [x] dyninstAPI/src/inst-x86.C:1811
- [x] dyninstAPI/src/inst-x86.C:1851
- [x] dyninstAPI/src/emit-x86.C:2233
- [x] dyninstAPI/src/emit-x86.C:2240

@mxz297 @sashanicolas 

Until we switch to using C++17, there isn't a compiler-agnostic method of making a switch statement fall through without a warning. I can cook up a quick macro to handle the gcc/clang method of doing it, but I want to make sure that **all** of these are supposed to actually fall through. If we could get this in for 11.0, that would be fantastic.

**Comment by mxz297** [comment]
@hainest Can you convert your list into a table checkboxes?

**Comment by hainest** [comment]
@mxz297 Updated.

**Comment by mxz297** [comment]
@hainest I have gone through a pass on the list. A checked box means that I am reasonably certain that falling through into the next clause is the intended behavior. As you can see, more than half of the lines are not checked. For these unchecked ones, I feel either uncertain or even leaning towards the feeling that there should be a break from the switch statement. 

So, I would say that this is a great way of exposing potential bugs. More eyes are needed here to investigate the unchecked ones. 

In addition, it looks like that you came up with the list on x86. Can you do something similar for power and arm?

**Comment by hainest** [comment]
>A checked box means that I am reasonably certain that falling through into the next clause is the intended behavior.

Ok. I will make a fallthrough macro to silence the compiler warnings.

>More eyes are needed here to investigate the unchecked ones.

Well, of all the Dyninst developers, you have the most knowledge of this type of question. Do you have someone specific in mind to look over these, or do you just want everyone to take a look to get a somewhat-informed consensus?

>In addition, it looks like that you came up with the list on x86. Can you do something similar for power and arm?

The ARM and Power builds show the same warnings (actually, fewer).

**Comment by mxz297** [comment]
@sashanicolas Can you take a look at "dwarf/src/dwarfExprParser.C:337" and see if a `break` is needed?

@hainest For other ones, it is probably just to get more thoughts. I am not familiar with these ones either.

**Comment by sashanicolas** [comment]
That case in  "dwarf/src/dwarfExprParser.C:337" should not have a break, so far. Unfortunately the way the DWARF state machine is implemented in Dyninst is a little weird and we need to consume that operation and then fall through to the next CASE to perform a SKIP operation.
And also the comment in the code says:
```
 // Do not break; fall through to skip
 ```
