### ISSUE TITLE
Does Dyninst not work for Windows 64-bit binaries?

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#992]
Hi,
I need to verify if Dyninst does not parse 64-bit Windows binaries on Windows platform. So I dont need to try building it on Windows.

Thanks

**Comment by hainest** [comment]
We do not currently support the Windows platform. There is a possibility that it will work, but we can't even guarantee that Dyninst will build on Windows.

**Comment by hainest** [comment]
We can't offer support for the Windows platform at this time. Please let us know if we can be of help in any other way.
