### ISSUE TITLE
Does Dyninst or Origin Tool not accept Stripped ELF binary?

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#996]
Hi,
Both "Dyninst" 10,2 and "Origin" on Linux cannot read a stripped ELF binary.
The error in Origin is :
File "Origin.py", line 216, in <module>
    endAddr = GetEndAddress(args.binpath, filename)
  File "Origin.py", line 34, in GetEndAddress
    endAddr = open(out, "r").read()[:-1]

Whereas Dyninst cannot read the Dwarf symbols from the Stripped ELF file and therefore doesn't output functions or any other info.
My question is, how can we use the above tools to parse a stripped ELF binary? Is it possible or not? If yes, then how?
Thanks

**Comment by hainest** [comment]
Dyninst is very limited in what information it can extract from a binary without debug (i.e., DWARF) information. What type of analysis are you trying to perform on a stripped binary?

**Comment by mali-arf** [comment]
Actually I wanted to strip a binary and test it on "Origin" for compiler provenance.
If "origin" accepts stripped binaries then it can work for any binary may that be PE or Elf.
But found out that neither dyninst nor origin parses a binary that is stripped of the header info.


On Feb 7, 2021 12:27, Tim Haines <notifications@github.com> wrote:

Dyninst is very limited in what information it can extract from a binary without debug (i.e., DWARF) information. What type of analysis are you trying to perform on a stripped binary?

**Comment by hainest** [comment]
@mxz297 Can we do provenance on stripped binaries?

**Comment by hainest** [comment]
@mxz297 Any thoughts on this?

**Comment by mxz297** [comment]
@hainest This origin tool just uses Dyninst to parse binary whether the binary is stripped or not.

**Comment by hainest** [comment]
Closing. Please re-open or submit a new question, if you require further help.
