### ISSUE TITLE
Why Dyninst does not recognize the installed "Boost" while building on Windows (in Visual Studio)?

### ISSUE THREAD

**Issue by mali-arf** [dyninst/dyninst#998]
1) Right now building Dyninst on Windows in Visual studio as a CMake Project.
The **Problem** is that During Build it is trying to download and build boost in the path of the Release/Debug Build. I dont understand why Dyninst does not recognize that Boost is already installed on Windows. I have set the environment variables and set CMake parameters to Dyinint as well.

Dyninst:10.2.1
Visual Studio 2019 (64-bit)
Cmake Generator: Visual Studio 2019 64 bit
Windows: 10

2) Also installed Dyninst in WSL on Ubuntu platform. Its working fine for ELFs. But please guide me as to how can I give it a Windows PE ?????
Anxious for making Dyninst run on Windows for PE binary ... any suggestion is appreciated.
Thanks

**Comment by hainest** [comment]
None of the developers uses Windows, so we can't help you with these installation issues. If you post the errors/warnings issued by CMake, we might be able to give you some advice, but we make no guarantees.

**Comment by mali-arf** [comment]
Thanks. I modifed the "FindBoost.cmake" file, set the PATH variables; commented the line where the code unsets the PATH variables, Sets the pattern of the "libboost" libraries format. I have done many changes and now the boost is FOUND on VS 2019 with Dyninst 10.2.1. So the cmake configuration is done on Windows 10 in VS,

**For now, can you help me with the following error**. Its something like the **Allocator should match the tbb hash_map.**
If any of the developers can suggest anything... it will save my time.

C:\Program Files (x86)\Intel\oneAPI\tbb\2021.1.1\include\tbb\../oneapi/tbb/concurrent_hash_map.h(561,77): error **C2338**: value_type of the container must be the same as its allocator's (compiling source file C:\Users\...\dyninst-10.2.1\symtabAPI\src\Type.C) [C:\Users\...\dyninst-10.2.1\build\symtabAPI\symtabAPI.vcxproj]
[build] C:\Users\...\dyninst-10.2.1\common\h\**concurrent.h(57):** message : see reference to class template instantiation 'tbb::detail::d1::concurrent_hash_map<K,V,tbb::detail::d1::tbb_hash_compare<K>,std::allocator<std::pair<K,V>>>' being compiled [C:\Users\...\dyninst-10.2.1\build\symtabAPI\**symtabAPI.vcxproj**]
[build]           with
[build]           [
[build]               K=Dyninst::SymtabAPI::Symbol *,
[build]               V=Dyninst::Offset
[build]           ] (compiling source file C:\Users\...\dyninst-10.2.1\symtabAPI\src\**Type.C**)
[build] C:\Users\...\dyninst-10.2.1\symtabAPI\h\Symtab.h(556): message : see reference to class template instantiation 'Dyninst::dyn_c_hash_map<Dyninst::SymtabAPI::Symbol *,Dyninst::Offset>' being compiled (compiling source file C:\Users\malih\dyninst-10.2.1\symtabAPI\src\Type.C) [C:\Users\...\dyninst-10.2.1\build\symtabAPI\symtabAPI.vcxproj]

This error is appearing in almost all the files of symtabAPI\src source files.
Thanks.

**Comment by hainest** [comment]
We can't offer support for the Windows platform at this time. Please let us know if we can be of help in any other way.
